billNumber = "HB00855"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB00855"
lastScraped = "2025-09-22T00:12:59.960667"
title = "HB00855"
longTitle = "AN ACT ALLOCATING TO THE AFP MODERNIZATION ACT TRUST FUND THE COLLECTION FROM CAPITAL GAINS TAX AND VALUE-ADDED TAX ON THE SALE OF REAL PROPERTY AND THE SHARE OF THE NATIONAL GOVERNMENT ON ALL TAXES, ROYALTIES AND CHARGES COLLECTED FROM THE MALAMPAYA NATURAL GAS PROJECT"
scope = "Local"
dateFiled = "2001-07-09"
status = "Pending with the Committee on WAYS AND MEANS since 2001-07-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Suarez, Aleta C."
[[authorsDetail]]
name = "Suarez, Aleta C."
nameCode = "Suarez"
date = ""
sequence = 0

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "2001-07-25"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "principal"
referralCode = "0537"

[firstReading]
id = 84015
congress = 12
bill_no = "HB00855"
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
date_read = "2001-07-25"
