billNumber = "HB01358"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB01358"
lastScraped = "2025-09-22T00:13:00.049550"
title = "HB01358"
longTitle = "AN ACT PROHIBITING THE DETAIL OR ASSIGNMENT OF MILITARY PERSONNEL IN CIVILIAN OFFICES AND PUBLIC UTILITIES AND PROVIDING PENALTIES FOR VIOLATION THEREOF"
scope = "National"
dateFiled = "2001-07-24"
status = "Pending with the Committee on NATIONAL DEFENSE since 2001-07-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Pichay, Prospero Jr. A."
coAuthors = [ "SYJUCO, AUGUSTO JR. L",]
[[authorsDetail]]
name = "Pichay, Prospero Jr. A."
nameCode = "Pichay"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "SYJUCO, AUGUSTO JR. L"
nameCode = "Syjuco"
date = ""
journalNo = "J041"
sessionNo = "3RS"

[[committee]]
name = "NATIONAL DEFENSE"
type = "primary"
referralCode = "0525"
dateRead = "2001-07-30"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 84518
congress = 12
bill_no = "HB01358"
referral = "0525"
ref_name = "NATIONAL DEFENSE"
sub_name = ""
date_read = "2001-07-30"
