billNumber = "HB03075"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB03075"
lastScraped = "2025-09-22T00:13:00.362074"
title = "HB03075"
longTitle = "AN ACT EXPANDING THE COVERAGE OF RAPE CRISIS CENTERS, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 8505"
scope = "National"
dateFiled = "2001-09-18"
status = "Pending with the Committee on SOCIAL SERVICES since 2001-09-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Angara-Castillo, Bellaflor J."
coAuthors = [ "DEL MAR, RAUL V.", "SUAREZ, ALETA C.", "SYJUCO, AUGUSTO JR. L",]
[[authorsDetail]]
name = "Angara-Castillo, Bellaflor J."
nameCode = "Angara-castillo"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DEL MAR, RAUL V."
nameCode = "Del Mar"
date = ""
journalNo = "J031"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SUAREZ, ALETA C."
nameCode = "Suarez"
date = ""
journalNo = "J047"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SYJUCO, AUGUSTO JR. L"
nameCode = "Syjuco"
date = ""
journalNo = "J012"
sessionNo = "3RS"

[[committee]]
name = "SOCIAL SERVICES"
type = "primary"
referralCode = "0535"
dateRead = "2001-09-27"

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "principal"
referralCode = "0506"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[[committee]]
name = "WOMEN AND GENDER EQUALITY"
type = "secondary"
referralCode = "A504"

[firstReading]
id = 86235
congress = 12
bill_no = "HB03075"
referral = "0535"
ref_name = "SOCIAL SERVICES"
sub_name = ""
date_read = "2001-09-27"
