billNumber = "HB03886"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB03886"
lastScraped = "2025-09-22T00:13:00.499811"
title = "HB03886"
longTitle = "AN ACT AMENDING ARTICLE THREE, SECTION 20 OF REPUBLIC ACT NO. 8749, OTHERWISE KNOWN AS `THE CLEAN AIR ACT', FOR THE PURPOSE OF ALLOWING LIMITED USE OF INCINERATORS IN SOLVING THE GARBAGE PROBLEM IN THE COUNTRY"
scope = "National"
dateFiled = "2001-11-19"
status = "Pending with the Committee on ECOLOGY since 2001-11-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Singson, Eric D."
coAuthors = [ "NIEVA, ERNESTO A.",]
[[authorsDetail]]
name = "Singson, Eric D."
nameCode = "Singson"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "NIEVA, ERNESTO A."
nameCode = "Nieva"
date = ""
journalNo = "J038"
sessionNo = "1RS"

[[committee]]
name = "ECOLOGY"
type = "primary"
referralCode = "A501"
dateRead = "2001-11-26"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 87046
congress = 12
bill_no = "HB03886"
referral = "A501"
ref_name = "ECOLOGY"
sub_name = ""
date_read = "2001-11-26"
