billNumber = "HB04523"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB04523"
lastScraped = "2025-09-22T00:13:00.621231"
title = "HB04523"
longTitle = "AN ACT CREATING A NATIONAL HIGH SCHOOL IN THE MUNICIPALITY OF SAN ANTONIO, QUEZON PROVINCE AND APPROPRIATING FUNDS THEREFORE"
scope = "Local"
dateFiled = "2002-03-05"
status = "Pending First Reading (Filed last 2002-03-05)"
statusOrder = 1.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Punzalan"
[[authorsDetail]]
name = "Punzalan"
nameCode = "Punzalan"
date = ""
sequence = 0

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

