billNumber = "HB04353"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB04353"
lastScraped = "2025-09-22T00:13:00.581631"
title = "HB04353"
longTitle = "AN ACT INTEGRATING THE BICOL UNIVERSITY GUBAT EXTENSION PROGRAM SITUATED IN THE MUNICIPALITY OF GUBAT, PROVINCE OF SORSOGON INTO A REGULAR COMPONENT OF THE BICOL UNIVERSITY LOCATED IN LEGASPI CITY, PROVINCE OF ALBAY, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2002-02-06"
status = "Substituted by HB06315"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Solis, Jose G."
coAuthors = [ "ESCUDERO, FRANCIS G.",]
[[authorsDetail]]
name = "Solis, Jose G."
nameCode = "Solis"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ESCUDERO, FRANCIS G."
nameCode = "Escudero"
date = ""
journalNo = "J002"
sessionNo = "2RS"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2002-02-12"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 87513
congress = 12
bill_no = "HB04353"
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
date_read = "2002-02-12"
