billNumber = "HB04190"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB04190"
lastScraped = "2025-09-22T00:13:00.551143"
title = "HB04190"
longTitle = "AN ACT FURTHER AMENDING PARAGRAPH (J) OF SECTION FOURTEEN (14) OF BATAS PAMBANSA BLG. 129, OTHERWISE KNOWN AS THE JUDICIARY REORGANIZATION ACT OF 1981, BY PROVIDING AN ADDITIONAL BRANCH OF THE REGIONAL TRIAL COURT IN LANAO DEL SUR TO BE STATIONED ATWAO, AND PROVIDING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2002-01-11"
status = "Substituted by HB05877"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Dumarpa, Faysah RPM"
[[authorsDetail]]
name = "Dumarpa, Faysah RPM"
nameCode = "Dumarpa"
date = ""
sequence = 0

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2002-01-21"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 87350
congress = 12
bill_no = "HB04190"
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
date_read = "2002-01-21"
