billNumber = "HB05226"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB05226"
lastScraped = "2025-09-22T00:13:00.771554"
title = "HB05226"
longTitle = "AN ACT STRENGTHENING THE WORKERS' CONSTITUTIONAL RIGHT TO SELF-ORGANIZATI ON, AMENDING FOR THIS PURPOSE PRESIDENTIAL DECREE NO. 442, AS AMENDED, OTHERWISE KNOWN AS THE LABOR CODE OF THE PHILIPPINES"
scope = "National"
dateFiled = "2002-09-05"
status = "Approved by the House on 2002-12-17, transmitted to on 2002-12-18 and received by the Senate on 2003-01-06"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "De Guzman, Del R."
coAuthors = [ "ROSALES, ETTA", "DE VENECIA, JOSE JR. C.", "ESPINOSA, EMILIO JR. R.", "GONZALES, NEPTALI II M.", "ESCUDERO, FRANCIS G.", "ANGARA-CASTILLO, BELLAFLOR J.", "FUENTEBELLA, FELIX WILLIAM B.", "BERSAMIN, LUIS JR. P.",]
[[authorsDetail]]
name = "De Guzman, Del R."
nameCode = "De Guzman"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ROSALES, ETTA"
nameCode = "Rosales"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DE VENECIA, JOSE JR. C."
nameCode = "De Venecia"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESPINOSA, EMILIO JR. R."
nameCode = "Espinosa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GONZALES, NEPTALI II M."
nameCode = "Gonzales"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESCUDERO, FRANCIS G."
nameCode = "Escudero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANGARA-CASTILLO, BELLAFLOR J."
nameCode = "Angara-castillo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FUENTEBELLA, FELIX WILLIAM B."
nameCode = "Fuentebella"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BERSAMIN, LUIS JR. P."
nameCode = "Bersamin"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2002-10-01"

[[committee]]
name = "SOCIAL SERVICES"
type = "principal"
referralCode = "0535"

[[motherBills]]
bill_no = "HB03040"
flag = "S"

[[substitutedBills]]
bill_no = "HB03040"
flag = "S"

[firstReading]
id = 88381
congress = 12
bill_no = "HB05226"
report = "00797"
referral = "0532"
ref_name = "RULES"
sub_name = "LABOR AND EMPLOYMENT"
recomm = "approval"
date_read = "2002-10-01"
date_ob = "2002-10-01"
date_report = "2002-09-05"

[secondReading]
id = 14622
congress = 12
bill_no = "HB05226"
date_calendared = "2002-10-08"
date_approved = "2002-11-28"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 5147
congress = 12
bill_no = "HB05226"
date_dist = "2002-12-11"
date_adopt = "2002-12-17"
no_yeas = 146
no_nays = 0
no_abstent = 0
date_trans = "2002-12-18"
date_rec = "2003-01-06"
