billNumber = "HB05480"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB05480"
lastScraped = "2025-09-22T00:13:00.827688"
title = "Establishing the Del Pilar National High School in Cagdianao, Surigao del Norte"
longTitle = "AN ACT ESTABLISHING A NATIONAL HIGH SCHOOL IN BARANGAY DEL PILAR, MUNICIPALITY OF CAGDIANAO, PROVINCE OF SURIGAO DEL NORTE, TO BE KNOWN AS THE DEL PILAR NATIONAL HIGH SCHOOL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2002-11-20"
status = "Approved by the House on 2002-12-17, transmitted to on 2002-12-18 and received by the Senate on 2003-01-06"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ecleo, Glenda B."
coAuthors = [ "REYES, EDMUNDO JR. O.",]
[[authorsDetail]]
name = "Ecleo, Glenda B."
nameCode = "Ecleo"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "REYES, EDMUNDO JR. O."
nameCode = "Reyes"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2002-11-26"

[[committee]]
name = "PEOPLE'S PARTICIPATION"
type = "principal"
referralCode = "0527"

[[motherBills]]
bill_no = "HB01245"
flag = "S"

[[substitutedBills]]
bill_no = "HB01245"
flag = "S"

[firstReading]
id = 88635
congress = 12
bill_no = "HB05480"
report = "01053"
referral = "0532"
ref_name = "RULES"
sub_name = "APPROPRIATIONS, BASIC EDUCATION AND CULTURE"
recomm = "approval"
date_read = "2002-11-26"
date_ob = "2002-11-26"
date_report = "2002-11-20"

[secondReading]
id = 14702
congress = 12
bill_no = "HB05480"
remarks = "Considered the Explanatory Note of the substituted HB1245 as the      sponsorship remarks."
date_approved = "2002-11-29"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 5221
congress = 12
bill_no = "HB05480"
date_dist = "2002-12-11"
date_adopt = "2002-12-17"
no_yeas = 155
no_nays = 0
no_abstent = 0
date_trans = "2002-12-18"
date_rec = "2003-01-06"
