billNumber = "HB05014"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HB05014"
lastScraped = "2025-09-22T00:13:00.725992"
title = "The Mt. Hamiguitan Range Wildlife Sanctuary Act of 2002"
longTitle = "AN ACT DECLARING MT. HAMIGUITAN RANGE AND ITS VICINITIES AS PROTECTED AREA UNDER THE CATEGORY OF WILDLIFE SANCTUARY AND ITS PERIPHERAL AREAS AS BUFFER ZONE AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2002-07-23"
status = "REPUBLIC ACT (RA09303) enacted on 2004-07-30"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Almario, Mayo Z."
coAuthors = [ "VELOSO, EDUARDO K.", "BANAAG, LEOVIGILDO B.", "GORDON, JAMES JR. J.", "JOAQUIN, ULIRAN T.", "LEVISTE, CHARITY P.", "SOLIS, JOSE G.", "RAMIREZ-SATO, JOSEPHINE Y.", "CHUNGALAO, SOLOMON R.", "DOMOGAN, MAURICIO G.", "JALA, ELADIO \"BOY\"", "SUMULONG, VICTOR R.",]
[[authorsDetail]]
name = "Almario, Mayo Z."
nameCode = "Almario"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "VELOSO, EDUARDO K."
nameCode = "Veloso"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BANAAG, LEOVIGILDO B."
nameCode = "Banaag"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GORDON, JAMES JR. J."
nameCode = "Gordon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JOAQUIN, ULIRAN T."
nameCode = "Joaquin"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LEVISTE, CHARITY P."
nameCode = "Leviste"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SOLIS, JOSE G."
nameCode = "Solis"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RAMIREZ-SATO, JOSEPHINE Y."
nameCode = "Ramirez-sato"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CHUNGALAO, SOLOMON R."
nameCode = "Chungalao"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DOMOGAN, MAURICIO G."
nameCode = "Domogan"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JALA, ELADIO \"BOY\""
nameCode = "Jala"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SUMULONG, VICTOR R."
nameCode = "Sumulong"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2002-07-31"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[[motherBills]]
bill_no = "HB02777"
flag = "S"

[[substitutedBills]]
bill_no = "HB02777"
flag = "S"

[firstReading]
id = 88169
congress = 12
bill_no = "HB05014"
report = "00638"
referral = "0532"
ref_name = "RULES"
sub_name = "APPROPRIATIONS, NATURAL RESOURCES"
recomm = "approval"
date_read = "2002-07-31"
date_ob = "2002-07-31"
date_report = "2002-07-23"

[secondReading]
id = 14584
congress = 12
bill_no = "HB05014"
remarks = "The Body approved to consider the Explanatory Note of the Bill as the sponsorship remarks."
date_approved = "2002-08-07"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 5113
congress = 12
bill_no = "HB05014"
date_dist = "2002-08-28"
date_adopt = "2002-09-03"
remarks = "   "
no_yeas = 142
no_nays = 0
no_abstent = 0
date_trans = "2002-09-05"
date_rec = "2002-09-06"
date_spass = "2004-06-10"
amend_ind = " "
ccreqby = " "
act_pres = "A"
cc_yeas = 0
cc_nays = 0
cc_absten = 0
dte_transp = "2004-07-08"
dte_actedp = "2004-07-30"
