billNumber = "HR00413"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HR00413"
lastScraped = "2025-09-22T00:13:01.229226"
title = "Addressing the Socioeconomic Issues Resulting from the Conduct of the Balikatan 2002"
longTitle = "RESOLUTION URGING THE HOUSE COMMITTEE ON NATIONAL DEFENSE TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, AS TO THE CAPABILITY AND READINESS OF THE PHILIPPINE GOVERNMENT TO ADDRESS THE SOCIOECONOMIC ISSUES RESULTING FROM THE CONDUCT OF THE BALIKATAN 2002 EXERCISES IN BASILAN PROVINCE AND OTHER AREAS IN THE PHILIPPINES, AND TO RECOMMEND APPROPRIATE MEASURES THEREFOR"
scope = "Local"
dateFiled = "2002-02-07"
status = "Adopted as Resolution No. HR00171 on 2002-02-27"
statusOrder = 15.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Salapuddin, Gerry A."
[[authorsDetail]]
name = "Salapuddin, Gerry A."
nameCode = "Salapuddin"
date = ""
sequence = 0

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2002-02-13"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 90351
congress = 12
bill_no = "HR00413"
report = "00259"
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Approval with amendments ."
date_read = "2002-02-13"
date_report = "2002-02-27"

[secondReading]
id = 15095
congress = 12
bill_no = "HR00413"
adopted_resolution = "HR00171"
adopted_resolution_title = "RESOLUTION DIRECTING THE COMMITTEES ON ECONOMIC AFFAIRS AND NATIONAL DEFENSE TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, AS TO THE CAPABILITY AND READINESS OF THE PHILIPPINE GOVERNMENT TO ADDRESS THE SOCIOECONOMIC ISSUES RESULTING FROM THE CONDUCT OF THE ?BALIKATAN? 2002 EXERCISES IN BASILAN PROVINCE AND OTHER AREAS IN THE PHILIPPINES, AND TO RECOMMEND APPROPRIATE MEASURES THEREFOR"
date_calendared = "2002-02-27"
date_approved = "2002-02-27"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"
file = "HR00171.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_12/HR00171.pdf"
