billNumber = "HR00337"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HR00337"
lastScraped = "2025-09-22T00:13:01.213818"
title = "Insufficient Rollbacks Implemented by Local Oil Companies Despite Substancial Reduction in International Oil Prices"
longTitle = "RESOLUTION URGING THE COMMITTEE ON ENERGY TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, ON THE STAGGERED AND ALLEGEDLY INSUFFICIENT PRICE ROLLBACKS IMPLEMENTED BY LOCAL OIL COMPANIES DESPITE THE SUBSTANTIAL REDUCTION IN INTERNATIONAL OIL PRICES SINCE THE SEPTEMBER 11 WORLD TRADE CENTER INCIDENT, AND TO LOOK INTO ALLEGATIONS THAT OIL COMPANIES LED BY MAJOR PLAYERS SHELL, PETRON AND CALTEX HAVE PROFITED IMMENSELY FROM THESE MINIMAL ROLLBACKS TO THE DISADVANTAGE OF FILIPINO CONSUMERS"
scope = "National"
dateFiled = "2001-12-12"
status = "Adopted Resolution (Pending with the committee on ENERGY since 2002-01-23)"
statusOrder = 5.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Beltran, Crispin B."
coAuthors = [ "OCAMPO, SATUR", "MAZA, LIZA", "CUENCO, ANTONIO V.", "DEDURO, SIEGFRED D.", "DE VENECIA, JOSE JR. C.", "ESPINOSA, EMILIO JR. R.", "GONZALES, NEPTALI II M.", "ESCUDERO, FRANCIS G.", "ANGARA-CASTILLO, BELLAFLOR J.", "FUENTEBELLA, FELIX WILLIAM B.", "BERSAMIN, LUIS JR. P.",]
[[authorsDetail]]
name = "Beltran, Crispin B."
nameCode = "Beltran"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "OCAMPO, SATUR"
nameCode = "Ocampo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAZA, LIZA"
nameCode = "Maza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CUENCO, ANTONIO V."
nameCode = "Cuenco"
date = ""
journalNo = "J065"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DEDURO, SIEGFRED D."
nameCode = "Deduro"
date = ""
journalNo = "J041"
sessionNo = "3RS"

[[coAuthorsDetail]]
name = "DE VENECIA, JOSE JR. C."
nameCode = "De Venecia"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESPINOSA, EMILIO JR. R."
nameCode = "Espinosa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GONZALES, NEPTALI II M."
nameCode = "Gonzales"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESCUDERO, FRANCIS G."
nameCode = "Escudero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANGARA-CASTILLO, BELLAFLOR J."
nameCode = "Angara-castillo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FUENTEBELLA, FELIX WILLIAM B."
nameCode = "Fuentebella"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BERSAMIN, LUIS JR. P."
nameCode = "Bersamin"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2001-12-19"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 90276
congress = 12
bill_no = "HR00337"
report = "00160"
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Approval without amendments ."
date_read = "2001-12-19"
date_report = "2002-01-23"

[secondReading]
id = 15052
congress = 12
bill_no = "HR00337"
adopted_resolution = "HR00126"
adopted_resolution_title = "RESOLUTION URGING THE COMMITTEE ON ENERGY TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, ON THE STAGGERED AND ALLEGEDLY INSUFFICIENT PRICE ROLLBACKS IMPLEMENTED BY LOCAL OIL COMPANIES DESPITE THE SUBSTANTIAL REDUCTION IN INTERNATIONAL OIL PRICES SINCE THE SEPTEMBER 11 WORLD TRADE CENTER INCIDENT, AND TO LOOK INTO ALLEGATIONS THAT OIL COMPANIES LED BY MAJOR PLAYERS SHELL, PETRON AND CALTEX HAVE PROFITED IMMENSELY FROM THESE MINIMAL ROLLBACKS TO THE DISADVANTAGE OF FILIPINO CONSUMERS"
date_calendared = "2002-01-23"
date_approved = "2002-01-23"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"
date_refferral = "2002-01-23"
file = "HR00126.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_12/HR00126.pdf"
