billNumber = "HR00294"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HR00294"
lastScraped = "2025-09-22T00:13:01.203499"
title = "HR00294"
longTitle = "RESOLUTION URGING THE VARIOUS DEPARTMENTS OF THE GOVERNMENT TO ALLOCATE FIVE PERCENT (5%) OF THEIR RESPECTIVE ANNUAL SAVINGS FOR THE TWENTY (20) DEPRESSED PROVINCES FOR THEIR POVERTY ALLEVIATION PROJECTS"
scope = "Local"
dateFiled = "2001-11-19"
status = "Substituted by HR00459"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Cruz, Benjamin A."
[[authorsDetail]]
name = "Cruz, Benjamin A."
nameCode = "Cruz"
date = ""
sequence = 0

[[committee]]
name = "20 PRIORITY PROVINCES"
type = "primary"
referralCode = "B517"
dateRead = "2001-11-26"

[[committee]]
name = "OVERSEAS WORKERS AFFAIRS"
type = "principal"
referralCode = "E513"

[firstReading]
id = 90233
congress = 12
bill_no = "HR00294"
referral = "B517"
ref_name = "20 PRIORITY PROVINCES"
sub_name = ""
date_read = "2001-11-26"
