billNumber = "HR00324"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HR00324"
lastScraped = "2025-09-22T00:13:01.209079"
title = "Proposal to Cut Current Wage Rate of Domestic Helpers in Hong Kong"
longTitle = "RESOLUTION CALLING ON THE SENSE OF THE LEGISLATURE OF THE HONG KONG ADMINISTRATIVE REGION OF THE PEOPLE'S REPUBLIC OF CHINA (PROC) TO CONSIDER THE DEMANDS OF THE FILIPINO DOMESTIC HELPERS IN HONG KONG IN REGARD TO THE HONG KONG GOVERNMENT'S PROPOSALTO CUT THE CURRENT WAGE RATE OF DOMESTIC HELPERS AND THE ABOLITION OF THEIR CURRENT LIVE-OUT ARRANGEMENTS"
scope = "National"
dateFiled = "2001-12-06"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 2001-12-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Barinaga, Roseller L."
coAuthors = [ "NIEVA, ERNESTO A.", "CUENCO, ANTONIO V.", "VILLANUEVA, EMMANUEL JOEL J.", "PUENTEBELLA, MONICO O.",]
[[authorsDetail]]
name = "Barinaga, Roseller L."
nameCode = "Barinaga"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "NIEVA, ERNESTO A."
nameCode = "Nieva"
date = ""
journalNo = "J046"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CUENCO, ANTONIO V."
nameCode = "Cuenco"
date = ""
journalNo = "J063"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "VILLANUEVA, EMMANUEL JOEL J."
nameCode = "Villanueva"
date = ""
journalNo = "J017"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "PUENTEBELLA, MONICO O."
nameCode = "Puentebella"
date = ""
journalNo = "J069"
sessionNo = "2RS"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "0521"
dateRead = "2001-12-11"

[[committee]]
name = "ENERGY"
type = "principal"
referralCode = "0510"

[firstReading]
id = 90263
congress = 12
bill_no = "HR00324"
report = "00146"
referral = "0521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = "LABOR AND EMPLOYMENT"
recomm = "Adoption withouit amendments ."
date_read = "2001-12-11"
date_ob = "2002-01-22"
date_report = "2002-01-10"
