billNumber = "HR01200"
billType = "HB"
congress = 12
apiCongressId = 12
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=12&q=HR01200"
lastScraped = "2025-09-22T00:13:01.416596"
title = "Mass Summary Execution of Peasants in Kananga, Leyte on April 16, 2003"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON CIVIL, POLITICAL AND HUMAN RIGHTS TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, INTO THE APPARENT MASS SUMMARY EXECUTION OF NINE PEASANTS, INCLUDING FOUR MINORS AND A WOMAN, IN KANANGA, LEYTE LAST APRIL 16, 2003 ALLEGEDLY BY ELEMENTS OF THE 19TH INFANTRY BATTALION OF THE PHILIPPINE ARMY UNDER COMMANDING OFFICER LT. COL. OSCAR LACTAO AND TO MAKE A DETERMINATION ON THE OBSERVANCE OF INTERNATIONAL HUMAN RIGHTS INSTRUMENTS AS WELL AS THE APPROPRIATE RECOMMENDATIONS AGAINST THE PERPETRATORS AND FOR INDEMNIFICATION FOR THE VICTIMS' FAMILIES"
scope = "Local"
dateFiled = "2003-06-18"
status = "Adopted Resolution (Pending with the committee on CIVIL, POLITICAL AND HUMAN RIGHTS since 2003-08-26)"
statusOrder = 5.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ocampo, Satur  C."
coAuthors = [ "BELTRAN, CRISPIN", "MAZA, LIZA", "DEDURO, SIEGFRED D.",]
[[authorsDetail]]
name = "Ocampo, Satur  C."
nameCode = "Ocampo"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "BELTRAN, CRISPIN"
nameCode = "Beltran"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAZA, LIZA"
nameCode = "Maza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEDURO, SIEGFRED D."
nameCode = "Deduro"
date = ""
journalNo = "J041"
sessionNo = "3RS"

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2003-07-30"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 91135
congress = 12
bill_no = "HR01200"
report = "1683"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Approval without amendments"
remarks = ""
date_read = "2003-07-30"
date_report = "2003-08-14"

[secondReading]
id = 15747
congress = 12
bill_no = "HR01200"
adopted_resolution = "HR00709"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2003-08-26"
date_approved = "2003-08-26"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"
concurrent_resolution_no = ""
date_refferral = "2003-08-26"
action_on_adopted_resolution = ""
