billNumber = "HBN-02258"
billType = "HBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=HBN-2258"
lastScraped = "2025-09-20T23:50:59.159470"
title = "LTO (CITY OF TANAUAN, PROVINCE OF BATANGAS)"
longTitle = "AN ACT ESTABLISHING A DISTRICT OFFICE OF THE LAND TRANSPORTATION OFFICE (LTO) IN THE CITY OF TANAUAN, PROVINCE OF BATANGAS AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Land Transportation Office (LTO)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/93798483!.pdf"
pdfFileName = "HBN-2258 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "11/20/2008"
action = "Filed in the Senate requesting for concurrence by Representative VICTORIA H. REYES as author;"

[[legislativeHistory]]
date = "11/25/2008"
action = "Read on First Reading and Referred to the Committee(s) on PUBLIC SERVICES and FINANCE;"

[status]
status = "Pending in the Committee"
date = "11/25/2008"

[committee]
name = "Public Services"
type = "primary"
