billNumber = "HBN-02227"
billType = "HBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=HBN-2227"
lastScraped = "2025-09-20T23:51:00.931265"
title = "CITY OF DAGUPAN, SPECIAL NONWORKING HOLIDAY"
longTitle = "AN ACT DECLARING JUNE 20 OF EVERY YEAR A SPECIAL NONWORKING HOLIDAY IN THE CITY OF DAGUPAN"
scope = "Local"
subject = [ "Holidays (Special Nonworking Holiday)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/105749383!.pdf"
pdfFileName = "HBN-2227 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "3/4/2009"
action = "Filed in the Senate requesting for concurrence by Representatives JOSE DE VENECIA JR. and GIORGIDI B. AGGABAO as authors;"

[[legislativeHistory]]
date = "4/13/2009"
action = "Read on First Reading and Referred to the Committee on LOCAL GOVERNMENT;"

[status]
status = "Pending in the Committee"
date = "4/13/2009"

[committee]
name = "Local Government"
type = "primary"
