billNumber = "HB00551"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB00551"
lastScraped = "2025-09-22T00:01:45.151220"
title = "HB00551"
longTitle = "AN ACT AMENDING CERTAIN PROVISIONS OF REPUBLIC ACT NO. 9372 ENTITLED 'AN ACT TO SECURE THE STATE AND PROTECT OUR PEOPLE FROM TERRORISM', OTHERWISE KNOWN AS THE 'HUMAN SECURITY ACT OF 2007'"
scope = "National"
dateFiled = "2019-07-01"
status = "Substituted by HB06875"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB00551.pdf"
fileSize = 5739730
author = "Biazon, Rozzano Rufino B."
coAuthors = [ "DALIPE, MANUEL JOSE M.", "TEJADA, JOSE \"PING-PING\" I.",]
[[authorsDetail]]
name = "Biazon, Rozzano Rufino B."
nameCode = "Biazon"
date = "2019-07-01"
sequence = 1

[[coAuthorsDetail]]
name = "DALIPE, MANUEL JOSE M."
nameCode = "Dalipe"
date = "2020-02-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "TEJADA, JOSE \"PING-PING\" I."
nameCode = "Tejada"
date = "2020-03-02"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "primary"
referralCode = "0529"
dateRead = "2019-07-23"

[[committee]]
name = "SENIOR CITIZENS"
type = "principal"
referralCode = "I505"

[[committee]]
name = "NATIONAL DEFENSE AND SECURITY"
type = "secondary"
referralCode = "0525"

[firstReading]
id = 19965
congress = 18
bill_no = "HB00551"
report = ""
comm_act = ""
referral = "0529"
ref_name = "PUBLIC ORDER AND SAFETY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-23"
