billNumber = "HB00002"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB00002"
lastScraped = "2025-09-22T00:01:44.988925"
title = "HB00002"
longTitle = "AN ACT CREATING THE DEPARTMENT OF OVERSEAS FILIPINO WORKERS (OFW) AND FOREIGN EMPLOYMENT, DEFINING ITS POWERS AND FUNCTIONS, APPROPRIATING FUNDS THEREFOR, RATIONALIZING THE ORGANIZATION AND FUNCTIONS OF GOVERNMENT AGENCIES RELATED TO MIGRATION, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2019-07-01"
status = "Substituted by HB05832"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB00002.pdf"
fileSize = 6306824
author = "Cayetano, Alan Peter \"CompaÃ±ero\" S."
coAuthors = [ "EBCAS, ADRIANO A.", "ROMAN, GERALDINE B.", "BUSTOS, JORGE ANTONIO P.", "HOFER, ANN K.", "VERGARA, ROSANNA \"RIA\"", "SAVELLANO, DEOGRACIAS VICTOR B.", "YAP, VICTOR A.", "SY-ALVARADO, JOSE ANTONIO R.", "GARCIA, PABLO JOHN F.", "GONZALEZ, CARLO LISANDRO L.", "CHATTO, EDGARDO M.", "ROBES, FLORIDA P.", "VILLANUEVA, NOEL L.", "OLIVAREZ, ERIC L.", "LARA, JOSEPH LASAM", "REVILLA, STRIKE B.", "VIOLAGO, MICAELA S.", "ZAMORA, WAY KURAT", "JIMENEZ, CESAR \"JAWO\" JR. I.", "SANGCOPAN, AMIHILDA J.", "HATAMAN, MUJIV S.", "DEL MAR, RAUL V.", "SUANSING, GING", "SALVADOR-TAMBUNTING, JOY MYRA", "FORTUN, LAWRENCE LEMUEL H.", "GOMEZ, LUCY T.", "PADIERNOS, JOSE GAY G.", "TOLENTINO, ABRAHAM \"BAMBOL\" N.", "VILLANUEVA, EDUARDO C.", "RIVERA, DOMINGO C.", "DALIPE, MANUEL JOSE M.", "LOPEZ, MANUEL LUIS T.", "TIANGCO, JOHN REYNALD M.", "ROMUALDO, XAVIER JESUS \"XJ\" D.", "LACSON-NOEL, JOSEPHINE VERONIQUE", "LOYOLA, DAHLIA A.", "GERON, RICO B.", "OUANO-DIZON, EMMARIE M.", "ERIGUEL, SANDRA YOUNG", "CUARESMA, LUISA LLOREN", "ZUBIRI, MANUEL ANTONIO F.", "VILLARICA, HENRY R.",]
[[authorsDetail]]
name = "Cayetano, Alan Peter \"CompaÃ±ero\" S."
nameCode = "Cayetano (A.P.)"
date = "2019-07-01"
sequence = 1

[[authorsDetail]]
name = "Cayetano, Ma. Laarni L."
nameCode = "Cayetano (M.L.)"
date = "2019-07-01"
sequence = 2

[[authorsDetail]]
name = "DUTERTE, PAOLO Z."
nameCode = "Duterte"
date = "2019-07-01"
sequence = 3

[[coAuthorsDetail]]
name = "EBCAS, ADRIANO A."
nameCode = "Ebcas"
date = "2019-09-04"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMAN, GERALDINE B."
nameCode = "Roman"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "BUSTOS, JORGE ANTONIO P."
nameCode = "Bustos"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "HOFER, ANN K."
nameCode = "Hofer"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "VERGARA, ROSANNA \"RIA\""
nameCode = "Vergara"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SAVELLANO, DEOGRACIAS VICTOR B."
nameCode = "Savellano"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "YAP, VICTOR A."
nameCode = "Yap (V.)"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SY-ALVARADO, JOSE ANTONIO R."
nameCode = "Sy-Alvarado"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "GARCIA, PABLO JOHN F."
nameCode = "Garcia (P.J.)"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "GONZALEZ, CARLO LISANDRO L."
nameCode = "Gonzalez"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "CHATTO, EDGARDO M."
nameCode = "Chatto"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ROBES, FLORIDA P."
nameCode = "Robes"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLANUEVA, NOEL L."
nameCode = "Villanueva (N.)"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "OLIVAREZ, ERIC L."
nameCode = "Olivarez"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "LARA, JOSEPH LASAM"
nameCode = "Lara"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "REVILLA, STRIKE B."
nameCode = "Revilla"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "VIOLAGO, MICAELA S."
nameCode = "Violago"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ZAMORA, WAY KURAT"
nameCode = "Zamora (W.K.)"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "JIMENEZ, CESAR \"JAWO\" JR. I."
nameCode = "Jimenez"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SANGCOPAN, AMIHILDA J."
nameCode = "Sangcopan"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "HATAMAN, MUJIV S."
nameCode = "Hataman"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "DEL MAR, RAUL V."
nameCode = "Del Mar"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SUANSING, GING"
nameCode = "Suansing (E.)"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SALVADOR-TAMBUNTING, JOY MYRA"
nameCode = "Salvador-Tambunting"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "FORTUN, LAWRENCE LEMUEL H."
nameCode = "Fortun"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "GOMEZ, LUCY T."
nameCode = "Torres-Gomez"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "PADIERNOS, JOSE GAY G."
nameCode = "Padiernos"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "TOLENTINO, ABRAHAM \"BAMBOL\" N."
nameCode = "Tolentino"
date = "2019-09-13"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLANUEVA, EDUARDO C."
nameCode = "Villanueva (E.)"
date = "2019-09-20"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "RIVERA, DOMINGO C."
nameCode = "Rivera"
date = "2019-09-20"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "DALIPE, MANUEL JOSE M."
nameCode = "Dalipe"
date = "2019-09-20"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "LOPEZ, MANUEL LUIS T."
nameCode = "Lopez (M.L.)"
date = "2019-09-20"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "TIANGCO, JOHN REYNALD M."
nameCode = "Tiangco"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMUALDO, XAVIER JESUS \"XJ\" D."
nameCode = "Romualdo"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "LACSON-NOEL, JOSEPHINE VERONIQUE"
nameCode = "Lacson-Noel"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "LOYOLA, DAHLIA A."
nameCode = "Loyola"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "GERON, RICO B."
nameCode = "Geron"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "OUANO-DIZON, EMMARIE M."
nameCode = "Ouano-Dizon"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ERIGUEL, SANDRA YOUNG"
nameCode = "Eriguel"
date = "2019-11-18"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "CUARESMA, LUISA LLOREN"
nameCode = "Cuaresma"
date = "2020-01-28"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ZUBIRI, MANUEL ANTONIO F."
nameCode = "Zubiri"
date = "2020-01-28"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLARICA, HENRY R."
nameCode = "Villarica"
date = "2020-01-28"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "primary"
referralCode = "0516"
dateRead = "2019-07-23"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[[committee]]
name = "OVERSEAS WORKERS AFFAIRS"
type = "secondary"
referralCode = "E513"

[firstReading]
id = 19416
congress = 18
bill_no = "HB00002"
report = ""
comm_act = ""
referral = "0516"
ref_name = "GOVERNMENT REORGANIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-23"
