billNumber = "HB01483"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB01483"
lastScraped = "2025-09-22T00:01:45.315602"
title = "HB01483"
longTitle = "AN ACT ALLOWING THE EXTENSION OF SERVICES OF RETIREABLE OFFICIALS AND EMPLOYEES IN THE GOVERNMENT SERVICE UNDER EXCEPTIONAL CIRCUMSTANCES"
scope = "National"
dateFiled = "2019-07-04"
status = "Pending with the Committee on CIVIL SERVICE AND PROFESSIONAL REGULATION since 2019-07-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB01483.pdf"
fileSize = 826936
author = "Chipeco, Joaquin Jr. M."
coAuthors = [ "SAVELLANO, DEOGRACIAS VICTOR B.",]
[[authorsDetail]]
name = "Chipeco, Joaquin Jr. M."
nameCode = "Chipeco"
date = "2019-07-04"
sequence = 1

[[coAuthorsDetail]]
name = "SAVELLANO, DEOGRACIAS VICTOR B."
nameCode = "Savellano"
date = "2019-09-24"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "primary"
referralCode = "0506"
dateRead = "2019-07-24"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 20892
congress = 18
bill_no = "HB01483"
report = ""
comm_act = ""
referral = "0506"
ref_name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-24"
