billNumber = "HB01472"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB01472"
lastScraped = "2025-09-22T00:01:45.313759"
title = "HB01472"
longTitle = "AN ACT STRENGTHENING THE DEPARTMENT OF SCIENCE AND TECHNOLOGY (DOST), DEFINING ITS FUNCTIONS AND REPEALING EXECUTIVE ORDER NO. 128 SERIES OF 1987, AS AMENDED APPROPRIATING FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2019-07-04"
status = "Pending with the Committee on GOVERNMENT REORGANIZATION since 2019-07-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB01472.pdf"
fileSize = 4283204
author = "Yu, Divina Grace C."
[[authorsDetail]]
name = "Yu, Divina Grace C."
nameCode = "Yu"
date = "2019-07-04"
sequence = 1

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "primary"
referralCode = "0516"
dateRead = "2019-07-24"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[[committee]]
name = "SCIENCE AND TECHNOLOGY"
type = "secondary"
referralCode = "0534"

[firstReading]
id = 20881
congress = 18
bill_no = "HB01472"
report = ""
comm_act = ""
referral = "0516"
ref_name = "GOVERNMENT REORGANIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-24"
