billNumber = "HB01474"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB01474"
lastScraped = "2025-09-22T00:01:45.314060"
title = "HB01474"
longTitle = "AN ACT PROVIDING FOR THE PROTECTION, REHABILITATION, AND SUSTAINABLE MANAGEMENT OF FOREST ECOSYSTEM AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2019-07-04"
status = "Substituted by HB08179"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB01474.pdf"
fileSize = 4060145
author = "Yu, Divina Grace C."
[[authorsDetail]]
name = "Yu, Divina Grace C."
nameCode = "Yu"
date = "2019-07-04"
sequence = 1

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "0526"
dateRead = "2019-07-24"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 20883
congress = 18
bill_no = "HB01474"
report = ""
comm_act = ""
referral = "0526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-24"
