billNumber = "HB02868"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB02868"
lastScraped = "2025-09-22T00:01:45.542711"
title = "HB02868"
longTitle = "AN ACT INCREASING THE MONTHLY SOCIAL PENSION OF SENIOR CITIZENS AND EXPANDING THE COVERAGE THEREOF"
scope = "National"
dateFiled = "2019-07-25"
status = "Substituted by HB09459"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB02868.pdf"
fileSize = 845070
author = "Tupas, Raul \"Boboy\" C."
coAuthors = [ "TEJADA, JOSE \"PING-PING\" I.", "GORRICETA, MICHAEL B.",]
[[authorsDetail]]
name = "Tupas, Raul \"Boboy\" C."
nameCode = "Tupas"
date = "2019-07-25"
sequence = 1

[[coAuthorsDetail]]
name = "TEJADA, JOSE \"PING-PING\" I."
nameCode = "Tejada"
date = "2019-09-11"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "GORRICETA, MICHAEL B."
nameCode = "Gorriceta"
date = "2019-09-11"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "SENIOR CITIZENS"
type = "primary"
referralCode = "I505"
dateRead = "2019-07-31"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 22277
congress = 18
bill_no = "HB02868"
report = ""
comm_act = ""
referral = "I505"
ref_name = "SENIOR CITIZENS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-31"
