billNumber = "HB02993"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB02993"
lastScraped = "2025-09-22T00:01:45.565996"
title = "HB02993"
longTitle = "AN ACT CREATING A COMPREHENSIVE LEGAL AID PROGRAM, RATIONALIZING STANDARDS FOR THE UNDERPRIVILEGED AND UNDERSERVED, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2019-07-29"
status = "Pending with the Committee on JUSTICE since 2019-08-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB02993.pdf"
fileSize = 3085487
author = "Nograles, Juan Fidel Felipe F."
[[authorsDetail]]
name = "Nograles, Juan Fidel Felipe F."
nameCode = "Nograles (J.F.F.)"
date = "2019-07-29"
sequence = 1

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2019-08-05"

[[committee]]
name = "TOURISM"
type = "principal"
referralCode = "0538"

[firstReading]
id = 22402
congress = 18
bill_no = "HB02993"
report = ""
comm_act = ""
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-08-05"
