billNumber = "HB02880"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB02880"
lastScraped = "2025-09-22T00:01:45.545105"
title = "HB02880"
longTitle = "AN ACT ESTABLISHING A GENERAL HOSPITAL IN ZAMBOANGA SIBUGAY, UNDER THE FULL ADMINISTRATIVE AND TECHNICAL SUPERVISION OF THE DEPARTMENT OF HEALTH, WHICH SHALL BE KNOWN AS THE ZAMBOANGA SIBUGAY MEDICAL CENTER, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2019-07-25"
status = "Substituted by HB10362"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB02880.pdf"
fileSize = 404067
author = "Hofer, Ann K."
[[authorsDetail]]
name = "Hofer, Ann K."
nameCode = "Hofer"
date = "2019-07-25"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2019-07-31"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 22289
congress = 18
bill_no = "HB02880"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-07-31"
