billNumber = "HB03033"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB03033"
lastScraped = "2025-09-22T00:01:45.574231"
title = "HB03033"
longTitle = "AN ACT REQUIRING THE REGISTRATION OF ALL USERS OF SUBSCRIBER IDENTITY MODULE (SIM) CARDS"
scope = "National"
dateFiled = "2019-07-29"
status = "Substituted by HB05793"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB03033.pdf"
fileSize = 3470290
author = "Vargas, Alfred D."
[[authorsDetail]]
name = "Vargas, Alfred D."
nameCode = "Vargas"
date = "2019-07-29"
sequence = 1

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "primary"
referralCode = "E504"
dateRead = "2019-08-05"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 22442
congress = 18
bill_no = "HB03033"
report = ""
comm_act = ""
referral = "E504"
ref_name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-08-05"
