billNumber = "HB03654"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB03654"
lastScraped = "2025-09-22T00:01:45.680814"
title = "HB03654"
longTitle = "AN ACT STRENGTHENING THE ROLES AND FUNCTIONS OF THE PHILIPPINE ECONOMIC ZONE AUTHORITY (PEZA) TO ACCELERATE COUNTRYSIDE DEVELOPMENT THROUGH ROBUST CREATION OF SPECIAL ECONOMIC ZONES IN RURAL AND NEW GROWTH AREAS, ENHANCING THE INCENTIVES THEREOF AND AMENDING FOR THIS PURPOSE, REPUBLIC ACT NO. 7916, OTHERWISE KNOWN AS \\\"THE SPECIAL ECONOMIC ZONE ACT OF 1995\\\", AS AMENDED BY RA 8748"
scope = "National"
dateFiled = "2019-08-07"
status = "Pending with the Committee on ECONOMIC AFFAIRS since 2019-08-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB03654.pdf"
fileSize = 4567266
author = "Jalosjos, Romeo Jr. M."
coAuthors = [ "GUICO, RAMON III V.", "SY-ALVARADO, JOSE ANTONIO R.",]
[[authorsDetail]]
name = "Jalosjos, Romeo Jr. M."
nameCode = "Jalosjos"
date = "2019-08-07"
sequence = 1

[[coAuthorsDetail]]
name = "GUICO, RAMON III V."
nameCode = "Guico"
date = "2019-09-03"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SY-ALVARADO, JOSE ANTONIO R."
nameCode = "Sy-Alvarado"
date = "2019-10-07"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "primary"
referralCode = "0536"
dateRead = "2019-08-14"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "secondary"
referralCode = "0539"

[firstReading]
id = 23063
congress = 18
bill_no = "HB03654"
report = ""
comm_act = ""
referral = "0536"
ref_name = "ECONOMIC AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-08-14"
