billNumber = "HB03781"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB03781"
lastScraped = "2025-09-22T00:01:45.702957"
title = "HB03781"
longTitle = "AN ACT PROVIDING FOR AN EXPANDED VOUCHER SYSTEM IN THE ELEMENTARY AND SECONDARY EDUCATION, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 6728, AS AMENDED"
scope = "National"
dateFiled = "2019-08-08"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2019-08-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB03781.pdf"
fileSize = 3866543
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "VILLARICA, HENRY R.",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez"
date = "2019-08-08"
sequence = 1

[[coAuthorsDetail]]
name = "VILLARICA, HENRY R."
nameCode = "Villarica"
date = "2021-05-21"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2019-08-14"

[[committee]]
name = "WELFARE OF CHILDREN"
type = "principal"
referralCode = "F501"

[firstReading]
id = 23190
congress = 18
bill_no = "HB03781"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-08-14"
