billNumber = "HB06601"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB06601"
lastScraped = "2025-09-22T00:01:46.307904"
title = "HB06601"
longTitle = "AN ACT ESTABLISHING A NATIONAL HIGH SCHOOL IN BARANGAY POBLACION, MUNICIPALITY OF KADINGILAN, PROVINCE OF BUKIDNON TO BE KNOWN AS POBLACION NATIONAL HIGH SCHOOL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2020-03-12"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2020-05-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB06601.pdf"
fileSize = 986035
author = "Zubiri, Manuel  F."
coAuthors = [ "GONZALEZ, CARLO LISANDRO L.", "LUSOTAN, MACNELL",]
[[authorsDetail]]
name = "Zubiri, Manuel  F."
nameCode = "Zubiri"
date = "2020-03-12"
sequence = 1

[[coAuthorsDetail]]
name = "GONZALEZ, CARLO LISANDRO L."
nameCode = "Gonzalez"
date = "2021-03-04"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "LUSOTAN, MACNELL"
nameCode = "Lusotan"
date = "2021-03-04"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2020-05-04"

[[committee]]
name = "SOCIAL SERVICES"
type = "principal"
referralCode = "0535"

[firstReading]
id = 26008
congress = 18
bill_no = "HB06601"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-05-04"
