billNumber = "HB07041"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB07041"
lastScraped = "2025-09-22T00:01:46.421206"
title = "HB07041"
longTitle = "AN ACT GRANTING FAIRWAVES BROADCASTING NETWORK FRANCHISE TO\r\nCONSTRUCT, MAINTAIN, ESTABLISH AND OPERATE RADIO AND TELEVISION\r\nSTATIONS IN VIGAN, ILOCOS SUR, AND OTHER AREAS IN THE PHILIPPINES\r\nWHERE FREQUENCIES AND/OR CHANNELS ARE AVAILABLE FOR RADIO\r\nAND TELEVISION BROADCASTING"
scope = "National"
dateFiled = "2020-06-29"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 2020-07-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB07041.pdf"
fileSize = 3155015
author = "Savellano, Deogracias Victor \"DV\" B."
[[authorsDetail]]
name = "Savellano, Deogracias Victor \"DV\" B."
nameCode = "Savellano"
date = "2020-06-29"
sequence = 1

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2020-07-28"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 26448
congress = 18
bill_no = "HB07041"
report = ""
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-07-28"
