billNumber = "HB07212"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB07212"
lastScraped = "2025-09-22T00:01:46.450158"
title = "HB07212"
longTitle = "AN ACT PROVIDING FOR COVID-19 RESPONSE AND RECOVERY INTERVENTIONS AND PROVIDING MECHANISMS TO ACCELERATE THE RECOVERY AND BOLSTER THE RESILIENCY OF THE PHILIPPINE ECONOMY, PROVIDING FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2020-07-30"
status = "Pending with the Committee on DEFEAT COVID-19 AD-HOC COMMITTEE since 2020-08-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB07212.pdf"
fileSize = 5173729
author = "Noel, Florencio Gabriel \"Bem\" G."
[[authorsDetail]]
name = "Noel, Florencio Gabriel \"Bem\" G."
nameCode = "Noel"
date = "2020-07-30"
sequence = 1

[[authorsDetail]]
name = "Lacson-Noel, Josephine Veronique \"Jaye\" R."
nameCode = "Lacson-Noel"
date = "2020-07-30"
sequence = 2

[[committee]]
name = "DEFEAT COVID-19 AD-HOC COMMITTEE"
type = "primary"
referralCode = "J503"
dateRead = "2020-08-05"

[[committee]]
name = "BANKS AND FINANCIAL INTERMEDIARIES"
type = "principal"
referralCode = "0505"

[firstReading]
id = 26619
congress = 18
bill_no = "HB07212"
report = ""
comm_act = ""
referral = "J503"
ref_name = "DEFEAT COVID-19 AD-HOC COMMITTEE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-08-05"
