billNumber = "HB07907"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB07907"
lastScraped = "2025-09-22T00:01:46.595887"
title = "HB07907"
longTitle = "AN ACT GRANTING BIRTHDAY CASH GIFT AMOUNTING TO ONE THOUSAND PESOS\r\n(PHP 1,000.00) TO REGISTERED PERSONS WITH DISABILITIES (PWDs)"
scope = "National"
dateFiled = "2020-10-20"
status = "Pending with the Committee on PERSONS WITH DISABILITIES since 2020-11-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB07907.pdf"
fileSize = 1027073
author = "Cabochan, Manuel III DG."
coAuthors = [ "SALVADOR-TAMBUNTING, JOY MYRA",]
[[authorsDetail]]
name = "Cabochan, Manuel III DG."
nameCode = "Cabochan"
date = "2020-10-20"
sequence = 1

[[coAuthorsDetail]]
name = "SALVADOR-TAMBUNTING, JOY MYRA"
nameCode = "Salvador-Tambunting"
date = "2021-02-26"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "PERSONS WITH DISABILITIES"
type = "primary"
referralCode = "J501"
dateRead = "2020-11-16"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 27312
congress = 18
bill_no = "HB07907"
report = ""
comm_act = ""
referral = "J501"
ref_name = "PERSONS WITH DISABILITIES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-11-16"
