billNumber = "HB07709"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB07709"
lastScraped = "2025-09-22T00:01:46.548789"
title = "HB07709"
longTitle = "AN ACT REDUCING FOOD WASTE THROUGH FOOD DONATIONS AND FOOD WASTE RECYCLING"
scope = "National"
dateFiled = "2020-09-18"
status = "Substituted by HB07956"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB07709.pdf"
fileSize = 2039791
author = "Salvador-Tambunting, Joy Myra"
coAuthors = [ "BORDADO, GABRIEL JR.",]
[[authorsDetail]]
name = "Salvador-Tambunting, Joy Myra"
nameCode = "Salvador-Tambunting"
date = "2020-09-18"
sequence = 1

[[coAuthorsDetail]]
name = "BORDADO, GABRIEL JR."
nameCode = "Bordado"
date = "2020-09-28"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "FOOD SECURITY"
type = "primary"
referralCode = "B513"
dateRead = "2020-09-22"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 27114
congress = 18
bill_no = "HB07709"
report = ""
comm_act = ""
referral = "B513"
ref_name = "FOOD SECURITY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-09-22"
