billNumber = "HB08787"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB08787"
lastScraped = "2025-09-22T00:01:46.804214"
title = "HB08787"
longTitle = "AN ACT GRANTING PHILIPPINE CITIZENSHIP TO ZHENGHUA ZHANG"
scope = "National"
dateFiled = "2021-02-22"
status = "Bill withdrawn on 2021-10-12"
statusOrder = 2.7
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB08787.pdf"
fileSize = 990825
author = "Pineda, Enrico A."
[[authorsDetail]]
name = "Pineda, Enrico A."
nameCode = "Pineda"
date = "2021-02-22"
sequence = 1

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2021-02-23"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 28192
congress = 18
bill_no = "HB08787"
report = ""
comm_act = ""
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2021-02-23"
