billNumber = "HB09917"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB09917"
lastScraped = "2025-09-22T00:01:47.082569"
title = "Establishing In The City Of Meycauayan, Province Of Bulacan, A Tertiary Hospital To Be Known As The “ospital Ng Meycauayan”"
longTitle = "AN ACT ESTABLISHING IN THE CITY OF MEYCAUAYAN, PROVINCE OF BULACAN, A TERTIARY HOSPITAL TO BE KNOWN AS THE “OSPITAL NG MEYCAUAYAN”, AND APPROPRIATING FUNDS THEREFOR\r\n"
scope = "Local"
dateFiled = "2021-08-02"
status = "Republic Act RA11878 enacted on 2022-06-29"
statusOrder = 34.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "VILLARICA, LINABELLE RUTH R."
[[authorsDetail]]
name = "VILLARICA, LINABELLE RUTH R."
nameCode = "Villarica"
date = "2021-08-02"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2021-08-03"

[[committee]]
name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
type = "principal"
referralCode = "E510"

[[motherBills]]
bill_no = "HB01668"
sequence = 1
date = "2021-08-02"
flag = "S"

[[substitutedBills]]
bill_no = "HB01668"
sequence = 1
date = "2021-08-02"
flag = "S"

[firstReading]
id = 29322
congress = 18
bill_no = "HB09917"
report = "01101"
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = "HEALTH, APPROPRIATIONS"
recomm = "Recommending its approval in substitution of House Bill No. 1668"
remarks = ""
file = "CR01101.pdf"
date_read = "2021-08-03"
date_ob = "2021-08-03"
date_fri = "2021-08-24"
date_report = "2021-08-02"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_18/CR01101.pdf"

[secondReading]
id = 2982
congress = 18
bill_no = "HB09917"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_approved = "2021-08-25"
recommitted_bill = ""
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
date_debate_closed = "2021-08-25"
date_amend_closed = "2021-08-25"

[thirdReading]
id = 12693
congress = 18
bill_no = "HB09917"
title_third = "AN ACT ESTABLISHING IN THE CITY OF MEYCAUAYAN, PROVINCE OF BULACAN,\r\nA TERTIARY HOSPITAL TO BE KNOWN AS THE \"OSPITAL NG MEYCAUAYAN\",\r\nAND APPROPRIATING FUNDS THEREFOR          "
date_dist = "2021-08-26"
date_adopt = "2021-08-31"
remarks = "Date passed by the Senate was received by the House on May 31, 2022. Transmitted to the Office  of the President through the PLLO on June 27, 2022.             "
no_yeas = 210
no_nays = 0
no_abstent = 0
date_trans = "2021-09-01"
date_rec = "2021-09-01"
date_spass = "2022-05-30"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = "A"
cc_yeas = 0
cc_nays = 0
cc_absten = 0
dte_signedenroll = "2022-06-23"
dte_copyenroll_sen = "2022-06-20"
dte_transp = "2022-06-27"
dte_actedp = "2022-06-29"
file = "HBT9917.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_18/HBT9917.pdf"
