billNumber = "HB09530"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB09530"
lastScraped = "2025-09-22T00:01:46.996840"
title = "HB09530"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF A BICOL-SOUTH LUZON SUB-NATIONAL REFERENCE LABORATORY AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2021-05-31"
status = "Pending with the Committee on HEALTH since 2021-06-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB09530.pdf"
fileSize = 224973
author = "Bordado, Gabriel Jr. H."
[[authorsDetail]]
name = "Bordado, Gabriel Jr. H."
nameCode = "Bordado"
date = "2021-05-31"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2021-06-02"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "principal"
referralCode = "0539"

[firstReading]
id = 28935
congress = 18
bill_no = "HB09530"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2021-06-02"
