billNumber = "HB10552"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HB10552"
lastScraped = "2025-09-22T00:01:47.246235"
title = "HB10552"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF LOCAL STUDIES CENTERS IN STATE UNIVERSITIES AND COLLEGES (SUCs) THROUGHOUT THE PHILIPPINES, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2021-11-26"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2021-12-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HB10552.pdf"
fileSize = 429627
author = "Legarda, Loren"
[[authorsDetail]]
name = "Legarda, Loren"
nameCode = "Legarda"
date = "2021-11-26"
sequence = 1

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2021-12-01"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 29956
congress = 18
bill_no = "HB10552"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2021-12-01"
