billNumber = "HJR0037"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HJR0037"
lastScraped = "2025-09-22T00:01:47.336540"
title = "HJR0037"
longTitle = "HOUSE JOINT RESOLUTION TO IMMEDIATELY TERMINATE OR WITHDRAW EXECUTIVE ORDER NO. 128, SERIES OF 2021, TEMPORARILY MODIFYING THE RATES OF IMPORT DUTY ON FRESH, CHILLED OR FROZEN PORK MEAT, AS WELL AS TO REJECT THE STAGGERING EXPANSION OF THE MINIMUM ACCESS VOLUME OF PORK IMPORTS"
scope = "National"
dateFiled = "2021-04-14"
status = "Pending with the Committee on WAYS AND MEANS since 2021-05-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HJR0037.pdf"
fileSize = 590829
author = "Zarate, Carlos Isagani T."
coAuthors = [ "CUEVA, LEO RAFAEL M.", "VILLANUEVA, NOEL L.", "ESCUDERO, EVELINA G.", "FARINAS, RIA CHRISTINA G.", "GORRICETA, MICHAEL B.", "TY ALAN", "CRISOLOGO, ANTHONY PETER D.", "TY, DIEGO C.", "ALONTE-NAGUIAT, LEN B.", "SANTOS-RECTO, VILMA",]
[[authorsDetail]]
name = "Zarate, Carlos Isagani T."
nameCode = "Zarate"
date = "2021-04-14"
sequence = 1

[[authorsDetail]]
name = "Arenas, Rose Marie \"Baby\" J."
nameCode = "Arenas"
date = "2021-04-14"
sequence = 2

[[authorsDetail]]
name = "Belmonte, Jose Christopher Y."
nameCode = "Belmonte"
date = "2021-04-14"
sequence = 3

[[authorsDetail]]
name = "Brosas, Arlene D."
nameCode = "Brosas"
date = "2021-04-14"
sequence = 4

[[authorsDetail]]
name = "Cabatbat, Argel Joseph T."
nameCode = "Cabatbat"
date = "2021-04-14"
sequence = 5

[[authorsDetail]]
name = "Castro, France L."
nameCode = "Castro (F.L.)"
date = "2021-04-14"
sequence = 6

[[authorsDetail]]
name = "Cullamat, Eufemia \"Ka Femia\" C."
nameCode = "Cullamat"
date = "2021-04-14"
sequence = 7

[[authorsDetail]]
name = "DEFENSOR, LORENZ R."
nameCode = "Defensor (L.)"
date = "2021-04-14"
sequence = 8

[[authorsDetail]]
name = "ELAGO, SARAH JANE I."
nameCode = "Elago"
date = "2021-04-14"
sequence = 9

[[authorsDetail]]
name = "ERICE, EDGAR R."
nameCode = "Erice"
date = "2021-04-14"
sequence = 10

[[authorsDetail]]
name = "Gaite, Ferdinand R."
nameCode = "Gaite"
date = "2021-04-14"
sequence = 11

[[authorsDetail]]
name = "GARIN, JANETTE L."
nameCode = "Garin (J.)"
date = "2021-04-14"
sequence = 12

[[authorsDetail]]
name = "Geron, Rico B."
nameCode = "Geron"
date = "2021-04-14"
sequence = 13

[[authorsDetail]]
name = "FLORES, JONATHAN KEITH T."
nameCode = "Flores"
date = "2021-04-14"
sequence = 14

[[authorsDetail]]
name = "Lagman, Edcel C."
nameCode = "Lagman"
date = "2021-04-14"
sequence = 15

[[authorsDetail]]
name = "Roman, Geraldine B."
nameCode = "Roman"
date = "2021-04-14"
sequence = 16

[[coAuthorsDetail]]
name = "CUEVA, LEO RAFAEL M."
nameCode = "Cueva"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLANUEVA, NOEL L."
nameCode = "Villanueva (N.)"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ESCUDERO, EVELINA G."
nameCode = "Escudero"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "FARINAS, RIA CHRISTINA G."
nameCode = "Fariñas (R.C.)"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "GORRICETA, MICHAEL B."
nameCode = "Gorriceta"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "TY ALAN"
nameCode = "Ty (A.)"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "CRISOLOGO, ANTHONY PETER D."
nameCode = "Crisologo"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "TY, DIEGO C."
nameCode = "Ty (D.)"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "ALONTE-NAGUIAT, LEN B."
nameCode = "Alonte"
date = "2021-05-17"
journalNo = "J000"
sessionNo = ""

[[coAuthorsDetail]]
name = "SANTOS-RECTO, VILMA"
nameCode = "Santos-Recto"
date = "2021-05-26"
journalNo = "J000"
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "2021-05-17"

[firstReading]
id = 30325
congress = 18
bill_no = "HJR0037"
report = ""
comm_act = ""
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2021-05-17"
