billNumber = "HR00390"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR00390"
lastScraped = "2025-09-22T00:01:47.410785"
title = "HR00390"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON ENERGY TO CONDUCT AN INQUIRY IN AID OF LEGISLATION ON THE SUDDEN INCREASE IN FUEL PRICES FOR SEPTEMBER 2019, WITH AN END VIEW OF PASSING LEGISLATION TO STABILIZE FUEL PRICES OR AMEND THE APPROPRIATE LAWS"
scope = "National"
dateFiled = "2019-09-30"
status = "Substituted by HB10823"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR00390.pdf"
fileSize = 796666
author = "Quimbo, Stella Luz A."
[[authorsDetail]]
name = "Quimbo, Stella Luz A."
nameCode = "Quimbo"
date = "2019-09-30"
sequence = 1

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "2019-10-02"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 30718
congress = 18
bill_no = "HR00390"
report = ""
comm_act = ""
referral = "0510"
ref_name = "ENERGY"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2019-11-27"
date_read = "2019-10-02"
