billNumber = "HR00666"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR00666"
lastScraped = "2025-09-22T00:01:47.462461"
title = "HR00666"
longTitle = "RESOLUTION STRONGLY URGING PRESIDENT RODRIGO ROA R. DUTERTE TO IMMEDIATELY RELEASE OF ALL POLITICAL PRISONERS, INCLUDING THE ELDERLY, THOSE WITH ILLNESSES, THE WOMEN, AND THOSE IMPRISONED FOR MORE THAN (10) YEARS, FOR JUST AND HUMANITARIAN REASONS, AND, THE RELEASE OF DETAINED CONSULTANTS OF THE NATIONAL DEMOCRATIC FRONT OF THE PHILIPPINES (NDFP) IN COMPLIANCE WITH THE JOINT AGREEMENT ON SAFETY AND IMMUNITY GUARANTEES (JASIG) SIGNED BY THE GOVERNMENT OF THE REPUBLIC OF THE PHILIPPINES (GRP) AND THE NATIONAL DEMOCRATIC FRONT OF THE PHILIPPINES (NDFP) AS A GOODWILL MEASURE IN THE RESUMPTION OF PEACE NEGOTIATIONS"
scope = "National"
dateFiled = "2020-01-27"
status = "Pending with the Committee on PEACE, RECONCILIATION AND UNITY since 2020-02-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR00666.pdf"
fileSize = 1626362
author = "Zarate, Carlos Isagani T."
[[authorsDetail]]
name = "Zarate, Carlos Isagani T."
nameCode = "Zarate"
date = "2020-01-27"
sequence = 1

[[authorsDetail]]
name = "Gaite, Ferdinand R."
nameCode = "Gaite"
date = "2020-01-27"
sequence = 2

[[authorsDetail]]
name = "Cullamat, Eufemia \"Ka Femia\" C."
nameCode = "Cullamat"
date = "2020-01-27"
sequence = 3

[[authorsDetail]]
name = "Castro, France L."
nameCode = "Castro (F.L.)"
date = "2020-01-27"
sequence = 4

[[authorsDetail]]
name = "Brosas, Arlene D."
nameCode = "Brosas"
date = "2020-01-27"
sequence = 5

[[authorsDetail]]
name = "ELAGO, SARAH JANE I."
nameCode = "Elago"
date = "2020-01-27"
sequence = 6

[[committee]]
name = "PEACE, RECONCILIATION AND UNITY"
type = "primary"
referralCode = "E512"
dateRead = "2020-02-03"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 30985
congress = 18
bill_no = "HR00666"
report = ""
comm_act = ""
referral = "E512"
ref_name = "PEACE, RECONCILIATION AND UNITY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-02-03"
