billNumber = "HR01849"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR01849"
lastScraped = "2025-09-22T00:01:47.691426"
title = "HR01849"
longTitle = "RESOLUTION\r\nURGING THE PRESIDENT OF THE PHILIPPINES TO DESIGNATE EVERY 12TH OF JUNE AS THE “PHILIPPINE TRADITIONAL WEAR DAY” TO FURTHER PROMOTE FILIPINO CULTURAL HERITAGE AND TRADITIONS"
scope = "National"
dateFiled = "2021-06-06"
status = "Adopted as Resolution No. HR00199 on 2021-08-31"
statusOrder = 15.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Gomez, Lucy T."
[[authorsDetail]]
name = "Gomez, Lucy T."
nameCode = "Torres-Gomez"
date = "2021-06-06"
sequence = 1

[[authorsDetail]]
name = "ROMULO, ROMAN T."
nameCode = "Romulo"
date = "2021-06-06"
sequence = 2

[[authorsDetail]]
name = "De Venecia, Christopher V.P."
nameCode = "De Venecia"
date = "2021-06-06"
sequence = 3

[[authorsDetail]]
name = "Escudero, Evelina G."
nameCode = "Escudero"
date = "2021-06-06"
sequence = 4

[[authorsDetail]]
name = "Lazatin, Carmelo \"Jon\" II B."
nameCode = "Lazatin"
date = "2021-06-06"
sequence = 5

[[authorsDetail]]
name = "Reyes, Allan Benedict S."
nameCode = "Reyes"
date = "2021-06-06"
sequence = 6

[[authorsDetail]]
name = "BASCUG, ALFELITO \"ALFEL\" M."
nameCode = "Bascug"
date = "2021-06-06"
sequence = 7

[[authorsDetail]]
name = "DALOG, MAXIMO Y., JR."
nameCode = "Dalog"
date = "2021-06-06"
sequence = 8

[[authorsDetail]]
name = "Cuaresma, Luisa Lloren"
nameCode = "Cuaresma"
date = "2021-06-06"
sequence = 9

[[authorsDetail]]
name = "Abueg-Zaldivar, Cyrille \"Beng\" F."
nameCode = "Abueg-Zaldivar"
date = "2021-06-06"
sequence = 10

[[authorsDetail]]
name = "CARI, CARL NICOLAS C."
nameCode = "Cari"
date = "2021-06-06"
sequence = 11

[[authorsDetail]]
name = "Loyola, Dahlia A."
nameCode = "Loyola"
date = "2021-06-06"
sequence = 12

[[authorsDetail]]
name = "ESPINA, GERARDO \"GERRYBOY\" JR. J."
nameCode = "Espina"
date = "2021-06-06"
sequence = 13

[[authorsDetail]]
name = "Lusotan, Macnell M."
nameCode = "Lusotan"
date = "2021-06-06"
sequence = 14

[[authorsDetail]]
name = "Mariano-Hernandez, Ruth"
nameCode = "Mariano-Hernandez"
date = "2021-06-06"
sequence = 15

[[authorsDetail]]
name = "Violago, Micaela S."
nameCode = "Violago"
date = "2021-06-06"
sequence = 16

[[authorsDetail]]
name = "Cabredo, Fernando T."
nameCode = "Cabredo"
date = "2021-06-06"
sequence = 17

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2021-07-28"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[motherBills]]
bill_no = "HR01374"
sequence = 1
date = "2021-06-06"
flag = "S"

[[substitutedBills]]
bill_no = "HR01374"
sequence = 1
date = "2021-06-06"
flag = "S"

[firstReading]
id = 32167
congress = 18
bill_no = "HR01849"
report = "01051"
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = "BASIC EDUCATION AND CULTURE"
recomm = "Recommending its adoption in substitution of House Resolution No. 1374"
remarks = ""
file = "CR01051.pdf"
date_read = "2021-07-28"
date_ob = "2021-07-28"
date_report = "2021-06-06"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_18/CR01051.pdf"

[secondReading]
id = 2939
congress = 18
bill_no = "HR01849"
adopted_resolution = "HR00199"
adopted_resolution_title = "RESOLUTION URGING THE PRESIDENT OF THE PHILIPPINES TO DESIGNATE EVERY 12TH OF JUNE AS THE “PHILIPPINE TRADITIONAL WEAR DAY” TO FURTHER PROMOTE FILIPINO CULTURAL HERITAGE AND TRADITIONS"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2021-08-03"
date_approved = "2021-08-31"
recommitted_bill = ""
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
file = "HR00199.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_18/HR00199.pdf"
