billNumber = "HR01267"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR01267"
lastScraped = "2025-09-22T00:01:47.583111"
title = "HR01267"
longTitle = "A RESOLUTION STRONGLY URGING THE HOUSE OF REPRESENTATIVES TO INCREASE THE FUNDS TO BE APPROPRIATED TO THE NATIONAL ANTI-POVERTY COMMISSION FOR FISCAL YEAR 2021 FOR THE EFFECTIVE IMPLEMENTATION OF THE SOCIAL\r\nREFORM AGENDA"
scope = "National"
dateFiled = "2020-10-01"
status = "Pending with the Committee on APPROPRIATIONS since 2020-10-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR01267.pdf"
fileSize = 1266856
author = "Matugas, Francisco Jose \"Bingo\" II F. CPA, CESO, LLB"
[[authorsDetail]]
name = "Matugas, Francisco Jose \"Bingo\" II F. CPA, CESO, LLB"
nameCode = "Matugas"
date = "2020-10-01"
sequence = 1

[[authorsDetail]]
name = "Campos, Luis Jr. N."
nameCode = "Campos"
date = "2020-10-01"
sequence = 2

[[committee]]
name = "APPROPRIATIONS"
type = "primary"
referralCode = "0504"
dateRead = "2020-10-05"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 31586
congress = 18
bill_no = "HR01267"
report = ""
comm_act = ""
referral = "0504"
ref_name = "APPROPRIATIONS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2020-10-05"
