billNumber = "HR02138"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR02138"
lastScraped = "2025-09-22T00:01:47.763187"
title = "HR02138"
longTitle = "RESOLUTION URGING THE HOUSE OF REPRESENTATIVES, THROUGH THE COMMITTEE ON HEALTH AND THE COMMITTEE ON GOOD GOVERNMENT AND PUBLIC ACCOUNTABILITY, TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, ON THE REPORTED UNPAID COVID 19 PANDEMIC- RELATED BENEFITS TO HEALTH WORKERS, AND TO MANDATE THE IMMEDIATE DISTRIBUTION OF SUCH TO ALL HEALTH WORKERS IN PUBLIC AND PRIVATE FACILITIES"
scope = "National"
dateFiled = "2021-08-17"
status = "Pending with the Committee on HEALTH since 2021-09-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR02138.pdf"
fileSize = 848987
author = "Gaite, Ferdinand R."
[[authorsDetail]]
name = "Gaite, Ferdinand R."
nameCode = "Gaite"
date = "2021-08-17"
sequence = 1

[[authorsDetail]]
name = "Zarate, Carlos Isagani T."
nameCode = "Zarate"
date = "2021-08-17"
sequence = 2

[[authorsDetail]]
name = "Cullamat, Eufemia \"Ka Femia\" C."
nameCode = "Cullamat"
date = "2021-08-17"
sequence = 3

[[authorsDetail]]
name = "Castro, France L."
nameCode = "Castro (F.L.)"
date = "2021-08-17"
sequence = 4

[[authorsDetail]]
name = "Brosas, Arlene D."
nameCode = "Brosas"
date = "2021-08-17"
sequence = 5

[[authorsDetail]]
name = "ELAGO, SARAH JANE I."
nameCode = "Elago"
date = "2021-08-17"
sequence = 6

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2021-08-23"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 32455
congress = 18
bill_no = "HR02138"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2021-09-01"
date_read = "2021-08-23"
