billNumber = "HR02606"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR02606"
lastScraped = "2025-09-22T00:01:47.876386"
title = "HR02606"
longTitle = "A RESOLUTION EXPRESSING THE PROFOUND SYMPATHY OF THE HOUSE OF REPRESENTATIVES TO THE FAMILY AND FRIENDS OF JESUSA PURIFICATION LEVY SONORA ALSO KNOWN AS SUSAN ROCES"
scope = "National"
dateFiled = "2022-05-31"
status = "Pending with the Committee on RULES since 2022-06-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR02606.pdf"
fileSize = 422209
author = "Sakaluran, Princess Rihan M."
[[authorsDetail]]
name = "Sakaluran, Princess Rihan M."
nameCode = "Sakaluran"
date = "2022-05-31"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2022-06-01"

[firstReading]
id = 32923
congress = 18
bill_no = "HR02606"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-06-01"
