billNumber = "HR02511"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR02511"
lastScraped = "2025-09-22T00:01:47.858368"
title = "HR02511"
longTitle = "A RESOLUTION URGING THE DEPARTMENT OF EDUCATION TO IMMEDIATELY EXPLORE SOLUTIONS AIMED AT SUPPORTING PRIVATE SCHOOLS DURING THE COVID-19 PANDEMIC TO AVERT AN EDUCATION CRISIS AMONG FILIPINO LEARNERS"
scope = "National"
dateFiled = "2022-03-05"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2022-05-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR02511.pdf"
fileSize = 333316
author = "Vargas, Alfred D."
[[authorsDetail]]
name = "Vargas, Alfred D."
nameCode = "Vargas"
date = "2022-03-05"
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2022-05-23"

[firstReading]
id = 32828
congress = 18
bill_no = "HR02511"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-05-23"
