billNumber = "HR02334"
billType = "HB"
congress = 18
apiCongressId = 18
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=18&q=HR02334"
lastScraped = "2025-09-22T00:01:47.799238"
title = "HR02334"
longTitle = "A RESOLUTION DIRECTING THE DEPARTMENT OF EDUCATION (DEPED) TO IMPLEMENT EFFECTIVE CLASSROOM TEACHER-STUDENT LEARNING STRATEGY FOR EFFECTIVE EDUCATION TO REVERSE THE 60-YEAR CONTINUING DETERIORATION OF EDUCATION IN THE PHILIPPINES, WITH A THREE (3) YEAR CONTINUING APPROPRIATION TO COVER THE 50 BILLION PESOS FUNDING REQUIREMENT"
scope = "National"
dateFiled = "2021-11-08"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2021-11-10"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_18/HR02334.pdf"
fileSize = 1596484
author = "Fernando, Bayani F."
[[authorsDetail]]
name = "Fernando, Bayani F."
nameCode = "Fernando"
date = "2021-11-08"
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2021-11-10"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 32651
congress = 18
bill_no = "HR02334"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2021-11-10"
