billNumber = "SBN-01004"
billType = "SBN"
congress = 17
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=17&q=SBN-1004"
lastScraped = "2025-09-20T23:21:49.413984"
title = "EVACUATION CENTER ACT"
filedDate = "August 8, 2016"
author = "Gatchalian, Sherwin T."
longTitle = "AN ACT ESTABLISHING EVACUATION CENTERS IN EVERY MUNICIPALITY AND CITY, PROVIDING FOR THE NECESSARY FACILITIES, ENSURING THEIR STRUCTURAL CAPACITY, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
subject = [ "Evacuation Center",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2457821161!.pdf"
pdfFileName = "SBN-1004 as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/8/2016"
action = "Introduced by Senator SHERWIN T. GATCHALIAN;"

[[legislativeHistory]]
date = "8/17/2016"
action = "Read on First Reading and Referred to the Committee(s) on NATIONAL DEFENSE AND SECURITY; PUBLIC WORKS; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/17/2016"

[committee]
name = "National Defense and Security"
type = "primary"
