billNumber = "SBN-00140"
billType = "SBN"
congress = 17
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=17&q=SBN-140"
lastScraped = "2025-09-20T23:10:43.613066"
title = "FREE IRRIGATION REFORM AND RESTRUCTURING ACT OF 2016"
filedDate = "June 30, 2016"
author = "Villar, Cynthia A., Legarda, Loren B."
longTitle = "AN ACT PROVIDING FOR FREE IRRIGATION SERVICES TO FARMERS, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 3601, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Farmers", "Irrigation", "National Irrigation Administration",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2355921229!.pdf"
pdfFileName = "SBN-140 as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/30/2016"
action = "Introduced by Senator CYNTHIA A. VILLAR;"

[[legislativeHistory]]
date = "8/1/2016"
action = "Read on First Reading and Referred to the Committee(s) on AGRICULTURE AND FOOD; and FINANCE;"

[[legislativeHistory]]
date = "8/18/2016"
action = "Letter from Senator LOREN B. LEGARDA dated August 10, 2016, requesting that she be made co-author of SBN-140, received by the LBIS;"

[[legislativeHistory]]
date = "4/17/2017"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "5/16/2017"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "5/22/2017"
action = "Returned and submitted jointly by the Committee(s) on AGRICULTURE AND FOOD and FINANCE per Committee Report No. 103, recommending that it be substituted by SBN-1465;"

[[legislativeHistory]]
date = "5/22/2017"
action = "Committee Report Calendared for Ordinary Business;"

[[legislativeHistory]]
date = "5/22/2017"
action = "Sponsor: Senator CYNTHIA A. VILLAR;"

[[legislativeHistory]]
date = "5/22/2017"
action = "SUBSTITUTED BY SBN-1465 UNDER COMMITTEE REPORT NO. 103, WHICH BECAME R.A. NO. 10969 ON FEBRUARY 2, 2019."

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "5/22/2017"

[committee]
name = "Agriculture and Food"
type = "primary"
