billNumber = "HB00737"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB00737"
lastScraped = "2025-09-22T00:15:37.880755"
title = "Extending Preference of Employment to any One Child of Veterans in the Government"
longTitle = "AN ACT EXTENDING PREFERENCE OF EMPLOYMENT TO ANY ONE CHILD OF VETERANS IN THE GOVERNMENT, INCLUDING GOVERNMENT-OWNED AND/OR GOVERNMENT-CONTROLLED CORPORATIONS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2007-07-04"
status = "Approved by the House on 2008-04-29, transmitted to on 2008-05-05 and received by the Senate on 2008-05-06"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Villar, Cynthia A."
coAuthors = [ "ROMAN, HERMINIA B.", "LAZATIN, CARMELO F.", "VILLANUEVA, EMMANUEL JOEL J.", "LIM, RENO G.", "ROMUALDO, PEDRO P.", "GARIN, JANETTE L.", "ALVAREZ, ANTONIO C.", "ANTONINO, RODOLFO W.", "DIAZ, ANTONIO M.",]
[[authorsDetail]]
name = "Villar, Cynthia A."
nameCode = "Villar"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "ROMAN, HERMINIA B."
nameCode = "Roman"
date = ""
journalNo = "J015"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "LAZATIN, CARMELO F."
nameCode = "Lazatin"
date = ""
journalNo = "J034"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "VILLANUEVA, EMMANUEL JOEL J."
nameCode = "Villanueva"
date = ""
journalNo = "J062"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "LIM, RENO G."
nameCode = "Lim (R.)"
date = ""
journalNo = "J062"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ROMUALDO, PEDRO P."
nameCode = "Romualdo"
date = ""
journalNo = "J078"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "GARIN, JANETTE L."
nameCode = "Garin"
date = ""
journalNo = "J015"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ALVAREZ, ANTONIO C."
nameCode = "Alvarez (A.)"
date = ""
journalNo = "J017"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ANTONINO, RODOLFO W."
nameCode = "Antonino"
date = ""
journalNo = "J017"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DIAZ, ANTONIO M."
nameCode = "Diaz"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "VETERANS AFFAIRS AND WELFARE"
type = "primary"
referralCode = "A506"
dateRead = "2007-07-31"

[[committee]]
name = "OVERSEAS WORKERS AFFAIRS"
type = "principal"
referralCode = "E513"

[firstReading]
id = 66708
congress = 14
bill_no = "HB00737"
report = "00309"
comm_act = ""
referral = "A506"
ref_name = "VETERANS AFFAIRS AND WELFARE"
sub_name = "VETERANS AFFAIRS AND WELFARE"
recomm = "approval without amendments"
remarks = ""
date_read = "2007-07-31"
date_ob = "2008-03-03"
date_report = "2008-02-27"

[secondReading]
id = 9299
congress = 14
bill_no = "HB00737"
adopted_resolution = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "On Mar. 12, 2008, the Body approved to consider the Explanatory Note of the Bill as the sponsorship remarks on the measure. "
recommended_reconsidered = " "
date_calendared = "2008-03-04"
date_approved = "2008-03-12"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""

[thirdReading]
id = 7054
congress = 14
bill_no = "HB00737"
date_dist = "2008-04-21"
date_adopt = "2008-04-29"
remarks = "     "
no_yeas = 180
no_nays = 0
no_abstent = 0
date_trans = "2008-05-05"
date_rec = "2008-05-06"
amend_ind = " "
ccreqby = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "hbt00737.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_14/hbt00737.pdf"
