billNumber = "HB00999"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB00999"
lastScraped = "2025-09-22T00:15:37.924039"
title = "\\\"Anti-Marital Infidelity Act of 2007\\\""
longTitle = "AN ACT DEFINING AND PENALIZING MARITAL INFIDELITY AMENDING FOR THE PURPOSE ARTICLES 333, 334 AND 344 OF ACT NO. 3815, OTHERWISE KNOWN AS THE REVISED PENAL CODE"
scope = "National"
dateFiled = "2007-07-10"
status = "Substituted by HB06811"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Villanueva, Emmanuel Joel J."
coAuthors = [ "GONZALES, CINCHONA CRUZ",]
[[authorsDetail]]
name = "Villanueva, Emmanuel Joel J."
nameCode = "Villanueva"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "GONZALES, CINCHONA CRUZ"
nameCode = "Cruz-Gonzales"
date = ""
journalNo = "J031"
sessionNo = "1RS"

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2007-08-01"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 66970
congress = 14
bill_no = "HB00999"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-08-01"
