billNumber = "HB00519"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB00519"
lastScraped = "2025-09-22T00:15:37.840374"
title = "HB00519"
longTitle = "AN ACT EXEMPTING THE SALE OR IMPORTATION OF COMPUTER HARDWARE AND SOFTWARE FROM THE PAYMENT OF VALUE ADDED TAX AND DONATIONS THEREOF FROM DONOR'S TAX, AMENDING FOR THE PURPOSE SECTION 109 OF THE NATIONAL INTERNAL REVENUE CODE OF 1997, AS AMENDED"
scope = "National"
dateFiled = "2007-07-02"
status = "Pending with the Committee on WAYS AND MEANS since 2007-07-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Mitra, Abraham Kahlil B."
[[authorsDetail]]
name = "Mitra, Abraham Kahlil B."
nameCode = "Mitra"
date = ""
sequence = 1

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "2007-07-30"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 66490
congress = 14
bill_no = "HB00519"
report = ""
comm_act = ""
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-07-30"
