billNumber = "HB00024"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB00024"
lastScraped = "2025-09-22T00:15:37.732528"
title = "HB00024"
longTitle = "AN ACT TO EXEMPT FROM THE INCOME REQUIREMENT CAPITAL TOWNS OF THE PROVINCES SUBJECT TO CERTAIN CONDITIONS, AMENDING FOR THE PURPOSE SECTION 450 OF REPUBLIC ACT NO. 7160, AS AMENDED BY REPUBLIC ACT NO. 9009, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2007-07-02"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2007-07-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Hofer, Ann K."
[[authorsDetail]]
name = "Hofer, Ann K."
nameCode = "Hofer"
date = ""
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2007-07-24"

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "principal"
referralCode = "0536"

[firstReading]
id = 65995
congress = 14
bill_no = "HB00024"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-07-24"
