billNumber = "HB00030"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB00030"
lastScraped = "2025-09-22T00:15:37.733703"
title = "\\\"Gifted Children Act of 2006\\\""
longTitle = "AN ACT ESTABLISHING A NATIONAL PROGRAM FOR FILIPINO GIFTED CHILDREN, PROVIDING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2007-07-02"
status = "Scheduled for first meeting/hearing on 2009-04-28"
statusOrder = 4.11
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lacson, Jose Carlos V."
coAuthors = [ "DEL MAR, RAUL V.", "UY, ROLANDO A.", "ESCUDERO, SALVADOR III H.", "ABANTE, BIENVENIDO JR. M.", "MANGUDADATU, DATU PAX S.", "CODILLA, EUFROCINO SR. M.", "VILLAR, CYNTHIA A.", "GULLAS, EDUARDO R.", "SYJUCO, JUDY J.",]
[[authorsDetail]]
name = "Lacson, Jose Carlos V."
nameCode = "Lacson"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "DEL MAR, RAUL V."
nameCode = "Del Mar"
date = ""
journalNo = "J007"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "UY, ROLANDO A."
nameCode = "Uy (R.A.)"
date = ""
journalNo = "J007"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ESCUDERO, SALVADOR III H."
nameCode = "Escudero"
date = ""
journalNo = "J013"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ABANTE, BIENVENIDO JR. M."
nameCode = "Abante"
date = ""
journalNo = "J016"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MANGUDADATU, DATU PAX S."
nameCode = "Mangudadatu"
date = ""
journalNo = "J017"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CODILLA, EUFROCINO SR. M."
nameCode = "Codilla"
date = ""
journalNo = "J017"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "VILLAR, CYNTHIA A."
nameCode = "Villar"
date = ""
journalNo = "J091"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "GULLAS, EDUARDO R."
nameCode = "Gullas"
date = ""
journalNo = "J013"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SYJUCO, JUDY J."
nameCode = "Syjuco"
date = ""
journalNo = "J082"
sessionNo = "2RS"

[[committee]]
name = "THE EDUCATION AND WELFARE OF SPECIAL PERSONS"
type = "primary"
referralCode = "E501"
dateRead = "2007-07-24"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 66001
congress = 14
bill_no = "HB00030"
report = ""
comm_act = ""
referral = "E501"
ref_name = "THE EDUCATION AND WELFARE OF SPECIAL PERSONS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-07-24"
