billNumber = "HB01519"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB01519"
lastScraped = "2025-09-22T00:15:38.023673"
title = "HB01519"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF AN INDIGENOUS TRAINING CENTER IN THE MUNICIPALITY OF SEN. NINOY AQUINO, SECOND DISTRICT OF SULTAN KUDARAT AND APPROPRIATING FUNDS THEREFORE AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "2007-07-30"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2007-08-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2007-08-08"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[[committee]]
name = "NATIONAL CULTURAL COMMUNITIES"
type = "secondary"
referralCode = "0524"

[firstReading]
id = 67490
congress = 14
bill_no = "HB01519"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-08-08"
