billNumber = "HB01924"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB01924"
lastScraped = "2025-09-22T00:15:38.093268"
title = "HB01924"
longTitle = "AN ACT CONSTITUTING THE LONE CONGRESSIONAL DISTRICTS OF MUNTINLUPA CITY AND LAS PINAS CITY AND THE FIRST AND SECOND CONGRESSIONAL DISTRICTS OF PARAÑAQUE CITY INTO A SEPARATE DISTRICT ENGINEERING OFFICE AND PROVIDING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2007-08-08"
status = "Substituted by HB05148"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Biazon, Rozzano Rufino B."
coAuthors = [ "VILLAR, CYNTHIA A.", "ZIALCITA, EDUARDO C.", "GOLEZ, ROILO S.",]
[[authorsDetail]]
name = "Biazon, Rozzano Rufino B."
nameCode = "Biazon"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "VILLAR, CYNTHIA A."
nameCode = "Villar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ZIALCITA, EDUARDO C."
nameCode = "Zialcita"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GOLEZ, ROILO S."
nameCode = "Golez"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2007-08-22"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 67895
congress = 14
bill_no = "HB01924"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-08-22"
