billNumber = "HB03578"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB03578"
lastScraped = "2025-09-22T00:15:38.397976"
title = "HB03578"
longTitle = "AN ACT CREATING AND ESTABLISHING THE INSTITUTE FOR STRATEGIC STUDIES AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2008-02-13"
status = "Pending with the Committee on GOVERNMENT REORGANIZATION since 2008-02-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "CODILLA, EUFROCINO SR. M.",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "CODILLA, EUFROCINO SR. M."
nameCode = "Codilla"
date = ""
journalNo = "J065"
sessionNo = "1RS"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "primary"
referralCode = "0516"
dateRead = "2008-02-26"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[firstReading]
id = 69549
congress = 14
bill_no = "HB03578"
report = ""
comm_act = ""
referral = "0516"
ref_name = "GOVERNMENT REORGANIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2008-02-26"
