billNumber = "HB03435"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB03435"
lastScraped = "2025-09-22T00:15:38.371723"
title = "\\\"Batas sa Sistemang Voucher\\\" (\\\"Voucher System Act\\\")"
longTitle = "ISANG PANUKALANG BATAS NA MAGSASAINSTITUSYON SA SISTEMANG VOUCHER O VOUCHER SYSTEM PARA SA PAGKAIN, GASOLINA, GAMOT AT TRABAHONG PANG-EMERGENCY, PAGLALAAN NG PONDO PARA DITO, AT PARA SA IBA PANG LAYUNIN (AN ACT INSTITUTIONALIZING THE VOUCHER SYSTEM FOR FOOD, FUEL, MEDICINE AND EMERGENCY EMPLOYMENT, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES)"
scope = "National"
dateFiled = "2008-01-28"
status = "Under study by the Technical Working Group(TWG) on 2009-01-27"
statusOrder = 4.23
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Joson, Eduardo Nonato N."
[[authorsDetail]]
name = "Joson, Eduardo Nonato N."
nameCode = "Joson"
date = ""
sequence = 1

[[committee]]
name = "SOCIAL SERVICES"
type = "primary"
referralCode = "0535"
dateRead = "2008-02-04"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 69406
congress = 14
bill_no = "HB03435"
report = ""
comm_act = ""
referral = "0535"
ref_name = "SOCIAL SERVICES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2008-02-04"
