billNumber = "HB03051"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB03051"
lastScraped = "2025-09-22T00:15:38.295624"
title = "HB03051"
longTitle = "AN ACT REQUIRING LOCAL GOVERNMENTS TO EARMARK A PORTION OF THEIR INTERNAL REVENUE ALLOTMENTS FOR FREE MEDICINES TO INDIGENT PATIENTS IN THEIR LOCALITIES, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2007-11-12"
status = "Pending with the Committee on REVISION OF LAWS since 2007-11-19"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "ARENAS, MA. RACHEL J.",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "ARENAS, MA. RACHEL J."
nameCode = "Arenas"
date = ""
journalNo = "J075"
sessionNo = "1RS"

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2007-11-19"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 69022
congress = 14
bill_no = "HB03051"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-11-19"
