billNumber = "HB03992"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB03992"
lastScraped = "2025-09-22T00:15:38.479825"
title = "HB03992"
longTitle = "AN ACT ESTABLISHING A SPECIAL ECONOMIC ZONE AND FREE PORT IN THE PROVINCE OF NORTHERN SAMAR, CREATING FOR THE PURPOSE THE NORTHERN SAMAR SPECIAL ECONOMIC ZONE AUTHORITY, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "2008-04-29"
status = "Approved by the Committee on Ways and Means on 2009-12-15"
statusOrder = 4.37
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Daza, Paul Ruiz"
[[authorsDetail]]
name = "Daza, Paul Ruiz"
nameCode = "Daza (P.)"
date = ""
sequence = 1

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "primary"
referralCode = "0536"
dateRead = "2008-05-06"

[[committee]]
name = "HUMAN RIGHTS"
type = "principal"
referralCode = "E507"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "secondary"
referralCode = "0539"

[[committee]]
name = "WAYS AND MEANS"
type = "secondary"
referralCode = "0542"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 69963
congress = 14
bill_no = "HB03992"
report = ""
comm_act = ""
referral = "0536"
ref_name = "ECONOMIC AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2008-05-06"
