billNumber = "HB05633"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB05633"
lastScraped = "2025-09-22T00:15:38.887808"
title = "The Bicycle Helmet Safety Act Of 2008"
longTitle = "AN ACT TO PROTECT CONSUMERS BY PROMULGATING UNIFORM MANUFACTURING STANDARDS FOR BICYCLE HELMETS AND PROMOTING ITS USE"
scope = "National"
dateFiled = "2008-12-16"
status = "Pending First Reading (Filed last 2008-12-16)"
statusOrder = 1.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Santiago, Narciso III D."
[[authorsDetail]]
name = "Santiago, Narciso III D."
nameCode = "Santiago (N.)"
date = ""
sequence = 1

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = ""

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 71604
congress = 14
bill_no = "HB05633"
report = ""
comm_act = ""
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
recomm = ""
remarks = ""
