billNumber = "HB05477"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB05477"
lastScraped = "2025-09-22T00:15:38.806982"
title = "HB05477"
longTitle = "AN ACT MAKING IBP LEGAL AID CLIENTS EXEMPT FROM PAYMENT OF DOCKET FEES AND OTHER FEES"
scope = "National"
dateFiled = "2008-11-10"
status = "Pending with the Committee on JUSTICE since 2008-11-12"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "ARAGO, MARIA EVITA R.", "SANTIAGO, NARCISO III D.", "CHATTO, EDGARDO M.",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "ARAGO, MARIA EVITA R."
nameCode = "Arago"
date = ""
journalNo = "J048"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SANTIAGO, NARCISO III D."
nameCode = "Santiago (N.)"
date = ""
journalNo = "J050"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CHATTO, EDGARDO M."
nameCode = "Chatto"
date = ""
journalNo = "J051"
sessionNo = "2RS"

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2008-11-12"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 71448
congress = 14
bill_no = "HB05477"
report = ""
comm_act = ""
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2008-11-12"
