billNumber = "HB06190"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB06190"
lastScraped = "2025-09-22T00:15:39.044498"
title = "Declaring Certain Portions Of A Parcel Of Land Of The Public Domain, Identified As Lot No. 4828, Cad 240, Located In Barangay Malaubang, Ozamiz City, Province Of Misamis Occidental, Agricultural Lands Open To Disposition For Socialized Housing"
longTitle = "AN ACT DECLARING CERTAIN PORTIONS OF A PARCEL OF LAND OF THE PUBLIC DOMAIN, IDENTIFIED AS LOT NO. 4828, CAD 240, LOCATED IN BARANGAY MALAUBANG, OZAMIZ CITY, PROVINCE OF MISAMIS OCCIDENTAL, AGRICULTURAL LANDS OPEN TO DISPOSITION FOR SOCIALIZED HOUSING"
scope = "Local"
dateFiled = "2009-04-14"
status = "Approved by the House on 2009-05-26, transmitted to on 2009-05-29 and received by the Senate on 2009-05-29"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramiro, Herminia M."
coAuthors = [ "ARROYO, IGNACIO T.", "CUA, JUNIE E.",]
[[authorsDetail]]
name = "Ramiro, Herminia M."
nameCode = "Ramiro"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "ARROYO, IGNACIO T."
nameCode = "Arroyo (I.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CUA, JUNIE E."
nameCode = "Cua (J.)"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2009-04-15"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[[motherBills]]
bill_no = "HB00585"
sequence = 1
flag = "S"

[[substitutedBills]]
bill_no = "HB00585"
sequence = 1
flag = "S"

[firstReading]
id = 72158
congress = 14
bill_no = "HB06190"
report = "01923"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "NATURAL RESOURCES, APPROPRIATIONS"
recomm = "approval"
remarks = ""
date_read = "2009-04-15"
date_ob = "2009-04-15"
date_fri = "2009-04-22"
date_report = "2009-04-14"

[secondReading]
id = 10968
congress = 14
bill_no = "HB06190"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "On May 06, 2009, the Body approved to consider the Explanatory Note of the Bill as the sponsorship remarks on the measure; terminated the sponsorship and debate; terminated the period of amendments; and approved the same on Second Reading. "
recommended_reconsidered = " "
date_approved = "2009-05-06"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""

[thirdReading]
id = 8227
congress = 14
bill_no = "HB06190"
date_dist = "2009-05-18"
date_adopt = "2009-05-26"
remarks = "     "
no_yeas = 194
no_nays = 0
no_abstent = 0
date_trans = "2009-05-29"
date_rec = "2009-05-29"
amend_ind = " "
ccreqby = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "hbt06190.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_14/hbt06190.pdf"
