billNumber = "HB06976"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HB06976"
lastScraped = "2025-09-22T00:15:39.208354"
title = "Converting The Pinaglabanan High School In The Municipality Of Goa, Province Of Camarines Sur Into A National High School To Be Known As Pinaglabanan National High School"
longTitle = "AN ACT CONVERTING THE PINAGLABANAN HIGH SCHOOL IN THE MUNICIPALITY OF GOA, PROVINCE OF CAMARINES SUR INTO A NATIONAL HIGH SCHOOL TO BE KNOWN AS PINAGLABANAN NATIONAL HIGH SCHOOL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2009-11-10"
status = "Approved on Second Reading on 2010-02-01"
statusOrder = 13.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Fuentebella, Arnulfo P."
coAuthors = [ "DE GUZMAN, DEL R.", "CUA, JUNIE E.",]
[[authorsDetail]]
name = "Fuentebella, Arnulfo P."
nameCode = "Fuentebella"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "DE GUZMAN, DEL R."
nameCode = "De Guzman"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CUA, JUNIE E."
nameCode = "Cua (J.)"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2009-11-16"

[[committee]]
name = "WELFARE OF CHILDREN"
type = "principal"
referralCode = "F501"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 72941
congress = 14
bill_no = "HB06976"
report = "02610"
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = "BASIC EDUCATION AND CULTURE, APPROPRIATIONS"
recomm = "approval with amendments"
remarks = ""
date_read = "2009-11-16"
date_ob = "2010-01-27"
date_fri = "2010-02-01"
date_report = "2010-01-27"

[secondReading]
id = 11665
congress = 14
bill_no = "HB06976"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "On Feb. 01, 2010, the Body approved to consider the Explanatory Note of the bill as the sponsorship remarks; terminated the period of sponsorship and debate; approved the Ctte. amendments as contained in the Ctte. Rpt., if any; terminated the period of amendments; and approved the same on Second Reading. "
recommended_reconsidered = " "
date_approved = "2010-02-01"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
