billNumber = "HJR0033"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HJR0033"
lastScraped = "2025-09-22T00:15:39.272455"
title = "HJR0033"
longTitle = "JOINT RESOLUTION URGING THE PRESIDENT OF THE PHILIPPINES TO TEMPORARILY SUSPEND THE IMPLEMENTATION OF EXECUTIVE ORDER NO. 366 WHICH \\\"DIRECTS A STARTEGIC REVIEW OF THE OPERATIONS AND ORGANIZATION OF THE EXECUTIVE BRANCH AND PROVIDING OPTIONS AND INCENTIVES FOR GOVERNMENT EMPLOYEES WHO MAY BE AFFECTED BY THE RATIONALIZATION OF THE FUNCTIONS AND AGENCIES OF THE EXECUTIVE BRANCH\\\""
scope = "National"
dateFiled = "2009-02-18"
status = "Pending with the Committee on GOVERNMENT REORGANIZATION since 2009-02-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Gonzalez, Raul Jr. T."
coAuthors = [ "PADILLA, CARLOS M.", "GOLEZ, ROILO S.", "ALMARIO, THELMA Z.", "REMULLA, JESUS CRISPIN C.", "MAZA, LIZA L.", "CERILLES, ANTONIO H.", "MARIANO, RAFAEL V.", "CHATTO, EDGARDO M.",]
[[authorsDetail]]
name = "Gonzalez, Raul Jr. T."
nameCode = "Gonzalez"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "PADILLA, CARLOS M."
nameCode = "Padilla"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GOLEZ, ROILO S."
nameCode = "Golez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALMARIO, THELMA Z."
nameCode = "Almario"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "REMULLA, JESUS CRISPIN C."
nameCode = "Remulla"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAZA, LIZA L."
nameCode = "Maza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CERILLES, ANTONIO H."
nameCode = "Cerilles"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MARIANO, RAFAEL V."
nameCode = "Mariano"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CHATTO, EDGARDO M."
nameCode = "Chatto"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "primary"
referralCode = "0516"
dateRead = "2009-02-23"

[firstReading]
id = 73233
congress = 14
bill_no = "HJR0033"
report = ""
comm_act = ""
referral = "0516"
ref_name = "GOVERNMENT REORGANIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2009-02-23"
