billNumber = "HR00935"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HR00935"
lastScraped = "2025-09-22T00:15:39.495181"
title = "HR00935"
longTitle = "RESOLUTION COMMENDING RODERICK \\\"JERICK\\\" D. TERNIDA FOR WINNING THE MIDDLEWEIGHT AND OVER-ALL TITLES IN THE 2008 MUSCLEMANIA MR. UNIVERSE CHAMPIONSHIP HELD IN MIAMI, FLORIDA, USA, AND MAKING HIM THE FIRST FILIPINO TO WIN AN OVER-ALL TITLE IN A WORLD BODYBUILDING COMPETITION"
scope = "National"
dateFiled = "2009-01-19"
status = "Adopted as Resolution No. HR00286 on 2009-01-19"
statusOrder = 15.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Nograles, Prospero C."
coAuthors = [ "DEFENSOR, ARTHUR D.", "ZAMORA, RONALDO B.", "PUNO, ROBERTO V.",]
[[authorsDetail]]
name = "Nograles, Prospero C."
nameCode = "Nograles"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "DEFENSOR, ARTHUR D."
nameCode = "Defensor (A.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ZAMORA, RONALDO B."
nameCode = "Zamora (R.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PUNO, ROBERTO V."
nameCode = "Puno"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2009-01-19"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 74189
congress = 14
bill_no = "HR00935"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2009-01-19"

[secondReading]
id = 10610
congress = 14
bill_no = "HR00935"
adopted_resolution = "HR00286"
adopted_resolution_title = "RESOLUTION COMMENDING RODERICK \"JERICK\" D. TERNIDA FOR WINNING THE MIDDLEWEIGHT AND OVER-ALL TITLES IN THE 2008 MUSCLEMANIA MR. UNIVERSE CHAMPIONSHIP HELD IN MIAMI, FLORIDA, USA, AND MAKING HIM THE FIRST FILIPINO TO WIN AN OVER-ALL TITLE IN A WORLD BODYBUILDING COMPETITION"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2009-01-19"
date_approved = "2009-01-19"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
file = "HR00935.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_14/HR00935.pdf"
