billNumber = "HR00604"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HR00604"
lastScraped = "2025-09-22T00:15:39.420376"
title = "HR00604"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON HOUSING AND URBAN DEVELOPMENT OF THE HOUSE OF REPRESENTATIVES TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, INTO THE FORECLOSURE OF LOW-COST HOUSING UNITS THAT ARE NOW OWNED BY BALIKATAN HOUSING FINANCE, INC."
scope = "National"
dateFiled = "2008-05-26"
status = "Adopted Measure Acted Upon on 2008-11-17"
statusOrder = 16.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Nograles, Prospero C."
coAuthors = [ "DEFENSOR, ARTHUR D.", "ZAMORA, RONALDO B.", "RULES",]
[[authorsDetail]]
name = "Nograles, Prospero C."
nameCode = "Nograles"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "DEFENSOR, ARTHUR D."
nameCode = "Defensor (A.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ZAMORA, RONALDO B."
nameCode = "Zamora (R.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RULES"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2008-05-27"

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 73858
congress = 14
bill_no = "HR00604"
report = "00568"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Adoption without amendments."
remarks = ""
date_read = "2008-05-27"
date_ob = "2008-05-27"
date_report = "2008-05-27"

[secondReading]
id = 9567
congress = 14
bill_no = "HR00604"
adopted_resolution = ""
adopted_resolution_title = "RESOLUTION DIRECTING THE COMMITTEE ON HOUSING AND URBAN DEVELOPMENT OF THE HOUSE OF REPRESENTATIVES TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, INTO THE FORECLOSURE OF LOW-COST HOUSING UNITS THAT ARE NOW OWNED BY BALIKATAN HOUSING FINANCE, INC."
reasons = ""
comm_report_no = "01500"
comm_report_action = "Report on the Ctte\\'s Findings and Recommendations."
submitted_on = "2008-10-29"
remarks = "Authorizes the Ctte. on Housing and Urban Development to conduct investigations."
recommended_reconsidered = " "
date_calendared = "2008-05-27"
date_approved = "2008-05-27"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
date_refferral = "2008-05-27"
date_ctte_rules = "2008-11-10"
date_resolution_acted = "2008-11-17"
action_on_adopted_resolution = "Adoption of Ctte. Rpt. No. 1500, the Committee\\'s findings and recommendations."
