billNumber = "HR00592"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HR00592"
lastScraped = "2025-09-22T00:15:39.416853"
title = "HR00592"
longTitle = "A RESOLUTION EXPRESSING THE SENSE OF THE HOUSE OF REPRESENTATIVES ON THE URGENT NECESSITY OF ADOPTING MEASURES THAT WILL ENSURE CONSUMER PROTECTION BY PROVIDING AN AFFORDABLE SUPPLY OF ELECTRIC POWER AT A FAIR AND REASONABLE PRICE TO CONSUMERS"
scope = "National"
dateFiled = "2008-05-19"
status = "Substituted by HR00818"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Villafuerte, Luis R."
[[authorsDetail]]
name = "Villafuerte, Luis R."
nameCode = "Villafuerte"
date = ""
sequence = 1

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "2008-05-19"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 73846
congress = 14
bill_no = "HR00592"
report = ""
comm_act = ""
referral = "0510"
ref_name = "ENERGY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2008-05-19"
