billNumber = "HR00880"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HR00880"
lastScraped = "2025-09-22T00:15:39.482806"
title = "HR00880"
longTitle = "RESOLUTION STRONGLY URGING THE PHILIPPINE CHARITY SWEEPSTAKES OFFICE (PCSO) TO ALLOW THE OPERATION OF SMALL TOWN LOTTERIES (STLs) IN LEGISLATIVE DISTRICTS AND LOCAL GOVERNMENT UNITS NATIONWIDE, AND TO PRIORITIZE AND FACILITATE THE GRANT OF APPROPRIATE AUTHORITY OR LICENSE TO OPERATE SMALL TOWN LOTTERIES (STLs) TO INTERESTED ENTITIES IN LEGISLATIVE DISTRICTS AND LOCAL GOVERNMENT UNITS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2008-11-24"
status = "Adopted as Resolution No. HR00594 on 2009-10-13"
statusOrder = 15.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Albano, Rodolfo III T."
coAuthors = [ "BONOAN-DAVID, MA. THERESA B.", "DUMPIT, THOMAS JR. L.", "UMALI, ALFONSO JR. V.", "AQUINO, JOSE II S.", "ROMARATE, GUILLERMO JR. A.", "BRIONES, NICANOR M.", "MATUGAS, FRANCISCO T.", "PICHAY, PHILIP A.", "TIENG, WILLIAM ERWIN C.", "ALFELOR, FELIX JR. R.", "MADRONA, ELEANDRO JESUS F.", "LAPUS, JECI A.", "ANGARA, JUAN EDGARDO M.", "BONDOC, ANNA YORK P.", "AGBAYANI, VICTOR E.", "DIASNES, CARLO OLIVER D.", "DANGWA, SAMUEL M.", "PADILLA, CARLOS M.", "GATLABAYAN, ANGELITO C.", "CHIPECO, JUSTIN MARC SB.",]
[[authorsDetail]]
name = "Albano, Rodolfo III T."
nameCode = "Albano"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "BONOAN-DAVID, MA. THERESA B."
nameCode = "Bonoan-David"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DUMPIT, THOMAS JR. L."
nameCode = "Dumpit (T.L.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "UMALI, ALFONSO JR. V."
nameCode = "Umali (A.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AQUINO, JOSE II S."
nameCode = "Aquino"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMARATE, GUILLERMO JR. A."
nameCode = "Romarate"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BRIONES, NICANOR M."
nameCode = "Briones"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MATUGAS, FRANCISCO T."
nameCode = "Matugas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PICHAY, PHILIP A."
nameCode = "Pichay"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TIENG, WILLIAM ERWIN C."
nameCode = "Tieng"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALFELOR, FELIX JR. R."
nameCode = "Alfelor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MADRONA, ELEANDRO JESUS F."
nameCode = "Madrona"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAPUS, JECI A."
nameCode = "Lapus"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANGARA, JUAN EDGARDO M."
nameCode = "Angara"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BONDOC, ANNA YORK P."
nameCode = "Bondoc"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AGBAYANI, VICTOR E."
nameCode = "Agbayani"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DIASNES, CARLO OLIVER D."
nameCode = "Diasnes"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DANGWA, SAMUEL M."
nameCode = "Dangwa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PADILLA, CARLOS M."
nameCode = "Padilla"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GATLABAYAN, ANGELITO C."
nameCode = "Gatlabayan"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CHIPECO, JUSTIN MARC SB."
nameCode = "Chipeco"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GAMES AND AMUSEMENTS"
type = "primary"
referralCode = "0514"
dateRead = "2008-11-26"

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 74134
congress = 14
bill_no = "HR00880"
report = "02389"
comm_act = ""
referral = "0514"
ref_name = "GAMES AND AMUSEMENTS"
sub_name = "GAMES AND AMUSEMENTS"
recomm = "Adoption without amendments."
remarks = ""
date_read = "2008-11-26"
date_ob = "2009-09-29"
date_report = "2009-09-23"

[secondReading]
id = 11482
congress = 14
bill_no = "HR00880"
adopted_resolution = "HR00594"
adopted_resolution_title = "RESOLUTION STRONGLY URGING THE PHILIPPINE CHARITY SWEEPSTAKES OFFICE (PCSO) TO ALLOW THE OPERATION OF SMALL TOWN LOTTERIES (STLS) IN LEGISLATIVE DISTRICTS AND LOCAL GOVERNMENT UNITS NATIONWIDE, AND TO PRIORITIZE AND FACILITATE THE GRANT OF APPROPRIATE AUTHORITY OR LICENSE TO OPERATE SMALL TOWN LOTTERIES (STLS) TO INTERESTED ENTITIES IN LEGISLATIVE DISTRICTS AND LOCAL GOVERNMENT UNITS AND FOR OTHER PURPOSES"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2009-09-29"
date_approved = "2009-10-13"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
file = "HR00880.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_14/HR00880.pdf"
