billNumber = "HR01268"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=HR01268"
lastScraped = "2025-09-22T00:15:39.566296"
title = "HR01268"
longTitle = "A RESOLUTION RESPECTFULLY URGING HER EXCELLENCY, PRESIDENT GLORIA MACAPAGAL-ARROYO TO DECLARE THE OLD PHILIPPINE EMBASSY BUILDING IN WASHINGTON D.C. AS A U.S.-PHILIPPINE WORLD WAR II VETERANS MEMORIAL BUILDING"
scope = "National"
dateFiled = "2009-07-20"
status = "Substituted by HR01402"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Mandanas, Hermilando I."
[[authorsDetail]]
name = "Mandanas, Hermilando I."
nameCode = "Mandanas"
date = ""
sequence = 1

[[committee]]
name = "FOREIGN AFFAIRS"
type = "primary"
referralCode = "0513"
dateRead = "2009-07-29"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 74522
congress = 14
bill_no = "HR01268"
report = ""
comm_act = ""
referral = "0513"
ref_name = "FOREIGN AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2009-07-29"
