billNumber = "PS00057"
billType = "HB"
congress = 14
apiCongressId = 14
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=14&q=PS00057"
lastScraped = "2025-09-22T00:15:39.641781"
title = "CHILD PORNOGRAPHY"
longTitle = "GREATER PROTECTION TO CHILDREN/MINORS"
scope = "National"
dateFiled = "2007-10-01"
status = "Pending with the Committee on THE WELFARE OF CHILDREN since 2007-10-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Cruz-Gonzales, Cinchona"
[[authorsDetail]]
name = "Cruz-Gonzales, Cinchona"
nameCode = "Cruz-Gonzales"
date = ""
sequence = 1

[[committee]]
name = "THE WELFARE OF CHILDREN"
type = "primary"
referralCode = "F501"
dateRead = "2007-10-09"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 74872
congress = 14
bill_no = "PS00057"
report = ""
comm_act = ""
referral = "F501"
ref_name = "THE WELFARE OF CHILDREN"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2007-10-09"
