billNumber = "HBN-07529"
billType = "HBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=HBN-7529"
lastScraped = "2025-09-20T21:20:30.156243"
title = "ALIBIJABAN PROTECTED LANDSCAPE AND SEASCAPE ACT"
longTitle = "AN ACT DECLARING A PARCEL OF LAND LOCATED IN THE MUNICIPALITY OF SAN ANDRES, IN THE PROVINCE OF QUEZON, A PROTECTED AREA WITH THE CATEGORY OF PROTECTED LANDSCAPE AND SEASCAPE UNDER THE NATIONAL INTEGRATED PROTECTED AREA SYSTEM, TO BE REFERRED TO AS THE ALIBIJABAN PROTECTED LANDSCAPE AND SEASCAPE, PROVIDING FOR ITS MANAGEMENT, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Protected Area", "Protected Landscape",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4159537886!.pdf"
pdfFileName = "HBN-7529 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "5/10/2023"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "5/16/2023"
action = "Read on First Reading and Referred to the Committees on ENVIRONMENT, NATURAL RESOURCES AND CLIMATE CHANGE and FINANCE;"

[[legislativeHistory]]
date = "5/25/2023"
action = "Returned jointly by the Committees on ENVIRONMENT, NATURAL RESOURCES AND CLIMATE CHANGE and FINANCE per Committee Report No. 89, recommending that it be considered in SBN-1725;"

[[legislativeHistory]]
date = "5/29/2023"
action = "Committee Report Calendared for Ordinary Business;"

[[legislativeHistory]]
date = "5/29/2023"
action = "CONSIDERED IN SBN-1725 UNDER COMMITTEE REPORT NO. 89."

[[legislativeHistory]]
date = "1/15/2025"
action = "Senate designated Senators Villar (C), Marcos, Villar (M), Dela Rosa and Hontiveros as conferees to the Bicameral Conference Committee on the disagreeing provisions of SBN-1725 and HBN-7529;"

[[legislativeHistory]]
date = "2/5/2025"
action = "House of Representatives adopted SBN-1725 as an amendment to HBN-7529 on January 22, 2025;"

[[legislativeHistory]]
date = "5/5/2025"
action = "etter from Senate Secretary Renato N. Bantug Jr., transmitting nine (9) enrolled copies of SBN-1725 and HBN-7529, for the signature of Speaker Ferdinand Martin G. Romualdez and Secretary General Reginald S. Velasco;"

[[legislativeHistory]]
date = "6/4/2025"
action = "Letter for Senate Secretary Renato N. Bantug Jr., returning eight (8) enrolled copies of SBN-1725 and HBN-7529, which were signed by Speaker Ferdinand Martin G. Romualdez and Secretary General Reginald S. Velasco;"

[[legislativeHistory]]
date = "6/9/2025"
action = "Enrolled copies of SBN-1725 and HBN-7529, sent to the Office of the President for the signature of the President of the Philippines, His Excellency, President Ferdinand R. Marcos Jr.;"

[[legislativeHistory]]
date = "7/16/2025"
action = "Consolidated with SBN-1725, which was Approved and signed into law by the President of the Philippines, His Excellency, President Ferdinand Romualdez Marcos, Jr. on July 9, 2025 and became"

[[legislativeHistory]]
date = "7/16/2025"
action = "REPUBLIC ACT NO. 12226."

[status]
status = "Consolidated with Approved Bill"
date = "7/9/2025"

[committee]
name = "Environment, Natural Resources and Climate Change"
type = "primary"
