billNumber = "HB00261"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB00261"
lastScraped = "2025-09-22T00:20:57.426071"
title = "HB00261"
longTitle = "AN ACT ESTABLISHING A UNIVERSAL, COMPREHENSIVE AND UNIFORM SOCIAL SECURITY AND INSURANCE PROGRAM FOR ALL GOVERNMENT EMPLOYEES, AND FOR THIS PURPOSE INTEGRATING, RATIONALIZING, CONSOLIDATING, REVISING, FURTHER INCREASING AND EXPANDING THE BENEFITS UNDER EXISTING LAWS BEING ADMINISTERED BY THE GOVERNMENT SERVICE INSURANCE SYSTEM, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1995-07-05"
status = "Substituted by HB08561"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Dragon"
coAuthors = [ "LIBAN, DANTE V.", "RODRIGUEZ, OSCAR S.",]
[[authorsDetail]]
name = "Dragon"
nameCode = "Dragon"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RODRIGUEZ, OSCAR S."
nameCode = "Rodriguez"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "1995-07-26"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 106682
congress = 10
bill_no = "HB00261"
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
date_read = "1995-07-26"
