billNumber = "HB00035"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB00035"
lastScraped = "2025-09-22T00:20:57.364845"
title = "HB00035"
longTitle = "AN ACT TO PROMOTE THE DEVELOPMENT OF THE PHILIPPINE MUTUAL FUNDS INDUSTRY, AMENDING FOR THE PURPOSE THE INVESTMENT COMPANY ACT (RA 2629) AND THE NATIONAL INTERNAL REVENUE CODE, AS AMENDED AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1995-06-30"
status = "Substituted by HB07815"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "De Venecia, Jose Jr."
coAuthors = [ "TEVES, MARGARITO B.", "JOAQUIN, NEREO R.", "ESPINA, GERARDO S.", "SATOR, BALTAZAR A.", "LEDESMA, JULIO IV A.", "DIAZ, RENATO V.", "ANGARA-CASTILLO, BELLAFLOR J.", "ALMARIO, THELMA Z.", "TY, MARIO S.", "AUMENTADO, ERICO B.", "RAMA, EDUARDO SR. L.", "TAJON, MARIANO M.", "REYES, CARMENCITA O.", "FALCON, JESNAR R.", "ABAYA, PLARIDEL M.", "SANDOVAL, VICENTE A.", "PALMA GIL, MA. ELENA T.", "BAGATSING, RAMON JR. S.", "LIBAN, DANTE V.", "ADIONG, ABDULMALIK MAMINTAL M.", "SEACHON, FAUSTO JR. L.", "CLAUDIO, JOVITO O.", "PAREDES, CEFERINO JR. S.", "SAN BUENAVENTURA, LEOPOLDO E.", "JAAFAR, NUR G.", "BAUTISTA, BENJAMIN SR. V.", "LOPEZ, ELIAS B.", "ALMENDRAS, ALEJANDRO JR. C.", "TAMMANG, ASANI S.", "TULAWIE, BENSAUDI O.", "VILLAREAL, JULITA L.", "VERCELES, LEANDRO JR. B.", "ROMERO, MIGUEL L.", "FIGUEROA, CATALINO V.", "GARCIA, ENRIQUE JR. T.", "BARBERS, ROBERT Z.", "NATIVIDAD, TEODULO C.", "ROXAS, MANUEL A.", "VERGARA, BERNARDO M.", "RECTO, RALPH G.", "SILVERIO, RICARDO C.", "MONFORT, NARCISO D.", "LOPEZ, JAIME C.", "JALOSJOS, ROMEO G.",]
[[authorsDetail]]
name = "De Venecia, Jose Jr."
nameCode = "De Venecia"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "TEVES, MARGARITO B."
nameCode = "Teves"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JOAQUIN, NEREO R."
nameCode = "Joaquin"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESPINA, GERARDO S."
nameCode = "Espina"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SATOR, BALTAZAR A."
nameCode = "Sator"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LEDESMA, JULIO IV A."
nameCode = "Ledesma"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DIAZ, RENATO V."
nameCode = "Diaz"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANGARA-CASTILLO, BELLAFLOR J."
nameCode = "Angara-castillo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALMARIO, THELMA Z."
nameCode = "Almario"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TY, MARIO S."
nameCode = "Ty"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AUMENTADO, ERICO B."
nameCode = "Aumentado"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RAMA, EDUARDO SR. L."
nameCode = "Rama"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAJON, MARIANO M."
nameCode = "Tajon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "REYES, CARMENCITA O."
nameCode = "Reyes"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FALCON, JESNAR R."
nameCode = "Falcon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ABAYA, PLARIDEL M."
nameCode = "Abaya"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SANDOVAL, VICENTE A."
nameCode = "Sandoval"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PALMA GIL, MA. ELENA T."
nameCode = "Palma Gil"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BAGATSING, RAMON JR. S."
nameCode = "Bagatsing"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ADIONG, ABDULMALIK MAMINTAL M."
nameCode = "Adiong"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SEACHON, FAUSTO JR. L."
nameCode = "Seachon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CLAUDIO, JOVITO O."
nameCode = "Claudio"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PAREDES, CEFERINO JR. S."
nameCode = "Paredes"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SAN BUENAVENTURA, LEOPOLDO E."
nameCode = "San Buenaventura"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JAAFAR, NUR G."
nameCode = "Jaafar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BAUTISTA, BENJAMIN SR. V."
nameCode = "Bautista"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOPEZ, ELIAS B."
nameCode = "Lopez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALMENDRAS, ALEJANDRO JR. C."
nameCode = "Almendras"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAMMANG, ASANI S."
nameCode = "Tammang"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TULAWIE, BENSAUDI O."
nameCode = "Tulawie"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLAREAL, JULITA L."
nameCode = "Villareal"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VERCELES, LEANDRO JR. B."
nameCode = "Verceles"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMERO, MIGUEL L."
nameCode = "Romero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FIGUEROA, CATALINO V."
nameCode = "Figueroa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GARCIA, ENRIQUE JR. T."
nameCode = "Garcia"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BARBERS, ROBERT Z."
nameCode = "Barbers"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "NATIVIDAD, TEODULO C."
nameCode = "Natividad"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROXAS, MANUEL A."
nameCode = "Roxas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VERGARA, BERNARDO M."
nameCode = "Vergara"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RECTO, RALPH G."
nameCode = "Recto"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SILVERIO, RICARDO C."
nameCode = "Silverio"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOPEZ, JAIME C."
nameCode = "Lopez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JALOSJOS, ROMEO G."
nameCode = "Jalosjos"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "BANKS AND FINANCIAL INTERMEDIARIES"
type = "primary"
referralCode = "0505"
dateRead = "1995-07-25"

[[committee]]
name = "TOURISM"
type = "principal"
referralCode = "0538"

[[committee]]
name = "WAYS AND MEANS"
type = "secondary"
referralCode = "0542"

[firstReading]
id = 106456
congress = 10
bill_no = "HB00035"
referral = "0505"
ref_name = "BANKS AND FINANCIAL INTERMEDIARIES"
date_read = "1995-07-25"
