billNumber = "HB01436"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB01436"
lastScraped = "2025-09-22T00:20:57.621059"
title = "HB01436"
longTitle = "AN ACT DECLARING SEPTEMBER 9TH AS A LIBERATION/VICT ORY DAY FOR NEGROS OCCIDENTAL FROM THE JAPANES OCCUPATION DURING WORLD WAR II"
scope = "Local"
dateFiled = "1995-07-28"
status = "Transmitted to the President for Signature on 1996-12-13"
statusOrder = 30.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lacson, Jose Carlos V."
[[authorsDetail]]
name = "Lacson, Jose Carlos V."
nameCode = "Lacson"
date = ""
sequence = 0

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "1995-08-02"

[[committee]]
name = "PERSONS WITH DISABILITIES"
type = "principal"
referralCode = "J501"

[firstReading]
id = 107857
congress = 10
bill_no = "HB01436"
report = "00059"
referral = "0531"
ref_name = "REVISION OF LAWS"
recomm = "APPROVAL WITHOUT AMENDMENTS"
date_read = "1995-08-02"
date_ob = "1995-11-08"
date_report = "1995-10-31"

[secondReading]
id = 17797
congress = 10
bill_no = "HB01436"
remarks = "Considered the Explanatory Note as the Sponsorship speech"
date_approved = "1995-11-09"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 2417
congress = 10
bill_no = "HB01436"
date_dist = "1995-11-14"
date_adopt = "1995-11-28"
no_yeas = 126
no_nays = 0
no_abstent = 0
date_trans = "1995-11-28"
date_rec = "1995-12-05"
amend_ind = "N"
dte_transp = "1996-12-13"
