billNumber = "HB01645"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB01645"
lastScraped = "2025-09-22T00:20:57.656494"
title = "HB01645"
longTitle = "AN ACT ESTABLISHING AN ELEMENTARY SCHOOL IN BARANGAY POBLACION, MUNTINLUPA, TO BE KNOWN AS THE BARANGAY POBLACION ELEMENTARY SCHOOL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1995-08-01"
status = "Pending with the Committee on EDUCATION AND CULTURE since 1995-08-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Villar"
[[authorsDetail]]
name = "Villar"
nameCode = "Villar"
date = ""
sequence = 0

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "0509"
dateRead = "1995-08-07"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 108066
congress = 10
bill_no = "HB01645"
referral = "0509"
ref_name = "EDUCATION AND CULTURE"
date_read = "1995-08-07"
