billNumber = "HB03957"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB03957"
lastScraped = "2025-09-22T00:20:58.106005"
title = "HB03957"
longTitle = "AN ACT DESIGNATING THE OLD PHILCOA BUILDING LOCATED AT CORNER OF ELLIPTICAL ROAD AND COMMONWEALTH AVENUE, QUEZON CITY, AS THE NATIONAL NGO-COOPERATIVE DEVELOPMENT CENTER OF THE PHILIPPINES"
scope = "Local"
dateFiled = "1995-09-27"
status = "Pending with the Committee on COOPERATIVES DEVELOPMENT (SPECIAL CTTE.) since 1995-10-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bautista"
coAuthors = [ "RAMIREZ, JOSE T.", "LIBAN, DANTE V.",]
[[authorsDetail]]
name = "Bautista"
nameCode = "Bautista"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "RAMIREZ, JOSE T."
nameCode = "Ramirez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "COOPERATIVES DEVELOPMENT (SPECIAL CTTE.)"
type = "primary"
referralCode = "B512"
dateRead = "1995-10-02"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 110378
congress = 10
bill_no = "HB03957"
referral = "B512"
ref_name = "COOPERATIVES DEVELOPMENT (SPECIAL CTTE.)"
date_read = "1995-10-02"
