billNumber = "HB03168"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB03168"
lastScraped = "2025-09-22T00:20:57.960476"
title = "HB03168"
longTitle = "AN ACT AMENDING SECTION THIRTEEN PARAGRAPH (C) OF REPUBLIC ACT NUMBERED SIX THOUSAND SEVEN HUNDRED AND FIFTY-EIGHT, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1995-09-04"
status = "Pending with the Committee on APPROPRIATIONS since 1995-09-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Monfort"
coAuthors = [ "LIBAN, DANTE V.", "PADILLA, CARLOS M.",]
[[authorsDetail]]
name = "Monfort"
nameCode = "Monfort"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PADILLA, CARLOS M."
nameCode = "Padilla"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "APPROPRIATIONS"
type = "primary"
referralCode = "0504"
dateRead = "1995-09-07"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 109589
congress = 10
bill_no = "HB03168"
referral = "0504"
ref_name = "APPROPRIATIONS"
date_read = "1995-09-07"
