billNumber = "HB03778"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB03778"
lastScraped = "2025-09-22T00:20:58.074262"
title = "HB03778"
longTitle = "AN ACT GRANTING THE DIGITAL NETWORK TELEPHONE AND TELECOMMUNICATI ONS' CORPORATION (D.N.T.T.) A FRANCHISE TO INSTALL, OPERATE AND MAINTAIN A TELEPHONE SYSTEM IN THE REPUBLIC OF THE PHILIPPINES FOR FIFTY (50) YEARS FROM THE APPROVAL OF APPLICATION OFFRANCHISE"
scope = "National"
dateFiled = "1995-09-25"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 1995-09-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Natividad"
[[authorsDetail]]
name = "Natividad"
nameCode = "Natividad"
date = ""
sequence = 0

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "1995-09-28"

[[committee]]
name = "DISASTER RESILIENCE"
type = "principal"
referralCode = "I504"

[firstReading]
id = 110199
congress = 10
bill_no = "HB03778"
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
date_read = "1995-09-28"
