billNumber = "HB04137"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB04137"
lastScraped = "2025-09-22T00:20:58.138881"
title = "HB04137"
longTitle = "AN ACT ESTABLISHING THE PHILIPPINE OPEN UNIVERSITY"
scope = "National"
dateFiled = "1995-10-02"
status = "Substituted by HB10520"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "De Venecia, Jose Jr."
coAuthors = [ "ESCUDERO, SALVADOR III H.", "ALBANO, RODOLFO JR. B.", "ROXAS, MANUEL A.", "SHAHANI, RANJIT R.", "ABLAN, ROQUE JR. R.", "SINGSON, ERIC D.", "CUENCO, ANTONIO V.", "ORTEGA, VICTOR F.", "AUMENTADO, ERICO B.", "MONTEMAYOR, LEONARDO Q.", "GOLEZ, ROILO S.", "LIBAN, DANTE V.", "LOPEZ, JAIME C.", "AVILA, EDGAR M.", "JALOSJOS, ROMEO G.",]
[[authorsDetail]]
name = "De Venecia, Jose Jr."
nameCode = "De Venecia"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ESCUDERO, SALVADOR III H."
nameCode = "Escudero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALBANO, RODOLFO JR. B."
nameCode = "Albano"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROXAS, MANUEL A."
nameCode = "Roxas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SHAHANI, RANJIT R."
nameCode = "Shahani"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ABLAN, ROQUE JR. R."
nameCode = "Ablan"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SINGSON, ERIC D."
nameCode = "Singson"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CUENCO, ANTONIO V."
nameCode = "Cuenco"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ORTEGA, VICTOR F."
nameCode = "Ortega"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AUMENTADO, ERICO B."
nameCode = "Aumentado"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = "Montemayor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GOLEZ, ROILO S."
nameCode = "Golez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOPEZ, JAIME C."
nameCode = "Lopez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AVILA, EDGAR M."
nameCode = "Avila"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JALOSJOS, ROMEO G."
nameCode = "Jalosjos"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "0509"
dateRead = "1995-10-04"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 110558
congress = 10
bill_no = "HB04137"
referral = "0509"
ref_name = "EDUCATION AND CULTURE"
date_read = "1995-10-04"
