billNumber = "HB05453"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB05453"
lastScraped = "2025-09-22T00:20:58.377581"
title = "HB05453"
longTitle = "AN ACT STRENGTHENING THE PHILIPPINE COCONUT AUTHORITY, INCREASING THE SMALL COCONUT FARMERS' PARTICIPATION IN, AND THEIR BENEFITS FROM, THE COCONUT INDUSTRY, AND BOLSTERING THE INDUSTRY'S DEVELOPMENT, AMENDING FOR THE PURPOSE PRESIDENTIAL DECREE NUMBERED FOURTEEN HUNDRED AND SIXTY-EIGHT, AS AMENDED, OTHERWISE KNOWN AS THE REVISED COCONUT INDUSTRY CODE"
scope = "National"
dateFiled = "1995-12-06"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 1995-12-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Tanada"
coAuthors = [ "GILLEGO, BONIFACIO H.", "DRAGON, RENATO P.", "QUIMPO, ALLEN S.", "AVILA, EDGAR M.",]
[[authorsDetail]]
name = "Tanada"
nameCode = "Tanada"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "GILLEGO, BONIFACIO H."
nameCode = "Gillego"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "QUIMPO, ALLEN S."
nameCode = "Quimpo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AVILA, EDGAR M."
nameCode = "Avila"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "0503"
dateRead = "1995-12-11"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[[committee]]
name = "WAYS AND MEANS"
type = "secondary"
referralCode = "0542"

[firstReading]
id = 111874
congress = 10
bill_no = "HB05453"
referral = "0503"
ref_name = "AGRICULTURE AND FOOD"
date_read = "1995-12-11"
