billNumber = "HB05893"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB05893"
lastScraped = "2025-09-22T00:20:58.457272"
title = "HB05893"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF A GARBAGE RECYCLING CENTER IN THE MUNICIPALITY OF ISABELA, PROVINCE OF BASILAN, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1996-01-24"
status = "Substituted by HB08622"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Muarip"
[[authorsDetail]]
name = "Muarip"
nameCode = "Muarip"
date = ""
sequence = 0

[[committee]]
name = "ECOLOGY"
type = "primary"
referralCode = "A501"
dateRead = "1996-01-29"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 112314
congress = 10
bill_no = "HB05893"
referral = "A501"
ref_name = "ECOLOGY"
date_read = "1996-01-29"
