billNumber = "HB05844"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB05844"
lastScraped = "2025-09-22T00:20:58.449576"
title = "HB05844"
longTitle = "AN ACT IMPOSING A TWENTY PERCENT (20%) IMPORT DUTIES ON ALL FOREIGN LEAF TOBACCO, THEREBY REPEALING REPUBLIC ACT NO. 4255 AS AMENDED, OTHERWISE KNOWN AS 'AN ACT TO PROMOTE AND STRENGTHEN THE VIRGINIA TOBACCO INDUSTRY'"
scope = "National"
dateFiled = "1996-01-23"
status = "Substituted by HB06451"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Tajon"
coAuthors = [ "SINGSON, ERIC D.", "LIBAN, DANTE V.", "PIMENTEL, EMMANUEL B.",]
[[authorsDetail]]
name = "Tajon"
nameCode = "Tajon"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "SINGSON, ERIC D."
nameCode = "Singson"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PIMENTEL, EMMANUEL B."
nameCode = "Pimentel"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "1996-01-29"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 112265
congress = 10
bill_no = "HB05844"
referral = "0542"
ref_name = "WAYS AND MEANS"
date_read = "1996-01-29"
