billNumber = "HB05661"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB05661"
lastScraped = "2025-09-22T00:20:58.417669"
title = "HB05661"
longTitle = "AN ACT TO STRENGTHEN THE PROMOTION, DEVELOPMENT AND ASSISTANCE TO SMALL AND MEDIUM SCALE ENTERPRISES, AMENDING FOR THAT PURPOSE REPUBLIC ACT NO. 6977, OTHERWISE KNOWN AS THE 'MAGNA CARTA FOR SMALL ENTERPRISES', AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1995-12-29"
status = "Substituted by HB09069"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Villar"
coAuthors = [ "AVILA, EDGAR M.", "LIBAN, DANTE V.", "VILLAREAL, JULITA L.",]
[[authorsDetail]]
name = "Villar"
nameCode = "Villar"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "AVILA, EDGAR M."
nameCode = "Avila"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLAREAL, JULITA L."
nameCode = "Villareal"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "primary"
referralCode = "0536"
dateRead = "1996-01-22"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 112082
congress = 10
bill_no = "HB05661"
referral = "0536"
ref_name = "ECONOMIC AFFAIRS"
date_read = "1996-01-22"
