billNumber = "HB06095"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB06095"
lastScraped = "2025-09-22T00:20:58.494192"
title = "HB06095"
longTitle = "AN ACT PROVIDING A MAGNA CARTA FOR SCIENTISTS, ENGINEERS, RESEARCHERS AND OTHER S & T PERSONNEL"
scope = "National"
dateFiled = "1996-02-05"
status = "REPUBLIC ACT (RA08439) enacted on 1997-12-22"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bagatsing"
coAuthors = [ "TY, MARIO S.", "FALCON, JESNAR R.", "SARMIENTO, ANGELITO M.", "SANDOVAL, VICENTE A.", "SCIENCE AND TECHNOLOGY", "AUMENTADO, ERICO B.", "BORJA-AGANA, VENICE", "ROMERO, MIGUEL L.", "DE LA CRUZ, ZOILO JR. V.", "DEJON, TEMISTOCLES SR. S.", "JABAR, RAMON J.", "MERCADO, ROGER G.", "GOLEZ, ROILO S.", "DIAZ, RENATO V.", "MONTEMAYOR, LEONARDO Q.",]
[[authorsDetail]]
name = "Bagatsing"
nameCode = "Bagatsing"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "TY, MARIO S."
nameCode = "Ty"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FALCON, JESNAR R."
nameCode = "Falcon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SARMIENTO, ANGELITO M."
nameCode = "Sarmiento"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SANDOVAL, VICENTE A."
nameCode = "Sandoval"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SCIENCE AND TECHNOLOGY"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AUMENTADO, ERICO B."
nameCode = "Aumentado"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BORJA-AGANA, VENICE"
nameCode = "Borja-agana"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMERO, MIGUEL L."
nameCode = "Romero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DE LA CRUZ, ZOILO JR. V."
nameCode = "De La Cruz"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEJON, TEMISTOCLES SR. S."
nameCode = "Dejon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JABAR, RAMON J."
nameCode = "Jabar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MERCADO, ROGER G."
nameCode = "Mercado"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GOLEZ, ROILO S."
nameCode = "Golez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DIAZ, RENATO V."
nameCode = "Diaz"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = "Montemayor"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1996-02-06"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "principal"
referralCode = "0515"

[[motherBills]]
bill_no = "HB03289"
flag = "S"

[[substitutedBills]]
bill_no = "HB03289"
flag = "S"

[firstReading]
id = 112516
congress = 10
bill_no = "HB06095"
report = "00173"
referral = "0532"
ref_name = "RULES"
recomm = "APPROVAL"
date_read = "1996-02-06"
date_ob = "1996-02-06"
date_unass = "1996-02-13"
date_report = "1996-02-05"

[secondReading]
id = 18299
congress = 10
bill_no = "HB06095"
date_calendared = "1996-05-07"
date_approved = "1996-05-21"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 2901
congress = 10
bill_no = "HB06095"
date_dist = "1996-05-30"
date_adopt = "1996-06-04"
no_yeas = 171
no_nays = 0
no_abstent = 0
date_trans = "1996-06-04"
date_rec = "1996-06-06"
date_rqcc = "1997-12-03"
date_agrcc = "1997-12-08"
ccreqby = "S"
act_pres = "A"
dte_hsagcc = "1997-12-16"
dte_snagcc = "1997-12-16"
dte_actedp = "1997-12-22"
