billNumber = "HB06296"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB06296"
lastScraped = "2025-09-22T00:20:58.532572"
title = "HB06296"
longTitle = "AN ACT CONVERTING THE AMAMPEREZ NATIONAL HIGH SCHOOL IN THE MUNICIPALITY OF VILLASIS, PROVINCE OF PANGASINAN, INTO AN AGRO-INDUSTRIAL HIGH SCHOOL TO BE KNOWN AS THE AMAMPEREZ AGRO-INDUSTRIAL HIGH SCHOOL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1996-02-20"
status = "REPUBLIC ACT RA08672 (Lapsed into law on 1998-06-25)"
statusOrder = 32.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Perez"
[[authorsDetail]]
name = "Perez"
nameCode = "Perez"
date = ""
sequence = 0

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "0509"
dateRead = "1996-02-22"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 112717
congress = 10
bill_no = "HB06296"
report = "00937"
referral = "0509"
ref_name = "EDUCATION AND CULTURE"
recomm = "approval with amendment"
date_read = "1996-02-22"
date_ob = "1997-05-20"
date_report = "1997-05-19"

[secondReading]
id = 18328
congress = 10
bill_no = "HB06296"
remarks = "Considered the Explantory Note as the Sponsorship Speech"
date_approved = "1997-05-22"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 2928
congress = 10
bill_no = "HB06296"
date_dist = "1997-05-27"
date_adopt = "1997-08-04"
no_yeas = 165
no_nays = 0
no_abstent = 0
date_trans = "1997-08-05"
date_rec = "1997-08-07"
amend_ind = "N"
act_pres = "L"
dte_transp = "1998-05-22"
dte_actedp = "1998-06-25"
