billNumber = "HB07278"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB07278"
lastScraped = "2025-09-22T00:20:58.712213"
title = "HB07278"
longTitle = "AN ACT ESTABLISHING A CERAMIC MAKING TRAINING CENTER IN THE MUNICIPALITY OF HINUNDAYAN, PROVINCE OF SOUTHERN LEYTE, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1996-06-04"
status = "Pending with the Committee on TRADE AND INDUSTRY since 1996-06-06"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "MERCADO, ROGER GAVIOLA"
[[authorsDetail]]
name = "MERCADO, ROGER GAVIOLA"
nameCode = "Mercado"
date = ""
sequence = 0

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = "1996-06-06"

[[committee]]
name = "CLIMATE CHANGE"
type = "principal"
referralCode = "H503"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 113699
congress = 10
bill_no = "HB07278"
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
date_read = "1996-06-06"
