billNumber = "HB08816"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HB08816"
lastScraped = "2025-09-22T00:20:59.043350"
title = "HB08816"
longTitle = "AN ACT CREATING THE PHILIPPINE INSTITUTE OF TRADITIONAL AND COMPLEMENTARY HEALTH CARE (PITCHC) TO ACCELERATE THE DEVELOPMENT OF TRADITIONAL AND COMPLEMENTARY HEALTH CARE IN THE PHILIPPINES, PROVIDING FOR A TRADITIONAL AND COMPLEMENTARY HEALTH CARE DEVELOPMENT FUND AND OTHER PURPOSES"
scope = "National"
dateFiled = "1997-01-28"
status = "Pending with the Committee on HEALTH since 1997-01-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ty"
coAuthors = [ "DATUMANONG, SIMEON A.", "DEJON, TEMISTOCLES SR. S.", "RODRIGUEZ, OSCAR S.",]
[[authorsDetail]]
name = "Ty"
nameCode = "Ty"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DATUMANONG, SIMEON A."
nameCode = "Datumanong"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEJON, TEMISTOCLES SR. S."
nameCode = "Dejon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RODRIGUEZ, OSCAR S."
nameCode = "Rodriguez"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "1997-01-30"

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "principal"
referralCode = "0536"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 115237
congress = 10
bill_no = "HB08816"
referral = "0517"
ref_name = "HEALTH"
date_read = "1997-01-30"
