billNumber = "HR00754"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HR00754"
lastScraped = "2025-09-22T00:20:59.567308"
title = "HR00754"
longTitle = "RESOLUTION OF THE HOUSE OF REPRESENTATIVES COMMENDING MANSUETO VELASCO, JR. FOR BRINGING HONOR TO THE COUNTRY THROUGH HIS STERLING PERFORMANCE IN THE FIELD OF BOXING AT THE OLYMPICS IN ATLANTA, U.S.A."
scope = "Local"
dateFiled = "1996-08-02"
status = "Substituted by HR00756"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Roxas"
coAuthors = [ "COLAMBO, FELIZARDO R.", "MONTEMAYOR, LEONARDO Q.", "LIBAN, DANTE V.",]
[[authorsDetail]]
name = "Roxas"
nameCode = "Roxas"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "COLAMBO, FELIZARDO R."
nameCode = "Colambo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = "Montemayor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1996-08-05"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 117808
congress = 10
bill_no = "HR00754"
referral = "0532"
ref_name = "RULES"
date_read = "1996-08-05"
