billNumber = "HR00798"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HR00798"
lastScraped = "2025-09-22T00:20:59.575535"
title = "HR00798"
longTitle = "RESOLUTION REQUESTING THE APPROPRIATE COMMITTEE(S) OF THE HOUSE OF REPRESENTATIVES TO INQUIRY, IN AID OF LEGISLATION, ON THE APPROPRIATENESS AND LEGALITY OF ALLOWING THE CONSTRUCTION OF LOW COST TENEMENT HOUSING UNITS ALONG BOTH SIDES OF THE RAILROAD TRACKS UNDER THE PABAHAY SA RILES PROJECT OF THE PHILIPPINE NATIONAL RAILWAYS"
scope = "National"
dateFiled = "1996-08-22"
status = "Pending with the Committee on RULES since 1996-08-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Suarez, Danilo E."
coAuthors = [ "JOAQUIN, NEREO R.", "DEJON, TEMISTOCLES SR. S.",]
[[authorsDetail]]
name = "Suarez, Danilo E."
nameCode = "Suarez"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "JOAQUIN, NEREO R."
nameCode = "Joaquin"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEJON, TEMISTOCLES SR. S."
nameCode = "Dejon"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1996-08-26"

[[committee]]
name = "INTER-PARLIAMENTARY RELATIONS AND DIPLOMACY"
type = "principal"
referralCode = "A505"

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "secondary"
referralCode = "0518"

[firstReading]
id = 117852
congress = 10
bill_no = "HR00798"
comm_act = "Change of Referral from the Ctte. on Rules to the Ctte. on Housing and Urban Developmen t on Aug. 27"
referral = "0532"
ref_name = "RULES"
date_read = "1996-08-26"
