billNumber = "HR00550"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HR00550"
lastScraped = "2025-09-22T00:20:59.525698"
title = "HR00550"
longTitle = "RESOLUTION MODIFYING THE PERIOD FOR PRIVILEGE HOUR, AMENDING FOR THE PURPOSE SECTION 53, RULE XII OF THE RULES OF THE HOUSE OF REPRESENTATIVES"
scope = "Local"
dateFiled = "1996-03-19"
status = "Pending with the Committee on RULES since 1996-03-21"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Osmeña"
coAuthors = [ "CALALAY, REYNALDO A.", "MONFORT, NARCISO D.",]
[[authorsDetail]]
name = "Osmeña"
nameCode = "Osmeña"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "CALALAY, REYNALDO A."
nameCode = "Calalay"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1996-03-21"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 117604
congress = 10
bill_no = "HR00550"
referral = "0532"
ref_name = "RULES"
date_read = "1996-03-21"
