billNumber = "HR00431"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HR00431"
lastScraped = "2025-09-22T00:20:59.502050"
title = "HR00431"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON ENERGY TO INVESTIGATE NATIONAL POWER CORPORATION (NAPOCOR) FOR NON-REDUCTION OF POWER RATES IN LEYTE-SAMAR (REGION VIII)"
scope = "Local"
dateFiled = "1996-01-30"
status = "Pending with the Committee on ENERGY since 1996-02-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Apostol, Sergio A. F."
[[authorsDetail]]
name = "Apostol, Sergio A. F."
nameCode = "Apostol"
date = ""
sequence = 0

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "1996-02-01"

[[committee]]
name = "TOURISM"
type = "principal"
referralCode = "0538"

[firstReading]
id = 117485
congress = 10
bill_no = "HR00431"
comm_act = "Change of Referral from the Ctte. on Rules to the Ctte. on Energy on Feb. 5, 1996."
referral = "0510"
ref_name = "ENERGY"
date_read = "1996-02-01"
