billNumber = "HR01437"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=HR01437"
lastScraped = "2025-09-22T00:20:59.699243"
title = "HR01437"
longTitle = "RESOLUTION CALLING UPON THE PROPER AGENCIES OF THE GOVERNMENT TO INSTITUTIONALIZ E THE ESTABLISHMENT AND MODERNIZATION OF DEMONSTRATION FARMS ON CROPS, FISHERIES, LIVESTOCK AND LIVELIHOOD DEVELOPMENT IN ALL CONGRESSIONAL DISTRICTS IN CONJUNCTION WITH THE SETTING UP OF INFORMATION TECHNOLOGY TRAINING CENTERS"
scope = "National"
dateFiled = "1997-11-19"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 1997-11-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Geronimo"
coAuthors = [ "CALALAY, REYNALDO A.",]
[[authorsDetail]]
name = "Geronimo"
nameCode = "Geronimo"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "CALALAY, REYNALDO A."
nameCode = "Calalay"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "0503"
dateRead = "1997-11-25"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[[committee]]
name = "PUBLIC INFORMATION"
type = "secondary"
referralCode = "0528"

[[committee]]
name = "SCIENCE AND TECHNOLOGY"
type = "secondary"
referralCode = "0534"

[[committee]]
name = "FOOD SECURITY"
type = "secondary"
referralCode = "B513"

[firstReading]
id = 118491
congress = 10
bill_no = "HR01437"
comm_act = "Jointly Referred to the Ctte's. on Public Informatio n, Agricultur e and Food, and Science and Techn"
referral = "0503"
ref_name = "AGRICULTURE AND FOOD"
date_read = "1997-11-25"
