billNumber = "RPT1492"
billType = "HB"
congress = 10
apiCongressId = 10
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=10&q=RPT1492"
lastScraped = "2025-09-22T00:20:59.719048"
title = "RPT1492"
longTitle = "PRIVILEGE SPEECH OF HONORABLE DIDAGEN P. DILANGALEN DELIVERED ON JULY 29, 1997"
scope = "Local"
dateFiled = "1998-02-10"
status = "Pending with the Committee on RULES since 1998-02-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1998-02-11"

[firstReading]
id = 118615
congress = 10
bill_no = "RPT1492"
report = "01492"
referral = "0532"
ref_name = "RULES"
date_read = "1998-02-11"
date_ob = "1998-02-11"
date_report = "1998-02-10"
