billNumber = "HBN-04861"
billType = "HBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=HBN-4861"
lastScraped = "2025-09-20T23:44:06.280385"
title = "PHYSICIANS ACT OF 2006"
longTitle = "AN ACT REGULATING THE EDUCATION AND LICENSURE OF PHYSICIANS AND THE PRACTICE OF MEDICINE IN THE PHILIPPINES, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. 2382, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Physician`S Act",]
pdfUrl = "https://web.senate.gov.ph/lisdata/47313883!.pdf"
pdfFileName = "HBN-4861 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "3/1/2006"
action = "Filed in the Senate requesting for concurrence by Representatives AGAPITO S. AQUINO, RAUL V. DEL MAR, FRANCIS 'BLUEBOY' L. NEPOMUCENO, ROLANDO G. ANDAYA JR., HARLIN C. ABAYON, ET. AL., as authors;"

[[legislativeHistory]]
date = "3/6/2006"
action = "Read on First Reading and Referred to the Committee(s) on CIVIL SERVICE AND GOVERNMENT REORGANIZATION; EDUCATION, ARTS AND CULTURE and FINANCE;"

[[legislativeHistory]]
date = "1/31/2007"
action = "Returned jointly by the Committee(s) on CIVIL SERVICE AND GOVERNMENT REORGANIZATION, EDUCATION, ARTS AND CULTURE and FINANCE per Committee Report No. 240, recommending that it be considered in SBN-2590;"

[[legislativeHistory]]
date = "1/31/2007"
action = "Submitted said Committee Report to the Senate;"

[[legislativeHistory]]
date = "1/31/2007"
action = "CONSIDERED IN SBN-2590."

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "1/31/2007"

[committee]
name = "Civil Service and Government Reorganization"
type = "primary"
