billNumber = "HB00210"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB00210"
lastScraped = "2025-09-22T00:13:47.880961"
title = "HB00210"
longTitle = "AN ACT GRANTING THE RIGHT TO FRANCHISEES TO DEVELOP THE RURAL AIRPORT INFRASTRUCTURE NETWORK IN THE PHILIPPINES FOR COMMERCIAL AND OTHER PURPOSES"
scope = "National"
dateFiled = "2004-07-01"
status = "Pending with the Committee on TRANSPORTATION since 2005-01-12"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/hb00210.pdf"
fileSize = 280110
author = "Biazon, Rozzano Rufino B."
coAuthors = [ "CODILLA, EUFROCINO SR. M.", "AMIN, HUSSIN U.", "FIGUEROA, CATALINO V.",]
[[authorsDetail]]
name = "Biazon, Rozzano Rufino B."
nameCode = "Biazon"
date = ""
sequence = 87

[[coAuthorsDetail]]
name = "CODILLA, EUFROCINO SR. M."
nameCode = "Codilla"
date = ""
journalNo = "J005"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "AMIN, HUSSIN U."
nameCode = "Amin"
date = ""
journalNo = "J006"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "FIGUEROA, CATALINO V."
nameCode = "Figueroa"
date = ""
journalNo = "J016"
sessionNo = "1RS"

[[committee]]
name = "TRANSPORTATION"
type = "primary"
referralCode = "E509"
dateRead = "2004-07-27"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "principal"
referralCode = "0537"

[firstReading]
id = 75300
congress = 13
bill_no = "HB00210"
report = ""
comm_act = ""
referral = "E509"
ref_name = "TRANSPORTATION"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2005-01-12"
date_read = "2004-07-27"
