billNumber = "HB00909"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB00909"
lastScraped = "2025-09-22T00:13:48.012095"
title = "HB00909"
longTitle = "AN ACT ESTABLISHING A NATIONAL HIGH SCHOOL IN BARANGAY LUMBIA, MUNICIPALITY OF ESTANCIA,PROVINCE OF ILOILO, TO BE KNOWN AS THE LUMBIA NATIONAL HIGH SCHOOL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2004-07-01"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2004-07-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB00909.pdf"
fileSize = 21906589
author = "Suplico, Rolex T."
[[authorsDetail]]
name = "Suplico, Rolex T."
nameCode = "Suplico"
date = ""
sequence = 0

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2004-07-28"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 75999
congress = 13
bill_no = "HB00909"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2004-07-28"
date_read = "2004-07-28"
