billNumber = "HB01606"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB01606"
lastScraped = "2025-09-22T00:13:48.136227"
title = "Magna Carta for Household Helpers or Batas Kasambahay"
longTitle = "AN ACT INSTITUTING POLICIES GOVERNING THE HOUSEHOLD EMPLOYMENT INDUSTRY, ESTABLISHING A STANDARD OF PROTECTION AND PROMOTING THE WELFARE OF HOUSEHOLD HELPERS"
scope = "National"
dateFiled = "2004-07-26"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 2004-08-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB01606.pdf"
fileSize = 607000
author = "Ponce Enrile, Juan Jr. C."
[[authorsDetail]]
name = "Ponce Enrile, Juan Jr. C."
nameCode = "Enrile"
date = ""
sequence = 1

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "0521"
dateRead = "2004-08-03"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 76696
congress = 13
bill_no = "HB01606"
report = ""
comm_act = ""
referral = "0521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2004-08-03"
date_read = "2004-08-03"
