billNumber = "HB01689"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB01689"
lastScraped = "2025-09-22T00:13:48.150848"
title = "HB01689"
longTitle = "AN ACT CREATING A NATIONAL HIGH SCHOOL IN BARANGAY CONCEPTION, MUNICIPALITY OF ARTECHE, PROVINCE OF EASTERN SAMAR, TO BE KNOWN AS THE CONCEPTION NATIONAL HIGH SCHOOL"
scope = "Local"
dateFiled = "2004-07-27"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2004-08-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB01689.pdf"
fileSize = 11906991
author = "LIBANAN, MARCELINO C."
[[authorsDetail]]
name = "LIBANAN, MARCELINO C."
nameCode = "Libanan"
date = ""
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2004-08-04"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 76779
congress = 13
bill_no = "HB01689"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2004-08-04"
date_read = "2004-08-04"
