billNumber = "HB01710"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB01710"
lastScraped = "2025-09-22T00:13:48.154468"
title = "HB01710"
longTitle = "AN ACT REPEALING REPUBLIC ACT NO. 9103, GRANTING LAOAG INTERNATIONAL AIRLINES, INC. A FRANCHISE TO ESTABLISH, OPERATE AND MAINTAIN DOMESTIC AND INTERNATIONAL AIR TRANSPORT SERVICES"
scope = "Local"
dateFiled = "2004-07-27"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 2004-08-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB01710.pdf"
fileSize = 17559776
author = "Ablan, Roque Jr. R."
[[authorsDetail]]
name = "Ablan, Roque Jr. R."
nameCode = "Ablan"
date = ""
sequence = 1

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2004-08-04"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 76800
congress = 13
bill_no = "HB01710"
report = ""
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2004-08-04"
date_read = "2004-08-04"
