billNumber = "HB01124"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB01124"
lastScraped = "2025-09-22T00:13:48.052854"
title = "HB01124"
longTitle = "AN ACT MANDATING THE REPRESENTATION OF COOPERATIVES IN THE BOARD 0F DIRECTORS OF THE LAND BANK OF THE PHILIPPINES, AMENDING THEREFOR REPUBLIC ACT NO. 3844, AS AMENDED"
scope = "National"
dateFiled = "2004-07-06"
status = "Substituted by HB04148"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Cua, Guillermo P."
coAuthors = [ "VELARDE, RENE M.", "OLANO, ARREL R.", "MANGUDADATU, SUHARTO T.", "NICOLAS, REYLINA \"NENENG\" G.",]
[[authorsDetail]]
name = "Cua, Guillermo P."
nameCode = "Cua"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "VELARDE, RENE M."
nameCode = "Velarde"
date = ""
journalNo = "J005"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "OLANO, ARREL R."
nameCode = "Olano"
date = ""
journalNo = "J008"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MANGUDADATU, SUHARTO T."
nameCode = "Mangudadatu"
date = ""
journalNo = "J040"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "NICOLAS, REYLINA \"NENENG\" G."
nameCode = "Nicolas"
date = ""
journalNo = "J056"
sessionNo = "1RS"

[[committee]]
name = "COOPERATIVES DEVELOPMENT"
type = "primary"
referralCode = "B512"
dateRead = "2004-08-02"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 76214
congress = 13
bill_no = "HB01124"
report = ""
comm_act = ""
referral = "B512"
ref_name = "COOPERATIVES DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2004-08-02"
date_read = "2004-08-02"
