billNumber = "HB02296"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB02296"
lastScraped = "2025-09-22T00:13:48.256712"
title = "HB02296"
longTitle = "AN ACT POSTPONING THE 2005 BARANGAY AND SANGGUNIANG KABATAAN ELECTIONS AND HOLDING THE SAME IN MAY 2007 TO COINCIDE WITH THE LOCAL ELECTIONS"
scope = "National"
dateFiled = "2004-08-10"
status = "Substituted by HB03742"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Puentevella, Monico O."
[[authorsDetail]]
name = "Puentevella, Monico O."
nameCode = "Puentevella"
date = ""
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2004-08-16"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "secondary"
referralCode = "0537"

[firstReading]
id = 77386
congress = 13
bill_no = "HB02296"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2004-08-16"
date_read = "2004-08-16"
