billNumber = "HB03846"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB03846"
lastScraped = "2025-09-22T00:13:48.551510"
title = "HB03846"
longTitle = "AN ACT REPEALING REPUBLIC ACT 7942, OTHERWISE KNOWN AS THE MINING ACT OF 1995"
scope = "National"
dateFiled = "2005-03-02"
status = "Pending with the Committee on NATURAL RESOURCES since 2005-03-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB03846.pdf"
fileSize = 188044
author = "Virador, Joel G."
coAuthors = [ "OCAMPO, SATUR", "CASIÑO, TEODORO A.", "MAZA, LIZA", "BELTRAN, CRISPIN", "MARIANO, RAFAEL V.",]
[[authorsDetail]]
name = "Virador, Joel G."
nameCode = "Virador"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "OCAMPO, SATUR"
nameCode = "Ocampo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CASIÑO, TEODORO A."
nameCode = "Casiño"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAZA, LIZA"
nameCode = "Maza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BELTRAN, CRISPIN"
nameCode = "Beltran"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MARIANO, RAFAEL V."
nameCode = "Mariano"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "0526"
dateRead = "2005-03-08"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[firstReading]
id = 78936
congress = 13
bill_no = "HB03846"
report = ""
comm_act = ""
referral = "0526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2005-03-08"
date_read = "2005-03-08"
