billNumber = "HB04718"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB04718"
lastScraped = "2025-09-22T00:13:48.761138"
title = "HB04718"
longTitle = "AN ACT CONVERTING THE ABONGAN BARANGAY HIGH SCHOOL IN BARANGAY ABONGAN, MUNICIPALITY OF TAYTAY, PROVINCE OF PALAWAN, INTO A NATIONAL HIGH SCHOOL TO BE KNOWN AS THE ABONGAN NATIONAL HIGH SCHOOL, PROVIDING FOR ITS FUNDING AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "2005-09-19"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2005-09-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB04718.pdf"
fileSize = 729671
author = "Alvarez, Antonio C."
[[authorsDetail]]
name = "Alvarez, Antonio C."
nameCode = "Alvarez"
date = ""
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2005-09-27"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 79808
congress = 13
bill_no = "HB04718"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2005-09-27"
date_read = "2005-09-27"
