billNumber = "HB04726"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB04726"
lastScraped = "2025-09-22T00:13:48.763484"
title = "\\\"National Museum Legislative Endowment Fund Act of 2005\\\""
longTitle = "AN ACT ESTABLISHING THE NATIONAL MUSEUM LEGISLATIVE ENDOWMENT FUND"
scope = "National"
dateFiled = "2005-09-20"
status = "Pending with the Committee on APPROPRIATIONS since 2005-09-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB04726.pdf"
fileSize = 830126
author = "Biazon, Rozzano Rufino B."
coAuthors = [ "CODILLA, EUFROCINO SR. M.", "FIGUEROA, CATALINO V.",]
[[authorsDetail]]
name = "Biazon, Rozzano Rufino B."
nameCode = "Biazon"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "CODILLA, EUFROCINO SR. M."
nameCode = "Codilla"
date = ""
journalNo = "J019"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "FIGUEROA, CATALINO V."
nameCode = "Figueroa"
date = ""
journalNo = "J035"
sessionNo = "2RS"

[[committee]]
name = "APPROPRIATIONS"
type = "primary"
referralCode = "0504"
dateRead = "2005-09-27"

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "principal"
referralCode = "0506"

[firstReading]
id = 79816
congress = 13
bill_no = "HB04726"
report = ""
comm_act = ""
referral = "0504"
ref_name = "APPROPRIATIONS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2005-09-27"
date_read = "2005-09-27"
