billNumber = "HB05711"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB05711"
lastScraped = "2025-09-22T00:13:48.987991"
title = "HB05711"
longTitle = "AN ACT ESTABLISHING A STATE COLLEGE IN THE MUNICIPALITY OF SAN JUAN, METRO MANILA TO BE KNOWN AS SAN JUAN STATE COLLEGE"
scope = "Local"
dateFiled = "2006-08-16"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2006-08-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB05711.pdf"
fileSize = 677709
author = "Zamora, Ronaldo B."
[[authorsDetail]]
name = "Zamora, Ronaldo B."
nameCode = "Zamora"
date = ""
sequence = 1

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2006-08-23"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "principal"
referralCode = "0529"

[firstReading]
id = 80801
congress = 13
bill_no = "HB05711"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2006-08-23"
date_read = "2006-08-23"
