billNumber = "HB05604"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HB05604"
lastScraped = "2025-09-22T00:13:48.965243"
title = "HB05604"
longTitle = "AN ACT CONVERTING THE FRIENDSHIP CIRCUMFERENTIAL ROAD IN THE CITY OF ANGELES, PAMPANGA INTO A NATIONAL ROAD"
scope = "Local"
dateFiled = "2006-06-21"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2006-07-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_13/HB05604.pdf"
fileSize = 702328
author = "Nepomuceno, Francis 'Blueboy'  L."
[[authorsDetail]]
name = "Nepomuceno, Francis 'Blueboy'  L."
nameCode = "Nepomuceno"
date = ""
sequence = 1

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2006-07-26"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 80694
congress = 13
bill_no = "HB05604"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2006-07-26"
date_read = "2006-07-26"
