billNumber = "HR00477"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HR00477"
lastScraped = "2025-09-22T00:13:49.212078"
title = "HR00477"
longTitle = "RESOLUTION URGING TO CONDUCT A THOROUGH INQUIRY ON AND REVIEW OF OUR FORESTRY LAWS AND RULES,AS WELL AS THE TLA, IFMA, SPECIAL PRIVATE LAND TIMBER PERMIT, PRIVATE LAND TIMBER UNIT, FOREST LAND GRAZING MANAGEMENT AGREEMENT, SOCIALIZED INDUSTRIAL FOREST MANAGEMENT AGREEMENT-- ALL WITH THE VIEW FOREMOST OF PROVIDING PROTECTION AND SECURITY TO THE PEOPLE AFFECTED IN THE AREAS CONCERNED"
scope = "National"
dateFiled = "2004-12-14"
status = "Adopted Resolution (Pending with the committee on NATURAL RESOURCES since 2005-02-02)"
statusOrder = 5.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Nantes, Rafael P."
coAuthors = [ "CUA, GUILLERMO P.", "NOGRALES, PROSPERO C.", "ESCUDERO, FRANCIS G.", "RULES",]
[[authorsDetail]]
name = "Nantes, Rafael P."
nameCode = "Nantes"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "CUA, GUILLERMO P."
nameCode = "Cua"
date = ""
journalNo = "J040"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "NOGRALES, PROSPERO C."
nameCode = "Nograles"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESCUDERO, FRANCIS G."
nameCode = "Escudero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RULES"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2004-12-14"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 81741
congress = 13
bill_no = "HR00477"
report = "00342"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Adoption with amendments."
remarks = ""
date_pend = "2004-12-14"
date_read = "2004-12-14"
date_report = "2005-01-27"

[secondReading]
id = 12042
congress = 13
bill_no = "HR00477"
adopted_resolution = ""
adopted_resolution_title = "RESOLUTION DIRECTING THE COMMITTEE ON NATURAL RESOURCES TO CONDUCT A THOROUGH INQUIRY, IN AID OF LEGISLATION, ON AND REVIEW OF OUR FORESTRY LAWS AND RULES,AS WELL AS THE TLA, IFMA, SPECIAL PRIVATE LAND TIMBER PERMIT, PRIVATE LAND TIMBER UNIT, FOREST LAND GRAZING MANAGEMENT AGREEMENT, SOCIALIZED INDUSTRIAL FOREST MANAGEMENT AGREEMENT-- ALL WITH THE VIEW FOREMOST OF PROVIDING PROTECTION AND SECURITY TO THE PEOPLE AFFECTED IN THE AREAS CONCERNED"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "Adopted for Referral to the Ctte. on Natural Resources."
recommended_reconsidered = " "
date_calendared = "2005-02-02"
date_approved = "2005-02-02"
adopted_resolution_with_amendment = "Y"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
date_refferral = "2005-02-02"
action_on_adopted_resolution = ""
