billNumber = "HR00829"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HR00829"
lastScraped = "2025-09-22T00:13:49.301646"
title = "HR00829"
longTitle = "RESOLUTION URGING HER EXCELLENCY, PRESIDENT GLORIA MACAPAGAL-ARROYO, TO LIFT THE REPRIEVES GRANTED TO CONVICTED DRUG OFFENDERS SENTENCED TO DEATH"
scope = "National"
dateFiled = "2005-05-30"
status = "Pending with the Committee on REVISION OF LAWS since 2005-05-31"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ablan, Roque Jr. R."
coAuthors = [ "GIDAYA, ERNESTO S.", "CUENCO, ANTONIO V.", "ZUBIRI, JUAN MIGUEL F.", "ESPINO, AMADO JR. T.", "BARBERS, ROBERT ACE S.", "BERSAMIN, LUIS JR. P.",]
[[authorsDetail]]
name = "Ablan, Roque Jr. R."
nameCode = "Ablan"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "GIDAYA, ERNESTO S."
nameCode = "Gidaya"
date = ""
journalNo = "J003"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CUENCO, ANTONIO V."
nameCode = "Cuenco"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ZUBIRI, JUAN MIGUEL F."
nameCode = "Zubiri"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESPINO, AMADO JR. T."
nameCode = "Espino"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BARBERS, ROBERT ACE S."
nameCode = "Barbers"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BERSAMIN, LUIS JR. P."
nameCode = "Bersamin"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2005-05-31"

[[committee]]
name = "ECOLOGY"
type = "principal"
referralCode = "A501"

[firstReading]
id = 82092
congress = 13
bill_no = "HR00829"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2005-05-31"
date_read = "2005-05-31"
