billNumber = "HR00898"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=HR00898"
lastScraped = "2025-09-22T00:13:49.317398"
title = "HR00898"
longTitle = "RESOLUTION EXPRESSING AND CONVEYING TO THE FAMILY OF THE HONORABLE RAUL S. ROCO THE CHAMBER'S PROFOUNDEST CONDOLENCES AND DEEPEST SYMPATHIES ON THE DEMISE OF A DISTINGUISHED AND EXEMPLARY MEMBER OF THE HOUSE OF REPRESENTATIVES, EIGHTH CONGRESS OF THE REPUBLIC OF THE PHILIPPINES"
scope = "National"
dateFiled = "2005-08-08"
status = "Consolidated into HR00897"
statusOrder = 9.2
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lagman, Edcel C."
coAuthors = [ " A L L  MEMBERS",]
[[authorsDetail]]
name = "Lagman, Edcel C."
nameCode = "Lagman"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = " A L L  MEMBERS"
nameCode = ""
date = ""
journalNo = "J006"
sessionNo = "2RS"

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2005-08-08"

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 82161
congress = 13
bill_no = "HR00898"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2005-08-08"
date_read = "2005-08-08"
