billNumber = "PS00473"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=PS00473"
lastScraped = "2025-09-22T00:13:49.540403"
title = "PS00473"
longTitle = "Lauding Speaker de Venecia for His Efforts in Convening the 4th International Conference on ASEAN Political Parties"
scope = "National"
dateFiled = "2006-09-12"
status = "Pending First Reading (Filed last 2006-09-12)"
statusOrder = 1.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Cerilles, Antonio H."
[[authorsDetail]]
name = "Cerilles, Antonio H."
nameCode = "Cerilles"
date = ""
sequence = 0

