billNumber = "PS00514"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=PS00514"
lastScraped = "2025-09-22T00:13:49.546455"
title = "PS00514"
longTitle = "Health Reform Program and the Exhorbitant Prices of Medicines"
scope = "National"
dateFiled = "2006-11-28"
status = "Pending with the Committee on TRADE AND INDUSTRY since 2006-12-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Hontiveros-Baraquel, Ana Theresia 'Risa'"
[[authorsDetail]]
name = "Hontiveros-Baraquel, Ana Theresia 'Risa'"
nameCode = "Hontiveros-baraquel"
date = ""
sequence = 0

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = "2006-12-05"

[firstReading]
id = 83123
congress = 13
bill_no = "PS00514"
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
date_read = "2006-12-05"
