billNumber = "PS00426"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=PS00426"
lastScraped = "2025-09-22T00:13:49.533759"
title = "PS00426"
longTitle = "That There Is a Scarcity of Classrooms and Teachers in Public Schools"
scope = "National"
dateFiled = "2006-06-06"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2006-08-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Teves, Herminio G."
[[authorsDetail]]
name = "Teves, Herminio G."
nameCode = "Teves"
date = ""
sequence = 0

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2006-08-01"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 83074
congress = 13
bill_no = "PS00426"
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
date_read = "2006-08-01"
