billNumber = "PS00446"
billType = "HB"
congress = 13
apiCongressId = 13
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=13&q=PS00446"
lastScraped = "2025-09-22T00:13:49.536360"
title = "PS00446"
longTitle = "Illegal Mining Operations in the Angat Watershed Reservation"
scope = "National"
dateFiled = "2006-08-02"
status = "Pending with the Committee on GOOD GOVERNMENT since 2006-08-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Sandoval, Federico II S."
[[authorsDetail]]
name = "Sandoval, Federico II S."
nameCode = "Sandoval"
date = ""
sequence = 0

[[committee]]
name = "GOOD GOVERNMENT"
type = "primary"
referralCode = "A502"
dateRead = "2006-08-29"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 83084
congress = 13
bill_no = "PS00446"
referral = "A502"
ref_name = "GOOD GOVERNMENT"
sub_name = ""
date_read = "2006-08-29"
