billNumber = "SBN-02332"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-2332"
lastScraped = "2025-09-20T23:32:54.644982"
title = "NATIONAL CHILD ABUSER REGISTRATION ACT"
filedDate = "August 3, 2010"
author = "Defensor Santiago, Miriam"
longTitle = "AN ACT REQUIRING GOVERNMENT AGENCIES AND NON-GOVERNMENT AGENCIES TO REGISTER ALL OFFENDERS CONVICTED OF ANY ACT INVOLVING CHILD ABUSE WITH THE DEPARTMENT OF JUSTICE"
scope = "National"
subject = [ "National Child Abuser Registration Act", "Child Care Laws",]
pdfUrl = "https://web.senate.gov.ph/lisdata/100118522!.pdf"
pdfFileName = "SBN-2332 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/3/2010"
action = "Introduced by Senator MIRIAM DEFENSOR SANTIAGO;"

[[legislativeHistory]]
date = "9/21/2010"
action = "Read on First Reading and Referred to the Committee(s) on JUSTICE AND HUMAN RIGHTS and YOUTH, WOMEN AND FAMILY RELATIONS;"

[status]
status = "Pending in the Committee"
date = "9/21/2010"

[committee]
name = "Justice and Human Rights"
type = "primary"
