billNumber = "SBN-01233"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-1233"
lastScraped = "2025-09-20T23:23:23.197934"
title = "ANTI-TELECOMMUNICATION FRAUD ACT OF 2010"
filedDate = "July 12, 2010"
author = "Villar, Manny B."
longTitle = "AN ACT PROHIBITING TELECOMMUNICATIONS FRAUD AND DESTRUCTION OF TELECOMMUNICATIONS FACILITIES, PROVIDING PENALTIES THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Telecommunications Fraud",]
pdfUrl = "https://web.senate.gov.ph/lisdata/87647306!.pdf"
pdfFileName = "SBN-1233 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/12/2010"
action = "Introduced by Senator MANNY VILLAR;"

[[legislativeHistory]]
date = "8/25/2010"
action = "Read on First Reading and Referred to the Committee on PUBLIC SERVICES;"

[status]
status = "Pending in the Committee"
date = "8/25/2010"

[committee]
name = "Public Services"
type = "primary"
