billNumber = "SBN-03308"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-3308"
lastScraped = "2025-09-20T23:45:20.930231"
title = "SOIL AND WATER CONSERVATION ACT OF 2012"
filedDate = "October 15, 2012"
author = "Legarda, Loren B."
longTitle = "AN ACT PROMOTING SOIL AND WATER CONSERVATION TECHNOLOGIES AND APPROACHES FOR SUSTAINABLE LAND MANAGEMENT IN THE PHILIPPINES AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Sustainable Land Management", "Conservation",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1423711974!.pdf"
pdfFileName = "SBN-3308 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "10/15/2012"
action = "Introduced by Senator LOREN B. LEGARDA;"

[[legislativeHistory]]
date = "10/16/2012"
action = "Read on First Reading and Referred to the Committee(s) on AGRICULTURE AND FOOD; ENVIRONMENT AND NATURAL RESOURCES and FINANCE;"

[status]
status = "Pending in the Committee"
date = "10/16/2012"

[committee]
name = "Agriculture and Food"
type = "primary"
