billNumber = "SBN-00408"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-408"
lastScraped = "2025-09-20T23:13:02.106360"
title = "PENALTIES IMPOSED AGAINST CONTRACTORS AND SUBCONTRACTORS WHO VIOLATE ANY MATERIAL (P.D. NO. 1759)"
filedDate = "July 6, 2010"
author = "Trillanes, Antonio \"Sonny\" F."
longTitle = "AN ACT INCREASING THE PENALTIES IMPOSED AGAINST CONTRACTORS AND SUBCONTRACTORS WHO VIOLATE ANY MATERIAL PROVISION OF CONTRACTS INVOLVING PUBLIC WORKS PROJECTS OF THE GOVERNMENT, AND PUBLIC OFFICIALS WHO ALLOW SUCH VIOLATIONS, AMENDING FOR THIS PURPOSE PRESIDENTIAL DECREE NO. 1759"
scope = "National"
subject = [ "Contractor Accountability",]
pdfUrl = "https://web.senate.gov.ph/lisdata/78076660!.pdf"
pdfFileName = "SBN-408, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/6/2010"
action = "Introduced by Senator ANTONIO 'SONNY' F. TRILLANES;"

[[legislativeHistory]]
date = "8/4/2010"
action = "Read on First Reading and Referred to the Committee(s) on PUBLIC WORKS and CONSTITUTIONAL AMENDMENTS, REVISION OF CODES AND LAWS;"

[status]
status = "Pending in the Committee"
date = "8/4/2010"

[committee]
name = "Public Works"
type = "primary"
