billNumber = "SBN-00082"
billType = "SBN"
congress = 20
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=20&q=SBN-82"
lastScraped = "2025-09-20T23:07:57.882330"
title = "ANTI-ABUSE OF PAKYAWAN WORKERS ACT"
filedDate = "July 3, 2025"
author = "Tulfo, Raffy T."
longTitle = "AN ACT STRENGTHENING THE RIGHTS OF PIECE-RATE WORKERS, PROVIDING FOR STRICTER REPORTORIAL REQUIREMENTS AND PENALTIES FOR VIOLATIONS THERETO AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Piece-Rate Workers (Pakyawan)", "Workers Protection",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4655642560!.pdf"
pdfFileName = "SBN-82 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/3/2025"
action = "Introduced by Senator RAFFY T. TULFO;"

[[legislativeHistory]]
date = "7/29/2025"
action = "Read on First Reading and Referred to the Committee on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT;"

[status]
status = "Pending in the Committee"
date = "7/29/2025"

[committee]
name = "Labor, Employment and Human Resources Development"
type = "primary"
