billNumber = "HB00113"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB00113"
lastScraped = "2025-09-22T00:23:15.514219"
title = "HB00113"
longTitle = "AN ACT PROVIDING FOR THREE SMALL FARMERS' REPRESENTATIVES IN THE NIA BOARD BY AMENDING REPUBLIC ACT NUMBERED THIRTY-SIX HUNDRED AND ONE, AS AMENDED BY PRESIDENTIAL DECREE NUMBERED FIVE-HUNDRED AND FIFTY-TWO AND FURTHER AMENDED BY EXECUTIVE ORDER NUMBERED TWO HUNDRED AND NINETY-TWO DATED JULY 25, 1987 ENTITLED, 'AN ACT CREATING THE NATIONAL IRRIGATION ADMINISTRATION'"
scope = "National"
dateFiled = "1998-07-01"
status = "Substituted by HB04968"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Montemayor, Leonardo Q."
coAuthors = [ "LORETO-GO, MA. CATALINA L.", "TAÑADA, WIGBERTO E.",]
[[authorsDetail]]
name = "Montemayor, Leonardo Q."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LORETO-GO, MA. CATALINA L."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAÑADA, WIGBERTO E."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 91554
congress = 11
bill_no = "HB00113"
referral = "0527"
ref_name = ""
sub_name = ""
date_read = "1998-07-28"
