billNumber = "HB00023"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB00023"
lastScraped = "2025-09-22T00:23:15.489902"
title = "HB00023"
longTitle = "AN ACT LIBERALIZING BUSINESS IN THE RETAIL TRADE SECTOR OF THE PHILIPPINES, THEREBY REPEALING REPUBLIC ACT NO. 1180, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1998-07-01"
status = "Substituted by HB07602"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Teves, Herminio G."
coAuthors = [ "TEODORO, GILBERTO JR. C.", "SARMIENTO, ROGELIO M.", "GONZALES, RODOLFO F.", "LEDESMA, JULIO IV A.", "LORETO-GO, MA. CATALINA L.", "LIBAN, DANTE V.", "ROMUALDO, JURDIN JESUS M.", "LAPUS, JESLI A.", "LOPEZ, EMILY R.",]
[[authorsDetail]]
name = "Teves, Herminio G."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "TEODORO, GILBERTO JR. C."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SARMIENTO, ROGELIO M."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GONZALES, RODOLFO F."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LEDESMA, JULIO IV A."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LORETO-GO, MA. CATALINA L."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMUALDO, JURDIN JESUS M."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAPUS, JESLI A."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOPEZ, EMILY R."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = "1998-07-28"

[[committee]]
name = "FOREIGN AFFAIRS"
type = "principal"
referralCode = "0513"

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "secondary"
referralCode = "0536"

[firstReading]
id = 91464
congress = 11
bill_no = "HB00023"
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
date_read = "1998-07-28"
