billNumber = "HB00459"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB00459"
lastScraped = "2025-09-22T00:23:15.586883"
title = "HB00459"
longTitle = "AN ACT AMENDING ARTICLES 223 AND 224 OF REPUBLIC ACT NO. 3815, OTHERWISE KNOWN AS THE REVISED PENAL CODE OF THE PHILIPPINES, BY INCREASING AND/OR PUTTING A STIFFER PENALTY IMPOSED FOR INFIDELITY IN THE CUSTODY OF THE PRISONER"
scope = "National"
dateFiled = "1998-07-01"
status = "Substituted by HB09089"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "JARAULA, CONSTANTINO G.", "CRUZ, TEODORO C.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "JARAULA, CONSTANTINO G."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CRUZ, TEODORO C."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "1998-07-29"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 91900
congress = 11
bill_no = "HB00459"
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
date_read = "1998-07-29"
