billNumber = "HB00583"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB00583"
lastScraped = "2025-09-22T00:23:15.610126"
title = "HB00583"
longTitle = "AN ACT DECLARING ALL IRRIGATED AND IRRIGABLE AGRICULTURAL LANDS AS PROTECTED AREAS FOR AGRICULTURE, BANNING ITS CONVERSION FOR USES OTHER THAN AGRICULTURE, AND AMENDING FOR THE PURPOSE SECTION 20 OF REPUBLIC ACT 7160, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE"
scope = "National"
dateFiled = "1998-07-02"
status = "Pending with the Committee on LOCAL GOVERNMENT since 1998-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Zubiri, Juan Miguel F."
coAuthors = [ "PAEZ, CRESENTE C.", "MALIKSI, ERINEO S.", "SILVERIO, RICARDO C.",]
[[authorsDetail]]
name = "Zubiri, Juan Miguel F."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PAEZ, CRESENTE C."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MALIKSI, ERINEO S."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SILVERIO, RICARDO C."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "1998-07-29"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 92024
congress = 11
bill_no = "HB00583"
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
date_read = "1998-07-29"
