billNumber = "HB00995"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB00995"
lastScraped = "2025-09-22T00:23:15.684820"
title = "HB00995"
longTitle = "AN ACT ESTABLISHING AN ENGINEERING DISTRICT IN THE FIRST DISTRICT OF THE PROVINCE OF LANAO DEL SUR, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1998-07-14"
status = "REPUBLIC ACT (RA08999) enacted on 2001-01-17"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1998-07-30"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "principal"
referralCode = "0537"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 92436
congress = 11
bill_no = "HB00995"
report = "00166"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = "APPROPRIATIONS, PUBLIC WORKS AND HIGHWAYS"
recomm = "approval without amendments"
date_read = "1998-07-30"
date_ob = "1999-02-02"
date_report = "1999-02-02"

[secondReading]
id = 16262
congress = 11
bill_no = "HB00995"
remarks = "Considered the Explanatory Note as the Sponsorship Speech"
date_approved = "1999-02-03"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 3537
congress = 11
bill_no = "HB00995"
date_dist = "1999-02-08"
date_adopt = "1999-03-01"
no_yeas = 170
no_nays = 0
no_abstent = 0
date_trans = "1999-03-02"
date_rec = "1999-03-03"
amend_ind = "N"
act_pres = "A"
dte_transp = "2000-12-18"
dte_actedp = "2001-01-17"
