billNumber = "HB01549"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB01549"
lastScraped = "2025-09-22T00:23:15.780776"
title = "HB01549"
longTitle = "AN ACT PROVIDING FOR THE PROTECTION OF WOMEN AGAINST HABITUAL WIFE BEATING, AND PROVIDING PENALTIES FOR VIOLATIONS THEREOF"
scope = "National"
dateFiled = "1998-07-31"
status = "Pending with the Committee on POPULATION AND FAMILY RELATIONS since 1998-08-06"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Reyes, Edmundo Jr. O."
coAuthors = [ "VERCELES, LEANDRO JR. B.", "AUMENTADO, ERICO B.", "GOLEZ, ROILO S.", "CALALAY, REYNALDO A.", "LORETO-GO, MA. CATALINA L.", "TULAGAN, GENEROSO D.",]
[[authorsDetail]]
name = "Reyes, Edmundo Jr. O."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "VERCELES, LEANDRO JR. B."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AUMENTADO, ERICO B."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GOLEZ, ROILO S."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CALALAY, REYNALDO A."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LORETO-GO, MA. CATALINA L."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TULAGAN, GENEROSO D."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "POPULATION AND FAMILY RELATIONS"
type = "primary"
referralCode = "0512"
dateRead = "1998-08-06"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[[committee]]
name = "WOMEN AND GENDER EQUALITY"
type = "secondary"
referralCode = "A504"

[firstReading]
id = 92990
congress = 11
bill_no = "HB01549"
referral = "0512"
ref_name = "POPULATION AND FAMILY RELATIONS"
sub_name = ""
date_read = "1998-08-06"
