billNumber = "HB02592"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB02592"
lastScraped = "2025-09-22T00:23:15.956441"
title = "HB02592"
longTitle = "AN ACT CONDONING TAX LEVIED ON THE UNTAXED INCOME EARNED BEFORE DECEMBER 31, 1997 AND REQUIRING THE FILING OF ITS STATEMENT OF ASSETS, LIABILITIES AND NETWORTH AS OF DECEMBER 31, 1997 (amnesty)"
scope = "National"
dateFiled = "1998-08-20"
status = "Substituted by HB05346"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Vicencio, Romualdo T."
[[authorsDetail]]
name = "Vicencio, Romualdo T."
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "1998-08-26"

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "principal"
referralCode = "0536"

[firstReading]
id = 94033
congress = 11
bill_no = "HB02592"
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
date_read = "1998-08-26"
