billNumber = "HB04900"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB04900"
lastScraped = "2025-09-22T00:23:16.453792"
title = "HB04900"
longTitle = "AN ACT AMENDING CERTAIN SECTIONS OF PRESIDENTIAL DECREE NO. 198, AS AMENDED AND FOR OTHER PURPOSES(RE: PER DIEMS BY THE MEMBERS OF THE BOARD OF DIRECTORS/TRUST EES OF LOCAL WATER DISTRICTS"
scope = "National"
dateFiled = "1998-10-22"
status = "Business for the day on 2000-10-03"
statusOrder = 10.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "ROMUALDO, JURDIN JESUS M."
[[authorsDetail]]
name = "ROMUALDO, JURDIN JESUS M."
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "1998-11-09"

[[committee]]
name = "WELFARE OF CHILDREN"
type = "principal"
referralCode = "F501"

[firstReading]
id = 96335
congress = 11
bill_no = "HB04900"
report = "01221"
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = "REVISION OF LAWS"
recomm = "approval without amendments"
date_read = "1998-11-09"
date_ob = "2000-09-25"
date_report = "2000-09-19"

[secondReading]
id = 16561
congress = 11
bill_no = "HB04900"
date_calendared = "2000-10-03"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"
