billNumber = "HB04188"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB04188"
lastScraped = "2025-09-22T00:23:16.318893"
title = "HB04188"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A SOCIAL HALL IN BANZA NATIONALIZED HIGH SCHOOL, BARANGAY BANZA, BUTUAN CITY, APPROPRIATING FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "1998-10-06"
status = "Pending with the Committee on BASIC EDUCATION since 1998-10-13"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Banaag, Leovigildo B."
[[authorsDetail]]
name = "Banaag, Leovigildo B."
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "BASIC EDUCATION"
type = "primary"
referralCode = "C501"
dateRead = "1998-10-13"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 95628
congress = 11
bill_no = "HB04188"
referral = "C501"
ref_name = "BASIC EDUCATION"
sub_name = ""
date_read = "1998-10-13"
