billNumber = "HB04503"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB04503"
lastScraped = "2025-09-22T00:23:16.382844"
title = "HB04503"
longTitle = "AN ACT PROVIDING FOR THE CONCRETE PAVING OF THE SAN GREGORIO STREET IN BARANGAY SAN SEBASTIAN IN THE TOWN OF SAN VICENTE, PROVINCE OF ILOCOS SUR, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1998-10-13"
status = "Pending First Reading (Filed last 1998-10-13)"
statusOrder = 1.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Baterina, Salacnib F."
[[authorsDetail]]
name = "Baterina, Salacnib F."
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

