billNumber = "HB05664"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB05664"
lastScraped = "2025-09-22T00:23:16.635532"
title = "HB05664"
longTitle = "AN ACT GRANTING THE DXZB/TV 13 COOPERATIVE FOR SERVICE INCORPORATED A FRANCHISE TO ESTABLISH, MAINTAIN AND OPERATE A RADIO BROADCASTING AND TELEVISION STATION IN WESTERN MINDANAO (REGION IX)"
scope = "Local"
dateFiled = "1998-11-24"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 1998-12-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Barinaga, Roseller L."
coAuthors = [ "CAPPLEMAN, BENJAMIN B.",]
[[authorsDetail]]
name = "Barinaga, Roseller L."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "CAPPLEMAN, BENJAMIN B."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "1998-12-01"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 97099
congress = 11
bill_no = "HB05664"
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
date_read = "1998-12-01"
