billNumber = "HB05936"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB05936"
lastScraped = "2025-09-22T00:23:16.694800"
title = "HB05936"
longTitle = "AN ACT PROVIDING FOR SURVIVORSHIP BENEFIT TO THE SPOUSE OF A DECEASED CONSTITUTIONAL OFFICIAL MENTIONED IN SECTION 2, ARTICLE XI OF THE CONSTITUTION AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1998-12-09"
status = "Pending with the Committee on CIVIL SERVICE AND PROFESSIONAL REGULATION since 1998-12-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "ABAYON, HARLIN CAST.", "HOFER, GEORGE T.", "AMIN, HUSSIN U.", "BANAAG, LEOVIGILDO B.", "NAVARRO, CONSTANTINO JR. H.", "VICENCIO, ROMUALDO T.", "DEL MAR, RAOUL B.", "DURANO, JOSEPH ACE H.", "HERRERA, EFREN T.", "JALA, ELADIO M.", "GONZALES, RODOLFO F.", "NEPOMUCENO, FRANCIS BLUEBOY L.", "PANCHO, PEDRO M.", "ANDAYA, ROLANDO JR. G.", "JACOB, JAIME DLS.", "GORDON, JAMES JR. J.", "LOZADA, JOSE APOLINARIO JR. L.", "TAÑADA, WIGBERTO E.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ABAYON, HARLIN CAST."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "HOFER, GEORGE T."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AMIN, HUSSIN U."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BANAAG, LEOVIGILDO B."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "NAVARRO, CONSTANTINO JR. H."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VICENCIO, ROMUALDO T."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEL MAR, RAOUL B."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DURANO, JOSEPH ACE H."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "HERRERA, EFREN T."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JALA, ELADIO M."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GONZALES, RODOLFO F."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "NEPOMUCENO, FRANCIS BLUEBOY L."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PANCHO, PEDRO M."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANDAYA, ROLANDO JR. G."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JACOB, JAIME DLS."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GORDON, JAMES JR. J."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOZADA, JOSE APOLINARIO JR. L."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAÑADA, WIGBERTO E."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "primary"
referralCode = "0506"
dateRead = "1998-12-16"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 97371
congress = 11
bill_no = "HB05936"
referral = "0506"
ref_name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
sub_name = ""
date_read = "1998-12-16"
