billNumber = "HB05641"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB05641"
lastScraped = "2025-09-22T00:23:16.631683"
title = "HB05641"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF ADDITIONAL ONE (1) METER HEIGHT DIKE ALONG BARAS RIVER AT A. BONIFACIO STREET IN BARANGAY SAN MIGUEL, MUNICIPALITY OF BARAS, PROVINCE OF RIZAL AND APPROPRIATING THE AMOUNT OF ONE HUNDRED EIGHTEEN THOUSAND FIVE HUNDRED SIXTY THREE PESOS FOR THE PURPOSE"
scope = "Local"
dateFiled = "1998-11-23"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1998-11-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Rodriguez, Isidro Jr. S."
[[authorsDetail]]
name = "Rodriguez, Isidro Jr. S."
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1998-11-26"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "principal"
referralCode = "0529"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 97076
congress = 11
bill_no = "HB05641"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1998-11-26"
