billNumber = "HB07567"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB07567"
lastScraped = "2025-09-22T00:23:16.984598"
title = "HB07567"
longTitle = "AN ACT PROVIDING FOR THE MANDATORY AUTOPSY OF ANY PERSON WHO DIED IN UNUSUAL, SUSPICIOUS AND/OR VIOLENT MANNER BY THE STATE, THE CONDITIONS FOR THE PROPER ISSUANCE OF THE DEATH CERTIFICATE OF SAID PERSON AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1999-05-18"
status = "Substituted by HB12356"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Avance-Fuentes, Daisy"
coAuthors = [ "VILLAROSA, MA. AMELITA C.", "BADELLES, ALIPIO CIRILO V.", "UNDE, GORGONIO P.",]
[[authorsDetail]]
name = "Avance-Fuentes, Daisy"
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "VILLAROSA, MA. AMELITA C."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BADELLES, ALIPIO CIRILO V."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "UNDE, GORGONIO P."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "1999-05-25"

[[committee]]
name = "REVISION OF LAWS"
type = "principal"
referralCode = "0531"

[firstReading]
id = 99002
congress = 11
bill_no = "HB07567"
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
date_read = "1999-05-25"
