billNumber = "HB07111"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB07111"
lastScraped = "2025-09-22T00:23:16.900893"
title = "HB07111"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF A WATER SYSTEM IN THE MUNICIPALITY OF PROSPERIDAD, PROVINCE OF AGUSAN DEL SUR AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1999-03-19"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1999-03-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1999-03-24"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 98546
congress = 11
bill_no = "HB07111"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1999-03-24"
