billNumber = "HB09518"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB09518"
lastScraped = "2025-09-22T00:23:17.345315"
title = "HB09518"
longTitle = "AN ACT EXCLUDING FROM THE OPERATION OF PROCLAMATION NO. 1826, WHICH ESTABLISHED THE NATIONAL GOVERNMENT CENTER (NGC) SITE AT QUEZON CITY, CERTAIN PORTIONS OF LAND THEREIN AND DECLARING THE SAME OPEN FOR DISPOSITION UNDER THE PROVISIONS OF ACT NO. 3038 IN RELATION TO THE PROVISIONS OF PUBLIC LAND ACT, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "2000-02-21"
status = "Pending with the Committee on HOUSING AND URBAN DEVELOPMENT since 2000-02-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "OSABEL, DIOGENES S.", "ABAYON, HARLIN CAST.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "OSABEL, DIOGENES S."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ABAYON, HARLIN CAST."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "primary"
referralCode = "0518"
dateRead = "2000-02-29"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 100951
congress = 11
bill_no = "HB09518"
referral = "0518"
ref_name = "HOUSING AND URBAN DEVELOPMENT"
sub_name = ""
date_read = "2000-02-29"
