billNumber = "HB11695"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB11695"
lastScraped = "2025-09-22T00:23:17.709360"
title = "HB11695"
longTitle = "AN ACT CREATING SENIOR CITIZENS COUNCILS IN EVERY BARANGAY THROUGHOUT THE COUNTRY, AMENDING FOR THE PURPOSE REPUBLIC ACTS NUMBERED SEVENTY ONE HUNDRED SIXTY AND SEVENTY FOUR HUNDRED THIRTY TWO ENTITLED `LOCAL GOVERNMENT CODE OF 1991' AND `AN ACT TOMAXIMIZE THE CONTRIBUTION OF SENIOR CITIZENS TO NATION-BUILDING GRANT BENEFITS AND SPECIAL PRIVILEGES AND FOR OTHER PURPOSES RESPECTIVELY"
scope = "National"
dateFiled = "2000-06-05"
status = "Pending with the Committee on POPULATION AND FAMILY RELATIONS since 2000-07-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "MONFORT, NARCISO D.", "GONZALEZ, JOSE MARI C.", "UNDE, GORGONIO P.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GONZALEZ, JOSE MARI C."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "UNDE, GORGONIO P."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "POPULATION AND FAMILY RELATIONS"
type = "primary"
referralCode = "0512"
dateRead = "2000-07-17"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "secondary"
referralCode = "0522"

[firstReading]
id = 103110
congress = 11
bill_no = "HB11695"
referral = "0512"
ref_name = "POPULATION AND FAMILY RELATIONS"
sub_name = ""
date_read = "2000-07-17"
