billNumber = "HB11429"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB11429"
lastScraped = "2025-09-22T00:23:17.662746"
title = "HB11429"
longTitle = "AN ACT REENACTING PRESIDENTIAL DECREE NO. 1608 DATED FEBRUARY 9, 1979, ENTITLED 'AMENDING PRESIDENTIAL DECREE NO. 1276, ENTITLED AUTHORIZING THE CENTRAL BANK OF THE PHILIPPINES TO CONTINUE THE IMPLEMENTATION OF ITS REWARD SYSTEM FOR INFORMATION LEADING TO THE CONFISCATION OF GOLD AND FOREIGN EXCHANGE'"
scope = "National"
dateFiled = "2000-05-19"
status = "Pending with the Committee on REVISION OF LAWS since 2000-05-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Fariñas, Rodolfo C."
[[authorsDetail]]
name = "Fariñas, Rodolfo C."
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2000-05-29"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 102844
congress = 11
bill_no = "HB11429"
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
date_read = "2000-05-29"
