billNumber = "HB11960"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB11960"
lastScraped = "2025-09-22T00:23:17.763038"
title = "HB11960"
longTitle = "AN ACT CREATING TWO (2) SCHOOL DIVISIONS IN THE PROVINCE OF AGUSAN DEL SUR AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2000-08-07"
status = "Pending with the Committee on BASIC EDUCATION since 2000-08-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "UNDE, GORGONIO P.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "UNDE, GORGONIO P."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "BASIC EDUCATION"
type = "primary"
referralCode = "C501"
dateRead = "2000-08-14"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 103375
congress = 11
bill_no = "HB11960"
referral = "C501"
ref_name = "BASIC EDUCATION"
sub_name = ""
date_read = "2000-08-14"
