billNumber = "HB12953"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB12953"
lastScraped = "2025-09-22T00:23:17.933895"
title = "HB12953"
longTitle = "AN ACT REQUIRING ALL COLLEGES AND UNIVERSITIES TO PROVIDE SCHOLARSHIP GRANTS TO AT LEAST FIVE PERCENT (5%) OF THEIR STUDENT POPULATION WHO ARE POOR BUT DESERVING STUDENTS, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2001-06-04"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2001-06-06"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2001-06-06"

[firstReading]
id = 104368
congress = 11
bill_no = "HB12953"
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
date_read = "2001-06-06"
