billNumber = "HB12661"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB12661"
lastScraped = "2025-09-22T00:23:17.882984"
title = "HB12661"
longTitle = "AN ACT CONVERTING THE PARTIDO STATE COLLEGE (PSC), SAN JOSE POLYTECHNIC INSTITUTE (SJPI), GOVERNOR MARIANO FUENTEBELLA MEMORIAL COLLEGE OF FISHERIES (GMFMCF), TINAMBAC POLYTECHNIC INSTITUTE (TPI), CARAMOAN TECHNICAL-VOCAT IONAL SCHOOL (CTVS), LAGONOY SCHOOL OF FISHERIES (LSF) AND SAN JOSE FISHERIES SCHOOL(SJFS) INTO A UNIVERSITY TO BE KNOWN AS THE PARTIDO STATE UNIVERSITY (PSU) AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2000-12-11"
status = "REPUBLIC ACT (RA09029) enacted on 2001-03-05"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "DUAVIT, GILBERTO M.", "FUENTEBELLA, ARNULFO P.", "VILLAR, MANUEL JR. B.", "BUNYE, IGNACIO R.", "ANGARA-CASTILLO, BELLAFLOR", "LAUREL, JOSE MACARIO IV L.", "DATUMANONG, SIMEON A.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DUAVIT, GILBERTO M."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FUENTEBELLA, ARNULFO P."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLAR, MANUEL JR. B."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BUNYE, IGNACIO R."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANGARA-CASTILLO, BELLAFLOR"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAUREL, JOSE MACARIO IV L."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DATUMANONG, SIMEON A."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2000-12-11"

[[motherBills]]
bill_no = "HB12009"
flag = "S"

[[substitutedBills]]
bill_no = "HB12009"
flag = "S"

[firstReading]
id = 104076
congress = 11
bill_no = "HB12661"
report = "01314"
referral = "0532"
ref_name = "RULES"
sub_name = "APPROPRIATIONS, HIGHER AND TECHNICAL EDUCATION"
recomm = "approval"
date_read = "2000-12-11"
date_report = "2000-12-11"

[secondReading]
id = 17348
congress = 11
bill_no = "HB12661"
remarks = "Considered the Explanatory Note as the sponsorship remarks."
date_approved = "2000-12-11"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 4562
congress = 11
bill_no = "HB12661"
date_dist = "2000-12-11"
date_adopt = "2000-12-14"
no_yeas = 151
no_nays = 0
no_abstent = 0
date_trans = "2000-12-14"
date_rec = "2000-12-14"
date_agram = "2001-01-30"
amend_ind = "Y"
act_pres = "A"
dte_transp = "2001-01-31"
dte_actedp = "2001-03-05"
