billNumber = "HB12930"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB12930"
lastScraped = "2025-09-22T00:23:17.930201"
title = "HB12930"
longTitle = "AN ACT PROVIDING FOR THE CONDUCT OF SPECIAL REGISTRATION OF VOTERS BEFORE THE MAY 14, 2001 NATIONAL AND LOCAL ELECTIONS, AMENDING FOR THIS PURPOSE, SECTION 8, 34, 35, 36, 37, 38 AND 39 OF REPUBLIC ACT NO. 8189, APPROPRIATING FUNDS THEREFOR, AND FOROTHER PURPOSES"
scope = "National"
dateFiled = "2001-03-16"
status = "Pending with the Committee on SUFFRAGE AND ELECTORAL REFORMS since 2001-03-20"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Belmonte, Feliciano Jr. R."
coAuthors = [ "REYES, EDMUNDO JR. O.",]
[[authorsDetail]]
name = "Belmonte, Feliciano Jr. R."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "REYES, EDMUNDO JR. O."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "primary"
referralCode = "0537"
dateRead = "2001-03-20"

[firstReading]
id = 104345
congress = 11
bill_no = "HB12930"
referral = "0537"
ref_name = "SUFFRAGE AND ELECTORAL REFORMS"
sub_name = ""
date_read = "2001-03-20"
