billNumber = "HB12468"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HB12468"
lastScraped = "2025-09-22T00:23:17.850418"
title = "HB12468"
longTitle = "AN ACT SEPARATING THE MOUNTAIN PROVINCE GENERAL COMPREHENSIVE HIGH SCHOOL ANNEX IN BARANGAY TOCUCAN, MUNICIPALITY OF BONTOC, MOUNTAIN PROVINCE FROM THE MOUNTAIN PROVINCE COMPREHENSIVE HIGH SCHOOL LOCATED IN AT BONTOC, MOUNTAIN PROVINCE AND CONVERTING THE SAME INTO AN INDEPENDENT NATIONAL HIGH SCHOOL TO BE KNOWN AS THE TOCUCAN NATIONAL HIGH SCHOOL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2000-10-10"
status = "Pending with the Committee on BASIC EDUCATION since 2000-10-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "BASIC EDUCATION"
type = "primary"
referralCode = "C501"
dateRead = "2000-10-16"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 103883
congress = 11
bill_no = "HB12468"
referral = "C501"
ref_name = "BASIC EDUCATION"
sub_name = ""
date_read = "2000-10-16"
