billNumber = "HR00217"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HR00217"
lastScraped = "2025-09-22T00:23:17.989038"
title = "HR00217"
longTitle = "RESOLUTION REQUESTING HIS EXCELLENCY, PRESIDENT JOSEPH EJERCITO ESTRADA TO DIRECT THE DEPARTMENT OF BUDGET AND MANAGEMENT TO LOOK INTO, AND RESOLVE IN THE MOST EXPEDITIOUS MANNER, THE FULL IMPLEMENTATION OF THE STAFFING PATTERN OF THE REGIONAL OFFICES OF THE NATIONAL GOVERNMENT AGENCIES IN THE CARAGA ADMINISTRATIVE REGION"
scope = "Local"
dateFiled = "1998-08-24"
status = "Substituted by HR01155"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "APPROPRIATIONS"
type = "primary"
referralCode = "0504"
dateRead = "1998-08-27"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 104675
congress = 11
bill_no = "HR00217"
referral = "0504"
ref_name = "APPROPRIATIONS"
sub_name = ""
date_read = "1998-08-27"
