billNumber = "HR00348"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HR00348"
lastScraped = "2025-09-22T00:23:18.011189"
title = "HR00348"
longTitle = "RESOLUTION URGING THE COMMITTEE ON VETERANS AFFAIRS OF THE HOUSE OF REPRESENTATIVES TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, INTO RECENT REPORTS THAT OVER FIVE HUNDRED MILLION PESOS (P500,000,000.0 0) WORTH OF CLAIMS HAS BEEN LOST TO A SYNDICATE AT THE PHILIPPINE VETERANS AFFAIRS OFFICE"
scope = "National"
dateFiled = "1998-09-24"
status = "Pending with the Committee on  since 1998-09-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Suplico, Rolex T."
coAuthors = [ "LIBAN, DANTE V.",]
[[authorsDetail]]
name = "Suplico, Rolex T."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 104806
congress = 11
bill_no = "HR00348"
referral = "A506"
ref_name = ""
sub_name = ""
date_read = "1998-09-29"
