billNumber = "HR00231"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HR00231"
lastScraped = "2025-09-22T00:23:17.991613"
title = "HR00231"
longTitle = "RESOLUTION URGING THE DEPARTMENT OF LABOR AND EMPLOYMENT (DOLE), OTHER GOVERNMENT ENTITIES AND THE PRIVATE EMPLOYMENT AGENCIES TO ABOLISH AND STOP IMMEDIATELY THE COLLECTION OF FEES AND CHARGING OF EXCESSIVE SUMS OF MONEY FROM OVERSEAS FILIPINO WORKERS BOUND FOR TAIWAN AND ALL OTHER COUNTRIES"
scope = "National"
dateFiled = "1998-08-27"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 1998-09-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Fortuno, Salvio B."
coAuthors = [ "MONTEMAYOR, LEONARDO Q.",]
[[authorsDetail]]
name = "Fortuno, Salvio B."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "0521"
dateRead = "1998-09-02"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 104689
congress = 11
bill_no = "HR00231"
referral = "0521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
date_read = "1998-09-02"
