billNumber = "HR00033"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HR00033"
lastScraped = "2025-09-22T00:23:17.955980"
title = "HR00033"
longTitle = "RESOLUTION DIRECTING THE APPROPRIATE COMMITTEE TO CONDUCT AN INQUIRY WITH A VIEW TO RECOMMENDING THE ADOPTION OF SUCH MEASURES AS MAY BE NECESSARY TO IMPROVE THE PERCEIVED LACK OF CREDIBILITY AND POOR PUBLIC IMAGE OF THE HOUSE OF REPRESENTATIVES"
scope = "National"
dateFiled = "1998-07-02"
status = "Pending with the Committee on RULES since 1998-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Nantes, Rafael P."
coAuthors = [ "LORENZO-VILLAREAL, JULITA",]
[[authorsDetail]]
name = "Nantes, Rafael P."
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LORENZO-VILLAREAL, JULITA"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1998-07-29"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[committee]]
name = "PUBLIC INFORMATION"
type = "secondary"
referralCode = "0528"

[firstReading]
id = 104491
congress = 11
bill_no = "HR00033"
referral = "0532"
ref_name = "RULES"
sub_name = ""
date_read = "1998-07-29"
