billNumber = "HR01584"
billType = "HB"
congress = 11
apiCongressId = 11
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=11&q=HR01584"
lastScraped = "2025-09-22T00:23:18.248660"
title = "HR01584"
longTitle = "RESOLUTION DIRECTING THE COMMITTEES ON TRANSPORTATION AND COMMUNICATIONS AND PUBLIC ORDER AND SECURITY TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, INTO THE LAPSES OF THE APPLICATION OF AIRPORT SECURITY MEASURES IN THE DAVAO AIRPORT TO THE DETRIMENT OF OUR RIDING PUBLIC AND TO RECOMMEND REMEDIAL LEGISLATIVE MEASURES THEREFOR"
scope = "Local"
dateFiled = "2000-05-30"
status = "Pending with the Committee on TRANSPORTATION AND COMMUNICATIONS since 2000-06-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[committee]]
name = "TRANSPORTATION AND COMMUNICATIONS"
type = "primary"
referralCode = "0540"
dateRead = "2000-06-05"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "secondary"
referralCode = "0529"

[firstReading]
id = 106039
congress = 11
bill_no = "HR01584"
referral = "0540"
ref_name = "TRANSPORTATION AND COMMUNICATIONS"
sub_name = ""
date_read = "2000-06-05"
