billNumber = "SBN-00108"
billType = "SBN"
congress = 20
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=20&q=SBN-108"
lastScraped = "2025-09-20T14:56:15.671712"
title = "AFP AND PNP CAMP DEVELOPMENT FUND ACT"
filedDate = "July 3, 2025"
author = "Cayetano, Alan Peter \"Compañero\" S."
longTitle = "AN ACT ESTABLISHING CAMP DEVELOPMENT FUNDS FOR THE ARMED FORCES OF THE PHILIPPINES AND THE PHILIPPINE NATIONAL POLICE, APPROPRIATING THE SUM TOTAL OF TWENTY-FIVE BILLION PESOS EACH FOR FIVE YEARS, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Camp Development Fund", "Armed Forces of the Philippines (AFP)", "Philippine National Police (PNP)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4658542589!.pdf"
pdfFileName = "SBN-108 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/3/2025"
action = "Introduced by Senator ALAN PETER 'COMPAÑERO' S. CAYETANO;"

[[legislativeHistory]]
date = "7/30/2025"
action = "Read on First Reading and Referred to the Committees on NATIONAL DEFENSE AND SECURITY, PEACE, UNIFICATION AND RECONCILIATION; PUBLIC ORDER AND DANGEROUS DRUGS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "7/30/2025"

[committee]
name = "National Defense and Security, Peace, Unification and Reconciliation"
type = "primary"
