billNumber = "SBN-00369"
billType = "SBN"
congress = 20
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=20&q=SBN-369"
lastScraped = "2025-09-20T23:11:14.588209"
title = "PHILIPPINE CIVIL REGISTRATION AND VITAL STATISTICS ACT"
filedDate = "July 10, 2025"
author = "Gatchalian, Win T."
longTitle = "AN ACT PROVIDING FOR A COMPREHENSIVE AND RESPONSIVE CIVIL REGISTRATION AND VITAL STATISTICS SYSTEM, REPEALING FOR THIS PURPOSE ACT NO. 3753 OR THE PHILIPPINE LAW ON REGISTRY OF CIVIL STATUS, PROVIDING FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Civil Registration System",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4686042867!.pdf"
pdfFileName = "SBN-369 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/10/2025"
action = "Introduced by Senator WIN GATCHALIAN;"

[[legislativeHistory]]
date = "8/12/2025"
action = "Read on First Reading and Referred to the Committees on JUSTICE AND HUMAN RIGHTS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/12/2025"

[committee]
name = "Justice and Human Rights"
type = "primary"
