billNumber = "SBN-01470"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1470"
lastScraped = "2025-09-20T23:24:51.702705"
title = "WORLD CUP FILIPINO ATHLETES INCLUSION IN RA 9064 COVERAGE"
filedDate = "July 26, 2004"
author = "Lapid, Manuel \"Lito\" M."
longTitle = "AN ACT EXPANDING THE COVERAGE OF INCENTIVES EXTENDED TO NATIONAL ATHLETES AMENDING FOR THE PURPOSE CERTAIN PROVISIONS OF REPUBLIC ACT NO. 9064 OTHERWISE KNOWN AS 'NATIONAL ATHLETES, COACHES AND TRAINERS BENEFITS AND INCENTIVES ACT OF 2001', AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Sports (World Cuppers Filipino Athletes)", "R.A.No. 9064 Coverage Expansion",]
pdfUrl = "https://web.senate.gov.ph/lisdata/26852050!.pdf"
pdfFileName = "SBN-1470 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/26/2004"
action = "Introduced by Senator MANUEL 'LITO' M. LAPID;"

[[legislativeHistory]]
date = "9/15/2004"
action = "Read on First Reading and referred to the Committee(s) on GAMES, AMUSEMENT AND SPORTS; and CONSTITUTIONAL AMENDMENTS, REVISION OF CODES AND LAWS;"

[status]
status = "Pending in the Committee"
date = "9/15/2004"

[committee]
name = "Games, Amusement and Sports"
type = "primary"
