billNumber = "SBN-00872"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-872"
lastScraped = "2025-09-20T23:18:15.377483"
title = "MUNICIPAL SEA WATER AS PART OF IRA COMPUTATION"
filedDate = "June 30, 2004"
author = "Ejercito-Estrada, Jinggoy P."
longTitle = "AN ACT MAKING MUNICIPAL SEA WATER WITHIN THE FIFTEEN-KILOMETER RADIUS JURISDICTION PART OF THE INTERNAL REVENUE ALLOTMENT COMPUTATION FOR MUNICIPALITIES"
scope = "National"
subject = [ "Municipal Sea Water (Ira Computation)", "Internal Revenue Allotment (IRA)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/20701560!.pdf"
pdfFileName = "SBN-872 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/30/2004"
action = "Introduced by Senator JINGGOY EJERCITO ESTRADA;"

[[legislativeHistory]]
date = "8/30/2004"
action = "Read on First Reading and referred to the Committee(s) on LOCAL GOVERNMENT; and ENVIRONMENT AND NATURAL RESOURCES;"

[status]
status = "Pending in the Committee"
date = "8/30/2004"

[committee]
name = "Local Government"
type = "primary"
