billNumber = "SBN-01731"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1731"
lastScraped = "2025-09-20T23:27:14.100710"
title = "ELECTRONIC FUND TRANSFER ACT"
filedDate = "August 17, 2004"
author = "Defensor Santiago, Miriam"
longTitle = "AN ACT DEFINING THE RIGHTS AND LIABILITIES OF PARTIES IN ELECTRONIC FUND TRANSFERS"
scope = "National"
subject = [ "Electronic Fund Transfer Act",]
pdfUrl = "https://web.senate.gov.ph/lisdata/29342515!.pdf"
pdfFileName = "SBN-1731 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/17/2004"
action = "Introduced by Senator MIRIAM DEFENSOR SANTIAGO;"

[[legislativeHistory]]
date = "9/21/2004"
action = "Read on First Reading and referred to the Committee(s) on BANKS, FINANCIAL INSTITUTIONS AND CURRENCIES;"

[status]
status = "Pending in the Committee"
date = "9/21/2004"

[committee]
name = "Banks, Financial Institutions and Currencies"
type = "primary"
