billNumber = "SBN-00424"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-424"
lastScraped = "2025-09-20T23:12:48.228645"
title = "NATIONAL TELECOMMUNICATIONS COMMISSION REORGANIZATION ACT"
filedDate = "June 30, 2004"
author = "Osmena III, Sergio R."
longTitle = "AN ACT REORGANIZING THE NATIONAL TELECOMMUNICATIONS COMMISSION, DEFINING ITS POWERS AND FUNCTIONS AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "National Telecommunications Commission", "Reorganization (NTC)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1580882!.pdf"
pdfFileName = "SBN-424 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/30/2004"
action = "Introduced by Senator SERGE OSMENA;"

[[legislativeHistory]]
date = "8/9/2004"
action = "Read on First Reading and referred to the Committee(s) on PUBLIC SERVICES; and CIVIL SERVICE AND GOVERNMENT REORGANIZATION;"

[status]
status = "Pending in the Committee"
date = "8/9/2004"

[committee]
name = "Public Services"
type = "primary"
