billNumber = "SBN-01211"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1211"
lastScraped = "2025-09-20T23:22:04.148362"
title = "JUVENILE JUSTICE ACT OF 2004"
filedDate = "July 1, 2004"
author = "Revilla Jr., Ramon A."
longTitle = "AN ACT ENHANCING THE ADMINISTRATION OF JUVENILE JUSTICE, APPROPRIATING FUNDS THEREFOR AND FOR OTHER RELATED PURPOSES"
scope = "National"
subject = [ "Juvenile Justice Act",]
pdfUrl = "https://web.senate.gov.ph/lisdata/24241790!.pdf"
pdfFileName = "SBN-1211 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/1/2004"
action = "Introduced by Senator RAMON BONG REVILLA JR.;"

[[legislativeHistory]]
date = "9/8/2004"
action = "Read on First Reading and referred to the Committee(s) on JUSTICE AND HUMAN RIGHTS; YOUTH, WOMEN AND FAMILY RELATIONS; and FINANCE;"

[[legislativeHistory]]
date = "9/12/2005"
action = "Returned and submitted jointly by the Committee(s) on JUSTICE AND HUMAN RIGHTS, YOUTH, WOMEN AND FAMILY RELATIONS and FINANCE per Committee Report No. 31, recommending that it be considered in SBN-1402;"

[[legislativeHistory]]
date = "9/19/2005"
action = "Submitted said Committee Report to the Senate;"

[[legislativeHistory]]
date = "9/19/2005"
action = "CONSIDERED IN SBN-1402, WHICH BECAME R.A.NO. 9344."

[[legislativeHistory]]
date = "8/23/2005"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "9/19/2005"

[committee]
name = "Justice and Human Rights"
type = "primary"
