billNumber = "SBN-01233"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1233"
lastScraped = "2025-09-20T23:22:30.229881"
title = "SCIENCE START GRANT PROGRAM ACT"
filedDate = "July 1, 2004"
author = "Defensor Santiago, Miriam"
longTitle = "AN ACT TO ESTABLISH A SCIENCE START GRANT PROGRAM"
scope = "National"
subject = [ "Science Start Grant Program", "Early Childhood Education", "Pre-School Education (Science/Math)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/24461812!.pdf"
pdfFileName = "SBN-1233 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/1/2004"
action = "Introduced by Senator MIRIAM DEFENSOR SANTIAGO;"

[[legislativeHistory]]
date = "9/8/2004"
action = "Read on First Reading and referred to the Committee(s) on EDUCATION, ARTS AND CULTURE; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "9/8/2004"

[committee]
name = "Education, Arts and Culture"
type = "primary"
