billNumber = "SBN-01398"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1398"
lastScraped = "2025-09-20T23:24:01.412849"
title = "GOVERNMENT EMPLOYEES' ENTREPRENEURSHIP DEVELOPMENT ACT"
filedDate = "July 6, 2004"
author = "Recto, Ralph G."
longTitle = "AN ACT TO DEVELOP ENTREPRENEURSHIP AMONG GOVERNMENT EMPLOYEES FOR AN INNOVATION-INSPIRED CORPS OF CIVIL SERVANTS AND A PRODUCTIVE POST-SERVICE CITIZENRY"
scope = "National"
subject = [ "Government Employees` Entrepreneurship",]
pdfUrl = "https://web.senate.gov.ph/lisdata/26101977!.pdf"
pdfFileName = "SBN-1398 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/6/2004"
action = "Introduced by Senator RECTO;"

[[legislativeHistory]]
date = "9/14/2004"
action = "Read on First Reading and referred to the Committee(s) on CIVIL SERVICE AND GOVERNMENT REORGANIZATION;"

[status]
status = "Pending in the Committee"
date = "9/14/2004"

[committee]
name = "Civil Service and Government Reorganization"
type = "primary"
