billNumber = "SBN-01672"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1672"
lastScraped = "2025-09-20T23:26:46.024864"
title = "SPECIAL LEAVE FOR OVERSEAS WORKERS' SPOUSES ACT"
filedDate = "August 9, 2004"
author = "Pimentel Jr., Aquilino Q."
longTitle = "AN ACT GRANTING A SPECIAL LEAVE OF ABSENCE OF FIFTEEN (15) DAYS A YEAR WITH FULL PAY TO ALL LEGITIMATE SPOUSES OF OVERSEAS WORKERS IN THE PRIVATE AND PUBLIC SECTORS AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Special Leave for OFWs Spouses Act", "Overseas Filipino Workers` Spouses", "Leave of Absence (OFWs Spouses)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/28982379!.pdf"
pdfFileName = "SBN-1672 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/4/2004"
action = "Introduced by Senator PIMENTEL JR.;"

[[legislativeHistory]]
date = "9/20/2004"
action = "Read on First Reading and referred to the Committee(s) on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT; and CIVIL SERVICE AND GOVERNMENT REORGANIZATION;"

[status]
status = "Pending in the Committee"
date = "9/20/2004"

[committee]
name = "Labor, Employment and Human Resources Development"
type = "primary"
