billNumber = "SBN-02648"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-2648"
lastScraped = "2025-09-20T23:37:45.135366"
title = "MONOPOLIES AND COMBINATIONS IN RESTRAINT OF TRADE"
filedDate = "June 4, 2007"
author = "Defensor Santiago, Miriam"
longTitle = "AN ACT AMENDING REPUBLIC ACT NO. 3815, ALSO KNOWN AS THE REVISED PENAL CODE, AS AMENDED, ARTICLE 186 ON MONOPOLIES AND COMBINATIONS IN RESTRAINT OF TRADE"
scope = "National"
subject = [ "Trade Competition", "Monopolies",]
pdfUrl = "https://web.senate.gov.ph/lisdata/71685795!.pdf"
pdfFileName = "SBN-2648 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/4/2007"
action = "Introduced by Senator MIRIAM DEFENSOR SANTIAGO;"

[[legislativeHistory]]
date = "6/5/2007"
action = "Read on First Reading and Referred to the Committee on TRADE AND COMMERCE;"

[status]
status = "Pending in the Committee"
date = "6/5/2007"

[committee]
name = "Trade and Commerce"
type = "primary"
