billNumber = "SBN-01999"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1999"
lastScraped = "2025-09-20T23:30:39.762459"
title = "NO-BIDDING SALE (HOUSING)"
filedDate = "May 11, 2005"
author = "Biazon, Rodolfo G."
longTitle = "AN ACT PROVIDING FOR THE NO-BIDDING SALE OF GOVERNMENT OWNED PROPERTIES TO ITS OCCUPANTS FOR SOCIALIZED HOUSING, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 7279 OTHERWISE KNOWN AS THE URBAN DEVELOPMENT AND HOUSING ACT OF 1972, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Socialized Housing Projects",]
pdfUrl = "https://web.senate.gov.ph/lisdata/34252704!.pdf"
pdfFileName = "SBN-1999 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "5/11/2005"
action = "Introduced by Senator RODOLFO G. BIAZON;"

[[legislativeHistory]]
date = "5/16/2005"
action = "Read on First Reading and Referred to the Committee on URBAN PLANNING, HOUSING AND RESETTLEMENT;"

[[legislativeHistory]]
date = "9/7/2005"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "11/21/2006"
action = "Returned and submitted by the Committee on URBAN PLANNING, HOUSING AND RESETTLEMENT per Committee Report No. 161, recommending that it be substituted by SBN-2518;"

[[legislativeHistory]]
date = "11/22/2006"
action = "Submitted said Committee Report to the Senate;"

[[legislativeHistory]]
date = "11/22/2006"
action = "SUBSTITUTED BY SBN-2518, WHICH BECAME R.A.NO. 9397."

[[legislativeHistory]]
date = "10/16/2006"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "8/8/2006"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "11/22/2006"

[committee]
name = "Urban Planning, Housing and Resettlement"
type = "primary"
