billNumber = "SBN-00570"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-570"
lastScraped = "2025-09-20T23:14:21.547348"
title = "SPECIAL PROGRAM FOR EMPLOYMENT OF STUDENTS (SPES)"
filedDate = "June 30, 2004"
author = "Villar Jr., Manuel B."
longTitle = "AN ACT STRENGTHENING FURTHER AND BROADENING THE COVERAGE OF THE SPECIAL PROGRAM FOR EMPLOYMENT OF STUDENTS, AMENDING FOR THE PURPOSE CERTAIN PROVISIONS OF REPUBLIC ACT NO. 7323, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "R.A.No. 7323, Spes)", "Student Employment Special Program",]
pdfUrl = "https://web.senate.gov.ph/lisdata/17251085!.pdf"
pdfFileName = "SBN-570 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/30/2004"
action = "Introduced by Senator VILLAR, JR.;"

[[legislativeHistory]]
date = "8/11/2004"
action = "Read on First Reading and referred to the Committee(s) on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/11/2004"

[committee]
name = "Labor, Employment and Human Resources Development"
type = "primary"
