billNumber = "SBN-02057"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-2057"
lastScraped = "2025-09-20T23:31:22.396676"
title = "UPGRADE OF STANDARD SALARY OF GOVERNMENT PERSONNEL ACT OF 2005"
filedDate = "June 15, 2005"
author = "Roxas, Mar"
longTitle = "AN ACT PROVIDING FOR UPGRADE OF THE STANDARD SALARY OF ALL GOVERNMENT PERSONNEL, PROVIDING BENEFITS FOR EARLY RETIREMENT AND VOLUNTARY SEPARATION FROM GOVERNMENT SERVICE, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 6758 ENTITLED AN ACT PRESCRIBING A REVISED COMPENSATION AND POSITION CLASSIFICATION SYSTEM IN THE GOVERNMENT, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Standard Salary of Government Personnel (Upgrading)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1032543!.pdf"
pdfFileName = "SBN-2057 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/15/2005"
action = "Introduced by Senator MAR ROXAS;"

[[legislativeHistory]]
date = "7/26/2005"
action = "Read on First Reading and Referred to the Committee(s) on CIVIL SERVICE AND GOVERNMENT REORGANIZATION and FINANCE;"

[[legislativeHistory]]
date = "2/7/2006"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Pending in the Committee"
date = "7/26/2005"

[committee]
name = "Civil Service and Government Reorganization"
type = "primary"
