billNumber = "SBN-01134"
billType = "SBN"
congress = 13
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=13&q=SBN-1134"
lastScraped = "2025-09-20T23:21:00.997374"
title = "FIREARMS REGULATION ACT OF 2004"
filedDate = "June 30, 2004"
author = "Pimentel Jr., Aquilino Q."
longTitle = "AN ACT TO REGULATE THE CARRYING OF FIREARMS, PROVIDE PENALTIES FOR ITS VIOLATION AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Firearms Regulation Act",]
pdfUrl = "https://web.senate.gov.ph/lisdata/23401628!.pdf"
pdfFileName = "SBN-1134 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/30/2004"
action = "Introduced by Senator PIMENTEL JR.;"

[[legislativeHistory]]
date = "9/7/2004"
action = "Read on First Reading and referred to the Committee(s) on PUBLIC ORDER AND ILLEGAL DRUGS;"

[status]
status = "Pending in the Committee"
date = "9/7/2004"

[committee]
name = "Public Order and Illegal Drugs"
type = "primary"
