billNumber = "SBN-01364"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-1364"
lastScraped = "2025-09-20T21:10:53.202355"
title = "PASSIVE INCOME AND FINANCIAL INTERMEDIARY TAXATION ACT"
filedDate = "October 5, 2022"
author = "Estrada, Jinggoy E."
longTitle = "AN ACT AMENDING SECTIONS 22, 24, 25, 27, 28, 29, 30, 32, 34, 37, 38, 39, 42, 51, 52, 54, 56, 57, 73, 108, 121, 122, 123, 174, 176, 179, 181, 182, 183, 184, 185,186,187,188,189, 190,191,194,195, 196,197,198, AND 199; AND REPEALING SECTIONS 127, 175, 177,178, 180,192, AND 193; ALL UNDER REPUBLIC ACT NO. 8424, OTHERWISE KNOWN AS THE NATIONAL INTERNAL REVENUE CODE OF 1997, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Passive Income/Financial Intermediary Taxation", "National Internal Revenue Code (NIRC)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3960335942!.pdf"
pdfFileName = "SBN-1364 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "10/5/2022"
action = "Introduced by Senator JINGGOY E. ESTRADA;"

[[legislativeHistory]]
date = "11/7/2022"
action = "Read on First Reading and Referred to the Committee on WAYS AND MEANS;"

[[legislativeHistory]]
date = "1/22/2024"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "1/29/2024"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "2/12/2024"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "2/20/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "2/26/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "3/4/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "3/7/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "3/11/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "3/14/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "3/21/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "4/1/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "4/4/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "2/17/2025"
action = "Conducted CONSULTATION/OCULAR;"

[[legislativeHistory]]
date = "2/24/2025"
action = "Conducted CONSULTATION/OCULAR;"

[status]
status = "Pending in the Committee"
date = "11/7/2022"

[committee]
name = "Ways and Means"
type = "primary"
