billNumber = "SBN-02000"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-2000"
lastScraped = "2025-09-20T21:13:43.768032"
title = "STRENGTHENING THE LOCAL HEALTH BOARDS (AMENDING SEC.102 OF R.A. NO. 7160), AS AMENDED"
filedDate = "March 14, 2023"
author = "Tulfo, Raffy T."
longTitle = "AN ACT STRENGTHENING THE LOCAL HEALTH BOARDS OF EVERY PROVINCE, CITY, OR MUNICIPALITY BY INCLUDING IN THE MEMBERSHIP THEREOF REPRESENTATIVE FROM THE BARANGAY HEALTH WORKERS FEDERATION, AMENDING FOR THE PURPOSE SECTION 102 OF REPUBUC ACT NO. 7160, AS AMENDED, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991"
scope = "National"
pdfUrl = "https://web.senate.gov.ph/lisdata/4116737479!.pdf"
pdfFileName = "SBN-2000 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "3/14/2023"
action = "Introduced by Senator RAFFY T. TULFO;"

[[legislativeHistory]]
date = "3/14/2023"
action = "Read on First Reading and Referred to the Committees on LOCAL GOVERNMENT; HEALTH AND DEMOGRAPHY and FINANCE;"

[status]
status = "Pending in the Committee"
date = "3/14/2023"

[committee]
name = "Local Government"
type = "primary"
