billNumber = "SBN-01796"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-1796"
lastScraped = "2025-09-20T21:12:47.244101"
title = "STATE UNIVERSITIES AND COLLEGES (SUCS) MENTAL HEALTH SERVICE ACT"
filedDate = "January 30, 2023"
author = "Lapid, Manuel \"Lito\" M."
longTitle = "AN ACT STRENGTHENING THE MENTAL HEALTH SERVICES OF STATE UNIVERSITIES AND COLLEGES AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
subject = [ "Mental Health Services", "State Universities and Colleges (SUCS)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4055536964!.pdf"
pdfFileName = "SBN-1796 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/30/2023"
action = "Introduced by Senator MANUEL 'LITO' M. LAPID;"

[[legislativeHistory]]
date = "2/1/2023"
action = "Read on First Reading and Referred to the Committees on HIGHER, TECHNICAL AND VOCATIONAL EDUCATION; HEALTH AND DEMOGRAPHY and FINANCE;"

[[legislativeHistory]]
date = "2/21/2023"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "3/28/2023"
action = "Conducted TECHNICAL WORKING GROUP;"

[[legislativeHistory]]
date = "3/11/2024"
action = "Returned and submitted jointly by the Committees on HIGHER, TECHNICAL AND VOCATIONAL EDUCATION, HEALTH AND DEMOGRAPHY and FINANCE per Committee Report No. 233, recommending that it be substituted by SBN-2598;"

[[legislativeHistory]]
date = "3/13/2024"
action = "Committee Report Calendared for Ordinary Business;"

[[legislativeHistory]]
date = "3/13/2024"
action = "SUBSTITUTED BY SBN-2598 UNDER COMMITTEE REPORT NO. 233."

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "3/13/2024"

[committee]
name = "Higher, Technical and Vocational Education"
type = "primary"
