billNumber = "SBN-00251"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-251"
lastScraped = "2025-09-20T21:05:45.672555"
title = "PRIORITY INFRASTRUCTURE FOR STATE UNIVERSITIES AND COLLEGES ACT"
filedDate = "July 11, 2022"
author = "Cayetano, Pia S., Cayetano, Alan Peter S."
longTitle = "AN ACT ESTABLISHING A PRIORITY INFRASTRUCTURE PLAN FOR STATE UNIVERSITIES AND COLLEGES, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
subject = [ "State Universities and Colleges (SUCS)", "Infrastructures",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3797734420!.pdf"
pdfFileName = "SBN-251 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/11/2022"
action = "Introduced by Senators PIA S. CAYETANO and ALLAN PETER S. CAYETANO;"

[[legislativeHistory]]
date = "8/3/2022"
action = "Read on First Reading and Referred to the Committees on HIGHER, TECHNICAL AND VOCATIONAL EDUCATION; PUBLIC WORKS and FINANCE;"

[[legislativeHistory]]
date = "9/7/2022"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "11/7/2022"
action = "Returned and submitted jointly by the Committees on HIGHER, TECHNICAL AND VOCATIONAL EDUCATION, PUBLIC WORKS and FINANCE per Committee Report No. 9, recommending that it be substituted by SBN-1470;"

[[legislativeHistory]]
date = "11/8/2022"
action = "Committee Report Calendared for Ordinary Business;"

[[legislativeHistory]]
date = "11/8/2022"
action = "SUBSTITUTED BY SBN-1470 UNDER COMMITTEE REPORT NO. 9."

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "11/8/2022"

[committee]
name = "Higher, Technical and Vocational Education"
type = "primary"
