billNumber = "SBN-01881"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-1881"
lastScraped = "2025-09-20T21:13:12.689060"
title = "MEDIA ARTS UNIVERSITY OF THE PHILIPPINES ACT"
filedDate = "February 14, 2023"
author = "Tulfo, Raffy T., Marcos, Imee R."
longTitle = "AN ACT CREATING THE MEDIA ARTS UNIVERSITY OF THE PHILIPPINES"
scope = "National"
subject = [ "Media Arts University of the Philippines",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4076137152!.pdf"
pdfFileName = "SBN-1881 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "2/14/2023"
action = "Introduced by Senator RAFFY T. TULFO;"

[[legislativeHistory]]
date = "2/15/2023"
action = "Read on First Reading and Referred to the Committees on HIGHER, TECHNICAL AND VOCATIONAL EDUCATION; PUBLIC INFORMATION AND MASS MEDIA and FINANCE;"

[[legislativeHistory]]
date = "3/1/2023"
action = "Letter from Senator IMEE R. MARCOS dated February 16, 2023, conveying her intention to be made co-author of SBN-1881, received by LBIS;"

[[legislativeHistory]]
date = "5/11/2023"
action = "Conducted COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "7/19/2023"
action = "Conducted TECHNICAL WORKING GROUP;"

[status]
status = "Pending in the Committee"
date = "2/15/2023"

[committee]
name = "Higher, Technical and Vocational Education"
type = "primary"
