billNumber = "SBN-02660"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-2660"
lastScraped = "2025-09-20T21:16:52.669976"
title = "OVERSEAS FILIPINO WORKERS (OFWS) REMITTANCE PROTECTION ACT"
filedDate = "May 7, 2024"
author = "Tulfo, Raffy T."
longTitle = "AN ACT PROVIDING FOR PROTECTION OF THE REMITTANCES OF OVERSEAS FILIPINO WORKERS"
scope = "National"
subject = [ "Overseas Filipino Workers (OFWS)/ Migrant Workers", "Remittance",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4403739993!.pdf"
pdfFileName = "SBN-2660 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "5/7/2024"
action = "Introduced by Senator RAFFY T. TULFO;"

[[legislativeHistory]]
date = "5/13/2024"
action = "Read on First Reading and Referred to the Committees on BANKS, FINANCIAL INSTITUTIONS AND CURRENCIES; MIGRANT WORKERS and WAYS AND MEANS;"

[status]
status = "Pending in the Committee"
date = "5/13/2024"

[committee]
name = "Banks, Financial Institutions and Currencies"
type = "primary"
