billNumber = "HB00146"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB00146"
lastScraped = "2025-09-21T23:55:44.106782"
title = "HB00146"
longTitle = "AN ACT INSTITUTIONALIZING VOLUNTEERISM AS A STRATEGY FOR NATIONAL DEVELOPMENT AND AS A DOMAIN OF PEOPLE´S PARTICIPATION, AMENDING FOR THE PURPOSE SECTION 12 OF REPUBLIC ACT NO. 9418 OR \\\"THE VOLUNTEER ACT OF 2007\\\""
scope = "National"
dateFiled = "2016-06-30"
status = "Transmitted to the Committee on Appropriations on 2018-01-24"
statusOrder = 4.34
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB00146.pdf"
fileSize = 632580
author = "Acosta-Alba, Ma. Lourdes"
coAuthors = [ "YU, DIVINA GRACE", "UY, JULIETTE T.", "SAVELLANO, DEOGRACIAS VICTOR B.", "ROBES, FLORIDA P.", "LABADLABAD, GLONA", "CASTELO, WINSTON \"WINNIE\"", "ZARATE, CARLOS ISAGANI T.", "FORTUN, LAWRENCE LEMUEL H.", "VILLARICA, LINABELLE RUTH R.",]
[[authorsDetail]]
name = "Acosta-Alba, Ma. Lourdes"
nameCode = "Acosta-Alba"
date = "2016-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "YU, DIVINA GRACE"
nameCode = "Yu"
date = "2016-10-03"
journalNo = "J031"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "UY, JULIETTE T."
nameCode = "Uy (J.)"
date = "2016-10-11"
journalNo = "J035"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SAVELLANO, DEOGRACIAS VICTOR B."
nameCode = "Savellano"
date = "2017-01-17"
journalNo = "J058"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ROBES, FLORIDA P."
nameCode = "Robes"
date = "2017-09-19"
journalNo = "J026"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "LABADLABAD, GLONA"
nameCode = "Labadlabad"
date = "2017-09-19"
journalNo = "J026"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CASTELO, WINSTON \"WINNIE\""
nameCode = "Castelo"
date = "2017-09-19"
journalNo = "J026"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ZARATE, CARLOS ISAGANI T."
nameCode = "Zarate"
date = "2017-09-19"
journalNo = "J026"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "FORTUN, LAWRENCE LEMUEL H."
nameCode = "Fortun"
date = "2017-09-19"
journalNo = "J026"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "VILLARICA, LINABELLE RUTH R."
nameCode = "Villarica"
date = "2018-02-20"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "PEOPLE PARTICIPATION"
type = "primary"
referralCode = "0527"
dateRead = "2016-07-26"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[firstReading]
id = 33614
congress = 17
bill_no = "HB00146"
report = ""
comm_act = ""
referral = "0527"
ref_name = "PEOPLE PARTICIPATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-07-26"
