billNumber = "HB00661"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB00661"
lastScraped = "2025-09-21T23:55:44.215894"
title = "HB00661"
longTitle = "AN ACT ENSURING THE WELFARE AND PROTECTION OF BUSINESS PROCESS OUTSOURCING (BPO) WORKERS AND THE RECOGNITION OF THEIR RIGHTS AS PROVIDED FOR IN THE LABOR CODE OF THE PHILIPPINES"
scope = "National"
dateFiled = "2016-06-30"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 2016-07-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB00661.pdf"
fileSize = 1416427
author = "ELAGO, SARAH JANE I."
coAuthors = [ "ALVAREZ, PANTALEON D.", "DE JESUS, EMMI A.", "BROSAS, ARLENE D.",]
[[authorsDetail]]
name = "ELAGO, SARAH JANE I."
nameCode = "Elago"
date = "2016-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "ALVAREZ, PANTALEON D."
nameCode = "Alvarez (P.)"
date = "2016-08-08"
journalNo = "J007"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DE JESUS, EMMI A."
nameCode = "De Jesus"
date = "2018-01-17"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "BROSAS, ARLENE D."
nameCode = "Brosas"
date = "2018-01-17"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "0521"
dateRead = "2016-07-27"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 34129
congress = 17
bill_no = "HB00661"
report = ""
comm_act = ""
referral = "0521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-07-27"
