billNumber = "HB00244"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB00244"
lastScraped = "2025-09-21T23:55:44.128820"
title = "HB00244"
longTitle = "AN ACT FURTHER AMENDING REPUBLIC ACT NO. 6728, AS AMENDED, OTHERWISE KNOWN AS THE \\\"EXPANDED GOVERNMENT ASSISTANCE TO STUDENTS AND TEACHERS IN PRIVATE EDUCATION ACT\\\" TO PROVIDE FOR AN EXPANDED VOUCHER IN SECONDARY AND TERTIARY EDUCATION, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2016-06-30"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2016-07-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB00244.pdf"
fileSize = 1935393
author = "Angara-Castillo, Bellaflor J."
coAuthors = [ "MALAPITAN, DALE GONZALO R.",]
[[authorsDetail]]
name = "Angara-Castillo, Bellaflor J."
nameCode = "Angara-Castillo"
date = "2016-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "MALAPITAN, DALE GONZALO R."
nameCode = "Malapitan"
date = "2017-12-12"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2016-07-26"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "secondary"
referralCode = "C502"

[firstReading]
id = 33712
congress = 17
bill_no = "HB00244"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-07-26"
