billNumber = "HB00414"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB00414"
lastScraped = "2025-09-21T23:55:44.163138"
title = "HB00414"
longTitle = "AN ACT MANDATING A TWO THOUSAND PESO (P2,000.00) INCREASE IN THE MONTHLY PENSION, WITH CORRESPONDING ADJUSTMENT OF THE MINIMUM MONTHLY PENSION UNDER THE SOCIAL SECURITY SYSTEM, AMENDING FOR THE PURPOSE SECTION 12 OF REPUBLIC ACT 1161 AS AMENDED, OTHERWISE KNOWN AS THE \\\"SOCIAL SECURITY ACT OF 1997\\\""
scope = "National"
dateFiled = "2016-06-30"
status = "Substituted by HJR0010"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB00414.pdf"
fileSize = 308330
author = "TIANGCO, TOBIAS \"TOBY\" M."
coAuthors = [ "ROMUALDEZ, YEDDA MARIE K.",]
[[authorsDetail]]
name = "TIANGCO, TOBIAS \"TOBY\" M."
nameCode = "Tiangco"
date = "2016-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "ROMUALDEZ, YEDDA MARIE K."
nameCode = "Romualdez"
date = "2016-11-07"
journalNo = "J040"
sessionNo = "1RS"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2016-07-26"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 33882
congress = 17
bill_no = "HB00414"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-07-26"
