billNumber = "HB00432"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB00432"
lastScraped = "2025-09-21T23:55:44.166157"
title = "HB00432"
longTitle = "AN ACT REQUIRING PUBLIC OFFICIALS AND EMPLOYEES TO SUBMIT A WRITTEN PERMISSION OR WAIVER IN FAVOR OF THE OMBUDSMAN TO LOOK INTO ALL DEPOSITS OF WHATEVER NATURE WITH BANKS OR BANKING INSTITUTIONS BOTH WITHIN AND OUTSIDE THE PHILIPPINES INCLUDING INVESTMENT BONDS ISSUED BY THE GOVERNMENT OF THE PHILIPPINES, ITS POLITICAL SUBDIVISIONS AND INSTRUMENTALITIES AND PROVIDING PENALTIES THEREFOR"
scope = "National"
dateFiled = "2016-06-30"
status = "Pending with the Committee on BANKS AND FINANCIAL INTERMEDIARIES since 2016-07-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB00432.pdf"
fileSize = 324254
author = "Escudero, Evelina G."
[[authorsDetail]]
name = "Escudero, Evelina G."
nameCode = "Escudero"
date = "2016-06-30"
sequence = 1

[[committee]]
name = "BANKS AND FINANCIAL INTERMEDIARIES"
type = "primary"
referralCode = "0505"
dateRead = "2016-07-26"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "principal"
referralCode = "0537"

[firstReading]
id = 33900
congress = 17
bill_no = "HB00432"
report = ""
comm_act = ""
referral = "0505"
ref_name = "BANKS AND FINANCIAL INTERMEDIARIES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-07-26"
