billNumber = "HB01050"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB01050"
lastScraped = "2025-09-21T23:55:44.285169"
title = "HB01050"
longTitle = "AN ACT REQUIRING LICENSED PROFESSIONALS UNDER THE SUPERVISION OF THE PROFESSIONAL REGULATION COMMISSION (PRC) TO PLANT A TREE OR RENDER COMMUNITY SERVICE EVERY YEAR AS REQUISITE FOR THE RENEWAL OF THEIR PROFESSIONAL IDENTIFICATION CARD"
scope = "National"
dateFiled = "2016-07-05"
status = "Pending with the Committee on CIVIL SERVICE AND PROFESSIONAL REGULATION since 2016-08-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB01050.pdf"
fileSize = 393302
author = "Antonino, Magnolia C."
[[authorsDetail]]
name = "Antonino, Magnolia C."
nameCode = "Antonino"
date = "2016-07-05"
sequence = 1

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "primary"
referralCode = "0506"
dateRead = "2016-08-01"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 34518
congress = 17
bill_no = "HB01050"
report = ""
comm_act = ""
referral = "0506"
ref_name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-01"
