billNumber = "HB01497"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB01497"
lastScraped = "2025-09-21T23:55:44.363484"
title = "HB01497"
longTitle = "AN ACT PRESCRIBING SCHOOL BUS SAFETY STANDARDS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2016-07-12"
status = "Pending with the Committee on TRANSPORTATION since 2016-08-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB01497.pdf"
fileSize = 725565
author = "Abayon, Harlin Neil III J."
[[authorsDetail]]
name = "Abayon, Harlin Neil III J."
nameCode = "Abayon"
date = "2016-07-12"
sequence = 1

[[committee]]
name = "TRANSPORTATION"
type = "primary"
referralCode = "E509"
dateRead = "2016-08-01"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 34965
congress = 17
bill_no = "HB01497"
report = ""
comm_act = ""
referral = "E509"
ref_name = "TRANSPORTATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-01"
