billNumber = "HB01402"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB01402"
lastScraped = "2025-09-21T23:55:44.345498"
title = "HB01402"
longTitle = "AN ACT PROVIDING FOR MANDATORY APPOINTMENT OF TOURISM OFFICERS IN PROVINCES AND CITIES AND OPTIONAL APPOINTMENT IN MUNICIPALITIES, AMENDING FOR THE PURPOSE REPUBLIC ACT 7160, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991 AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2016-07-12"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2016-08-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB01402.pdf"
fileSize = 774658
author = "Amante, Erlpe John \"Ping\" M."
coAuthors = [ "DE VENECIA, CHRISTOPHER P.", "CATAMCO, NANCY A.",]
[[authorsDetail]]
name = "Amante, Erlpe John \"Ping\" M."
nameCode = "Amante"
date = "2016-07-12"
sequence = 1

[[coAuthorsDetail]]
name = "DE VENECIA, CHRISTOPHER P."
nameCode = "De Venecia"
date = "2016-08-24"
journalNo = "J015"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CATAMCO, NANCY A."
nameCode = "Catamco"
date = "2016-09-28"
journalNo = "J028"
sessionNo = "1RS"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2016-08-01"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 34870
congress = 17
bill_no = "HB01402"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-01"
