billNumber = "HB01390"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB01390"
lastScraped = "2025-09-21T23:55:44.343582"
title = "HB01390"
longTitle = "AN ACT PROVIDING FOR STUDENT HOUSING FINANCING SCHEME"
scope = "National"
dateFiled = "2016-07-11"
status = "Referred to Stakeholders on 2019-01-14"
statusOrder = 4.01
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB01390.pdf"
fileSize = 519296
author = "Vargas, Alfred D."
[[authorsDetail]]
name = "Vargas, Alfred D."
nameCode = "Vargas"
date = "2016-07-11"
sequence = 1

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "primary"
referralCode = "0518"
dateRead = "2016-08-01"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 34858
congress = 17
bill_no = "HB01390"
report = ""
comm_act = ""
referral = "0518"
ref_name = "HOUSING AND URBAN DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-01"
