billNumber = "HB02673"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB02673"
lastScraped = "2025-09-21T23:55:44.623721"
title = "HB02673"
longTitle = "AN ACT PROVIDING FOR FREE PARKING IN ALL MALLS AND SHOPPING ESTABLISHMENTS AND PROVIDING PENALTY FOR VIOLATION THEREOF"
scope = "National"
dateFiled = "2016-08-08"
status = "Referred to Stakeholders on 2016-09-19"
statusOrder = 4.01
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB02673.pdf"
fileSize = 763390
author = "Pancho, Gavini  \"Apol\" C."
coAuthors = [ "ALVAREZ, FRANZ E.", "MONTORO, TEODORO G.", "SILVERIO, LORNA C.",]
[[authorsDetail]]
name = "Pancho, Gavini  \"Apol\" C."
nameCode = "Pancho"
date = "2016-08-08"
sequence = 1

[[coAuthorsDetail]]
name = "ALVAREZ, FRANZ E."
nameCode = "Alvarez (F.)"
date = "2016-09-06"
journalNo = "J019"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MONTORO, TEODORO G."
nameCode = "Montoro"
date = "2016-09-27"
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SILVERIO, LORNA C."
nameCode = "Silverio"
date = "2017-07-25"
journalNo = "J002"
sessionNo = "2RS"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = "2016-08-15"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 36141
congress = 17
bill_no = "HB02673"
report = ""
comm_act = ""
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-15"
