billNumber = "HB02188"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB02188"
lastScraped = "2025-09-21T23:55:44.521476"
title = "HB02188"
longTitle = "AN ACT PROVIDING AN ADDITIONAL REQUISITE FOR FILING OF COMPLAINTS AGAINST MEMBERS OF CONGRESS IN RELATION TO THEIR OFFICE"
scope = "National"
dateFiled = "2016-08-01"
status = "Pending with the Committee on REVISION OF LAWS since 2016-08-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB02188.pdf"
fileSize = 672403
author = "Robes, Florida \"Rida\" P."
[[authorsDetail]]
name = "Robes, Florida \"Rida\" P."
nameCode = "Robes"
date = "2016-08-01"
sequence = 1

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2016-08-08"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 35656
congress = 17
bill_no = "HB02188"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-08"
