billNumber = "HB03557"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB03557"
lastScraped = "2025-09-21T23:55:44.787433"
title = "HB03557"
longTitle = "AN ACT EXPANDING TRAVEL TAX EXEMPTION TO INCLUDE THE COUNTRY'S REPRESENTATIVES TO INTERNATIONAL SPORTS TOURNAMENTS, ACADEMIC CONFERENCES AND BEAUTY PAGEANTS, AMENDING PD 1183 AS AMENDED"
scope = "National"
dateFiled = "2016-09-07"
status = "Substituted by HB08884"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB03557.pdf"
fileSize = 389325
author = "Go, Mark O."
coAuthors = [ "DALOG, MAXIMO B.", "ORTEGA, PABLO", "AGGABAO, MA. LOURDES R.", "SINGSON, ERIC D.", "VARGAS-ALFONSO, BABY ALINE", "CELESTE, JESUS \"BOYING\" F.", "ALBANO, RODOLFO III T.", "BATAOIL, LEOPOLDO N.", "GO, ANA CRISTINA SIQUIAN", "MANGAOANG, ALLEN JESSE C.", "CUARESMA, LUISA LLOREN", "BELARO, SALVADOR \"BONG\" JR. B.", "DE VERA, EUGENE MICHAEL B.", "MENDING, MAKMOD JR. D.", "ESPINO, AMADO JR.", "SALON, ORESTES T.", "SAMBAR, MARK AERON H.", "COSALAN, RONALD M.", "ROQUE, HARRY L.", "SUANSING, GING", "LAZATIN, CARMELO II B.", "SY-ALVARADO, JOSE ANTONIO R.", "ROMERO, MICHAEL ODYLON L.", "MARCOS, IMELDA R.", "TY, ARNEL U.", "TING, RANDOLPH S.", "BERTIZ, ANICETO \"JOHN\" III D.", "VILLARIN, TOMASITO S.", "MARCOLETA, RODANTE D.", "ATIENZA, JOSE JR. L.", "VIOLAGO, MICALEA S.", "MACAPAGAL ARROYO, GLORIA", "PINEDA, ENRICO A.", "HERRERA-DY, BERNADETTE C.", "PANGANIBAN, JOSE JR. T.", "ACOSTA, GIL P.", "SAVELLANO, DEOGRACIAS VICTOR B.", "BOLILIA, LIANDA B.", "ALONTE-NAGUIAT, LEN B.", "BILLONES, TAWI", "PANOTES, MARISOL C.", "MATUGAS, FRANCISCO \"BINGO\" T.", "PIMENTEL, JOHNNY TY", "SARMIENTO, EDGAR S.", "GERON, RICO B.", "BRAVO, ANTHONY M.", "AGLIPAY-VILLAR, EMMELINE", "SAGARBARRIA, MANUEL", "BAUTISTA-BANDIGAN, LORNA", "DIMAPORO, KHALID QUIBRANZA", "MADRONA, EMMANUEL F.", "BERNOS, JOSEPH STO. NINO B.", "NAVA, LUCILLE", "GARCIA, JOSE ENRIQUE III S.", "ROBES, FLORIDA P.", "DEL ROSARIO, MONSOUR", "DELOSO-MONTALLA, CHERYL P.", "NOGRALES, JERICHO JONAS B.", "CANAMA, SABINIANO S.", "TAMBUNTING, GUSTAVO S.",]
[[authorsDetail]]
name = "Go, Mark O."
nameCode = "Go (M.)"
date = "2016-09-07"
sequence = 1

[[coAuthorsDetail]]
name = "DALOG, MAXIMO B."
nameCode = "Dalog"
date = "2016-09-27"
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ORTEGA, PABLO"
nameCode = "Ortega (P.)"
date = "2016-09-27"
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "AGGABAO, MA. LOURDES R."
nameCode = "Aggabao"
date = "2016-09-27"
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SINGSON, ERIC D."
nameCode = "Singson (E.)"
date = "2016-09-27"
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "VARGAS-ALFONSO, BABY ALINE"
nameCode = "Vargas-Alfonso"
date = "2016-09-27"
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CELESTE, JESUS \"BOYING\" F."
nameCode = "Celeste"
date = "2016-09-28"
journalNo = "J028"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ALBANO, RODOLFO III T."
nameCode = "Albano"
date = "2016-09-29"
journalNo = "J029"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BATAOIL, LEOPOLDO N."
nameCode = "Bataoil"
date = "2016-09-29"
journalNo = "J029"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "GO, ANA CRISTINA SIQUIAN"
nameCode = "Go (A.C.)"
date = "2016-09-30"
journalNo = "J030"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MANGAOANG, ALLEN JESSE C."
nameCode = "Mangaoang"
date = "2016-10-05"
journalNo = "J033"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CUARESMA, LUISA LLOREN"
nameCode = "Cuaresma"
date = "2016-10-10"
journalNo = "J034"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BELARO, SALVADOR \"BONG\" JR. B."
nameCode = "Belaro"
date = "2016-10-10"
journalNo = "J034"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DE VERA, EUGENE MICHAEL B."
nameCode = "De Vera"
date = "2016-10-10"
journalNo = "J034"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MENDING, MAKMOD JR. D."
nameCode = "Mending"
date = "2016-10-11"
journalNo = "J035"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ESPINO, AMADO JR."
nameCode = "Espino"
date = "2016-10-17"
journalNo = "J037"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SALON, ORESTES T."
nameCode = "Salon"
date = "2016-10-17"
journalNo = "J037"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SAMBAR, MARK AERON H."
nameCode = "Sambar"
date = "2016-10-17"
journalNo = "J037"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "COSALAN, RONALD M."
nameCode = "Cosalan"
date = "2016-10-17"
journalNo = "J037"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ROQUE, HARRY L."
nameCode = "Roque (H.)"
date = "2016-10-17"
journalNo = "J037"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SUANSING, GING"
nameCode = "Suansing (E.)"
date = "2016-10-17"
journalNo = "J037"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "LAZATIN, CARMELO II B."
nameCode = "Lazatin"
date = "2016-10-18"
journalNo = "J038"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SY-ALVARADO, JOSE ANTONIO R."
nameCode = "Sy-Alvarado"
date = "2016-10-18"
journalNo = "J038"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ROMERO, MICHAEL ODYLON L."
nameCode = "Romero"
date = "2016-10-18"
journalNo = "J038"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MARCOS, IMELDA R."
nameCode = "Marcos"
date = "2016-10-18"
journalNo = "J038"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "TY, ARNEL U."
nameCode = "Ty"
date = "2016-10-18"
journalNo = "J038"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "TING, RANDOLPH S."
nameCode = "Ting"
date = "2016-10-18"
journalNo = "J038"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BERTIZ, ANICETO \"JOHN\" III D."
nameCode = "Bertiz"
date = "2016-10-19"
journalNo = "J039"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "VILLARIN, TOMASITO S."
nameCode = "Villarin"
date = "2016-11-07"
journalNo = "J040"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MARCOLETA, RODANTE D."
nameCode = "Marcoleta"
date = "2016-11-07"
journalNo = "J040"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ATIENZA, JOSE JR. L."
nameCode = "Atienza"
date = "2016-11-14"
journalNo = "J043"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "VIOLAGO, MICALEA S."
nameCode = "Violago"
date = "2016-11-16"
journalNo = "J045"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MACAPAGAL ARROYO, GLORIA"
nameCode = "Macapagal Arroyo"
date = "2016-11-21"
journalNo = "J046"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "PINEDA, ENRICO A."
nameCode = "Pineda"
date = "2016-11-21"
journalNo = "J046"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "HERRERA-DY, BERNADETTE C."
nameCode = "Herrera-Dy"
date = "2016-11-23"
journalNo = "J048"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "PANGANIBAN, JOSE JR. T."
nameCode = "Panganiban"
date = "2016-11-23"
journalNo = "J048"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ACOSTA, GIL P."
nameCode = "Acosta"
date = "2016-11-28"
journalNo = "J049"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SAVELLANO, DEOGRACIAS VICTOR B."
nameCode = "Savellano"
date = "2016-11-28"
journalNo = "J049"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BOLILIA, LIANDA B."
nameCode = "Bolilia"
date = "2016-11-28"
journalNo = "J049"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ALONTE-NAGUIAT, LEN B."
nameCode = "Alonte"
date = "2016-11-28"
journalNo = "J049"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BILLONES, TAWI"
nameCode = "Billones"
date = "2016-11-28"
journalNo = "J049"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "PANOTES, MARISOL C."
nameCode = "Panotes"
date = "2016-12-14"
journalNo = "J056"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MATUGAS, FRANCISCO \"BINGO\" T."
nameCode = "Matugas"
date = "2016-12-14"
journalNo = "J056"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "PIMENTEL, JOHNNY TY"
nameCode = "Pimentel"
date = "2016-12-14"
journalNo = "J056"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SARMIENTO, EDGAR S."
nameCode = "Sarmiento (E.M.)"
date = "2016-12-14"
journalNo = "J056"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "GERON, RICO B."
nameCode = "Geron"
date = "2017-01-16"
journalNo = "J057"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BRAVO, ANTHONY M."
nameCode = "Bravo (A.)"
date = "2017-02-01"
journalNo = "J065"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "AGLIPAY-VILLAR, EMMELINE"
nameCode = "Aglipay-Villar"
date = "2017-02-06"
journalNo = "J066"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "SAGARBARRIA, MANUEL"
nameCode = "Sagarbarria"
date = "2017-02-06"
journalNo = "J066"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BAUTISTA-BANDIGAN, LORNA"
nameCode = "Bautista-Bandigan"
date = "2017-02-06"
journalNo = "J066"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DIMAPORO, KHALID QUIBRANZA"
nameCode = "Dimaporo (M.K.)"
date = "2017-02-06"
journalNo = "J066"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MADRONA, EMMANUEL F."
nameCode = "Madrona"
date = "2017-02-06"
journalNo = "J066"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BERNOS, JOSEPH STO. NINO B."
nameCode = "Bernos"
date = "2017-02-07"
journalNo = "J067"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "NAVA, LUCILLE"
nameCode = "Nava"
date = "2017-02-08"
journalNo = "J068"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "GARCIA, JOSE ENRIQUE III S."
nameCode = "Garcia (J.E.)"
date = "2017-02-13"
journalNo = "J069"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ROBES, FLORIDA P."
nameCode = "Robes"
date = "2017-03-06"
journalNo = "J078"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DEL ROSARIO, MONSOUR"
nameCode = "Del Rosario"
date = "2017-03-08"
journalNo = "J080"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DELOSO-MONTALLA, CHERYL P."
nameCode = "Deloso-Montalla"
date = "2017-05-02"
journalNo = "J084"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "NOGRALES, JERICHO JONAS B."
nameCode = "Nograles (J.J.)"
date = "2017-05-02"
journalNo = "J084"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CANAMA, SABINIANO S."
nameCode = "Canama"
date = "2018-05-30"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "TAMBUNTING, GUSTAVO S."
nameCode = "Tambunting"
date = "2019-01-14"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "TOURISM"
type = "primary"
referralCode = "0538"
dateRead = "2016-09-14"

[[committee]]
name = "APPROPRIATIONS"
type = "principal"
referralCode = "0504"

[firstReading]
id = 37025
congress = 17
bill_no = "HB03557"
report = ""
comm_act = ""
referral = "0538"
ref_name = "TOURISM"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-09-14"
