billNumber = "HB03446"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB03446"
lastScraped = "2025-09-21T23:55:44.765151"
title = "HB03446"
longTitle = "AN ACT REQUIRING PARENTS TO PLANT TWO TREES FOR EVERY CHILD BORN TO THEM, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2016-09-05"
status = "Substituted by HB08727"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB03446.pdf"
fileSize = 376243
author = "PRIMICIAS-AGABAS, MARLYN L."
[[authorsDetail]]
name = "PRIMICIAS-AGABAS, MARLYN L."
nameCode = "Primicias-Agabas"
date = "2016-09-05"
sequence = 1

[[committee]]
name = "REFORESTATION"
type = "primary"
referralCode = "B505"
dateRead = "2016-09-13"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 36914
congress = 17
bill_no = "HB03446"
report = ""
comm_act = ""
referral = "B505"
ref_name = "REFORESTATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-09-13"
