billNumber = "HB03684"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB03684"
lastScraped = "2025-09-21T23:55:44.809590"
title = "HB03684"
longTitle = "AN ACT DECLARING A NATIONAL EMERGENCY AGAINST DRUGS AND TERRORISM, ESTABLISHING A NATIONAL POLICY TO AUTHORIZE THE PRESIDENT, IN ACCORDANCE WITH THE CONSTITUTION, TO EXERCISE NECESSARY AND PROPER POWERS TO ADDRESS SUCH EMERGENCY"
scope = "National"
dateFiled = "2016-09-20"
status = "Pending with the Committee on PUBLIC ORDER AND SAFETY since 2016-09-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB03684.pdf"
fileSize = 905770
author = "MACAPAGAL-ARROYO, GLORIA"
coAuthors = [ "OLIVAREZ, ERIC L.",]
[[authorsDetail]]
name = "MACAPAGAL-ARROYO, GLORIA"
nameCode = "Macapagal Arroyo"
date = "2016-09-20"
sequence = 1

[[coAuthorsDetail]]
name = "OLIVAREZ, ERIC L."
nameCode = "Olivarez"
date = "2018-09-04"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "primary"
referralCode = "0529"
dateRead = "2016-09-27"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[[committee]]
name = "DANGEROUS DRUGS"
type = "secondary"
referralCode = "D502"

[firstReading]
id = 37152
congress = 17
bill_no = "HB03684"
report = ""
comm_act = ""
referral = "0529"
ref_name = "PUBLIC ORDER AND SAFETY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-09-27"
