billNumber = "HB03476"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB03476"
lastScraped = "2025-09-21T23:55:44.771759"
title = "HB03476"
longTitle = "AN ACT STRENGTHENING PRESIDENTIAL DECREE NO. 1096, THE NATIONAL BUILDING CODE OF THE PHILIPPINES, AS AMENDED, BY MANDATING A COMPREHENSIVE NATIONWIDE INSPECTION OF BUILDINGS AND IMPOSING STIFF PENALTIES AGAINST BUILDING OFFICIALS WHO VIOLATE THE PERTINENT PROVISIONS OF THE SAID CODE"
scope = "National"
dateFiled = "2016-09-06"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2016-09-13"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB03476.pdf"
fileSize = 267588
author = "Escudero, Evelina G."
coAuthors = [ "CHIPECO, JOAQUIN JR. M.", "BRAVO, MARIA VIDA E.", "NIETO, YUL SERVO", "REVILLA, STRIKE B.",]
[[authorsDetail]]
name = "Escudero, Evelina G."
nameCode = "Escudero"
date = "2016-09-06"
sequence = 1

[[coAuthorsDetail]]
name = "CHIPECO, JOAQUIN JR. M."
nameCode = "Chipeco"
date = "2016-10-05"
journalNo = "J033"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BRAVO, MARIA VIDA E."
nameCode = "Bravo (M.)"
date = "2016-10-19"
journalNo = "J039"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "NIETO, YUL SERVO"
nameCode = "Nieto"
date = "2018-03-22"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "REVILLA, STRIKE B."
nameCode = "Revilla"
date = "2018-07-03"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2016-09-13"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 36944
congress = 17
bill_no = "HB03476"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-09-13"
