billNumber = "HB03212"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB03212"
lastScraped = "2025-09-21T23:55:44.722520"
title = "HB03212"
longTitle = "AN ACT INSTITUTING THE BOY SCOUTS OF THE PHILIPPINES CHARTER, DEFINING ITS OBJECTIVES, POWER AND FUNCTIONS, REPEALING FOR THE PURPOSE COMMONWEALTH ACT NO. 111, AS AMENDED"
scope = "National"
dateFiled = "2016-08-23"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 2016-08-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB03212.pdf"
fileSize = 1130144
author = "Escudero, Evelina G."
[[authorsDetail]]
name = "Escudero, Evelina G."
nameCode = "Escudero"
date = "2016-08-23"
sequence = 1

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2016-08-30"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 36680
congress = 17
bill_no = "HB03212"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-08-30"
