billNumber = "HB04906"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB04906"
lastScraped = "2025-09-21T23:55:45.052874"
title = "HB04906"
longTitle = "AN ACT EXTENDING FOR ANOTHER TWENTY-FIVE (25) YEARS THE FRANCHISE GRANTED TO THE DELTA BROADCASTING SYSTEM, INC. TO ESTABLISH, MAINTAIN AND OPERATE RADIO AND TELEVISION BROADCASTING STATIONS WITHIN THE PHILIPPINES UNDER REPUBLIC ACT NO. 7723"
scope = "National"
dateFiled = "2017-02-01"
status = "Substituted by HB07199"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB04906.pdf"
fileSize = 620963
author = "Velasco, Lord Allan Jay Q."
[[authorsDetail]]
name = "Velasco, Lord Allan Jay Q."
nameCode = "Velasco, L.A."
date = "2017-02-01"
sequence = 1

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2017-02-08"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "principal"
referralCode = "0539"

[firstReading]
id = 38374
congress = 17
bill_no = "HB04906"
report = ""
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-02-08"
