billNumber = "HB05713"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB05713"
lastScraped = "2025-09-21T23:55:45.227642"
title = "HB05713"
longTitle = "AN ACT ESTABLISHING THE POLICE LAW ENFORCEMENT COURTS, GRANTING THESE EXCLUSIVE ORIGINAL JURISDICTION OVER VIOLATIONS OF CONSTITUTIONAL RIGHTS AND PNP RULES OF ENGAGEMENT COMMITTED BY THE POLICE, AMENDING BATAS PAMBANSA BILANG 129, AS AMENDED, OTHERWISE KNOWN AS \\\"THE JUDICIARY REORGANIZATION ACT OF 1980\\\", APPROPRIATING FUNDS THEREFORE AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2017-05-24"
status = "Pending with the Committee on JUSTICE since 2017-05-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB05713.pdf"
fileSize = 1660849
author = "HERNANDEZ, FERDINAND L."
[[authorsDetail]]
name = "HERNANDEZ, FERDINAND L."
nameCode = "Hernandez (F.)"
date = "2017-05-24"
sequence = 1

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2017-05-29"

[[committee]]
name = "GAMES AND AMUSEMENTS"
type = "principal"
referralCode = "0514"

[firstReading]
id = 39181
congress = 17
bill_no = "HB05713"
report = ""
comm_act = ""
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-05-29"
