billNumber = "HB05303"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB05303"
lastScraped = "2025-09-21T23:55:45.138062"
title = "HB05303"
longTitle = "AN ACT GRANTING MAGNUM.AIR (SKY JET) INC. A FRANCHISE TO ESTABLISH, OPERATE AND MAINTAIN DOMESTIC AND INTERNATIONAL AIR TRANSPORT SERVICES, WITH NINOY AQUINO INTERNATIONAL AIRPORT - TERMINAL 4 AS ITS BASE"
scope = "National"
dateFiled = "2017-03-15"
status = "Substituted by HB06317"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB05303.pdf"
fileSize = 845337
author = "Tugna, Sherwin N."
coAuthors = [ "VIOLAGO, MICALEA S.",]
[[authorsDetail]]
name = "Tugna, Sherwin N."
nameCode = "Tugna"
date = "2017-03-15"
sequence = 1

[[coAuthorsDetail]]
name = "VIOLAGO, MICALEA S."
nameCode = "Violago"
date = "2017-08-08"
journalNo = "J008"
sessionNo = "2RS"

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2017-05-02"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 38771
congress = 17
bill_no = "HB05303"
report = ""
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-05-02"
