billNumber = "HB05330"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB05330"
lastScraped = "2025-09-21T23:55:45.142997"
title = "HB05330"
longTitle = "AN ACT REGULATING THE PRACTICE OF SPEECH LANGUAGE PATHOLOGY IN THE PHILIPPINES, PROVIDING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2017-03-16"
status = "Substituted by HB08529"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB05330.pdf"
fileSize = 1468980
author = "Nieto, John Marvin \"Yul Servo\" C."
coAuthors = [ "BORDADO, GABRIEL JR.",]
[[authorsDetail]]
name = "Nieto, John Marvin \"Yul Servo\" C."
nameCode = "Nieto"
date = "2017-03-16"
sequence = 1

[[authorsDetail]]
name = "Maceda, Edward Vera Perez"
nameCode = "Maceda"
date = "2017-03-16"
sequence = 2

[[coAuthorsDetail]]
name = "BORDADO, GABRIEL JR."
nameCode = "Bordado"
date = "2018-02-20"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "primary"
referralCode = "0506"
dateRead = "2017-05-02"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 38798
congress = 17
bill_no = "HB05330"
report = ""
comm_act = ""
referral = "0506"
ref_name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-05-02"
