billNumber = "HB05401"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB05401"
lastScraped = "2025-09-21T23:55:45.156778"
title = "HB05401"
longTitle = "AN ACT GRANTING AUTOMATIC ADDITIONAL FINANCIAL ASSISTANCE AND SCHOLARSHIP GRANT TO CHILDREN OF A HOUSEHOLD COVERED BY THE PANTAWID PAMILYANG PILIPINO PROGRAM (4Ps)"
scope = "National"
dateFiled = "2017-04-03"
status = "Substituted by HB07773"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB05401.pdf"
fileSize = 1529006
author = "OLIVAREZ, ERIC L."
[[authorsDetail]]
name = "OLIVAREZ, ERIC L."
nameCode = "Olivarez"
date = "2017-04-03"
sequence = 1

[[committee]]
name = "POVERTY ALLEVIATION"
type = "primary"
referralCode = "B502"
dateRead = "2017-05-02"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 38869
congress = 17
bill_no = "HB05401"
report = ""
comm_act = ""
referral = "B502"
ref_name = "POVERTY ALLEVIATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-05-02"
