billNumber = "HB06422"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB06422"
lastScraped = "2025-09-21T23:55:45.484719"
title = "HB06422"
longTitle = "AN ACT ESTABLISHING AN EDUCATION COMMITTEE IN EVERY BARANGAY IN THE COUNTRY TO ENSURE THAT ALL SCHOOL AGE CHILDREN ENTER THE SCHOOL SYSTEM AT KINDERGARTEN AGE AND SENIOR HIGH SCHOOL UPON COMPLETION OF GRADE 10 AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2017-09-19"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2017-09-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB06422.pdf"
fileSize = 319123
author = "Belaro, Salvador Jr. B."
coAuthors = [ "BRAVO, MARIA VIDA E.", "SY-ALVARADO, JOSE ANTONIO R.",]
[[authorsDetail]]
name = "Belaro, Salvador Jr. B."
nameCode = "Belaro"
date = "2017-09-19"
sequence = 1

[[coAuthorsDetail]]
name = "BRAVO, MARIA VIDA E."
nameCode = "Bravo (M.)"
date = "2017-10-11"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SY-ALVARADO, JOSE ANTONIO R."
nameCode = "Sy-Alvarado"
date = "2017-10-04"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2017-09-25"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "principal"
referralCode = "0529"

[firstReading]
id = 39889
congress = 17
bill_no = "HB06422"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-09-25"
