billNumber = "HB06027"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB06027"
lastScraped = "2025-09-21T23:55:45.304007"
title = "HB06027"
longTitle = "AN ACT PROVIDING  FOR GROUNDS FOR THE DISSOLUTION OF A MARRIAGE"
scope = "National"
dateFiled = "2017-07-24"
status = "Substituted by HB07303"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB06027.pdf"
fileSize = 935048
author = "Baguilat, Teddy Jr. Brawner"
coAuthors = [ "ROQUE, HARRY L.", "BULUT-BEGTANG, ELEONOR C.",]
[[authorsDetail]]
name = "Baguilat, Teddy Jr. Brawner"
nameCode = "Baguilat"
date = "2017-07-24"
sequence = 1

[[authorsDetail]]
name = "Batocabe, Rodel M."
nameCode = "Batocabe"
date = "2017-07-24"
sequence = 2

[[authorsDetail]]
name = "Brosas, Arlene D."
nameCode = "Brosas"
date = "2017-07-24"
sequence = 3

[[authorsDetail]]
name = "Casilao, Ariel  'Ka Ayik' B."
nameCode = "Casilao"
date = "2017-07-24"
sequence = 4

[[authorsDetail]]
name = "Castro, France L."
nameCode = "Castro (F.L.)"
date = "2017-07-24"
sequence = 5

[[authorsDetail]]
name = "Catamco, Nancy A."
nameCode = "Catamco"
date = "2017-07-24"
sequence = 6

[[authorsDetail]]
name = "Cayetano, Pia S."
nameCode = "Cayetano"
date = "2017-07-24"
sequence = 7

[[authorsDetail]]
name = "De Jesus,  Emmi A."
nameCode = "De Jesus"
date = "2017-07-24"
sequence = 8

[[authorsDetail]]
name = "ELAGO, SARAH JANE I."
nameCode = "Elago"
date = "2017-07-24"
sequence = 9

[[authorsDetail]]
name = "Garcia, Gwendolyn F."
nameCode = "Garcia (G.)"
date = "2017-07-24"
sequence = 10

[[authorsDetail]]
name = "Go, Ana Cristina S."
nameCode = "Go (A.C.)"
date = "2017-07-24"
sequence = 11

[[authorsDetail]]
name = "Lagman, Edcel C."
nameCode = "Lagman"
date = "2017-07-24"
sequence = 12

[[authorsDetail]]
name = "Alvarez, Pantaleon D."
nameCode = "Alvarez (P.)"
date = "2017-07-24"
sequence = 13

[[authorsDetail]]
name = "TINIO, ANTONIO L."
nameCode = "Tinio"
date = "2017-07-24"
sequence = 14

[[authorsDetail]]
name = "Zarate, Carlos Isagani T."
nameCode = "Zarate"
date = "2017-07-24"
sequence = 15

[[coAuthorsDetail]]
name = "ROQUE, HARRY L."
nameCode = "Roque (H.)"
date = "2017-09-07"
journalNo = "J020"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "BULUT-BEGTANG, ELEONOR C."
nameCode = "Bulut-Begtang"
date = "2017-09-25"
journalNo = "J028"
sessionNo = "2RS"

[[committee]]
name = "POPULATION AND FAMILY RELATIONS"
type = "primary"
referralCode = "0512"
dateRead = "2017-07-31"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 39495
congress = 17
bill_no = "HB06027"
report = ""
comm_act = ""
referral = "0512"
ref_name = "POPULATION AND FAMILY RELATIONS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2017-09-07"
date_read = "2017-07-31"
