billNumber = "HB06230"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB06230"
lastScraped = "2025-09-21T23:55:45.404676"
title = "HB06230"
longTitle = "AN ACT ESTABLISHING A NATIONAL HIGH SCHOOL IN BARANGAY MARIA CLARA, MAASIN CITY, SOUTHERN LEYTE"
scope = "Local"
dateFiled = "2017-08-22"
status = "Scheduled for meeting/hearing on 2017-09-25"
statusOrder = 4.11
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB06230.pdf"
fileSize = 368200
author = "Mercado, Roger G."
coAuthors = [ "SY-ALVARADO, JOSE ANTONIO R.",]
[[authorsDetail]]
name = "Mercado, Roger G."
nameCode = "Mercado"
date = "2017-08-22"
sequence = 1

[[coAuthorsDetail]]
name = "SY-ALVARADO, JOSE ANTONIO R."
nameCode = "Sy-Alvarado"
date = "2017-09-06"
journalNo = "J019"
sessionNo = "2RS"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2017-08-29"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 39698
congress = 17
bill_no = "HB06230"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2017-08-29"
