billNumber = "HB06924"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB06924"
lastScraped = "2025-09-21T23:55:45.610258"
title = "HB06924"
longTitle = "AN ACT ESTABLISHING THE PHILIPPINE DEFENSE UNIVERSITY SYSTEM AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2017-12-21"
status = "Pending with the Committee on NATIONAL DEFENSE AND SECURITY since 2018-01-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB06924.pdf"
fileSize = 2978218
author = "Alvarez, Pantaleon D."
coAuthors = [ "BRAVO, ANTHONY M.", "MAGSAYSAY, MILAGROS A.", "SUANSING, GING", "DALIPE, MANUEL JOSE M.", "ROMERO, MICHAEL ODYLON L.", "CASTELO, WINSTON \"WINNIE\"", "BATOCABE, RODEL M.", "VARGAS-ALFONSO, BABY ALINE", "TAMBUNTING, GUSTAVO S.", "DE VERA, EUGENE MICHAEL B.", "MONTORO, TEODORO G.", "SY-ALVARADO, JOSE ANTONIO R.", "GARBIN, ALFREDO JR. A.", "DATOL, FRANCISCO JR. G.", "YAP, ARTHUR C.", "MENDING, MAKMOD JR. D.", "PANGANIBAN, JOSE JR. T.", "DE VENECIA, CHRISTOPHER P.", "MARCOLETA, RODANTE D.", "CANAMA, SABINIANO S.", "TUGNA, SHERWIN N.",]
[[authorsDetail]]
name = "Alvarez, Pantaleon D."
nameCode = "Alvarez (P.)"
date = "2017-12-21"
sequence = 1

[[authorsDetail]]
name = "Fariñas, Rodolfo C."
nameCode = "Fariñas"
date = "2017-12-21"
sequence = 2

[[authorsDetail]]
name = "Garcia, Gwendolyn F."
nameCode = "Garcia (G.)"
date = "2017-12-21"
sequence = 3

[[authorsDetail]]
name = "ALVAREZ, MERCEDES K."
nameCode = "Alvarez (M.)"
date = "2017-12-21"
sequence = 4

[[authorsDetail]]
name = "Sema, Bai Sandra A."
nameCode = "Sema"
date = "2017-12-21"
sequence = 5

[[authorsDetail]]
name = "LOYOLA, ROY M."
nameCode = "Loyola"
date = "2017-12-21"
sequence = 6

[[authorsDetail]]
name = "Almario, Mayo Z."
nameCode = "Almario"
date = "2017-12-21"
sequence = 7

[[authorsDetail]]
name = "ZAMORA, MARIA CARMEN S."
nameCode = "Zamora (M.C.)"
date = "2017-12-21"
sequence = 8

[[authorsDetail]]
name = "Teves, Arnolfo \"Arnie\" Jr. A."
nameCode = "Teves"
date = "2017-12-21"
sequence = 9

[[coAuthorsDetail]]
name = "BRAVO, ANTHONY M."
nameCode = "Bravo (A.)"
date = "2018-02-20"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "MAGSAYSAY, MILAGROS A."
nameCode = "Aquino-Magsaysay"
date = "2018-02-26"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SUANSING, GING"
nameCode = "Suansing (E.)"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DALIPE, MANUEL JOSE M."
nameCode = "Dalipe"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ROMERO, MICHAEL ODYLON L."
nameCode = "Romero"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CASTELO, WINSTON \"WINNIE\""
nameCode = "Castelo"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "BATOCABE, RODEL M."
nameCode = "Batocabe"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "VARGAS-ALFONSO, BABY ALINE"
nameCode = "Vargas-Alfonso"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "TAMBUNTING, GUSTAVO S."
nameCode = "Tambunting"
date = "2018-01-24"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DE VERA, EUGENE MICHAEL B."
nameCode = "De Vera"
date = "2018-02-13"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "MONTORO, TEODORO G."
nameCode = "Montoro"
date = "2018-02-15"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SY-ALVARADO, JOSE ANTONIO R."
nameCode = "Sy-Alvarado"
date = "2018-02-14"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "GARBIN, ALFREDO JR. A."
nameCode = "Garbin"
date = "2018-02-21"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DATOL, FRANCISCO JR. G."
nameCode = "Datol"
date = "2018-02-06"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "YAP, ARTHUR C."
nameCode = "Yap (A.)"
date = "2018-02-06"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "MENDING, MAKMOD JR. D."
nameCode = "Mending"
date = "2018-02-07"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "PANGANIBAN, JOSE JR. T."
nameCode = "Panganiban"
date = "2018-02-07"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DE VENECIA, CHRISTOPHER P."
nameCode = "De Venecia"
date = "2018-03-20"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "MARCOLETA, RODANTE D."
nameCode = "Marcoleta"
date = "2018-04-04"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CANAMA, SABINIANO S."
nameCode = "Canama"
date = "2018-04-11"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "TUGNA, SHERWIN N."
nameCode = "Tugna"
date = "2018-07-19"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "NATIONAL DEFENSE AND SECURITY"
type = "primary"
referralCode = "0525"
dateRead = "2018-01-16"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "principal"
referralCode = "0529"

[firstReading]
id = 40391
congress = 17
bill_no = "HB06924"
report = ""
comm_act = ""
referral = "0525"
ref_name = "NATIONAL DEFENSE AND SECURITY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2018-01-16"
