billNumber = "HB07200"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB07200"
lastScraped = "2025-09-21T23:55:45.669636"
title = "HB07200"
longTitle = "AN ACT ESTABLISHING THE PHILIPPINE DATA INTERCONNECTIVITY SYSTEM AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2018-02-19"
status = "Pending with the Committee on INFORMATION AND COMMUNICATIONS TECHNOLOGY since 2018-02-21"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB07200.pdf"
fileSize = 2009973
author = "Salo, Ron P."
coAuthors = [ "BRAVO, MARIA VIDA E.", "BORDADO, GABRIEL JR.", "SINGSON, ERIC D.", "ALEJANO, GARY C.", "ESTRELLA, CONRADO III M.", "CERILLES, AURORA ENERIO", "DAZA, RAUL A.", "BENITEZ, ALFREDO \"ALBEE\" B.", "MALAPITAN, DALE GONZALO R.", "DY, NAPOLEON S.", "ALCALA, VICENTE J.", "LOPEZ, MANNY", "HERNANDEZ, PAUL P.",]
[[authorsDetail]]
name = "Salo, Ron P."
nameCode = "Salo"
date = "2018-02-19"
sequence = 1

[[authorsDetail]]
name = "Calalang, Ciriaco S."
nameCode = "Calalang"
date = "2018-02-19"
sequence = 2

[[coAuthorsDetail]]
name = "BRAVO, MARIA VIDA E."
nameCode = "Bravo (M.)"
date = "2018-03-19"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "BORDADO, GABRIEL JR."
nameCode = "Bordado"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SINGSON, ERIC D."
nameCode = "Singson (E.)"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ALEJANO, GARY C."
nameCode = "Alejano"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ESTRELLA, CONRADO III M."
nameCode = "Estrella"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CERILLES, AURORA ENERIO"
nameCode = "Cerilles Enerio"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DAZA, RAUL A."
nameCode = "Daza"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "BENITEZ, ALFREDO \"ALBEE\" B."
nameCode = "Benitez"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "MALAPITAN, DALE GONZALO R."
nameCode = "Malapitan"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DY, NAPOLEON S."
nameCode = "Dy"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ALCALA, VICENTE J."
nameCode = "Alcala"
date = "2018-05-28"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "LOPEZ, MANNY"
nameCode = "Lopez (M.L.)"
date = "2018-03-20"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "HERNANDEZ, PAUL P."
nameCode = "Hernandez (P.)"
date = "2018-12-18"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "primary"
referralCode = "E504"
dateRead = "2018-02-21"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 40667
congress = 17
bill_no = "HB07200"
report = ""
comm_act = ""
referral = "E504"
ref_name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2018-02-21"
