billNumber = "HB07635"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB07635"
lastScraped = "2025-09-21T23:55:45.809902"
title = "HB07635"
longTitle = "AN ACT AMENDING ACT NO. 2031, OTHERWISE KNOWN AS THE NEGOTIABLE INSTRUMENTS LAW, BY REQUIRING THE DRAWER OF THE CHECK TO LEGIBLY PRINT HIS/HER NAME BEFORE SIGNING THE SAME"
scope = "National"
dateFiled = "2018-05-08"
status = "Pending with the Committee on BANKS AND FINANCIAL INTERMEDIARIES since 2018-05-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB07635.pdf"
fileSize = 421770
author = "RODRIGUEZ, MAXIMO B., JR."
[[authorsDetail]]
name = "RODRIGUEZ, MAXIMO B., JR."
nameCode = "Rodriguez (M.)"
date = "2018-05-08"
sequence = 1

[[committee]]
name = "BANKS AND FINANCIAL INTERMEDIARIES"
type = "primary"
referralCode = "0505"
dateRead = "2018-05-16"

[[committee]]
name = "PERSONS WITH DISABILITIES"
type = "principal"
referralCode = "J501"

[firstReading]
id = 41102
congress = 17
bill_no = "HB07635"
report = ""
comm_act = ""
referral = "0505"
ref_name = "BANKS AND FINANCIAL INTERMEDIARIES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2018-05-16"
