billNumber = "HB08649"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB08649"
lastScraped = "2025-09-21T23:55:46.028565"
title = "Renaming Clark International Airport Located In Angeles City, Province Of Pampanga As Diosdado Macapagal International Airport"
longTitle = "AN ACT RENAMING CLARK INTERNATIONAL AIRPORT LOCATED IN ANGELES CITY, PROVINCE OF PAMPANGA AS DIOSDADO MACAPAGAL INTERNATIONAL AIRPORT"
scope = "Local"
dateFiled = "2018-11-26"
status = "Approved by the House on 2018-12-03, transmitted to the Senate on 2018-12-04 and received by the Senate on 2018-12-04"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Gonzales, Aurelio \"Dong\" Jr. D."
[[authorsDetail]]
name = "Gonzales, Aurelio \"Dong\" Jr. D."
nameCode = "Gonzales (A.D.)"
date = "2018-11-26"
sequence = 1

[[authorsDetail]]
name = "Marcoleta, Rodante D."
nameCode = "Marcoleta"
date = "2018-11-26"
sequence = 2

[[authorsDetail]]
name = "Andaya, Rolando Jr. G."
nameCode = "Andaya"
date = "2018-11-26"
sequence = 3

[[authorsDetail]]
name = "Yap, Arthur C."
nameCode = "Yap (A.)"
date = "2018-11-26"
sequence = 4

[[authorsDetail]]
name = "Lazatin, Carmelo \"Jon\" II B."
nameCode = "Lazatin"
date = "2018-11-26"
sequence = 5

[[authorsDetail]]
name = "Sarmiento, Cesar V."
nameCode = "Sarmiento (C.)"
date = "2018-11-26"
sequence = 6

[[authorsDetail]]
name = "Del Mar, Raul V."
nameCode = "Del Mar"
date = "2018-11-26"
sequence = 7

[[authorsDetail]]
name = "GONZALES, ALEXANDRIA \"QUEENIE\""
nameCode = "Gonzales (A.P.)"
date = "2018-11-26"
sequence = 8

[[authorsDetail]]
name = "Batocabe, Rodel M."
nameCode = "Batocabe"
date = "2018-11-26"
sequence = 9

[[authorsDetail]]
name = "Uy, Juliette T."
nameCode = "Uy (J.)"
date = "2018-11-26"
sequence = 10

[[authorsDetail]]
name = "Acosta-Alba, Ma. Lourdes"
nameCode = "Acosta-Alba"
date = "2018-11-26"
sequence = 11

[[authorsDetail]]
name = "Manalo, Jesulito \"Jess\" A."
nameCode = "Manalo"
date = "2018-11-26"
sequence = 12

[[authorsDetail]]
name = "Aumentado, Erico Aristotle C."
nameCode = "Aumentado"
date = "2018-11-26"
sequence = 13

[[authorsDetail]]
name = "Estrella, Conrado III M."
nameCode = "Estrella"
date = "2018-11-26"
sequence = 14

[[authorsDetail]]
name = "ACOP, ROMEO M."
nameCode = "Acop"
date = "2018-11-26"
sequence = 15

[[authorsDetail]]
name = "Unabia, Peter 'Sr. Pedro'  M."
nameCode = "Unabia"
date = "2018-11-26"
sequence = 16

[[authorsDetail]]
name = "Almonte, Jorge T."
nameCode = "Almonte"
date = "2018-11-26"
sequence = 17

[[authorsDetail]]
name = "Sarmiento, Edgar Mary S."
nameCode = "Sarmiento (E.M.)"
date = "2018-11-26"
sequence = 18

[[authorsDetail]]
name = "Gonzalez, Fernando V."
nameCode = "Gonzalez"
date = "2018-11-26"
sequence = 19

[[authorsDetail]]
name = "Pimentel, Johnny Ty"
nameCode = "Pimentel"
date = "2018-11-26"
sequence = 20

[[authorsDetail]]
name = "Pichay, Prospero Jr. A."
nameCode = "Pichay"
date = "2018-11-26"
sequence = 21

[[authorsDetail]]
name = "Violago, Micaela S."
nameCode = "Violago"
date = "2018-11-26"
sequence = 22

[[authorsDetail]]
name = "Garin, Sharon S."
nameCode = "Garin (S.)"
date = "2018-11-26"
sequence = 23

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2018-11-26"

[[committee]]
name = "SCIENCE AND TECHNOLOGY"
type = "principal"
referralCode = "0534"

[[motherBills]]
bill_no = "HB02274"
sequence = 1
date = "2018-11-26"
flag = "S"

[[motherBills]]
bill_no = "HB08289"
sequence = 2
date = "2018-11-26"
flag = "S"

[[substitutedBills]]
bill_no = "HB02274"
sequence = 1
date = "2018-11-26"
flag = "S"

[[substitutedBills]]
bill_no = "HB08289"
sequence = 2
date = "2018-11-26"
flag = "S"

[firstReading]
id = 42116
congress = 17
bill_no = "HB08649"
report = "00954"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "TRANSPORTATION"
recomm = "Approval in substitution of House Bills Numbered 2274 and 8289"
remarks = ""
file = "CR00954.pdf"
date_read = "2018-11-26"
date_ob = "2018-11-26"
date_report = "2018-11-26"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_17/CR00954.pdf"

[secondReading]
id = 4495
congress = 17
bill_no = "HB08649"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "Spo. speech of Hon. Sarmiento, C. be inserted into the records. "
recommended_reconsidered = " "
date_calendared = "2018-11-27"
date_approved = "2018-11-27"
recommitted_bill = ""
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
date_debate_closed = "2018-11-27"
date_amend_closed = "2018-11-27"

[thirdReading]
id = 11353
congress = 17
bill_no = "HB08649"
date_dist = "2018-11-29"
date_adopt = "2018-12-03"
remarks = "    "
no_yeas = 199
no_nays = 0
no_abstent = 0
date_trans = "2018-12-04"
date_rec = "2018-12-04"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "HBT8649.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_17/HBT8649.pdf"
