billNumber = "HB08057"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB08057"
lastScraped = "2025-09-21T23:55:45.895900"
title = "HB08057"
longTitle = "AN ACT EXTENDING FOR ANOTHER TWENTY-FIVE (25) YEARS THE FRANCHISE GRANTED TO SOUNDSTREAM BROADCASTING CORPORATION UNDER REPUBLIC ACT NO. 8209, ENTITLED \\\"AN ACT GRANTING THE SOUNDSTREAM BROADCASTING CORPORATION A FRANCHISE TO CONSTRUCT, INSTALL, ESTABLISH, OPERATE AND MAINTAIN RADIO AND TELEVISION BROADCASTING STATIONS IN THE PROVINCE OF ISABEL AND IN OTHER PLACES IN THE PHILIPPINES"
scope = "National"
dateFiled = "2018-08-06"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 2018-08-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB08057.pdf"
fileSize = 1605347
author = "Garcia, Gwendolyn F."
coAuthors = [ "BRAVO, MARIA VIDA E.",]
[[authorsDetail]]
name = "Garcia, Gwendolyn F."
nameCode = "Garcia (G.)"
date = "2018-08-06"
sequence = 1

[[coAuthorsDetail]]
name = "BRAVO, MARIA VIDA E."
nameCode = "Bravo (M.)"
date = "2018-09-18"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2018-08-08"

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "principal"
referralCode = "0506"

[firstReading]
id = 41524
congress = 17
bill_no = "HB08057"
report = ""
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2018-08-08"
