billNumber = "HB09154"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HB09154"
lastScraped = "2025-09-21T23:55:46.192961"
title = "HB09154"
longTitle = "AN ACT PROHIBITING THE SPREAD OF ONLINE VIRAL CHALLENGE THAT IS DETRIMENTAL TO THE MORAL, MENTAL AND PHYSICAL DEVELOPMENT OF CHILDREN"
scope = "National"
dateFiled = "2019-03-04"
status = "Pending with the Committee on WELFARE OF CHILDREN since 2019-05-20"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HB09154.pdf"
fileSize = 504249
author = "Sy-Alvarado, \"Kuya\" Jose Antonio R."
[[authorsDetail]]
name = "Sy-Alvarado, \"Kuya\" Jose Antonio R."
nameCode = "Sy-Alvarado"
date = "2019-03-04"
sequence = 1

[[committee]]
name = "WELFARE OF CHILDREN"
type = "primary"
referralCode = "F501"
dateRead = "2019-05-20"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 42621
congress = 17
bill_no = "HB09154"
report = ""
comm_act = ""
referral = "F501"
ref_name = "WELFARE OF CHILDREN"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2019-05-20"
