billNumber = "HR00335"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HR00335"
lastScraped = "2025-09-21T23:55:46.281436"
title = "HR00335"
longTitle = "RESOLUTION CALLING FOR AN INVESTIGATION IN AID OF LEGISLATION BY THE APPROPRIATE COMMITTEE OF THE HOUSE OF REPRESENTATIVES TO REVIEW THE STRUCTURE OF THE PHILIPPINE VETERANS BANK (PVB) TO PROTECT THE BENEFITS AND RIGHTS OF WORLD WAR II PHILIPPINE VETERANS"
scope = "National"
dateFiled = "2016-09-13"
status = "Deliberated upon by the Mother Committee on 2018-02-06"
statusOrder = 4.21
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HR00335.pdf"
fileSize = 327457
author = "Suarez, Danilo E."
[[authorsDetail]]
name = "Suarez, Danilo E."
nameCode = "Suarez"
date = "2016-09-13"
sequence = 1

[[committee]]
name = "BANKS AND FINANCIAL INTERMEDIARIES"
type = "primary"
referralCode = "0505"
dateRead = "2016-09-20"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 43077
congress = 17
bill_no = "HR00335"
report = ""
comm_act = ""
referral = "0505"
ref_name = "BANKS AND FINANCIAL INTERMEDIARIES"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2016-11-29"
date_read = "2016-09-20"
