billNumber = "HR00414"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HR00414"
lastScraped = "2025-09-21T23:55:46.295474"
title = "HR00414"
longTitle = "A RESOLUTION OF THE HOUSE OF REPRESENTATIVES EXPRESSING PROFOUND CONDOLENCES ON THE DEMISE OF FORMER SENATOR MIRIAM PALMA DEFENSOR-SANTIAGO, THE PRIDE OF PANAY ISLAND"
scope = "National"
dateFiled = "2016-09-29"
status = "Pending with the Committee on RULES since 2016-10-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HR00414.pdf"
fileSize = 879429
author = "Marquez, Carlito S."
[[authorsDetail]]
name = "Marquez, Carlito S."
nameCode = "Marquez"
date = "2016-09-29"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2016-10-05"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 43156
congress = 17
bill_no = "HR00414"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2016-10-05"
