billNumber = "HR01426"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HR01426"
lastScraped = "2025-09-21T23:55:46.520509"
title = "HR01426"
longTitle = "RESOLUTION DIRECTING THE PROPER HOUSE COMMITTEES TO INVESTIGATE, IN AID OF LEGISLATION, THE FIFTY (50) PESOS ADDITIONAL CHARGE FOR PAPER BILLING OF TELECOMMUNICATIONS COMPANIES"
scope = "National"
dateFiled = "2017-10-24"
status = "Pending with the Committee on INFORMATION AND COMMUNICATIONS TECHNOLOGY since 2017-11-21"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HR01426.pdf"
fileSize = 431075
author = "Garcia, Gwendolyn F."
[[authorsDetail]]
name = "Garcia, Gwendolyn F."
nameCode = "Garcia (G.)"
date = "2017-10-24"
sequence = 1

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "primary"
referralCode = "E504"
dateRead = "2017-11-20"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 44168
congress = 17
bill_no = "HR01426"
report = ""
comm_act = ""
referral = "E504"
ref_name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2017-11-21"
date_read = "2017-11-20"
