billNumber = "HR01331"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HR01331"
lastScraped = "2025-09-21T23:55:46.501421"
title = "HR01331"
longTitle = "A RESOLUTION URGING THE COMMITTEE ON OVERSEAS WORKERS AFFAIRS TO INVESTIGATE, IN AID OF LEGISLATION, THE DATA CITED BY THE DEPARTMENT OF FOREIGN AFFAIRS (DFA) IN A REPORT IT SUBMITTED TO THE SENATE ON SEPTEMBER 19, 2017 STATING THAT SOME 3,827 FILIPINOS ARE LANGUISHING IN JAILS ACROSS 52 COUNTRIES AND TERRITORIES AS OF THE END OF 2016"
scope = "National"
dateFiled = "2017-09-20"
status = "Pending with the Committee on OVERSEAS WORKERS AFFAIRS since 2017-10-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HR01331.pdf"
fileSize = 395009
author = "Castelo, Winston 'Winnie'"
[[authorsDetail]]
name = "Castelo, Winston 'Winnie'"
nameCode = "Castelo"
date = "2017-09-20"
sequence = 1

[[committee]]
name = "OVERSEAS WORKERS AFFAIRS"
type = "primary"
referralCode = "E513"
dateRead = "2017-09-25"

[[committee]]
name = "APPROPRIATIONS"
type = "principal"
referralCode = "0504"

[firstReading]
id = 44073
congress = 17
bill_no = "HR01331"
report = ""
comm_act = ""
referral = "E513"
ref_name = "OVERSEAS WORKERS AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2017-10-04"
date_read = "2017-09-25"
