billNumber = "HR02142"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=HR02142"
lastScraped = "2025-09-21T23:55:46.658709"
title = "HR02142"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON HEALTH TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, ON THE CLAIMS OF DR. FARRAH AGUSTIN-BUNCH NATURAL MEDICAL CENTER IN VICTORIA, TARLAC REGARDING CANCER TREATMENT FOR THE PURPOSE OF PROTECTING THE HEALTH AND WELFARE OF THE PUBLIC AND UPHOLDING THE RIGHT OF PATIENTS TO FIND CURE FOR THEIR ILLNESSES CONSISTENT WITH GOVERNMENT STANDARDS ON MEDICAL PRACTICE"
scope = "National"
dateFiled = "2018-09-04"
status = "Pending with the Committee on RULES since 2018-09-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_17/HR02142.pdf"
fileSize = 661401
author = "Tan, Angelina"
[[authorsDetail]]
name = "Tan, Angelina"
nameCode = "Tan (A.)"
date = "2018-09-04"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2018-09-05"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 44884
congress = 17
bill_no = "HR02142"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2018-09-05"
