billNumber = "RBH0000"
billType = "HB"
congress = 17
apiCongressId = 17
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=17&q=RBH0000"
lastScraped = "2025-09-21T23:55:46.806975"
title = "RBH0000"
longTitle = ""
scope = "National"
dateFiled = ""
status = "Pending with the Committee on RULES since 2018-02-12"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2018-02-12"

[firstReading]
id = 45788
congress = 17
bill_no = "RBH0000"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2018-02-12"
