billNumber = "HBN-05620"
billType = "HBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=HBN-5620"
lastScraped = "2025-09-20T23:53:21.100880"
title = "MUNICIPALITY CONVERSION INTO A COMPONENT CITY"
longTitle = "AN ACT EXEMPTING FROM THE POPULATION AND THE LAND AREA REQUIREMENTS THE CONVERSION OF A MUNICIPALITY INTO A COMPONENT CITY IF IT HAS A LOCALLY GENERATED AVERAGE ANNUAL INCOME OF AT LEAST TWO HUNDRED TWENTY MILLION PESOS (P220,000,000.00), AMENDING FOR THE PURPOSE SECTION 450 OF REPUBLIC ACT NO. 7160, AS AMENDED, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991"
scope = "National"
subject = [ "Local Government Code, Amendments (R.A.No. 7160)", "City Charter, Revision",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1296810906!.pdf"
pdfFileName = "HBN-5620 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "3/8/2012"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "3/13/2012"
action = "Read on First Reading and Referred to the Committee on LOCAL GOVERNMENT;"

[[legislativeHistory]]
date = "11/15/2012"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Pending in the Committee"
date = "3/13/2012"

[committee]
name = "Local Government"
type = "primary"
