billNumber = "HBN-07087"
billType = "HBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=HBN-7087"
lastScraped = "2025-09-20T23:57:30.496736"
title = "JOSE MARIA C. PANGANIBAN DAY"
longTitle = "AN ACT DECLARING FEBRUARY 1 OF EVERY YEAR A SPECIAL NONWORKING PUBLIC HOLIDAY IN THE PROVINCE OF CAMARINES NORTE, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 9090, ENTITLED AN ACT DECLARING FEBRUARY FIRST OF EVERY YEAR AS 'JOSE MARIA C. PANGANIBAN DAY' AND A SPECIAL WORKING PUBLIC HOLIDAY IN THE PROVINCE OF CAMARINES NORTE"
scope = "Local"
subject = [ "Holidays (Special Nonworking Holiday)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1355511970!.pdf"
pdfFileName = "HBN-7087 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/28/2010"
action = "Filed in the Senate requesting for concurrence by Representatives LIWAYWAY VINZONS-CHATO and GIORGIDI B. AGGABAO as authors;"

[[legislativeHistory]]
date = "2/1/2010"
action = "Read on First Reading and Referred to the Committee on LOCAL GOVERNMENT;"

[status]
status = "Pending in the Committee"
date = "2/1/2010"

[committee]
name = "Local Government"
type = "primary"
