billNumber = "HBN-04677"
billType = "HBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=HBN-4677"
lastScraped = "2025-09-20T23:55:19.524608"
title = "HARING - DUGCAL - SUA ROAD"
longTitle = "AN ACT CONVERTING THE HARING - DUGCAL - SUA ROAD CONNECTING THE MUNICIPALITIES OF CANAMAN AND CAMALIGAN, PROVINCE OF CAMARINES SUR INTO A NATIONAL ROAD"
scope = "Local"
subject = [ "Roads, Conversion Into a National Road",]
pdfUrl = "https://web.senate.gov.ph/lisdata/85897795!.pdf"
pdfFileName = "HBN-4677 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "9/16/2008"
action = "Filed in the Senate requesting for concurrence by Representative LUIS R. VILLAFUERTE as author;"

[[legislativeHistory]]
date = "9/23/2008"
action = "Read on First Reading and Referred to the Committee(s) on PUBLIC WORKS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "9/23/2008"

[committee]
name = "Public Works"
type = "primary"
