billNumber = "HBN-06403"
billType = "HBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=HBN-6403"
lastScraped = "2025-09-20T23:57:03.784387"
title = "PHYSICIANS ACT OF 2009"
longTitle = "AN ACT REGULATING THE EDUCATION AND LICENSURE OF PHYSICIANS AND THE PRACTICE OF MEDICINE IN THE PHILIPPINES, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. 2382. AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Physicians Act",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1191910532!.pdf"
pdfFileName = "HBN-6403, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/21/2009"
action = "Filed in the Senate requesting for concurrence by Representatives MAR-LEN ABIGAIL S. BINAY, JANETTE L. GARIN, BIENVENIDO M. ABANTE JR., RAUL T. GONZALEZ JR. and JUNIE E. CUA, et. al., as authors;"

[[legislativeHistory]]
date = "8/10/2009"
action = "Read on First Reading and Referred to the Committee(s) on CIVIL SERVICE AND GOVERNMENT REORGANIZATION; EDUCATION, ARTS AND CULTURE and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/10/2009"

[committee]
name = "Civil Service and Government Reorganization"
type = "primary"
