billNumber = "HB00599"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB00599"
lastScraped = "2025-09-21T23:56:21.586481"
title = "HB00599"
longTitle = "AN ACT ESTABLISHING A MUNICIPAL LIVELIHOOD AND EMPLOYMENT RESOURCE CENTER IN EVERY CITY AND MUNICIPALITY AND PROVIDING FUNDS THEREFOR"
scope = "National"
dateFiled = "2013-07-01"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 2013-07-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB00599.pdf"
fileSize = 382591
author = "Santiago, Erlinda M."
coAuthors = [ "CO, CHRISTOPHER S.", "BATOCABE, RODEL M.",]
[[authorsDetail]]
name = "Santiago, Erlinda M."
nameCode = "Santiago"
date = "2013-07-01"
sequence = 1

[[coAuthorsDetail]]
name = "CO, CHRISTOPHER S."
nameCode = "Co"
date = "2013-09-17"
journalNo = "J021"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BATOCABE, RODEL M."
nameCode = "Batocabe"
date = "2013-09-17"
journalNo = "J021"
sessionNo = "1RS"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "0521"
dateRead = "2013-07-24"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[[committee]]
name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
type = "secondary"
referralCode = "E510"

[firstReading]
id = 46413
congress = 16
bill_no = "HB00599"
report = ""
comm_act = ""
referral = "0521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-07-24"
