billNumber = "HB00041"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB00041"
lastScraped = "2025-09-21T23:56:21.474925"
title = "Part-time Independent Students Grant Act"
longTitle = "AN ACT TO PROVIDE GRANTS TO PART-TIME AND INDEPENDENT STUDENTS"
scope = "National"
dateFiled = "2013-07-01"
status = "Substituted by HB04591"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB00041.pdf"
fileSize = 784439
author = "Piamonte, Mariano Jr. U."
coAuthors = [ "KHO, ELISA T.", "REVILLA, LANI MERCADO", "TAMBUNTING, GUSTAVO S.", "MAGSAYSAY, EULOGIO RODRIGUEZ", "CO, CHRISTOPHER S.", "BATOCABE, RODEL M.", "GULLAS, GERALD ANTHONY JR. V.", "TAN, ANGELINA D.", "ABAYON, HARLIN C.", "CAGAS, MERCEDES C.", "CORTUNA, JULIETA R.",]
[[authorsDetail]]
name = "Piamonte, Mariano Jr. U."
nameCode = "Piamonte"
date = "2013-07-01"
sequence = 1

[[coAuthorsDetail]]
name = "KHO, ELISA T."
nameCode = "Kho"
date = "2013-08-12"
journalNo = "J010"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "REVILLA, LANI MERCADO"
nameCode = "Mercado-Revilla"
date = "2013-08-27"
journalNo = "J013"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "TAMBUNTING, GUSTAVO S."
nameCode = "Tambunting"
date = "2013-08-27"
journalNo = "J013"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MAGSAYSAY, EULOGIO RODRIGUEZ"
nameCode = "Magsaysay"
date = "2013-09-09"
journalNo = "J018"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CO, CHRISTOPHER S."
nameCode = "Co"
date = "2013-09-10"
journalNo = "J019"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BATOCABE, RODEL M."
nameCode = "Batocabe"
date = "2013-09-10"
journalNo = "J019"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "GULLAS, GERALD ANTHONY JR. V."
nameCode = "Gullas"
date = "2013-09-17"
journalNo = "J021"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "TAN, ANGELINA D."
nameCode = "Tan (A.)"
date = "2014-05-19"
journalNo = "J060"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ABAYON, HARLIN C."
nameCode = "Abayon"
date = "2014-07-30"
journalNo = "J002"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CAGAS, MERCEDES C."
nameCode = "Cagas"
date = "2015-02-23"
journalNo = "J052"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CORTUNA, JULIETA R."
nameCode = "Cortuna"
date = "2013-07-01"
journalNo = ""
sessionNo = ""

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2013-07-23"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "principal"
referralCode = "0537"

[firstReading]
id = 45855
congress = 16
bill_no = "HB00041"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-07-23"
