billNumber = "HB01760"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB01760"
lastScraped = "2025-09-21T23:56:21.794242"
title = "HB01760"
longTitle = "AN ACT TO EFFECTIVELY INSTILL HEALTH CONSCIOUSNESS THROUGH PICTURE-BASED WARNINGS ON TOBACCO PRODUCTS"
scope = "National"
dateFiled = "2013-07-24"
status = "Pending with the Committee on HEALTH since 2013-07-31"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB01760.pdf"
fileSize = 1547040
author = "Violago, Joseph Gilbert F."
[[authorsDetail]]
name = "Violago, Joseph Gilbert F."
nameCode = "Violago"
date = "2013-07-24"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2013-07-31"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 47574
congress = 16
bill_no = "HB01760"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-07-31"
