billNumber = "HB01147"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB01147"
lastScraped = "2025-09-21T23:56:21.684841"
title = "HB01147"
longTitle = "AN ACT TO PROMOTE AGRITOURISM IN THE PHILIPPINES AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2013-07-08"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 2013-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB01147.pdf"
fileSize = 794232
author = "Suansing, Estrellita B."
coAuthors = [ "BICHARA, AL FRANCIS DEL CASTILLO", "TAN, ANGELINA D.",]
[[authorsDetail]]
name = "Suansing, Estrellita B."
nameCode = "Suansing"
date = "2013-07-08"
sequence = 1

[[coAuthorsDetail]]
name = "BICHARA, AL FRANCIS DEL CASTILLO"
nameCode = "Bichara"
date = "2013-08-13"
journalNo = "J011"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "TAN, ANGELINA D."
nameCode = "Tan (A.)"
date = "2013-11-18"
journalNo = "J025"
sessionNo = "1RS"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "E505"
dateRead = "2013-07-29"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 46961
congress = 16
bill_no = "HB01147"
report = ""
comm_act = ""
referral = "E505"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-07-29"
