billNumber = "HB01264"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB01264"
lastScraped = "2025-09-21T23:56:21.708131"
title = "Establishing Multipurpose Fishery Breeding Farms And Hatcheries For The Production/multiplication Of Crabs, Shrimps And Lobsters In The City Of Bislig, Province Of Surigao Del Sur"
longTitle = "AN ACT ESTABLISHING MULTIPURPOSE FISHERY BREEDING FARMS AND HATCHERIES FOR THE PRODUCTION/MULTIPLICATION OF CRABS, SHRIMPS AND LOBSTERS IN THE CITY OF BISLIG, PROVINCE OF SURIGAO DEL SUR AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2013-07-09"
status = "Approved by the House on 2014-06-02, transmitted to the Senate on 2014-06-04 and received by the Senate on 2014-06-04"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB01264.pdf"
fileSize = 255192
author = "Garay, Florencio C."
[[authorsDetail]]
name = "Garay, Florencio C."
nameCode = "Garay"
date = "2013-07-09"
sequence = 1

[[committee]]
name = "AQUACULTURE AND FISHERIES RESOURCES"
type = "primary"
referralCode = "E506"
dateRead = "2013-07-29"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 47078
congress = 16
bill_no = "HB01264"
report = "00209"
comm_act = ""
referral = "E506"
ref_name = "AQUACULTURE AND FISHERIES RESOURCES"
sub_name = "AQUACULTURE AND FISHERIES RESOURCES, APPROPRIATIONS"
recomm = "approval with amendment"
remarks = ""
file = "CR00209.pdf"
date_read = "2013-07-29"
date_ob = "2014-05-19"
date_fri = "2014-05-20"
date_report = "2014-05-15"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_16/CR00209.pdf"

[secondReading]
id = 5212
congress = 16
bill_no = "HB01264"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_approved = "2014-05-20"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""

[thirdReading]
id = 9856
congress = 16
bill_no = "HB01264"
date_dist = "2014-05-28"
date_adopt = "2014-06-02"
remarks = "    "
no_yeas = 202
no_nays = 0
no_abstent = 0
date_trans = "2014-06-04"
date_rec = "2014-06-04"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "hbt1264.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_16/hbt1264.pdf"
