billNumber = "HB01704"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB01704"
lastScraped = "2025-09-21T23:56:21.785058"
title = "HB01704"
longTitle = "AN ACT EXEMPTING CAPITAL TOWNS OF PROVINCES WITHOUT CITIES FROM THE INCOME REQUIREMENT SUBJECT TO CERTAIN CONDITIONS, AMENDING FOR THE PURPOSE OF SECTION 450 OF REPUBLIC ACT 7160, AS AMENDED BY REPUBLIC ACT 9009, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2013-07-23"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2013-07-31"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB01704.pdf"
fileSize = 331884
author = "Bernos, Maria Jocelyn V."
coAuthors = [ "ZAMORA, MARIA CARMEN S.", "ALIPING, NICASIO JR. M.", "ARENAS, ROSE MARIE J.", "AGYAO, MANUEL S.", "ANGARA-CASTILLO, BELLAFLOR J.", "BULUT-BEGTANG, ELEONOR C.",]
[[authorsDetail]]
name = "Bernos, Maria Jocelyn V."
nameCode = "Bernos"
date = "2013-07-23"
sequence = 1

[[coAuthorsDetail]]
name = "ZAMORA, MARIA CARMEN S."
nameCode = "Zamora (M.)"
date = "2013-10-14"
journalNo = "J022"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ALIPING, NICASIO JR. M."
nameCode = "Aliping"
date = "2013-11-18"
journalNo = "J025"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ARENAS, ROSE MARIE J."
nameCode = "Arenas"
date = "2013-11-18"
journalNo = "J025"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "AGYAO, MANUEL S."
nameCode = "Agyao"
date = "2013-11-27"
journalNo = "J030"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ANGARA-CASTILLO, BELLAFLOR J."
nameCode = "Angara-Castillo"
date = "2014-01-29"
journalNo = "J042"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BULUT-BEGTANG, ELEONOR C."
nameCode = "Bulut-Begtang"
date = "2014-06-09"
journalNo = "J069"
sessionNo = "1RS"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2013-07-31"

[[committee]]
name = "SENIOR CITIZENS"
type = "principal"
referralCode = "I505"

[firstReading]
id = 47518
congress = 16
bill_no = "HB01704"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-07-31"
