billNumber = "HB01357"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB01357"
lastScraped = "2025-09-21T23:56:21.724978"
title = "HB01357"
longTitle = "AN ACT DECLARING AS UNLAWFUL THE REPRODUCTION OF COPYRIGHTED BOOKS AND PRINTED MATERIALS THROUGH PHOTOCOPYING, DUPLICATING, PRINTING MACHINES OR SIMILAR MEANS WITHOUT THE WRITTEN CONSENT OF THE COPYRIGHT OWNER, WHETHER THE PUBLISHER OR THE AUTHOR OR BOTH"
scope = "National"
dateFiled = "2013-07-11"
status = "Pending with the Committee on TRADE AND INDUSTRY since 2013-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB01357.pdf"
fileSize = 337894
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "RODRIGUEZ, MAXIMO JR. B.",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez (R.)"
date = "2013-07-11"
sequence = 1

[[coAuthorsDetail]]
name = "RODRIGUEZ, MAXIMO JR. B."
nameCode = "Rodriguez (M.)"
date = "2013-07-11"
journalNo = ""
sessionNo = ""

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = "2013-07-29"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 47171
congress = 16
bill_no = "HB01357"
report = ""
comm_act = ""
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-07-29"
