billNumber = "HB02918"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB02918"
lastScraped = "2025-09-21T23:56:22.005014"
title = "HB02918"
longTitle = "AN ACT CREATING THE MAGNA CARTA OF BARANGAY NUTRITION SCHOLARS AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2013-09-18"
status = "Pending with the Committee on HEALTH since 2013-09-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB02918.pdf"
fileSize = 819511
author = "Aggabao, Giorgidi B."
coAuthors = [ "VARGAS, ALFRED PAOLO III", "REYES, REGINA ONGSIAKO",]
[[authorsDetail]]
name = "Aggabao, Giorgidi B."
nameCode = "Aggabao"
date = "2013-09-18"
sequence = 1

[[coAuthorsDetail]]
name = "VARGAS, ALFRED PAOLO III"
nameCode = "Vargas"
date = "2014-01-27"
journalNo = "J040"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "REYES, REGINA ONGSIAKO"
nameCode = "Reyes"
date = "2015-08-05"
journalNo = "J006"
sessionNo = "3RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2013-09-23"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[firstReading]
id = 48732
congress = 16
bill_no = "HB02918"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-09-23"
