billNumber = "HB02122"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB02122"
lastScraped = "2025-09-21T23:56:21.859780"
title = "HB02122"
longTitle = "AN ACT REQUIRING THE DEPARTMENT OF PUBLIC WORKS AND HIGHWAYS (DPWH) TO SEEK THE CONCURRENCE OF THE REPRESENTATIVE ON THE APPOINTMENT, ASSIGNMENT OR DESIGNATION OF A DISTRICT ENGINEER WITHIN THE TERRITORIAL JURISDICTION OF HIS LEGISLATIVE DISTRICT"
scope = "National"
dateFiled = "2013-07-31"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2013-08-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB02122.pdf"
fileSize = 172833
author = "TEODORO, MARCELINO \"MARCY\" R."
coAuthors = [ "ABUEG, FREDERICK F.",]
[[authorsDetail]]
name = "TEODORO, MARCELINO \"MARCY\" R."
nameCode = "Teodoro"
date = "2013-07-31"
sequence = 1

[[coAuthorsDetail]]
name = "ABUEG, FREDERICK F."
nameCode = "Abueg"
date = "2014-09-15"
journalNo = "J017"
sessionNo = "2RS"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2013-08-07"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 47936
congress = 16
bill_no = "HB02122"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-08-07"
