billNumber = "HB02498"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB02498"
lastScraped = "2025-09-21T23:56:21.928619"
title = "HB02498"
longTitle = "AN ACT AMENDING SECTIONS 23 AND 24 OF REPUBLIC ACT NO. 9165, ALSO KNOWN AS THE COMPREHENSIVE DANGEROUS DRUGS ACT OF 2002 BY RESTORING PLEA BARGAINING AND PROBATION LAWS"
scope = "National"
dateFiled = "2013-08-27"
status = "Pending with the Committee on DANGEROUS DRUGS since 2013-09-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB02498.pdf"
fileSize = 242142
author = "Castelo, Winston 'Winnie'"
[[authorsDetail]]
name = "Castelo, Winston 'Winnie'"
nameCode = "Castelo"
date = "2013-08-27"
sequence = 1

[[committee]]
name = "DANGEROUS DRUGS"
type = "primary"
referralCode = "D502"
dateRead = "2013-09-02"

[[committee]]
name = "REFORESTATION"
type = "principal"
referralCode = "B505"

[firstReading]
id = 48312
congress = 16
bill_no = "HB02498"
report = ""
comm_act = ""
referral = "D502"
ref_name = "DANGEROUS DRUGS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-09-02"
