billNumber = "HB02289"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB02289"
lastScraped = "2025-09-21T23:56:21.890416"
title = "HB02289"
longTitle = "AN ACT CONVERTING RUJALE ROAD LOCATED IN CALZADA, TIPAS TAGUIG CITY FROM A CITY ROAD TO A NATIONAL ROAD"
scope = "Local"
dateFiled = "2013-08-06"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2013-08-13"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB02289.pdf"
fileSize = 138122
author = "Cerafica, Arnel M."
[[authorsDetail]]
name = "Cerafica, Arnel M."
nameCode = "Cerafica"
date = "2013-08-06"
sequence = 1

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2013-08-13"

[[committee]]
name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
type = "principal"
referralCode = "E510"

[firstReading]
id = 48103
congress = 16
bill_no = "HB02289"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-08-13"
