billNumber = "HB02196"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB02196"
lastScraped = "2025-09-21T23:56:21.873086"
title = "HB02196"
longTitle = "AN ACT ABOLISHING THE USE OF COMMUNITY TAX CERTIFICATE AND THE POWER TO LEVY COMMUNITY TAX REPEALING FOR THAT PURPOSE THE PERTINENT PROVISIONS OF REPUBLIC ACT NO. 7160, AS AMENDED, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991"
scope = "National"
dateFiled = "2013-08-01"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2013-08-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB02196.pdf"
fileSize = 4274830
author = "Bravo, Anthony M., Ph.D."
coAuthors = [ "PAEZ, CRESENTE C.",]
[[authorsDetail]]
name = "Bravo, Anthony M., Ph.D."
nameCode = "Bravo (A.)"
date = "2013-08-01"
sequence = 1

[[coAuthorsDetail]]
name = "PAEZ, CRESENTE C."
nameCode = "Paez"
date = "2013-08-01"
journalNo = ""
sessionNo = ""

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2013-08-07"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 48010
congress = 16
bill_no = "HB02196"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-08-07"
