billNumber = "HB03124"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB03124"
lastScraped = "2025-09-21T23:56:22.041211"
title = "HB03124"
longTitle = "AN ACT EXPANDING THE SCOPE OF ACTS CONSTITUTING SEXUAL HARASSMENT, AMENDING FOR THE PURPOSE REPUBLIC ACT NUMBER 7877, OTHERWISE KNOWN AS THE 'SEXUAL HARASSMENT ACT OF 1995'"
scope = "National"
dateFiled = "2013-10-14"
status = "Substituted by HB05663"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB03124.pdf"
fileSize = 404245
author = "Andaya, Rolando Jr. G."
coAuthors = [ "DE VENECIA, MA. GEORGINA PEREZ", "CALIXTO-RUBIANO, IMELDA GALLARDO", "ABAYON, HARLIN C.",]
[[authorsDetail]]
name = "Andaya, Rolando Jr. G."
nameCode = "Andaya"
date = "2013-10-14"
sequence = 1

[[coAuthorsDetail]]
name = "DE VENECIA, MA. GEORGINA PEREZ"
nameCode = "De Venecia"
date = "2013-12-16"
journalNo = "J036"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "CALIXTO-RUBIANO, IMELDA GALLARDO"
nameCode = "Calixto-Rubiano"
date = "2015-02-17"
journalNo = "J050"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ABAYON, HARLIN C."
nameCode = "Abayon"
date = "2015-05-18"
journalNo = "J070"
sessionNo = "2RS"

[[committee]]
name = "WOMEN AND GENDER EQUALITY"
type = "primary"
referralCode = "A504"
dateRead = "2013-10-21"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 48938
congress = 16
bill_no = "HB03124"
report = ""
comm_act = ""
referral = "A504"
ref_name = "WOMEN AND GENDER EQUALITY"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2014-11-24"
date_read = "2013-10-21"
