billNumber = "HB03424"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB03424"
lastScraped = "2025-09-21T23:56:22.097922"
title = "HB03424"
longTitle = "AN ACT DECLARING THE THIRD FRIDAY OF OCTOBER EVERY YEAR AS A SPECIAL NON-WORKING HOLIDAY IN THE MUNICIPALITY OF BAUNGON, PROVINCE OF BUKIDNON TO BE KNOWN AS ARAW NG BAUNGON"
scope = "Local"
dateFiled = "2013-11-25"
status = "Substituted by HB04122"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB03424.pdf"
fileSize = 197538
author = "Acosta-Alba, Ma. Lourdes"
[[authorsDetail]]
name = "Acosta-Alba, Ma. Lourdes"
nameCode = "Acosta-Alba"
date = "2013-11-25"
sequence = 1

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2013-12-02"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 49238
congress = 16
bill_no = "HB03424"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-12-02"
