billNumber = "HB04406"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB04406"
lastScraped = "2025-09-21T23:56:22.293926"
title = "HB04406"
longTitle = "AN ACT CREATING AN ADDITIONAL BRANCH OF THE REGIONAL TRIAL COURT IN OZAMIS CITY, CONVERTING THE MUNICIPAL CIRCUIT TRIAL COURT COMPRISING THE MUNICIPALITIES OF CLARIN AND TUDELA INTO THE MUNICIPAL TRIAL COURT OF CLARIN, AND CREATING A NEW MUNICIPAL CIRCUIT TRIAL COURT COMPRISING THE MUNICIPALITIES OF SINACABAN AND TUDELA, ALL IN THE SECOND LEGISLATIVE DISTRICT OF THE PROVINCE OF MISAMIS OCCIDENTAL, AMENDING FOR THE PURPOSE BATAS PAMBANSA BLG. 129 OTHERWISE KNOWN AS 'THE JUDICIARY REORGANIZATION ACT OF 1980', AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2014-05-13"
status = "Pending with the Committee on JUSTICE since 2014-05-20"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB04406.pdf"
fileSize = 438661
author = "Oaminal, Henry S."
[[authorsDetail]]
name = "Oaminal, Henry S."
nameCode = "Oaminal"
date = "2014-05-13"
sequence = 1

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2014-05-20"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 50220
congress = 16
bill_no = "HB04406"
report = ""
comm_act = ""
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-05-20"
