billNumber = "HB04294"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB04294"
lastScraped = "2025-09-21T23:56:22.270161"
title = "HB04294"
longTitle = "AN ACT CHANGING THE ALLOCATION FORMULA USED IN THE COMPUTATION OF THE SHARE OF THE LOCAL GOVERNMENT UNITS IN THE TWO PERCENT (2%) TAX ON GROSS INCOME EARNED BY ALL BUSINESS ENTERPRISES WITHIN THE SUBIC SPECIAL ECONOMIC ZONE, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 7227, OTHERWISE KNOWN AS 'BASES CONVERSION AND DEVELOPMENT ACT OF 1992,' AS AMENDED"
scope = "National"
dateFiled = "2014-04-08"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 2014-11-18"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB04294.pdf"
fileSize = 388898
author = "Roman, Herminia B."
[[authorsDetail]]
name = "Roman, Herminia B."
nameCode = "Roman"
date = "2014-04-08"
sequence = 1

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2014-05-06"

[[committee]]
name = "INDIGENOUS CULTURAL COMMUNITIES AND INDIGENOUS PEOPLES"
type = "principal"
referralCode = "H502"

[[committee]]
name = "BASES CONVERSION"
type = "secondary"
referralCode = "A509"

[firstReading]
id = 50108
congress = 16
bill_no = "HB04294"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2014-11-18"
date_read = "2014-05-06"
