billNumber = "HB04667"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB04667"
lastScraped = "2025-09-21T23:56:22.358506"
title = "HB04667"
longTitle = "AN ACT INSTITUTIONALIZING AWARENESS AND GRASSROOT ADVOCACY AND TIGHTENING THE ISSUANCE OF CREDIT CARDS THEREBY AVERTING DELINQUENCY ON THE PART OF THE CREDIT CARD HOLDERS AND BANKRUPTCY ON THE PART OF THE BANKS AND OTHER PARTIES INVOLVED IN THE CREDIT CARD SYSTEM AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2014-06-19"
status = "Pending with the Committee on BANKS AND FINANCIAL INTERMEDIARIES since 2014-07-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB04667.pdf"
fileSize = 327736
author = "Castelo, Winston 'Winnie'"
[[authorsDetail]]
name = "Castelo, Winston 'Winnie'"
nameCode = "Castelo"
date = "2014-06-19"
sequence = 1

[[committee]]
name = "BANKS AND FINANCIAL INTERMEDIARIES"
type = "primary"
referralCode = "0505"
dateRead = "2014-07-30"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 50481
congress = 16
bill_no = "HB04667"
report = ""
comm_act = ""
referral = "0505"
ref_name = "BANKS AND FINANCIAL INTERMEDIARIES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-07-30"
