billNumber = "HB05061"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05061"
lastScraped = "2025-09-21T23:56:22.458700"
title = "HB05061"
longTitle = "AN ACT DECLARING AUGUST 2 OF EVERY YEAR AS BUTUAN CITY CHARTER DAY AND A SPECIAL NON-WORKING HOLIDAY IN THE CITY TO BE KNOWN AS THE ADLAW HONG BUTUAN"
scope = "Local"
dateFiled = "2014-09-25"
status = "Substituted by HB06344"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB05061.pdf"
fileSize = 197603
author = "Fortun, Lawrence H."
[[authorsDetail]]
name = "Fortun, Lawrence H."
nameCode = "Fortun"
date = "2014-09-25"
sequence = 1

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2014-10-20"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 50875
congress = 16
bill_no = "HB05061"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-10-20"
