billNumber = "HB05555"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05555"
lastScraped = "2025-09-21T23:56:22.565197"
title = "HB05555"
longTitle = "AN ACT MANDATING THE PHILIPPINE CHARITY SWEEPSTAKES OFFICE (PCSO) TO ADMIT PRESENTATION OF SECONDARY AND OTHER CIRCUMSTANTIAL EVIDENCE IF THE LOTTO TICKET CANNOT BE VALIDATED BY THE MACHINE WHILE MAINTAINING ITS INTEGRITY AND FREEDOM FROM ANY FRAUDULENT CLAIM"
scope = "National"
dateFiled = "2015-03-10"
status = "Pending with the Committee on GAMES AND AMUSEMENTS since 2015-03-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB05555.pdf"
fileSize = 177573
author = "Castelo, Winston 'Winnie'"
[[authorsDetail]]
name = "Castelo, Winston 'Winnie'"
nameCode = "Castelo"
date = "2015-03-10"
sequence = 1

[[committee]]
name = "GAMES AND AMUSEMENTS"
type = "primary"
referralCode = "0514"
dateRead = "2015-03-16"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 51369
congress = 16
bill_no = "HB05555"
report = ""
comm_act = ""
referral = "0514"
ref_name = "GAMES AND AMUSEMENTS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-03-16"
