billNumber = "HB05818"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05818"
lastScraped = "2025-09-21T23:56:22.629093"
title = "HB05818"
longTitle = "AN ACT ESTABLISHING AN ARBORETUM IN THE MUNICIPALITY OF TAGOLOAN, LANAO DEL NORTE WITH THE MIGHTY CAVE PARK IN IT, TO BE KNOWN AS THE MIGHTY CAVE PARK ARBORETUM AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2015-05-28"
status = "Pending with the Committee on NATURAL RESOURCES since 2015-06-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB05818.pdf"
fileSize = 608058
author = "DIMAPORO, IMELDA QUIBRANZA"
coAuthors = [ "DIMAPORO, ABDULLAH D.",]
[[authorsDetail]]
name = "DIMAPORO, IMELDA QUIBRANZA"
nameCode = "Dimaporo (I.)"
date = "2015-05-28"
sequence = 1

[[coAuthorsDetail]]
name = "DIMAPORO, ABDULLAH D."
nameCode = "Dimaporo (A.)"
date = "2015-05-28"
journalNo = ""
sessionNo = ""

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "0526"
dateRead = "2015-06-03"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[firstReading]
id = 51632
congress = 16
bill_no = "HB05818"
report = ""
comm_act = ""
referral = "0526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-06-03"
