billNumber = "HB05403"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05403"
lastScraped = "2025-09-21T23:56:22.532627"
title = "HB05403"
longTitle = "AN ACT MANDATING THE PHILIPPINE HEALTH INSURANCE CORPORATION TO INCREASE THE DIALYSIS TREATMENT COVERAGE OF MEMBERS OF THE NATIONAL HEALTH INSURANCE PROGRAM TO NINETY SESSIONS PER YEAR"
scope = "National"
dateFiled = "2015-02-04"
status = "Substituted by HB05956"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB05403.pdf"
fileSize = 278627
author = "Calalay, Francisco Jr. A."
coAuthors = [ "SUAREZ, ALETA C.", "ASILO, BENJAMIN D.", "PRIMICIAS-AGABAS, MARLYN L.", "SAMACO-PAQUIZ, LEAH PRIMITIVA G.", "CHIPECO, JOAQUIN JR. M.", "PAGDILAO, SAMUEL D.", "GUIAO, JOSELLER \"YENG\" M.", "ARAGONES, SOL", "VILLAR, MARK AGUILAR", "TAN, ANGELINA D.", "BELMONTE, JOSE CHRISTOPHER Y.",]
[[authorsDetail]]
name = "Calalay, Francisco Jr. A."
nameCode = "Calalay"
date = "2015-02-04"
sequence = 1

[[coAuthorsDetail]]
name = "SUAREZ, ALETA C."
nameCode = "Suarez"
date = "2015-02-11"
journalNo = "J048"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ASILO, BENJAMIN D."
nameCode = "Asilo"
date = "2015-02-16"
journalNo = "J049"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "PRIMICIAS-AGABAS, MARLYN L."
nameCode = "Primicias-Agabas"
date = "2015-02-17"
journalNo = "J050"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "SAMACO-PAQUIZ, LEAH PRIMITIVA G."
nameCode = "Paquiz"
date = "2015-03-16"
journalNo = "J061"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CHIPECO, JOAQUIN JR. M."
nameCode = "Chipeco"
date = "2015-03-18"
journalNo = "J063"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "PAGDILAO, SAMUEL D."
nameCode = "Pagdilao"
date = "2015-03-18"
journalNo = "J063"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "GUIAO, JOSELLER \"YENG\" M."
nameCode = "Guiao"
date = "2015-03-18"
journalNo = "J063"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ARAGONES, SOL"
nameCode = "Aragones"
date = "2015-03-18"
journalNo = "J063"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "VILLAR, MARK AGUILAR"
nameCode = "Villar"
date = "2015-05-12"
journalNo = "J068"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "TAN, ANGELINA D."
nameCode = "Tan (A.)"
date = "2015-05-25"
journalNo = "J071"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "BELMONTE, JOSE CHRISTOPHER Y."
nameCode = "Belmonte (J.)"
date = "2015-07-28"
journalNo = "J002"
sessionNo = "3RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2015-02-09"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 51217
congress = 16
bill_no = "HB05403"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-02-09"
