billNumber = "HB05017"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05017"
lastScraped = "2025-09-21T23:56:22.448590"
title = "HB05017"
longTitle = "AN ACT AMENDING REPUBLIC ACT NO. 8049 OTHERWISE KNOWN AS THE ANTI-HAZING ACT OF 1995"
scope = "National"
dateFiled = "2014-09-17"
status = "Substituted by HB05760"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB05017.pdf"
fileSize = 372804
author = "Barcelona-Reyes, Catherine, M.D."
coAuthors = [ "ABAYON, HARLIN C.",]
[[authorsDetail]]
name = "Barcelona-Reyes, Catherine, M.D."
nameCode = "Barcelona-Reyes"
date = "2014-09-17"
sequence = 1

[[coAuthorsDetail]]
name = "ABAYON, HARLIN C."
nameCode = "Abayon"
date = "2015-05-25"
journalNo = "J071"
sessionNo = "2RS"

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "2014-09-22"

[[committee]]
name = "SCIENCE AND TECHNOLOGY"
type = "principal"
referralCode = "0534"

[firstReading]
id = 50831
congress = 16
bill_no = "HB05017"
report = ""
comm_act = ""
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-09-22"
