billNumber = "HB05830"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05830"
lastScraped = "2025-09-21T23:56:22.631316"
title = "HB05830"
longTitle = "AN ACT CREATING THE MUNICIPALITY OF LINTANGAN IN THE PROVINCE OF ZAMBOANGA DEL NORTE"
scope = "Local"
dateFiled = "2015-06-02"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2015-06-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB05830.pdf"
fileSize = 352899
author = "Amatong, Isagani S."
[[authorsDetail]]
name = "Amatong, Isagani S."
nameCode = "Amatong (I.)"
date = "2015-06-02"
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2015-06-03"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 51644
congress = 16
bill_no = "HB05830"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-06-03"
