billNumber = "HB05697"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB05697"
lastScraped = "2025-09-21T23:56:22.601846"
title = "HB05697"
longTitle = "AN ACT PROVIDING FOR A MAGNA CARTA FOR WORKERS IN THE ENERGY SECTOR OF THE PHILIPPINES, AUTHORIZING THE COLLECTION AND APPROPRIATION OF FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2015-05-04"
status = "Pending with the Committee on ENERGY since 2015-05-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Masongsong, Edgardo R."
coAuthors = [ "ABUEG, FREDERICK F.",]
[[authorsDetail]]
name = "Masongsong, Edgardo R."
nameCode = "Masongsong"
date = "2015-05-04"
sequence = 1

[[coAuthorsDetail]]
name = "ABUEG, FREDERICK F."
nameCode = "Abueg"
date = "2015-05-25"
journalNo = "J071"
sessionNo = "2RS"

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "2015-05-11"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 51511
congress = 16
bill_no = "HB05697"
report = ""
comm_act = ""
referral = "0510"
ref_name = "ENERGY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-05-11"
