billNumber = "HB06433"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB06433"
lastScraped = "2025-09-21T23:56:22.768049"
title = "Fostering A Culture Of Voluntary Compliance With Labor Laws, Amending For The Purpose Article 128 Of Presidential Decree No. 442, As Amended, Otherwise Known As The \\\" Labor Code Of The Philippines\\\""
longTitle = "AN ACT FOSTERING A CULTURE OF VOLUNTARY COMPLIANCE WITH LABOR LAWS, AMENDING FOR THE PURPOSE ARTICLE 128 OF PRESIDENTIAL DECREE NO. 442, AS AMENDED, OTHERWISE KNOWN AS THE \\\"LABOR CODE OF THE PHILIPPINES\\\""
scope = "National"
dateFiled = "2016-02-02"
status = "Printed copies distributed to members on 2016-05-23"
statusOrder = 18.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Nograles, Karlo Alexei B."
coAuthors = [ "GUANLAO, AGAPITO H.",]
[[authorsDetail]]
name = "Nograles, Karlo Alexei B."
nameCode = "Nograles"
date = "2016-02-02"
sequence = 1

[[coAuthorsDetail]]
name = "GUANLAO, AGAPITO H."
nameCode = "Guanlao"
date = "2016-02-02"
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2016-02-03"

[[committee]]
name = "WELFARE OF CHILDREN"
type = "principal"
referralCode = "F501"

[[motherBills]]
bill_no = "HB04659"
sequence = 1
date = "2016-02-02"
flag = "S"

[[substitutedBills]]
bill_no = "HB04659"
sequence = 1
date = "2016-02-02"
flag = "S"

[firstReading]
id = 52247
congress = 16
bill_no = "HB06433"
report = "01012"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "LABOR AND EMPLOYMENT"
recomm = "approval"
remarks = ""
file = "CR01012.pdf"
date_read = "2016-02-03"
date_ob = "2016-02-03"
date_report = "2016-02-02"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_16/CR01012.pdf"

[secondReading]
id = 6101
congress = 16
bill_no = "HB06433"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2016-02-03"
date_approved = "2016-05-23"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""

[thirdReading]
id = 10520
congress = 16
bill_no = "HB06433"
date_dist = "2016-05-23"
remarks = "  "
no_yeas = 0
no_nays = 0
no_abstent = 0
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
