billNumber = "HB06134"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB06134"
lastScraped = "2025-09-21T23:56:22.699198"
title = "HB06134"
longTitle = "AN ACT PROVIDING FOR AFFORDABLE DRUG REHABILITATION TREATMENT FOR PHILIPPINE HEALTH INSURANCE CORPORATION (PHIC) BENEFICIARIES, FURTHER AMENDING REPUBLIC ACT 7875, AS AMENDED"
scope = "National"
dateFiled = "2015-09-14"
status = "Pending with the Committee on HEALTH since 2015-09-21"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB06134.pdf"
fileSize = 343101
author = "MERCADO-REVILLA, LANI"
[[authorsDetail]]
name = "MERCADO-REVILLA, LANI"
nameCode = "Mercado-Revilla"
date = "2015-09-14"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2015-09-21"

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "principal"
referralCode = "0537"

[firstReading]
id = 51948
congress = 16
bill_no = "HB06134"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-09-21"
