billNumber = "HB06249"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB06249"
lastScraped = "2025-09-21T23:56:22.726502"
title = "HB06249"
longTitle = "AN ACT REQUIRING THE PHILIPPINE HEALTH INSURANCE CORPORATION TO PROVIDE COVERAGE FOR THE DIAGNOSTIC SERVICES FOR BREAST AND CERVICAL CANCER, PROVIDING FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2015-11-04"
status = "Pending with the Committee on HEALTH since 2015-11-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB06249.pdf"
fileSize = 326083
author = "Vargas, Alfred D."
coAuthors = [ "PANCHO, GAVINI \"APOL\" C.",]
[[authorsDetail]]
name = "Vargas, Alfred D."
nameCode = "Vargas"
date = "2015-11-04"
sequence = 1

[[coAuthorsDetail]]
name = "PANCHO, GAVINI \"APOL\" C."
nameCode = "Pancho"
date = "2015-11-25"
journalNo = "J034"
sessionNo = "3RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2015-11-11"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 52063
congress = 16
bill_no = "HB06249"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-11-11"
