billNumber = "HB06011"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HB06011"
lastScraped = "2025-09-21T23:56:22.671949"
title = "Granting Veritas Media Arts Inc. A Franchise To Construct, Install, Establish, Operate And Maintain Radio And Television Broadcasting Stations In The Province Of Bohol"
longTitle = "AN ACT GRANTING VERITAS MEDIA ARTS INC. A FRANCHISE TO CONSTRUCT, INSTALL, ESTABLISH, OPERATE AND MAINTAIN RADIO AND TELEVISION BROADCASTING STATIONS IN THE PROVINCE OF BOHOL"
scope = "Local"
dateFiled = "2015-08-11"
status = "REPUBLIC ACT RA10899 (Lapsed into law on 2016-07-21)"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HB06011.pdf"
fileSize = 933935
author = "ROBES, ARTURO B."
coAuthors = [ "TEODORO, MARCELINO R.", "SALVACION, ANDRES D.", "CAMINERO, WILFREDO S.", "UNABIA, PETER \"SR. PEDRO\" M.", "BELLO, SILVESTRE \"BEBOT\"", "ARNAIZ, GEORGE P.", "TAMBUNTING, GUSTAVO S.", "DE LA CRUZ, JONATHAN A.",]
[[authorsDetail]]
name = "ROBES, ARTURO B."
nameCode = "Robes"
date = "2015-08-11"
sequence = 1

[[coAuthorsDetail]]
name = "TEODORO, MARCELINO R."
nameCode = "Teodoro"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SALVACION, ANDRES D."
nameCode = "Salvacion"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CAMINERO, WILFREDO S."
nameCode = "Caminero"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "UNABIA, PETER \"SR. PEDRO\" M."
nameCode = "Unabia"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BELLO, SILVESTRE \"BEBOT\""
nameCode = "Bello (S.)"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ARNAIZ, GEORGE P."
nameCode = "Arnaiz"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAMBUNTING, GUSTAVO S."
nameCode = "Tambunting"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DE LA CRUZ, JONATHAN A."
nameCode = "Dela Cruz"
date = "2015-09-15"
journalNo = ""
sessionNo = ""

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2015-08-18"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 51825
congress = 16
bill_no = "HB06011"
report = "00876"
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = "LEGISLATIVE FRANCHISES"
recomm = "approval with amendments"
remarks = ""
file = "CR00876.pdf"
date_read = "2015-08-18"
date_ob = "2015-09-21"
date_report = "2015-09-15"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_16/CR00876.pdf"

[secondReading]
id = 5974
congress = 16
bill_no = "HB06011"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_approved = "2015-10-02"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""

[thirdReading]
id = 10427
congress = 16
bill_no = "HB06011"
date_dist = "2015-10-06"
date_adopt = "2015-10-09"
remarks = "        "
no_yeas = 200
no_nays = 0
no_abstent = 0
date_trans = "2015-10-13"
date_rec = "2015-10-13"
date_spass = "2016-05-23"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = "L"
cc_yeas = 0
cc_nays = 0
cc_absten = 0
dte_transp = "2016-06-20"
dte_actedp = "2016-07-21"
file = "hbt6011.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_16/hbt6011.pdf"
