billNumber = "HR00419"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR00419"
lastScraped = "2025-09-21T23:56:22.872938"
title = "HR00419"
longTitle = "A RESOLUTION DIRECTING THE HOUSE OF REPRESENTATIVES COMMITTEE ON INDIGENOUS PEOPLES TO CONDUCT AN INQUIRY AND/OR INVESTIGATION, IN AID OF LEGISLATION, ON THE BLATANT DEVIATION FROM THE INDIGENOUS CONCEPT OF OWNERSHIP OF ANCESTRAL LANDS/DOMAINS OVER WHICH CERTIFICATES OF ANCESTRAL LAND TITLES/ANCESTRAL DOMAIN TITLES (CALT/CADT) WERE ISSUED BY THE NATIONAL COMMISSION ON INDIGENOUS PEOPLES (NCIP)"
scope = "National"
dateFiled = "2013-10-22"
status = "Pending with the Committee on NATIONAL CULTURAL COMMUNITIES since 2013-12-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR00419.pdf"
fileSize = 225714
author = "Aliping, Nicasio Jr. M."
[[authorsDetail]]
name = "Aliping, Nicasio Jr. M."
nameCode = "Aliping"
date = "2013-10-22"
sequence = 1

[[committee]]
name = "NATIONAL CULTURAL COMMUNITIES"
type = "primary"
referralCode = "0524"
dateRead = "2013-11-18"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 52818
congress = 16
bill_no = "HR00419"
report = ""
comm_act = ""
referral = "0524"
ref_name = "NATIONAL CULTURAL COMMUNITIES"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2013-12-16"
date_read = "2013-11-18"
