billNumber = "HR00365"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR00365"
lastScraped = "2025-09-21T23:56:22.863868"
title = "HR00365"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON HUMAN RIGHTS OF THE HOUSE OF REPRESENTATIVES TO CONDUCT AN INQUIRY IN AID OF LEGISLATION INTO THE ENFORCED OR INVOLUNTARY DISAPPEARANCE OF BRYAN EPA, AN ORGANIZER OF THE KATRIBU PARTYLIST IN BAYOMBONG, NUEVA VIZCAYA, ALLEGEDLY PERPETRATED BY THE ELEMENTS OF THE BAYOMBONG POLICE STATION"
scope = "National"
dateFiled = "2013-10-07"
status = "Pending with the Committee on HUMAN RIGHTS since 2013-12-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR00365.pdf"
fileSize = 239392
author = "Padilla, Carlos M."
[[authorsDetail]]
name = "Padilla, Carlos M."
nameCode = "Padilla"
date = "2013-10-07"
sequence = 1

[[committee]]
name = "HUMAN RIGHTS"
type = "primary"
referralCode = "E507"
dateRead = "2013-10-14"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 52764
congress = 16
bill_no = "HR00365"
report = ""
comm_act = ""
referral = "E507"
ref_name = "HUMAN RIGHTS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2013-12-09"
date_read = "2013-10-14"
