billNumber = "HR00267"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR00267"
lastScraped = "2025-09-21T23:56:22.846550"
title = "HR00267"
longTitle = "A RESOLUTION EXPRESSING THE SENSE OF THE HOUSE IN COMMENDING MR. JAIME ENGAY SR. FOR HIS INVALUABLE AND COUNTLESS CONTRIBUTIONS TO CATHOLIC EDUCATION IN THE DAVAO PROVINCES, AND TO DIRECT THE SECRETARY-GENERAL OF THE HOUSE OF REPRESENTATIVES, TO ENTER INTO THE RECORDS OF THE HOUSE, THE SENTIMENTS OF GRATITUDE OF THE FILIPINO PEOPLE"
scope = "National"
dateFiled = "2013-09-04"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2013-09-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR00267.pdf"
fileSize = 247104
author = "Cortuna, Julieta R."
coAuthors = [ "PIAMONTE, MARIANO JR. U.",]
[[authorsDetail]]
name = "Cortuna, Julieta R."
nameCode = "Cortuna"
date = "2013-09-04"
sequence = 1

[[coAuthorsDetail]]
name = "PIAMONTE, MARIANO JR. U."
nameCode = "Piamonte"
date = "2013-09-04"
journalNo = ""
sessionNo = ""

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2013-09-09"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 52666
congress = 16
bill_no = "HR00267"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-09-09"
