billNumber = "HR00666"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR00666"
lastScraped = "2025-09-21T23:56:22.920246"
title = "HR00666"
longTitle = "A RESOLUTION DIRECTING THE HOUSE OF REPRESENTATIVES, THROUGH THE COMMITTEE ON ECONOMIC AFFAIRS OR THE COMMITTEE ON TRADE AND INDUSTRY, EITHER JOINTLY OR SEPARATELY, TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, ON THE COUNTRY'S STATE OF PREPAREDNESS TO THE ECONOMIC INTEGRATION OF THE ASSOCIATION OF SOUTHEAST ASIAN NATIONS (ASEAN) IN 2015"
scope = "National"
dateFiled = "2014-01-13"
status = "Pending with the Committee on ECONOMIC AFFAIRS since 2014-01-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR00666.pdf"
fileSize = 242109
author = "Acosta-Alba, Ma. Lourdes"
[[authorsDetail]]
name = "Acosta-Alba, Ma. Lourdes"
nameCode = "Acosta-Alba"
date = "2014-01-13"
sequence = 1

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "primary"
referralCode = "0536"
dateRead = "2014-01-21"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 53065
congress = 16
bill_no = "HR00666"
report = ""
comm_act = ""
referral = "0536"
ref_name = "ECONOMIC AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2014-01-28"
date_read = "2014-01-21"
