billNumber = "HR00100"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR00100"
lastScraped = "2025-09-21T23:56:22.815708"
title = "HR00100"
longTitle = "A RESOLUTION URGING THE HOUSE COMMITTEE ON GOOD GOVERNMENT AND PUBLIC ACCOUNTABILITY TO IMMEDIATELY RECOMMEND THE FILING OF APPROPRIATE ADMINISTRATIVE, CIVIL AND CRIMINAL CHARGES AGAINST OFFICIALS OF THE METROPOLITAN WATERWORKS AND SEWERAGE SYSTEM (MWSS) FOR ALLOWING TWO WATER UTILITIES TO PASS ON TO CONSUMERS THE COST OF THEIR CORPORATE INCOME TAX PAYMENTS"
scope = "National"
dateFiled = "2013-07-24"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 2013-11-19"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR00100.pdf"
fileSize = 316413
author = "Violago, Joseph Gilbert F."
[[authorsDetail]]
name = "Violago, Joseph Gilbert F."
nameCode = "Violago"
date = "2013-07-24"
sequence = 1

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2013-07-31"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 52499
congress = 16
bill_no = "HR00100"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2013-11-19"
date_read = "2013-07-31"
