billNumber = "HR00381"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR00381"
lastScraped = "2025-09-21T23:56:22.866628"
title = "HR00381"
longTitle = "RESOLUTION CONGRATULATING AND COMMENDING THE PHILIPPINE TEAM FOR WINNING THE SILVER MEDAL IN THE THIRD FIBA ASIA UNDER-16 CHAMPIONSHIP AND FOR GIVING THE PHILIPPINES THE HONOR TO REPRESENT ASIA IN THE 2014 FIBA UNDER-17 WORLD CHAMPIONSHIP"
scope = "National"
dateFiled = "2013-10-16"
status = "Substituted by HR00876"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Yap, Susan"
[[authorsDetail]]
name = "Yap, Susan"
nameCode = "Yap (S.)"
date = "2013-10-16"
sequence = 1

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "primary"
referralCode = "0543"
dateRead = "2013-10-22"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 52780
congress = 16
bill_no = "HR00381"
report = ""
comm_act = ""
referral = "0543"
ref_name = "YOUTH AND SPORTS DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
file = "CR00087.pdf"
date_pend = "2014-01-20"
date_read = "2013-10-22"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_16/CR00087.pdf"
