billNumber = "HR01268"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR01268"
lastScraped = "2025-09-21T23:56:23.030139"
title = "HR01268"
longTitle = "RESOLUTION DIRECTING THE HOUSE COMMITTEE ON HUMAN RIGHTS TO CONDUCT AN IMMEDIATE INVESTIGATION, IN AID OF LEGISLATION, INTO THE EXTRAJUDICIAL KILLINGS OF FREDDIE LIGIW, EDGAR LIGIW, AND LICUBEN LIGIW BY THE 41ST INFANTRY BATTALION OF THE PHILIPPINE ARMY, AND THE CONTINUED HARASSMENT OF CIVILIANS BY STATE SECURITY FORCES UNDER THE GUISE OF OPLAN BAYANIHAN IN THE PROVINCE OF ABRA"
scope = "National"
dateFiled = "2014-07-07"
status = "Pending with the Committee on HUMAN RIGHTS since 2014-10-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Zarate, Carlos Isagani T."
coAuthors = [ "COLMENARES, NERI",]
[[authorsDetail]]
name = "Zarate, Carlos Isagani T."
nameCode = "Zarate"
date = "2014-07-07"
sequence = 1

[[coAuthorsDetail]]
name = "COLMENARES, NERI"
nameCode = "Colmenares"
date = "2014-07-07"
journalNo = ""
sessionNo = ""

[[committee]]
name = "HUMAN RIGHTS"
type = "primary"
referralCode = "E507"
dateRead = "2014-07-30"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 53665
congress = 16
bill_no = "HR01268"
report = ""
comm_act = ""
referral = "E507"
ref_name = "HUMAN RIGHTS"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2014-10-29"
date_read = "2014-07-30"
