billNumber = "HR01200"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR01200"
lastScraped = "2025-09-21T23:56:23.018266"
title = "HR01200"
longTitle = "RESOLUTION URGING THE COMMISSION ON HIGHER EDUCATION, THE DEPARTMENT OF EDUCATION, THE TECHNICAL EDUCATION AND SKILLS DEVELOPMENT AUTHORITY AND THE DEPARTMENT OF LABOR AND EMPLOYMENT TO ISSUE THE IMPLEMENTING RULES AND REGULATIONS ON THE LABOR IMPLICATIONS OF REPUBLIC ACT NO. 10533, OTHERWISE KNOWN AS THE 'ENHANCED BASIC EDUCATION ACT OF 2013' OR THE K TO 12 LAW"
scope = "National"
dateFiled = "2014-06-09"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2014-06-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Vargas, Alfred D."
coAuthors = [ "ROMULO, ROMAN TECSON",]
[[authorsDetail]]
name = "Vargas, Alfred D."
nameCode = "Vargas"
date = "2014-06-09"
sequence = 1

[[coAuthorsDetail]]
name = "ROMULO, ROMAN TECSON"
nameCode = "Romulo"
date = "2014-06-09"
journalNo = ""
sessionNo = ""

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2014-06-11"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 53598
congress = 16
bill_no = "HR01200"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-06-11"
