billNumber = "HR01159"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR01159"
lastScraped = "2025-09-21T23:56:23.010465"
title = "HR01159"
longTitle = "RESOLUTION URGING THE COMMITTEE ON AGRICULTURE AND FOOD AND THE SPECIAL COMMITTEE ON FOOD SECURITY TO CONDUCT A JOINT INQUIRY, IN AID OF LEGISLATION, IN ORDER TO DETERMINE THE UTILIZATION OF THE 'COCO LEVY' FUND"
scope = "National"
dateFiled = "2014-05-26"
status = "Pending with the Committee on RULES since 2014-06-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Guanlao, Agapito H."
[[authorsDetail]]
name = "Guanlao, Agapito H."
nameCode = "Guanlao"
date = "2014-05-26"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2014-06-02"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 53557
congress = 16
bill_no = "HR01159"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-06-02"
