billNumber = "HR02071"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR02071"
lastScraped = "2025-09-21T23:56:23.179642"
title = "HR02071"
longTitle = "A RESOLUTION OF THE HOUSE OF THE REPRESENTATIVES CONGRATULATING AND COMMENDING BATANG GILAS FOR WINNING THE SOUTHEAST ASIA BASKETBALL ASSOCIATION (SEABA) UNDER-16"
scope = "National"
dateFiled = "2015-05-06"
status = "Pending with the Committee on YOUTH AND SPORTS DEVELOPMENT since 2015-05-13"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR02071.pdf"
fileSize = 184227
author = "OLIVAREZ, ERIC L."
[[authorsDetail]]
name = "OLIVAREZ, ERIC L."
nameCode = "Olivarez"
date = "2015-05-06"
sequence = 1

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "primary"
referralCode = "0543"
dateRead = "2015-05-13"

[[committee]]
name = "ECOLOGY"
type = "principal"
referralCode = "A501"

[firstReading]
id = 54468
congress = 16
bill_no = "HR02071"
report = ""
comm_act = ""
referral = "0543"
ref_name = "YOUTH AND SPORTS DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-05-13"
