billNumber = "HR02162"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=HR02162"
lastScraped = "2025-09-21T23:56:23.197284"
title = "HR02162"
longTitle = "HOUSE RESOLUTION DIRECTING THE COMMITTEE ON NATURAL RESOURCES TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, INTO THE REPORTED ILLEGAL MINING ACTIVITIES OF GEOGEN CORPORATION IN THE MUNICIPALITY OF DINAPIGUE, PROVINCE OF ISABELA, INQUIRING INTO ITS OVER-ALL IMPACT ON THE ENVIRONMENT, HEALTH AND SAFETY OF THE RESIDENTS, ENSURING THAT THESE ILLEGAL MINING ACTIVITIES ARE PUT TO A STOP AND THAT GEOGEN CORPORATION BE HELD ACCOUNTABLE FOR ITS DESTRUCTIVE MINING ACTIVITIES, AND THAT THE NECESSARY REHABILITATION OF THE AFFECTED SITES ARE IMMEDIATELY UNDERTAKEN, AND COMPENSATION FOR THE AFFECTED COMMUNITIES ARE PROVIDED"
scope = "National"
dateFiled = "2015-06-09"
status = "Pending with the Committee on RULES since 2015-06-10"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/HR02162.pdf"
fileSize = 149241
author = "Aggabao, Giorgidi B."
[[authorsDetail]]
name = "Aggabao, Giorgidi B."
nameCode = "Aggabao"
date = "2015-06-09"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2015-06-10"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 54559
congress = 16
bill_no = "HR02162"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2015-06-10"
