billNumber = "PS00221"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=PS00221"
lastScraped = "2025-09-21T23:56:23.328836"
title = "White Paper"
longTitle = ""
scope = "National"
dateFiled = "2014-06-11"
status = "Pending with the Committee on RULES since 2014-06-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/PS221_ Rep. Tiangco.pdf"
fileSize = 79042
author = "TIANGCO, TOBIAS \"TOBY\" M."
[[authorsDetail]]
name = "TIANGCO, TOBIAS \"TOBY\" M."
nameCode = "Tiangco"
date = "2014-06-11"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2014-06-11"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 55291
congress = 16
bill_no = "PS00221"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-06-11"
