billNumber = "PS00105"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=PS00105"
lastScraped = "2025-09-21T23:56:23.311370"
title = "World Trade Organization Conference"
longTitle = "GATT-WTO AGREEMENTS IMPACT ON PHILIPPINE AGRICULTURE"
scope = "National"
dateFiled = "2013-12-11"
status = "Pending with the Committee on GLOBALIZATION AND WTO since 2014-01-22"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/PS105_Rep. Bello (W.).pdf"
fileSize = 53697
author = "Bello, Walden F."
[[authorsDetail]]
name = "Bello, Walden F."
nameCode = "Bello (W.)"
date = "2013-12-11"
sequence = 1

[[committee]]
name = "GLOBALIZATION AND WTO"
type = "primary"
referralCode = "D504"
dateRead = "2014-01-22"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 55213
congress = 16
bill_no = "PS00105"
report = ""
comm_act = ""
referral = "D504"
ref_name = "GLOBALIZATION AND WTO"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-01-22"
