billNumber = "PS00286"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=PS00286"
lastScraped = "2025-09-21T23:56:23.338337"
title = "Andres Bonifacio"
longTitle = ""
scope = "National"
dateFiled = "2014-12-01"
status = "Pending with the Committee on RULES since 2014-12-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/PS286_Rep. Hicap.pdf"
fileSize = 50096
author = "Hicap, Fernando \"Ka Pando\" L."
[[authorsDetail]]
name = "Hicap, Fernando \"Ka Pando\" L."
nameCode = "Hicap"
date = "2014-12-01"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2014-12-01"

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 55343
congress = 16
bill_no = "PS00286"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2014-12-01"
