billNumber = "PS00110"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=PS00110"
lastScraped = "2025-09-21T23:56:23.312130"
title = "Nelson Mandela"
longTitle = "COMMEMORATION OF THE LIFE AND WORKS OF NELSON MANDELA"
scope = "Local"
dateFiled = "2013-12-16"
status = "Consigned to the Archives on 2014-01-22"
statusOrder = 2.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/PS110_Rep. Ridon.pdf"
fileSize = 95340
author = "RIDON, TERRY L."
[[authorsDetail]]
name = "RIDON, TERRY L."
nameCode = "Ridon"
date = "2013-12-16"
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

