billNumber = "PS00073"
billType = "HB"
congress = 16
apiCongressId = 16
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=16&q=PS00073"
lastScraped = "2025-09-21T23:56:23.306931"
title = "In Defense Of Batanes And Secretary Abad"
longTitle = "REACTION TO A NEWSPAPER ARTICLE THAT MALIGNED HER FAMILY"
scope = "National"
dateFiled = "2013-10-22"
status = "Pending with the Committee on PUBLIC INFORMATION since 2013-11-20"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_16/PS073_Rep. Abad.pdf"
fileSize = 61204
author = "Abad, Henedina R."
[[authorsDetail]]
name = "Abad, Henedina R."
nameCode = "Abad"
date = "2013-10-22"
sequence = 1

[[committee]]
name = "PUBLIC INFORMATION"
type = "primary"
referralCode = "0528"
dateRead = "2013-11-20"

[[committee]]
name = "PEACE, RECONCILIATION AND UNITY"
type = "principal"
referralCode = "E512"

[firstReading]
id = 55181
congress = 16
bill_no = "PS00073"
report = ""
comm_act = ""
referral = "0528"
ref_name = "PUBLIC INFORMATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-11-20"
