billNumber = "HB03569"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB03569"
lastScraped = "2025-09-22T00:25:55.226995"
title = "HB03569"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF A MODEST COCONUT COIR EXTRACTING PLANT IN THE MUNICIPALITY OF GUINAYANGAN, FOURTH DISTRICT OF QUEZON PROVINCE, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1992-10-12"
status = "Pending with the Committee on TRADE AND INDUSTRY since 1992-10-15"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lavides"
[[authorsDetail]]
name = "Lavides"
nameCode = "Lavides"
date = ""
sequence = 0

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "0539"
dateRead = "1992-10-15"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "principal"
referralCode = "0515"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 122188
congress = 9
bill_no = "HB03569"
referral = "0539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
date_read = "1992-10-15"
