billNumber = "HB05229"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB05229"
lastScraped = "2025-09-22T00:25:55.593364"
title = "HB05229"
longTitle = "AN ACT INCREASING THE FUNERAL BENEFITS OF PENSIONERS UNDER THE GOVERNMENT SERVICE INSURANCE SYSTEM (GSIS), AMENDING FOR THE PURPOSE SECTION 19 OF PRESIDENTIAL DECREE NUMBERED ELEVEN HUNDRED AND FORTY-SIX"
scope = "National"
dateFiled = "1992-11-26"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 1992-12-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Punzalan"
coAuthors = [ "DEL MAR, RAUL V.", "NAZARENO, DOMINADOR JR. G.",]
[[authorsDetail]]
name = "Punzalan"
nameCode = "Punzalan"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DEL MAR, RAUL V."
nameCode = "Del Mar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "NAZARENO, DOMINADOR JR. G."
nameCode = "Nazareno"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "1992-12-07"

[[committee]]
name = "PUBLIC ORDER AND SAFETY"
type = "principal"
referralCode = "0529"

[firstReading]
id = 123848
congress = 9
bill_no = "HB05229"
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
date_read = "1992-12-07"
