billNumber = "HB05786"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB05786"
lastScraped = "2025-09-22T00:25:55.685010"
title = "HB05786"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A CULTURAL AND SPORTS COMPLEX IN THE POBLACION OF THE MUNICIPALITY OF MAGUING, PROVINCE OF LANAO DEL SUR, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1992-12-11"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1992-12-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Adiong"
[[authorsDetail]]
name = "Adiong"
nameCode = "Adiong"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1992-12-16"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 124405
congress = 9
bill_no = "HB05786"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1992-12-16"
