billNumber = "HB06323"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB06323"
lastScraped = "2025-09-22T00:25:55.771025"
title = "HB06323"
longTitle = "AN ACT DECLARING DECEMBER THIRTY-FIRST OF EVERY YEAR AS A NATIONAL DAY OF THANKSGIVING AND PRAYER"
scope = "National"
dateFiled = "1993-01-12"
status = "Approved by the House on 1994-08-17, transmitted to on 1994-08-23 and received by the Senate on 1994"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Baguio"
[[authorsDetail]]
name = "Baguio"
nameCode = "Baguio"
date = ""
sequence = 0

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "1993-01-19"

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "principal"
referralCode = "0518"

[firstReading]
id = 124942
congress = 9
bill_no = "HB06323"
report = "00454"
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = "REVISION OF LAWS"
recomm = "APPROVAL"
date_read = "1993-01-19"
date_ob = "1994-02-02"
date_cal = "1994-02-02"
date_unass = "1994-02-02"
date_report = "1993-12-21"

[secondReading]
id = 19389
congress = 9
bill_no = "HB06323"
remarks = "CONSIDERED THE EXPLANATORY NOTE AS THE SPONSORSHIP SPEECH"
date_approved = "1994-08-04"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 1656
congress = 9
bill_no = "HB06323"
date_dist = "1994-08-11"
date_adopt = "1994-08-17"
no_yeas = 150
no_nays = 0
no_abstent = 0
date_trans = "1994-08-23"
date_rec = "1994-08-24"
