billNumber = "HB07667"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB07667"
lastScraped = "2025-09-22T00:25:55.990175"
title = "HB07667"
longTitle = "AN ACT ENSURING THE PAYMENT OF RETIREMENT BENEFIT TO ALL SSS MEMBERS RETIREE OF THE SYSTEM ON THE DATE OF THEIR RETIREMENT"
scope = "National"
dateFiled = "1993-02-18"
status = "Substituted by HB11122"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lacson, Jose Carlos V."
coAuthors = [ "BAGATSING, RAMON JR. S.", "LIBAN, DANTE V.",]
[[authorsDetail]]
name = "Lacson, Jose Carlos V."
nameCode = "Lacson"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "BAGATSING, RAMON JR. S."
nameCode = "Bagatsing"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "1993-02-23"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 126286
congress = 9
bill_no = "HB07667"
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
date_read = "1993-02-23"
