billNumber = "HB07484"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB07484"
lastScraped = "2025-09-22T00:25:55.961918"
title = "HB07484"
longTitle = "AN ACT ESTABLISHING A NATIONAL BAMBOO PROPAGATION PROGRAM, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1993-02-15"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 1993-02-18"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Fajardo"
coAuthors = [ "DRAGON, RENATO P.",]
[[authorsDetail]]
name = "Fajardo"
nameCode = "Fajardo"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "0503"
dateRead = "1993-02-18"

[[committee]]
name = "TOURISM"
type = "principal"
referralCode = "0538"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 126103
congress = 9
bill_no = "HB07484"
referral = "0503"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
date_read = "1993-02-18"
