billNumber = "HB08305"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB08305"
lastScraped = "2025-09-22T00:25:56.096721"
title = "HB08305"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A MULTIPURPOSE CENTER IN BARANGAY NEW LUCBAN IN BAGUIO CITY, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1993-03-22"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1993-03-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Vergara, Bernardo M."
[[authorsDetail]]
name = "Vergara, Bernardo M."
nameCode = "Vergara"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1993-03-25"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 126924
congress = 9
bill_no = "HB08305"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1993-03-25"
