billNumber = "HB08773"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB08773"
lastScraped = "2025-09-22T00:25:56.178285"
title = "HB08773"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A BARANGAY MULTIPURPOSE HALL IN BARANGAY TUGAYA, IN THE MUNICIPALITY OF ALORAN, PROVINCE OF MISAMIS OCCIDENTAL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1993-04-22"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1993-05-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Catane"
[[authorsDetail]]
name = "Catane"
nameCode = "Catane"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1993-05-04"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 127391
congress = 9
bill_no = "HB08773"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1993-05-04"
