billNumber = "HB09610"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB09610"
lastScraped = "2025-09-22T00:25:56.340098"
title = "HB09610"
longTitle = "AN ACT CREATING THE NEW NORTH EXPRESSWAY TOLLWAY AUTHORITY, PRESCRIBING ITS POWERS AND FUNCTIONS AND PROVIDING FUNDS THEREFOR, AND ESTABLISHING THE REGULATORY POWERS OF THE TOLL REGULATORY BOARD AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "1993-06-05"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 1993-06-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Diaz"
coAuthors = [ "VIOLAGO, ELEUTERIO R.", "FAJARDO, PACIFICO M.", "LORENZO, VICTORIO A.", "SILVERIO, RICARDO C.", "VILLAVIZA, ALEJANDRO C.", "SANCHEZ, MANUEL R.", "ESTRELLA, CONRADO III M.",]
[[authorsDetail]]
name = "Diaz"
nameCode = "Diaz"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "VIOLAGO, ELEUTERIO R."
nameCode = "Violago"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FAJARDO, PACIFICO M."
nameCode = "Fajardo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LORENZO, VICTORIO A."
nameCode = "Lorenzo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SILVERIO, RICARDO C."
nameCode = "Silverio"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLAVIZA, ALEJANDRO C."
nameCode = "Villaviza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SANCHEZ, MANUEL R."
nameCode = "Sanchez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESTRELLA, CONRADO III M."
nameCode = "Estrella"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "1993-06-05"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[[committee]]
name = "WAYS AND MEANS"
type = "secondary"
referralCode = "0542"

[firstReading]
id = 128228
congress = 9
bill_no = "HB09610"
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
date_read = "1993-06-05"
