billNumber = "HB09893"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB09893"
lastScraped = "2025-09-22T00:25:56.385490"
title = "HB09893"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF AN ICE PLANT AND COLD STORAGE IN THE MUNICIPALITY OF BAGAC, PROVINCE OF BATAAN, AND APPROPRIATING FUNDS  THEREFOR"
scope = "Local"
dateFiled = "1993-07-21"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1993-07-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Venegas"
[[authorsDetail]]
name = "Venegas"
nameCode = "Venegas"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1993-07-28"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "principal"
referralCode = "0515"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 128511
congress = 9
bill_no = "HB09893"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1993-07-28"
