billNumber = "HB10560"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB10560"
lastScraped = "2025-09-22T00:25:56.511311"
title = "HB10560"
longTitle = "AN ACT CREATING THE NATIONAL ENVIRONMENTAL MANAGEMENT AUTHORITY, DEFINING ITS POWERS, FUNCTIONS AND RESPONSIBILITIE S, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1993-08-30"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 1993-09-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Acosta"
coAuthors = [ "RAMIREZ, JOSE T.", "YAP, RENATO A.", "DE LA CRUZ, ZOILO JR. V.", "DINGLASAN, ANDRES JR. L.", "JABAR, RAMON J.", "MONTEMAYOR, LEONARDO Q.", "VERCELES, ERNESTO C.", "VILLAVIZA, ALEJANDRO C.", "RECTO, RALPH G.",]
[[authorsDetail]]
name = "Acosta"
nameCode = "Acosta"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "RAMIREZ, JOSE T."
nameCode = "Ramirez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "YAP, RENATO A."
nameCode = "Yap"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DE LA CRUZ, ZOILO JR. V."
nameCode = "De La Cruz"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DINGLASAN, ANDRES JR. L."
nameCode = "Dinglasan"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JABAR, RAMON J."
nameCode = "Jabar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = "Montemayor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VERCELES, ERNESTO C."
nameCode = "Verceles"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLAVIZA, ALEJANDRO C."
nameCode = "Villaviza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RECTO, RALPH G."
nameCode = "Recto"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "1993-09-02"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[[committee]]
name = "WAYS AND MEANS"
type = "secondary"
referralCode = "0542"

[[committee]]
name = "ECOLOGY"
type = "secondary"
referralCode = "A501"

[firstReading]
id = 129178
congress = 9
bill_no = "HB10560"
comm_act = "joint referral as per Rules Memo dtd. Sept. 26, 1994"
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
date_read = "1993-09-02"
