billNumber = "HB10799"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB10799"
lastScraped = "2025-09-22T00:25:56.555554"
title = "HB10799"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT OF A MINI-ORGANIC FERTILIZER PRODUCTION STATION IN THE MUNICIPALITY OF MOGPOG, PROVINCE OF MARINDUQUE, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1993-09-20"
status = "Substituted by HB13528"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Reyes, Carmencita O."
[[authorsDetail]]
name = "Reyes, Carmencita O."
nameCode = "Reyes"
date = ""
sequence = 0

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "0503"
dateRead = "1993-09-23"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 129417
congress = 9
bill_no = "HB10799"
referral = "0503"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
date_read = "1993-09-23"
