billNumber = "HB10372"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB10372"
lastScraped = "2025-09-22T00:25:56.474254"
title = "HB10372"
longTitle = "AN ACT GRANTING PRIORITY WATER RIGHTS TO PROVINCES, CITIES OR MUNICIPALITIES WHERE SPRING, CREEKS, RIVERS, PONDS OR LAKES ARE LOCATED"
scope = "National"
dateFiled = "1993-08-12"
status = "Pending with the Committee on NATURAL RESOURCES since 1993-08-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Perez"
coAuthors = [ "PLAZA, CHARITO B.", "RAMIREZ, JOSE T.", "BARBERS, ROBERT Z.",]
[[authorsDetail]]
name = "Perez"
nameCode = "Perez"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PLAZA, CHARITO B."
nameCode = "Plaza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RAMIREZ, JOSE T."
nameCode = "Ramirez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BARBERS, ROBERT Z."
nameCode = "Barbers"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "0526"
dateRead = "1993-08-17"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 128990
congress = 9
bill_no = "HB10372"
referral = "0526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
date_read = "1993-08-17"
