billNumber = "HB10012"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB10012"
lastScraped = "2025-09-22T00:25:56.404900"
title = "HB10012"
longTitle = "AN ACT TO REFORM THE VALUE-ADDED TAX SYSTEM OF THE PHILIPPINES, BY REDUCING THE RATE OF VALUE-ADDED TAX IMPOSED ON SALE AND IMPORTATION OF GOODS, AND SALE OF SERVICES, AMENDING FOR THE PURPOSE VARIOUS SECTIONS OF THE NATIONAL INTERNAL REVENUE CODE OF 1986, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1993-07-28"
status = "Substituted by HB11197"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Isidro"
coAuthors = [ "PLAZA, CHARITO B.", "SOON-RUIZ, NERISSA CORAZON S.",]
[[authorsDetail]]
name = "Isidro"
nameCode = "Isidro"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PLAZA, CHARITO B."
nameCode = "Plaza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SOON-RUIZ, NERISSA CORAZON S."
nameCode = "Soon-ruiz"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "1993-08-03"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "principal"
referralCode = "0515"

[firstReading]
id = 128630
congress = 9
bill_no = "HB10012"
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
date_read = "1993-08-03"
