billNumber = "HB10725"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB10725"
lastScraped = "2025-09-22T00:25:56.541091"
title = "HB10725"
longTitle = "AN ACT PROVIDING FOR THE CONCRETING OF THE BARANGAY ROAD IN BARANGAY STA. CRUZ, MUNICIPALITY OF GUIGUINTO, PROVINCE OF BULACAN, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1993-09-08"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1993-09-20"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Pancho, Pedro M."
[[authorsDetail]]
name = "Pancho, Pedro M."
nameCode = "Pancho"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "1993-09-20"

[[committee]]
name = "GAMES AND AMUSEMENTS"
type = "principal"
referralCode = "0514"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 129343
congress = 9
bill_no = "HB10725"
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1993-09-20"
