billNumber = "HB10100"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB10100"
lastScraped = "2025-09-22T00:25:56.423422"
title = "HB10100"
longTitle = "AN ACT AMENDING CERTAIN PROVISIONS OF THE NATIONAL INTERNAL REVENUE CODE ON VALUE-ADDED TAX (Applies to INSTALLMENT SALES; provides that the seller's obligation to pay the VAT shall arise ONLY AFTER ACTUAL RECEIPT BY HIM OF THE BUYER'S PAYMENT)"
scope = "National"
dateFiled = "1993-08-03"
status = "Substituted by HB11197"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Gullas, Eduardo R."
coAuthors = [ "PLAZA, CHARITO B.", "LIBAN, DANTE V.",]
[[authorsDetail]]
name = "Gullas, Eduardo R."
nameCode = "Gullas"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PLAZA, CHARITO B."
nameCode = "Plaza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "1993-08-09"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 128718
congress = 9
bill_no = "HB10100"
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
date_read = "1993-08-09"
