billNumber = "HB11660"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB11660"
lastScraped = "2025-09-22T00:25:56.727005"
title = "HB11660"
longTitle = "AN ACT AMENDING SECTIONS FOUR AND SEVEN OF REPUBLIC ACT NUMBERED SEVEN THOUSAND SIX HUNDRED AND FORTY EIGHT, KNOWN AS THE ELECTRIC POWER CRISIS ACT OF 1993, FOR THE PURPOSE OF EXTENDING THE DURATION OF THE EXEMPTION OF PROVINCES HOSTING GEOTHERMAL POWER PLANTS FROM POWER RATE INCREASES TO A PERIOD OF TEN YEARS, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1993-12-17"
status = "Pending with the Committee on ENERGY since 1994-01-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Romero"
[[authorsDetail]]
name = "Romero"
nameCode = "Romero"
date = ""
sequence = 0

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "1994-01-25"

[firstReading]
id = 130275
congress = 9
bill_no = "HB11660"
referral = "0510"
ref_name = "ENERGY"
sub_name = ""
date_read = "1994-01-25"
