billNumber = "HB12205"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB12205"
lastScraped = "2025-09-22T00:25:56.848116"
title = "HB12205"
longTitle = "AN ACT TO ADOPT A REVISED GOVERNMENT AUDITING CODE OF THE PHILIPPINES REVISING PRESIDENTIAL DECREE NO. 1445, AS AMENDED BY EXECUTIVE ORDER MO. 292, OTHERWISE KNOWN AS \"THE GOVERNMENT AUDITING CODE OF THE PHILIPPINES\""
scope = "National"
dateFiled = "1994-03-02"
status = "Substituted by HB14329"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Garcia, Pablo P."
coAuthors = [ "AUMENTADO, ERICO B.", "RAMIREZ, JOSE T.", "ROMERO, MIGUEL L.",]
[[authorsDetail]]
name = "Garcia, Pablo P."
nameCode = "Garcia"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "AUMENTADO, ERICO B."
nameCode = "Aumentado"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RAMIREZ, JOSE T."
nameCode = "Ramirez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMERO, MIGUEL L."
nameCode = "Romero"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "0531"
dateRead = "1994-03-08"

[firstReading]
id = 130820
congress = 9
bill_no = "HB12205"
referral = "0531"
ref_name = "REVISION OF LAWS"
sub_name = ""
date_read = "1994-03-08"
