billNumber = "HB12376"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB12376"
lastScraped = "2025-09-22T00:25:56.881880"
title = "HB12376"
longTitle = "AN ACT TO ESTABLISH A CASSAVA PROPAGATION AND DISTRIBUTION CENTER IN THE MUNICIPALITY OF GIPORLOS, PROVINCE OF EASTERN SAMAR, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1994-03-22"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 1994-03-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramirez"
[[authorsDetail]]
name = "Ramirez"
nameCode = "Ramirez"
date = ""
sequence = 0

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "0503"
dateRead = "1994-03-24"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 130991
congress = 9
bill_no = "HB12376"
referral = "0503"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
date_read = "1994-03-24"
