billNumber = "HB14124"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB14124"
lastScraped = "2025-09-22T00:25:57.215091"
title = "HB14124"
longTitle = "AN ACT ESTABLISHING AT LEAST ONE YOUTH CENTER-HALFWAY HOUSE IN EVERY REGION IN THE PHILIPPINES, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1994-11-10"
status = "Pending with the Committee on SOCIAL SERVICES since 1994-11-15"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Avila"
coAuthors = [ "LIBAN, DANTE V.", "DEJON, TEMISTOCLES SR. S.",]
[[authorsDetail]]
name = "Avila"
nameCode = "Avila"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEJON, TEMISTOCLES SR. S."
nameCode = "Dejon"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "SOCIAL SERVICES"
type = "primary"
referralCode = "0535"
dateRead = "1994-11-15"

[[committee]]
name = "APPROPRIATIONS"
type = "secondary"
referralCode = "0504"

[firstReading]
id = 132733
congress = 9
bill_no = "HB14124"
referral = "0535"
ref_name = "SOCIAL SERVICES"
sub_name = ""
date_read = "1994-11-15"
