billNumber = "HB14470"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB14470"
lastScraped = "2025-09-22T00:25:57.300495"
title = "HB14470"
longTitle = "AN ACT PROVIDING FOR THE FULL UTILIZATION OF TEACHERS FOR TEACHING ITEMS"
scope = "National"
dateFiled = "1995-01-25"
status = "Approved by the House on 1995-02-07, transmitted to on 1995-02-08 and received by the Senate on 1995"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Antonino"
coAuthors = [ "ESCUDERO, SALVADOR III H.", "TUPAS, NIEL D.", "QUIMPO, ALLEN S.", "LIBAN, DANTE V.", "JAAFAR, NUR G.", "ECLEO, GLENDA B.", "PAREDES, CEFERINO JR. S.", "PONCE DE LEON, DAVID A.", "VIOLAGO, ELEUTERIO R.", "ALMARIO, THELMA Z.", "LOBREGAT, MA. CLARA L.", "CLAUDIO, JOVITO O.", "LOPEZ, ELIAS B.", "LAUREL-TRINIDAD, MILAGROS", "MONTEMAYOR, LEONARDO Q.", "MASTURA, MICHAEL O.", "MONTEJO, CIRILO ROY G.", "DANGWA, SAMUEL M.", "REYES, CARMENCITA O.", "DEJON, TEMISTOCLES SR. S.", "ALBANO, RODOLFO JR. B.", "LAGMAN, EDCEL C.", "VELOSO, ALBERTO S.", "ROMUALDO, PEDRO P.", "GARCIA, PABLO P.", "TAJON, MARIANO M.", "DIAZ, ANTONIO M.", "DAMASING, ERASMO B.",]
[[authorsDetail]]
name = "Antonino"
nameCode = "Antonino"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ESCUDERO, SALVADOR III H."
nameCode = "Escudero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TUPAS, NIEL D."
nameCode = "Tupas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "QUIMPO, ALLEN S."
nameCode = "Quimpo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "JAAFAR, NUR G."
nameCode = "Jaafar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ECLEO, GLENDA B."
nameCode = "Ecleo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PAREDES, CEFERINO JR. S."
nameCode = "Paredes"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PONCE DE LEON, DAVID A."
nameCode = "Ponce De Leon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VIOLAGO, ELEUTERIO R."
nameCode = "Violago"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALMARIO, THELMA Z."
nameCode = "Almario"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOBREGAT, MA. CLARA L."
nameCode = "Lobregat"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CLAUDIO, JOVITO O."
nameCode = "Claudio"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOPEZ, ELIAS B."
nameCode = "Lopez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAUREL-TRINIDAD, MILAGROS"
nameCode = "Laurel-trinidad"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = "Montemayor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MASTURA, MICHAEL O."
nameCode = "Mastura"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEJO, CIRILO ROY G."
nameCode = "Montejo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DANGWA, SAMUEL M."
nameCode = "Dangwa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "REYES, CARMENCITA O."
nameCode = "Reyes"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEJON, TEMISTOCLES SR. S."
nameCode = "Dejon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALBANO, RODOLFO JR. B."
nameCode = "Albano"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAGMAN, EDCEL C."
nameCode = "Lagman"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VELOSO, ALBERTO S."
nameCode = "Veloso"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMUALDO, PEDRO P."
nameCode = "Romualdo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GARCIA, PABLO P."
nameCode = "Garcia"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAJON, MARIANO M."
nameCode = "Tajon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DIAZ, ANTONIO M."
nameCode = "Diaz"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DAMASING, ERASMO B."
nameCode = "Damasing"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1995-01-26"

[[motherBills]]
bill_no = "HB13491"
flag = "S"

[[substitutedBills]]
bill_no = "HB13491"
flag = "S"

[firstReading]
id = 133079
congress = 9
bill_no = "HB14470"
report = "01109"
referral = "0532"
ref_name = "RULES"
sub_name = "EDUCATION AND CULTURE"
recomm = "APPROVAL"
date_read = "1995-01-26"
date_ob = "1995-01-26"
date_cal = "1995-01-26"
date_unass = "1995-01-26"
date_report = "1995-01-25"

[secondReading]
id = 20036
congress = 9
bill_no = "HB14470"
date_calendared = "1995-01-26"
date_approved = "1995-01-31"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 2250
congress = 9
bill_no = "HB14470"
date_dist = "1995-02-02"
date_adopt = "1995-02-07"
no_yeas = 145
no_nays = 0
no_abstent = 0
date_trans = "1995-02-08"
date_rec = "1995-02-08"
