billNumber = "HB14475"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB14475"
lastScraped = "2025-09-22T00:25:57.302465"
title = "HB14475"
longTitle = "AN ACT CREATING BARANGAY WEST FAIRVIEW, SECOND DISTRICT, IN QUEZON CITY"
scope = "Local"
dateFiled = "1995-01-26"
status = "Approved by the House on 1995-02-16, transmitted to on 1995-02-17 and received by the Senate on 1995"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Liban"
coAuthors = [ "ALFELOR, CIRIACO R.", "MONTEMAYOR, LEONARDO Q.", "LOCAL GOVERNMENT",]
[[authorsDetail]]
name = "Liban"
nameCode = "Liban"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ALFELOR, CIRIACO R."
nameCode = "Alfelor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONTEMAYOR, LEONARDO Q."
nameCode = "Montemayor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOCAL GOVERNMENT"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "1995-02-06"

[[motherBills]]
bill_no = "HB03399"
flag = "S"

[[substitutedBills]]
bill_no = "HB03399"
flag = "S"

[firstReading]
id = 133084
congress = 9
bill_no = "HB14475"
report = "01114"
referral = "0532"
ref_name = "RULES"
sub_name = "LOCAL GOVERNMENT"
recomm = "APPROVAL"
date_read = "1995-02-06"
date_ob = "1995-02-06"
date_cal = "1995-02-06"
date_unass = "1995-02-06"
date_report = "1995-01-26"

[secondReading]
id = 20039
congress = 9
bill_no = "HB14475"
remarks = "Considered the Explanatory Note as the Sponsorship Speech"
date_approved = "1995-02-09"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 2253
congress = 9
bill_no = "HB14475"
date_dist = "1995-02-13"
date_adopt = "1995-02-16"
no_yeas = 151
no_nays = 0
no_abstent = 0
date_trans = "1995-02-17"
date_rec = "1995-02-17"
