billNumber = "HB14242"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HB14242"
lastScraped = "2025-09-22T00:25:57.246712"
title = "HB14242"
longTitle = "AN ACT GRANTING THE KUMINTANG BROADCASTING SYSTEM A FRANCHISE TO ESTABLISH, MAINTAIN AND OPERATE FOR COMMERCIAL PURPOSES A RADIO/TELEVISIO N BROADCASTING STATION IN THE PHILIPPINES"
scope = "National"
dateFiled = "1994-12-01"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 1994-12-06"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Recto, Ralph G."
[[authorsDetail]]
name = "Recto, Ralph G."
nameCode = "Recto"
date = ""
sequence = 0

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "1994-12-06"

[firstReading]
id = 132851
congress = 9
bill_no = "HB14242"
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
date_read = "1994-12-06"
