billNumber = "HR00323"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HR00323"
lastScraped = "2025-09-22T00:25:57.424664"
title = "HR00323"
longTitle = "RESOLUTION EXPRESSING THE SENSE OF THE HOUSE OF REPRESENTATIVES TO CONGRATULATE MR. RAFAEL 'PAENG' V. NEPOMUCENO FOR HAVING WON THE WORLD CUP BOWLING TITLE FOR A RECORD THIRD TIME IN LE MANS, FRANCE"
scope = "Local"
dateFiled = "1992-11-10"
status = "Substituted by HR00342"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Recto, Ralph G."
coAuthors = [ "LIBAN, DANTE V.",]
[[authorsDetail]]
name = "Recto, Ralph G."
nameCode = "Recto"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LIBAN, DANTE V."
nameCode = "Liban"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "primary"
referralCode = "0543"
dateRead = "1992-11-16"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 133635
congress = 9
bill_no = "HR00323"
referral = "0543"
ref_name = "YOUTH AND SPORTS DEVELOPMENT"
sub_name = ""
date_read = "1992-11-16"
