billNumber = "HR00253"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HR00253"
lastScraped = "2025-09-22T00:25:57.412501"
title = "HR00253"
longTitle = "RESOLUTION DIRECTING THE COMMITTEES ON SOCIAL SERVICES, PUBLIC WORKS AND HIGHWAYS, TO URGE HIS EXCELLENCY PRESIDENT FIDEL V. RAMOS, IN AID OF LEGISLATION, TO STOP ALL ACTIVITIES ABOUT LAHAR IN ORDER TO SAVE MEAGER RESOURCES FROM BEING DISSIPATED ONINEFFECTIVE WORK, AND TO DEVOTE THE MONEY INTENDED FOR MT. PINATUBO VICTIMS TO RESETTLING THEM AND PROVIDING THEM WITH LIVELIHOOD PROJECTS SO THAT THE GOVERNMENT WILL NOT HAVE TO CONTINUE APPROPRIATING MONEY TO THE PREJUDICE OF THE REST THE COUNTRY"
scope = "National"
dateFiled = "1992-10-13"
status = "Pending with the Committee on SOCIAL SERVICES since 1992-10-15"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ty"
[[authorsDetail]]
name = "Ty"
nameCode = "Ty"
date = ""
sequence = 0

[[committee]]
name = "SOCIAL SERVICES"
type = "primary"
referralCode = "0535"
dateRead = "1992-10-15"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "secondary"
referralCode = "0530"

[firstReading]
id = 133565
congress = 9
bill_no = "HR00253"
referral = "0535"
ref_name = "SOCIAL SERVICES"
sub_name = ""
date_read = "1992-10-15"
