billNumber = "HR00631"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HR00631"
lastScraped = "2025-09-22T00:25:57.481635"
title = "HR00631"
longTitle = "RESOLUTION REQUESTING THE PHILIPPINE VETERANS AFFAIRS OFFICE NOT TO DELAY THE MONTHLY CHECKS FOR VETERANS AND TO RELEASE THE MONTHLY VETERANS CHECKS ON THE MONTH AS IT FALLS DUE"
scope = "National"
dateFiled = "1993-05-18"
status = "Pending with the Committee on  since 1993-05-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Dureza"
[[authorsDetail]]
name = "Dureza"
nameCode = "Dureza"
date = ""
sequence = 0

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 133943
congress = 9
bill_no = "HR00631"
referral = "A506"
ref_name = ""
sub_name = ""
date_read = "1993-05-25"
