billNumber = "HR00642"
billType = "HB"
congress = 9
apiCongressId = 9
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=9&q=HR00642"
lastScraped = "2025-09-22T00:25:57.483920"
title = "HR00642"
longTitle = "RESOLUTION DIRECTING THE HOUSE COMMITTEE ON HOUSING TO CONDUCT AN INVESTIGATION, IN AID OF LEGISLATION, INTO THE QUESTIONABLE DELAY AND ALLEGED IRREGULARITIES SURROUNDING THE PROGRAMMING OF THE REBEL RETURNEES RESETTLEMENT HOUSING PROJECT IN THE MUNICIPALITY OF STA. RITA, PROVINCE OF SAMAR, AND TO INITIATE THE NECESSARY REMEDIAL MEASURES RELATING THERETO"
scope = "Local"
dateFiled = "1993-05-27"
status = "Pending with the Committee on HOUSING AND URBAN DEVELOPMENT since 1993-06-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Figueroa, Catalino V."
[[authorsDetail]]
name = "Figueroa, Catalino V."
nameCode = "Figueroa"
date = ""
sequence = 0

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "primary"
referralCode = "0518"
dateRead = "1993-06-02"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 133954
congress = 9
bill_no = "HR00642"
comm_act = "Change of referral from the Committee on Rules(J.10 7, p.219)"
referral = "0518"
ref_name = "HOUSING AND URBAN DEVELOPMENT"
sub_name = ""
date_read = "1993-06-02"
