billNumber = "HBN-09199"
billType = "HBN"
congress = 17
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=17&q=HBN-9199"
lastScraped = "2025-09-20T23:50:56.081281"
title = "HUMAN RIGHTS DEFENDERS PROTECTION ACT"
longTitle = "AN ACT DEFINING THE RIGHTS AND FUNDAMENTAL FREEDOMS OF HUMAN RIGHTS DEFENDERS, DECLARING STATE RESPONSIBILITIES, AND INSTITUTING EFFECTIVE MECHANISMS FOR THE PROTECTION AND PROMOTION OF THESE RIGHTS AND FREEDOMS"
scope = "National"
subject = [ "Human Rights",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3019327013!.pdf"
pdfFileName = "HBN-9199 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/4/2019"
action = "Sent to the Senate requesting for concurrence;"

[status]
status = "Pending First Reading"
date = "6/4/2019"
