billNumber = "SBN-01118"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-1118"
lastScraped = "2025-09-20T21:09:17.506020"
title = "GUIDELINES FOR THE OPERATION AND MAINTENANCE OF DORMITORIES AND BOARDING HOUSES"
filedDate = "October 14, 2019"
author = "Revilla Jr., Ramon Bong"
longTitle = "AN ACT ESTABLISHING A COMPREHENSIVE AND INTEGRATED NATIONAL POLICY AND PROGRAM GUIDELINES FOR THE OPERATION AND MAINTENANCE OF DORMITORIES AND BOARDING HOUSES, PROVIDING PENALTIES THEREFOR, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Dormitories", "Boarding Houses",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3170428554!.pdf"
pdfFileName = "SBN-1118 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "10/14/2019"
action = "Introduced by Senator RAMON BONG REVILLA JR.;"

[[legislativeHistory]]
date = "11/5/2019"
action = "Read on First Reading and Referred to the Committee(s) on URBAN PLANNING, HOUSING AND RESETTLEMENT; and LOCAL GOVERNMENT;"

[[legislativeHistory]]
date = "3/2/2020"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "3/5/2020"
action = "Conducted TECHNICAL WORKING GROUP;"

[status]
status = "Pending in the Committee"
date = "11/5/2019"

[committee]
name = "Urban Planning, Housing and Resettlement"
type = "primary"
