billNumber = "SBN-00079"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-79"
lastScraped = "2025-09-20T21:04:21.620765"
title = "PERMANENT ITEM FOR DISASTER RISK OFFICER IN EVERY LOCAL GOVERNMENT UNIT"
filedDate = "July 1, 2019"
author = "Revilla Jr., Ramon Bong"
longTitle = "AN ACT AMENDING TITLE V - BOOK III OF REPUBLIC ACT 7160, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991, PROPOSING A PERMANENT ITEM FOR A DISASTER OFFICER IN EVERY LOCAL GOVERNMENT UNIT"
scope = "National"
subject = [ "Local Government Code (R.A.No. 7160)", "Disaster Risk Officer",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3030927136!.pdf"
pdfFileName = "SBN-79, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/1/2019"
action = "Introduced by Senator RAMON A. REVILLA JR.;"

[[legislativeHistory]]
date = "7/23/2019"
action = "Read on First Reading and Referred to the Committee on LOCAL GOVERNMENT;"

[[legislativeHistory]]
date = "2/18/2020"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Pending in the Committee"
date = "7/23/2019"

[committee]
name = "Local Government"
type = "primary"
