billNumber = "SBN-01228"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-1228"
lastScraped = "2025-09-20T21:09:45.510191"
title = "MANDATORY EVACUATION CENTER ACT OF 2019"
filedDate = "December 10, 2019"
author = "Go, Christopher Lawrence T."
longTitle = "AN ACT ESTABLISHING A MANDATORY EVACUATION CENTER IN ALL CITIES, PROVINCES AND MUNICIPALITIES, APPROPRIATING FUNDS THEREFOR"
scope = "National"
subject = [ "Evacuation Center",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3201128862!.pdf"
pdfFileName = "SBN-1228 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "12/10/2019"
action = "Introduced by Senator CHRISTOPHER LAWRENCE T. GO;"

[[legislativeHistory]]
date = "12/11/2019"
action = "Read on First Reading and Referred to the Committee(s) on NATIONAL DEFENSE AND SECURITY, PEACE, UNIFICATION AND RECONCILIATION; PUBLIC WORKS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "12/11/2019"

[committee]
name = "National Defense and Security, Peace, Unification and Reconciliation"
type = "primary"
