billNumber = "SBN-00852"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-852"
lastScraped = "2025-09-20T21:07:56.671939"
title = "NATIONAL SIGHT STRATEGY PLAN ACT"
filedDate = "August 1, 2019"
author = "De Lima, Leila M."
longTitle = "AN ACT TO ESTABLISH THE NATIONAL SIGHT STRATEGY PLAN"
scope = "National"
subject = [ "Sight Strategy Plan", "Vision Care",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3122328123!.pdf"
pdfFileName = "SBN-852 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/1/2019"
action = "Introduced by Senator LEILA M. DE LIMA;"

[[legislativeHistory]]
date = "8/19/2019"
action = "Read on First Reading and Referred to the Committee(s) on HEALTH AND DEMOGRAPHY; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/19/2019"

[committee]
name = "Health and Demography"
type = "primary"
