billNumber = "SBN-03549"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-3549"
lastScraped = "2025-09-20T23:49:34.956319"
title = "MEDICAL PAROLE ACT OF 2009"
filedDate = "December 7, 2009"
author = "Defensor Santiago, Miriam"
longTitle = "AN ACT PROVIDING FOR MEDICAL PAROLE TO QUALIFIED PRISONERS AND SETTING RULES ON THE GRANT THEREOF"
scope = "National"
subject = [ "Prisoners",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1316011762!.pdf"
pdfFileName = "SBN-3549 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "12/7/2009"
action = "Introduced by Senator MIRIAM DEFENSOR SANTIAGO;"

[[legislativeHistory]]
date = "12/7/2009"
action = "Read on First Reading and Referred to the Committee on JUSTICE AND HUMAN RIGHTS;"

[status]
status = "Pending in the Committee"
date = "12/7/2009"

[committee]
name = "Justice and Human Rights"
type = "primary"
