billNumber = "SBN-02622"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-2622"
lastScraped = "2025-09-20T23:38:39.088153"
title = "SUPPLEMENTAL APPROPRIATION"
filedDate = "September 16, 2008"
author = "Roxas, Mar"
longTitle = "AN ACT APPROPRIATING THE SUM OF TWENTY BILLION PESOS (P20,000,000,000.00) AS SUPPLEMENTAL APPROPRIATION FOR THE IMPLEMENTATION OF RELIEF OPERATIONS, RECONSTRUCTION AND REHABILITATION OF THE PROVINCES OF ILOILO, AKLAN, CAPIZ, ANTIQUE, AND ILOILO CITY, PANAY ISLAND, BACOLOD CITY, AND PROVINCES OF NEGROS OCCIDENTAL AND GUIMARAS WHICH SUFFERED DEVASTATION BROUGHT ABOUT BY TYPHOON FRANK, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Supplemental Appropriation", "Paglaum Fund",]
pdfUrl = "https://web.senate.gov.ph/lisdata/84357633!.pdf"
pdfFileName = "SBN-2622 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "9/16/2008"
action = "Introduced by Senator MAR ROXAS;"

[[legislativeHistory]]
date = "9/17/2008"
action = "Read on First Reading and Referred to the Committee on RULES;"

[[legislativeHistory]]
date = "1/28/2009"
action = "Referred to the Committee on FINANCE on motion of Senator Zubiri;"

[[legislativeHistory]]
date = "4/20/2009"
action = "Returned and submitted by the Committee on FINANCE per Committee Report No. 302, recommending that it be considered in HBN-5604;"

[[legislativeHistory]]
date = "4/21/2009"
action = "Committee Report calendared for Ordinary Business;"

[[legislativeHistory]]
date = "4/21/2009"
action = "CONSIDERED IN HBN-5604."

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "4/21/2009"

[committee]
name = "Finance"
type = "primary"
