billNumber = "SBN-00643"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-643"
lastScraped = "2025-09-20T23:15:36.527649"
title = "BREAST IMPLANTS RESEARCH AND INFORMATION ACT"
filedDate = "July 3, 2007"
author = "Ejercito-Estrada, Jinggoy P."
longTitle = "AN ACT IDENTIFYING AND PROMOTING RESEARCH ON HEALTH IMPLICATIONS OF BREAST IMPLANTS"
scope = "National"
subject = [ "Breast Implant",]
pdfUrl = "https://web.senate.gov.ph/lisdata/48544229!.pdf"
pdfFileName = "SBN-643 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/3/2007"
action = "Introduced by Senator JINGGOY P. EJERCITO-ESTRADA;"

[[legislativeHistory]]
date = "8/28/2007"
action = "Read on First Reading and Referred to the Committee(s) on HEALTH AND DEMOGRAPHY; YOUTH, WOMEN AND FAMILY RELATIONS; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/28/2007"

[committee]
name = "Health and Demography"
type = "primary"
