billNumber = "SBN-00466"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-466"
lastScraped = "2025-09-20T23:13:23.034267"
title = "TRADING AND EXPORTING OF FLORA AND FAUNA (PROHIBITION)"
filedDate = "July 2, 2007"
author = "Ejercito-Estrada, Jinggoy P."
longTitle = "AN ACT TO ABSOLUTELY PROHIBIT THE TRADE OR EXPORT OF WILDLIFE, BOTH FLORA AND FAUNA OF WHATEVER SPECIES, WHETHER DEAD OR ALIVE, PROVIDING PENALTY THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Flora and Fauna (Trade/Export Ban)", "Wildlife/ Habitats",]
pdfUrl = "https://web.senate.gov.ph/lisdata/46713995!.pdf"
pdfFileName = "SBN-466 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/2/2007"
action = "Introduced by Senator JINGGOY P. EJERCITO-ESTRADA;"

[[legislativeHistory]]
date = "8/14/2007"
action = "Read on First Reading and Referred to the Committee(s) on ENVIRONMENT AND NATURAL RESOURCES; and AGRICULTURE AND FOOD;"

[status]
status = "Pending in the Committee"
date = "8/14/2007"

[committee]
name = "Environment and Natural Resources"
type = "primary"
