billNumber = "SBN-00196"
billType = "SBN"
congress = 16
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=16&q=SBN-196"
lastScraped = "2025-09-20T23:11:16.332610"
title = "PHILIPPINE HIGH SCHOOL FOR SPORTS (PHSS) ACT"
filedDate = "July 1, 2013"
author = "Angara, Juan Edgardo \"Sonny\" M."
longTitle = "AN ACT CREATING AND ESTABLISHING THE PHILIPPINE HIGH SCHOOL FOR SPORTS"
scope = "National"
subject = [ "Philippine High School for Sports (PHSS)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1602213259!.pdf"
pdfFileName = "SBN-196 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/1/2013"
action = "Introduced by Senator JUAN EDGARDO 'SONNY' M. ANGARA;"

[[legislativeHistory]]
date = "7/29/2013"
action = "Read on First Reading and Referred to the Committee(s) on EDUCATION, ARTS AND CULTURE; GAMES, AMUSEMENT AND SPORTS; WAYS AND MEANS and FINANCE;"

[[legislativeHistory]]
date = "9/19/2013"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Pending in the Committee"
date = "7/29/2013"

[committee]
name = "Education, Arts and Culture"
type = "primary"
