billNumber = "SBN-00005"
billType = "SBN"
congress = 16
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=16&q=SBN-5"
lastScraped = "2025-09-20T23:08:54.209214"
title = "LOCAL GOVERNMENT CODE OF 1991, AMENDMENT"
filedDate = "July 1, 2013"
author = "Sotto III, Vicente C."
longTitle = "AN ACT AMENDING SECTION 150 OF REPUBLIC ACT 7160, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991"
scope = "National"
subject = [ "Local Government Code (R.A.No. 7160)", "Taxes/Taxation",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1581313049!.pdf"
pdfFileName = "SBN-5, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/1/2013"
action = "Introduced by Senator VICENTE C. SOTTO III;"

[[legislativeHistory]]
date = "7/23/2013"
action = "Read on First Reading and Referred to the Committee(s) on LOCAL GOVERNMENT and WAYS AND MEANS;"

[status]
status = "Pending in the Committee"
date = "7/23/2013"

[committee]
name = "Local Government"
type = "primary"
