billNumber = "SBN-00682"
billType = "SBN"
congress = 16
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=16&q=SBN-682"
lastScraped = "2025-09-20T23:17:13.298657"
title = "INVENTORS AND INVENTION INCENTIVES ACT OF 2013"
filedDate = "July 9, 2013"
author = "Legarda, Loren B., Escudero, Francis \"Chiz\" G."
longTitle = "AN ACT CREATING A PHILIPPINE INVENTORS COMMISSION, DEFINING ITS POWERS, FUNCTIONS AND DUTIES, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Inventors and Inventions",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1664313882!.pdf"
pdfFileName = "SBN-682 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/9/2013"
action = "Introduced by Senator LOREN B. LEGARDA;"

[[legislativeHistory]]
date = "8/7/2013"
action = "Read on First Reading and Referred to the Committee(s) on SCIENCE AND TECHNOLOGY; WAYS AND MEANS; and FINANCE;"

[[legislativeHistory]]
date = "1/23/2014"
action = "By virtue of the approved motion of Senator Cayetano (A.) on the process of coauthorship on January 21, 2014, letter of Senator FRANCIS 'CHIZ' G. ESCUDERO dated October 16, 2013, requesting Senator Legarda that he be made coauthor of this Bill, received by the LBIS;"

[status]
status = "Pending in the Committee"
date = "8/7/2013"

[committee]
name = "Science and Technology"
type = "primary"
