billNumber = "HB00551"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB00551"
lastScraped = "2025-09-21T23:55:20.175082"
title = "HB00551"
longTitle = "AN ACT INCREASING THE SOCIAL PENSION OF INDIGENT SENIOR CITIZENS AND APPROPRIATING FUNDS THEREFOR, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 7432 ENTITLED, “AN ACT TO MAXIMIZE THE CONTRIBUTION OF SENIOR CITIZENS TO NATION BUILDING, GRANT BENEFITS AND SPECIAL PRIVILEGES AND FOR OTHER PURPOSES,” AS AMENDED"
scope = "National"
dateFiled = "2022-06-30"
status = "Pending with the Committee on SENIOR CITIZENS since 2022-07-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB00551.pdf"
fileSize = 2732539
author = "Castro, France L."
coAuthors = [ "RIVERA, BONG", "DIONISIO, ERNESTO JR. M.",]
[[authorsDetail]]
name = "Castro, France L."
nameCode = "Castro (F.)"
date = "2022-06-30"
sequence = 1

[[authorsDetail]]
name = "Brosas, Arlene D."
nameCode = "Brosas"
date = "2022-06-30"
sequence = 2

[[authorsDetail]]
name = "Manuel, Raoul Danniel A."
nameCode = "Manuel"
date = "2022-06-30"
sequence = 3

[[coAuthorsDetail]]
name = "RIVERA, BONG"
nameCode = "Rivera"
date = "2022-11-14"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DIONISIO, ERNESTO JR. M."
nameCode = "Dionisio"
date = "2024-07-29"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "SENIOR CITIZENS"
type = "primary"
referralCode = "I505"
dateRead = "2022-07-27"

[[committee]]
name = "SENIOR CITIZENS"
type = "principal"
referralCode = "I505"

[firstReading]
id = 5470
congress = 19
bill_no = "HB00551"
report = ""
comm_act = ""
referral = "I505"
ref_name = "SENIOR CITIZENS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-07-27"
