billNumber = "HB00217"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB00217"
lastScraped = "2025-09-21T23:55:20.108372"
title = "HB00217"
longTitle = "AN ACT TO PROTECT WORKERS AND THEIR FAMILIES FROM THE HAZARDS OF WORKING IN AGRICULTURAL SITES"
scope = "National"
dateFiled = "2022-06-30"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 2022-07-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB00217.pdf"
fileSize = 1916731
author = "SUANSING, MIKAELA ANGELA B."
coAuthors = [ "OAMINAL, ANDO",]
[[authorsDetail]]
name = "SUANSING, MIKAELA ANGELA B."
nameCode = "Suansing (M.A.)"
date = "2022-06-30"
sequence = 1

[[authorsDetail]]
name = "Suansing, Horacio Jr. P."
nameCode = "Suansing (H.)"
date = "2022-06-30"
sequence = 2

[[coAuthorsDetail]]
name = "OAMINAL, ANDO"
nameCode = "Oaminal"
date = "2022-11-14"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "E505"
dateRead = "2022-07-26"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 5136
congress = 19
bill_no = "HB00217"
report = ""
comm_act = ""
referral = "E505"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-07-26"
