billNumber = "HB00489"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB00489"
lastScraped = "2025-09-21T23:55:20.162914"
title = "HB00489"
longTitle = "AN ACT TO ADDRESS THE SOCIAL HEALTH INSURANCE CRISIS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2022-06-30"
status = "Substituted by HB11357"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB00489.pdf"
fileSize = 3009320
author = "Quimbo, Stella Luz A."
coAuthors = [ "ARENAS, MA. RACHEL J.", "REYES, RAY FLORENCE T.", "RIVERA, BONG",]
[[authorsDetail]]
name = "Quimbo, Stella Luz A."
nameCode = "Quimbo"
date = "2022-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "ARENAS, MA. RACHEL J."
nameCode = "Arenas"
date = "2022-09-05"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "REYES, RAY FLORENCE T."
nameCode = "Reyes"
date = "2022-09-08"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "RIVERA, BONG"
nameCode = "Rivera"
date = "2022-09-22"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2022-07-26"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 5408
congress = 19
bill_no = "HB00489"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-07-26"
