billNumber = "HB00343"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB00343"
lastScraped = "2025-09-21T23:55:20.130157"
title = "HB00343"
longTitle = "AN ACT MANDATING MOVIE THEATER OPERATORS NATIONWIDE TO RUN MTRCB APPROVED AND RATED LOCAL MOVIES TO SUPPORT LOCAL MOVIE PRODUCERS AND PROMOTE ORIGINAL FILIPINO MOVIES"
scope = "National"
dateFiled = "2022-06-30"
status = "Pending with the Committee on PUBLIC INFORMATION since 2022-07-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB00343.pdf"
fileSize = 990896
author = "Fernandez, Dan S."
[[authorsDetail]]
name = "Fernandez, Dan S."
nameCode = "Fernandez"
date = "2022-06-30"
sequence = 1

[[committee]]
name = "PUBLIC INFORMATION"
type = "primary"
referralCode = "0528"
dateRead = "2022-07-26"

[[committee]]
name = "PUBLIC INFORMATION"
type = "principal"
referralCode = "0528"

[firstReading]
id = 5262
congress = 19
bill_no = "HB00343"
report = ""
comm_act = ""
referral = "0528"
ref_name = "PUBLIC INFORMATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-07-26"
