billNumber = "HB00768"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB00768"
lastScraped = "2025-09-21T23:55:20.217867"
title = "HB00768"
longTitle = "AN ACT DECLARING JORDAN WATERFALLS IN THE CITY OF\r\nBAYUGAN, PROVINCE OF AGUSAN DEL SUR AS AN ECOTOURISM\r\nSITE AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2022-07-01"
status = "Substituted by HB07615"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB00768.pdf"
fileSize = 417804
author = "BASCUG, ALFELITO \"ALFEL\" M."
[[authorsDetail]]
name = "BASCUG, ALFELITO \"ALFEL\" M."
nameCode = "Bascug"
date = "2022-07-01"
sequence = 1

[[authorsDetail]]
name = "PLAZA, EDDIEBONG G."
nameCode = "Plaza"
date = "2022-07-01"
sequence = 2

[[committee]]
name = "TOURISM"
type = "primary"
referralCode = "0538"
dateRead = "2022-07-27"

[[committee]]
name = "TOURISM"
type = "principal"
referralCode = "0538"

[firstReading]
id = 5687
congress = 19
bill_no = "HB00768"
report = ""
comm_act = ""
referral = "0538"
ref_name = "TOURISM"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-07-27"
