billNumber = "HB01775"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB01775"
lastScraped = "2025-09-21T23:55:20.385192"
title = "HB01775"
longTitle = "AN ACT EXPANDING THE INVOLUNTARY SEPARATION BENEFIT, AMENDING SECTION 14-B OF THE REPUBLIC ACT NO. 11199, OTHERWISE KNOWN AS THE “SOCIAL SECURITY ACT OF 2018.”"
scope = "National"
dateFiled = "2022-07-11"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 2022-08-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB01775.pdf"
fileSize = 338249
author = "Pimentel, Johnny Ty"
[[authorsDetail]]
name = "Pimentel, Johnny Ty"
nameCode = "Pimentel"
date = "2022-07-11"
sequence = 1

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2022-08-02"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "principal"
referralCode = "0515"

[firstReading]
id = 6694
congress = 19
bill_no = "HB01775"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-02"
