billNumber = "HB01922"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB01922"
lastScraped = "2025-09-21T23:55:20.410097"
title = "HB01922"
longTitle = "AN ACT MANDATING THE DEPARTMENT OF HEALTH TO ASSIGN AT LEAST ONE (1) BARANGAY HEALTH WORKER TO EACH FAMILY INCREASING THEIR SALARIES AND BENEFITS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2022-07-13"
status = "Substituted by HB06557"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB01922.pdf"
fileSize = 250983
author = "Delos Santos, Alfred C."
[[authorsDetail]]
name = "Delos Santos, Alfred C."
nameCode = "Delos Santos"
date = "2022-07-13"
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2022-08-02"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 6841
congress = 19
bill_no = "HB01922"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-02"
