billNumber = "HB01923"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB01923"
lastScraped = "2025-09-21T23:55:20.410230"
title = "HB01923"
longTitle = "AN ACT INTEGRATING BASIC MEDICAL AND HEALTH TRAINING AND RISK REDUCTION NATIONAL EMERGENCY OR DISASTER AWARENESS PREPAREDNESS AND RESPONSE IN THE CURRICULUM OF SCHOOLS AND INSTITUTIONS OF LEARNING"
scope = "National"
dateFiled = "2022-07-13"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2022-08-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB01923.pdf"
fileSize = 253347
author = "Delos Santos, Alfred C."
[[authorsDetail]]
name = "Delos Santos, Alfred C."
nameCode = "Delos Santos"
date = "2022-07-13"
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2022-08-02"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "secondary"
referralCode = "C502"

[firstReading]
id = 6842
congress = 19
bill_no = "HB01923"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-02"
