billNumber = "HB02753"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB02753"
lastScraped = "2025-09-21T23:55:20.557858"
title = "HB02753"
longTitle = "AN ACT MANDATING THE ESTABLISHMENT AND MAINTENANCE OF A\r\nRAINWATER HARVESTING FACILITY IN ALL NEW INSTITUTIONAL,\r\nCOMMERCIAL, AND RESIDENTIAL DEVELOPMENT PROJECTS IN METRO MANILA"
scope = "National"
dateFiled = "2022-07-29"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2022-08-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB02753.pdf"
fileSize = 357544
author = "Delos Santos, Alfred C."
coAuthors = [ "RIVERA, BONG",]
[[authorsDetail]]
name = "Delos Santos, Alfred C."
nameCode = "Delos Santos"
date = "2022-07-29"
sequence = 1

[[coAuthorsDetail]]
name = "RIVERA, BONG"
nameCode = "Rivera"
date = "2023-03-27"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2022-08-08"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 7672
congress = 19
bill_no = "HB02753"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-08"
