billNumber = "HB02279"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB02279"
lastScraped = "2025-09-21T23:55:20.473594"
title = "HB02279"
longTitle = "AN ACT STRENGTHENING ACCESS TO CREDIT OF MICRO, SMALL, AND\r\nMEDIUM ENTERPRISES, AMENDING FOR THE PURPOSE,\r\nREPUBLIC ACT NO. 6977, AS AMENDED, OTHERWISE KNOWN AS\r\nTHE “MAGNA CARTA FOR MICRO, SMALL AND MEDIUM\r\nENTERPRISES” AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2022-07-25"
status = "Substituted by HB10049"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB02279.pdf"
fileSize = 285549
author = "VILLANUEVA, EDUARDO \"BRO. EDDIE\" C."
[[authorsDetail]]
name = "VILLANUEVA, EDUARDO \"BRO. EDDIE\" C."
nameCode = "Villanueva (E)"
date = "2022-07-25"
sequence = 1

[[committee]]
name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
type = "primary"
referralCode = "E510"
dateRead = "2022-08-02"

[[committee]]
name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
type = "principal"
referralCode = "E510"

[firstReading]
id = 7198
congress = 19
bill_no = "HB02279"
report = ""
comm_act = ""
referral = "E510"
ref_name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-02"
