billNumber = "HB02428"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB02428"
lastScraped = "2025-09-21T23:55:20.499219"
title = "HB02428"
longTitle = "AN ACT ESTABLISHING MULTI-SPECIES MARINE HATCHERY IN BARANGAY BUGO IN THE 2ND DISTRICT OF CAGAYAN DE ORO CITY AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2022-07-27"
status = "Pending with the Committee on AQUACULTURE AND FISHERIES RESOURCES since 2022-08-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB02428.pdf"
fileSize = 83340
author = "RODRIGUEZ, RUFUS B."
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez (R.)"
date = "2022-07-27"
sequence = 1

[[committee]]
name = "AQUACULTURE AND FISHERIES RESOURCES"
type = "primary"
referralCode = "E506"
dateRead = "2022-08-03"

[[committee]]
name = "AQUACULTURE AND FISHERIES RESOURCES"
type = "principal"
referralCode = "E506"

[firstReading]
id = 7347
congress = 19
bill_no = "HB02428"
report = ""
comm_act = ""
referral = "E506"
ref_name = "AQUACULTURE AND FISHERIES RESOURCES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-03"
