billNumber = "HB02029"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB02029"
lastScraped = "2025-09-21T23:55:20.428339"
title = "HB02029"
longTitle = "AN ACT PROVIDING FOR THE DEVELOPMENT OF SUSTAINABLE CITIES AND COMMUNITIES IN THE COUNTRY, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2022-07-18"
status = "Substituted by HB06715"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB02029.pdf"
fileSize = 1818416
author = "GUINTU, HOWARD A."
[[authorsDetail]]
name = "GUINTU, HOWARD A."
nameCode = "Guintu"
date = "2022-07-18"
sequence = 1

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "primary"
referralCode = "0518"
dateRead = "2022-08-02"

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "principal"
referralCode = "0518"

[firstReading]
id = 6948
congress = 19
bill_no = "HB02029"
report = ""
comm_act = ""
referral = "0518"
ref_name = "HOUSING AND URBAN DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-02"
