billNumber = "HB02974"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB02974"
lastScraped = "2025-09-21T23:55:20.593942"
title = "HB02974"
longTitle = "AN ACT PROTECTING THE RIGHTS OF INTERNALLY DISPLACED\r\nPERSONS"
scope = "National"
dateFiled = "2022-08-02"
status = "Substituted by HB08269"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB02974.pdf"
fileSize = 5494683
author = "ADIONG, ZIAUR-RAHMAN \"ZIA\" ALONTO"
[[authorsDetail]]
name = "ADIONG, ZIAUR-RAHMAN \"ZIA\" ALONTO"
nameCode = "Adiong"
date = "2022-08-02"
sequence = 1

[[authorsDetail]]
name = "BALINDONG, YASSER ALONTO"
nameCode = "Balindong"
date = "2022-08-02"
sequence = 2

[[committee]]
name = "HUMAN RIGHTS"
type = "primary"
referralCode = "E507"
dateRead = "2022-08-08"

[[committee]]
name = "HUMAN RIGHTS"
type = "principal"
referralCode = "E507"

[firstReading]
id = 7893
congress = 19
bill_no = "HB02974"
report = ""
comm_act = ""
referral = "E507"
ref_name = "HUMAN RIGHTS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-08"
