billNumber = "HB03122"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB03122"
lastScraped = "2025-09-21T23:55:20.617317"
title = "HB03122"
longTitle = "AN ACT GRANTING BENEFITS AND INCENTIVES TO ACCREDITED BANTAY DAGAT AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2022-08-03"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2022-11-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB03122.pdf"
fileSize = 336434
author = "Morden, Michael M."
[[authorsDetail]]
name = "Morden, Michael M."
nameCode = "Morden"
date = "2022-08-03"
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2022-08-09"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 8041
congress = 19
bill_no = "HB03122"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2022-11-23"
date_read = "2022-08-09"
