billNumber = "HB03378"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB03378"
lastScraped = "2025-09-21T23:55:20.662175"
title = "HB03378"
longTitle = "AN ACT ESTABLISHING A CREDIT ASSISTANCE PROGRAM FOR OVERSEAS FILIPINO WORKERS"
scope = "National"
dateFiled = "2022-08-09"
status = "Measure approved by the Committee on 2022-10-13"
statusOrder = 4.33
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB03378.pdf"
fileSize = 823054
author = "REVILLA, BRYAN B."
[[authorsDetail]]
name = "REVILLA, BRYAN B."
nameCode = "Revilla (B.)"
date = "2022-08-09"
sequence = 1

[[authorsDetail]]
name = "MERCADO-REVILLA, LANI"
nameCode = "Mercado-Revilla"
date = "2022-08-09"
sequence = 2

[[authorsDetail]]
name = "REVILLA, RAMON JOLO III B."
nameCode = "Revilla (R.J.)"
date = "2022-08-09"
sequence = 3

[[committee]]
name = "OVERSEAS WORKERS AFFAIRS"
type = "primary"
referralCode = "E513"
dateRead = "2022-08-15"

[[committee]]
name = "OVERSEAS WORKERS AFFAIRS"
type = "principal"
referralCode = "E513"

[firstReading]
id = 8297
congress = 19
bill_no = "HB03378"
report = ""
comm_act = ""
referral = "E513"
ref_name = "OVERSEAS WORKERS AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-15"
