billNumber = "HB04819"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB04819"
lastScraped = "2025-09-21T23:55:20.920494"
title = "HB04819"
longTitle = "AN ACT AMENDING SECTION 2 OF REPUBLIC ACT 10868 OTHERWISE KNOWN AS \"AN ACT HONORING AND GRANTING ADDITIONAL BENEFITS AND PRIVELEGES TO FILIPINO CENTENARIANS, AND FOR OTHER PURPOSES\""
scope = "National"
dateFiled = "2022-09-14"
status = "Substituted by HB07535"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB04819.pdf"
fileSize = 508903
author = "Violago, Joseph Gilbert F."
[[authorsDetail]]
name = "Violago, Joseph Gilbert F."
nameCode = "Violago"
date = "2022-09-14"
sequence = 1

[[committee]]
name = "SENIOR CITIZENS"
type = "primary"
referralCode = "I505"
dateRead = "2022-09-19"

[[committee]]
name = "SENIOR CITIZENS"
type = "principal"
referralCode = "I505"

[firstReading]
id = 9738
congress = 19
bill_no = "HB04819"
report = ""
comm_act = ""
referral = "I505"
ref_name = "SENIOR CITIZENS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-09-19"
