billNumber = "HB04401"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB04401"
lastScraped = "2025-09-21T23:55:20.850857"
title = "HB04401"
longTitle = "AN ACT AMENDING REPUBLIC ACT NO. 9439 OTHERWISE KNOWN AS \"AN\r\nACT PROHIBITING THE DETENTION OF PATIENTS IN HOSPITALS AND\r\nMEDICAL CLINICS ON GROUNDS OF NONPAYMENT OF HOSPITAL BILLS OR\r\nMEDICAL EXPENSES\""
scope = "National"
dateFiled = "2022-09-05"
status = "Pending with the Committee on HEALTH since 2022-09-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB04401.pdf"
fileSize = 115591
author = "Abunda, Maria Fe R."
coAuthors = [ "VILLANUEVA, EDUARDO \"Bro. Eddie\" C.", "REGENCIA, CELSO G.", "LEE, WILBERT T.",]
[[authorsDetail]]
name = "Abunda, Maria Fe R."
nameCode = "Abunda"
date = "2022-09-05"
sequence = 1

[[coAuthorsDetail]]
name = "VILLANUEVA, EDUARDO \"Bro. Eddie\" C."
nameCode = "Villanueva (E)"
date = "2023-08-07"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "REGENCIA, CELSO G."
nameCode = "Regencia"
date = "2023-09-26"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "LEE, WILBERT T."
nameCode = "Lee"
date = "2024-09-16"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2022-09-07"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 9320
congress = 19
bill_no = "HB04401"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-09-07"
