billNumber = "HB04130"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB04130"
lastScraped = "2025-09-21T23:55:20.805541"
title = "HB04130"
longTitle = "AN ACT DECLARING APRIL 7 OF EVERY YEAR AS BARANGAY HEALTH WORKERS\r\nDAY TO BE KNOWN AS BHW DAY"
scope = "National"
dateFiled = "2022-08-30"
status = "Substituted by HB06557"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB04130.pdf"
fileSize = 323144
author = "Ongchuan, Harris Christopher M."
[[authorsDetail]]
name = "Ongchuan, Harris Christopher M."
nameCode = "Ongchuan"
date = "2022-08-30"
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2022-09-05"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 9049
congress = 19
bill_no = "HB04130"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-09-05"
