billNumber = "HB05953"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB05953"
lastScraped = "2025-09-21T23:55:21.171919"
title = "HB05953"
longTitle = "AN ACT GRANTING CIVIL SERVICE ELIGIBILITY AND NATIONAL CERTIFICATE TO OVERSEAS FILIPINO WORKERS"
scope = "National"
dateFiled = "2022-11-08"
status = "Pending with the Committee on CIVIL SERVICE AND PROFESSIONAL REGULATION since 2022-11-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB05953.pdf"
fileSize = 1402940
author = "Sakaluran, Princess Rihan M."
[[authorsDetail]]
name = "Sakaluran, Princess Rihan M."
nameCode = "Sakaluran"
date = "2022-11-08"
sequence = 1

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "primary"
referralCode = "0506"
dateRead = "2022-11-14"

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "principal"
referralCode = "0506"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "secondary"
referralCode = "C502"

[firstReading]
id = 10872
congress = 19
bill_no = "HB05953"
report = ""
comm_act = ""
referral = "0506"
ref_name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-14"
