billNumber = "HB05359"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB05359"
lastScraped = "2025-09-21T23:55:21.015893"
title = "HB05359"
longTitle = "AN ACT TO PROVIDE FOR A HOUSING PROGRAM FOR TEACHERS"
scope = "National"
dateFiled = "2022-10-03"
status = "Deliberated upon by the Mother Committee on 2024-01-24"
statusOrder = 4.21
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB05359.pdf"
fileSize = 2948205
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "RIVERA, BONG",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez (R.)"
date = "2022-10-03"
sequence = 1

[[coAuthorsDetail]]
name = "RIVERA, BONG"
nameCode = "Rivera"
date = "2024-06-10"
journalNo = "J000"
sessionNo = "2RS"

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "primary"
referralCode = "0518"
dateRead = "2022-11-07"

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "principal"
referralCode = "0518"

[firstReading]
id = 10278
congress = 19
bill_no = "HB05359"
report = ""
comm_act = ""
referral = "0518"
ref_name = "HOUSING AND URBAN DEVELOPMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-07"
