billNumber = "HB05985"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB05985"
lastScraped = "2025-09-21T23:55:21.185603"
title = "HB05985"
longTitle = "AN ACT PROVIDING FOR THE MANDATORY APPOINTMENT OF PROVINCIAL, CITY AND MUNICIPAL ENVIRONMENT AND NATURAL RESOURCES OFFICER, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 7160, AS AMENDED, OTHERWISE KNOWN AS THE \"LOCAL GOVERNMENT CODE OF 1991 \""
scope = "National"
dateFiled = "2022-11-14"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2022-11-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB05985.pdf"
fileSize = 274360
author = "Unabia, Christian S."
[[authorsDetail]]
name = "Unabia, Christian S."
nameCode = "Unabia"
date = "2022-11-14"
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2022-11-14"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 10904
congress = 19
bill_no = "HB05985"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-14"
