billNumber = "HB05652"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB05652"
lastScraped = "2025-09-21T23:55:21.118218"
title = "HB05652"
longTitle = "AN ACT PROVIDING FOR MODERNIZATION FUNDINGFOR THE PHILIPPINE FIBER INDUSTRY DEVELOPMENT AUTHORITY (PHILFIDA), INCREASING AND REORGANIZING ITS ADMINISTRATION, PROVIDING FOR A PROGRESSIVE COMMUNITY OF FIBER PRODUCERS AND ENTREPRENEURS IN AN ENVIRONMENT-FRIENDLY, ECONOMICALLY VIABLE AND GLOBALLY COMPETITIVE PHILIPPINE NATURAL FIBER INDUSTRY AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2022-10-20"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 2022-11-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB05652.pdf"
fileSize = 338991
author = "Romero, Michael L. Ph.D."
[[authorsDetail]]
name = "Romero, Michael L. Ph.D."
nameCode = "Romero"
date = "2022-10-20"
sequence = 1

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "E505"
dateRead = "2022-11-08"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 10571
congress = 19
bill_no = "HB05652"
report = ""
comm_act = ""
referral = "E505"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-08"
