billNumber = "HB05253"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB05253"
lastScraped = "2025-09-21T23:55:20.997882"
title = "HB05253"
longTitle = "AN ACT REGULATING THE AQUARIUM AQUATIC LIFE TRADE AND INDUSTRY"
scope = "National"
dateFiled = "2022-09-28"
status = "Pending with the Committee on NATURAL RESOURCES since 2022-11-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB05253.pdf"
fileSize = 308804
author = "VARGAS, PATRICK MICHAEL D."
[[authorsDetail]]
name = "VARGAS, PATRICK MICHAEL D."
nameCode = "Vargas"
date = "2022-09-28"
sequence = 1

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "0526"
dateRead = "2022-11-07"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[firstReading]
id = 10172
congress = 19
bill_no = "HB05253"
report = ""
comm_act = ""
referral = "0526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-07"
