billNumber = "HB06213"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB06213"
lastScraped = "2025-09-21T23:55:21.226249"
title = "HB06213"
longTitle = "AN ACT ESTABLISHING AN E-LIBRARY AND COMPUTER LABORATORY IN PINUKPUK ELEMENTARY SCHOOL IN BARANGAY PINUKPUK JUNCTION, MUNICIPALITY OF PINUKPUK, PROVINCE OF KALINGA AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2022-11-21"
status = "Pending with the Committee on BASIC EDUCATION AND CULTURE since 2022-11-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB06213.pdf"
fileSize = 405481
author = "Mangaoang, Allen Jesse C."
[[authorsDetail]]
name = "Mangaoang, Allen Jesse C."
nameCode = "Mangaoang"
date = "2022-11-21"
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2022-11-23"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 11132
congress = 19
bill_no = "HB06213"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-23"
