billNumber = "HB07201"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB07201"
lastScraped = "2025-09-21T23:55:21.438261"
title = "HB07201"
longTitle = "AN ACT ESTABLISHING THE SIQUIJOR SPECIAL ECONOMIC ZONE IN THE MUNICIPALITY OF MARIA, PROVINCE OF SIQUIJOR, CREATING FOR THE PURPOSE THE SIQUIJOR SPECIAL ECONOMIC ZONE AUTHORITY, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "2023-02-15"
status = "Pending with the Committee on ECONOMIC AFFAIRS since 2023-02-21"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB07201.pdf"
fileSize = 1109929
author = "VILLA, ZALDY S."
[[authorsDetail]]
name = "VILLA, ZALDY S."
nameCode = "Villa"
date = "2023-02-15"
sequence = 1

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "primary"
referralCode = "0536"
dateRead = "2023-02-21"

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "principal"
referralCode = "0536"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "secondary"
referralCode = "0539"

[firstReading]
id = 12120
congress = 19
bill_no = "HB07201"
report = ""
comm_act = ""
referral = "0536"
ref_name = "ECONOMIC AFFAIRS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-02-21"
