billNumber = "HB07880"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB07880"
lastScraped = "2025-09-21T23:55:21.602672"
title = "HB07880"
longTitle = "AN ACT DECLARING OCTOBER 24 OF EVERY YEAR A SPECIAL NON-WORKING HOLIDAY IN THE MUNICIPALITY OF ANGAT, PROVINCE OF BULACAN IN CELEBRATION OF ITS FOUNDING ANNIVERSARY TO BE KNOWN AS “ARAW NG ANGAT”"
scope = "Local"
dateFiled = "2023-04-19"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2023-05-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB07880.pdf"
fileSize = 2065421
author = "PLEYTO, SALVADOR A."
[[authorsDetail]]
name = "PLEYTO, SALVADOR A."
nameCode = "Pleyto"
date = "2023-04-19"
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2023-05-08"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 12799
congress = 19
bill_no = "HB07880"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-05-08"
