billNumber = "HB07454"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB07454"
lastScraped = "2025-09-21T23:55:21.516841"
title = "HB07454"
longTitle = "AN ACT GRANTING ADDITIONAL BENEFITS TO FILIPINO CENTENARIANS,\r\nRECOGNIZING OCTOGENARIANS AND NONAGENARIANS, AND APPROPRIATING FUNDS THEREFOR, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 10868, OTHERWISE KNOWN AS THE `CENTENARIANS ACT OF 2016´"
scope = "National"
dateFiled = "2023-03-06"
status = "Pending with the Committee on SENIOR CITIZENS since 2023-03-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB07454.pdf"
fileSize = 360922
author = "Fariñas, Rudys Caesar I G."
[[authorsDetail]]
name = "Fariñas, Rudys Caesar I G."
nameCode = "Fariñas"
date = "2023-03-06"
sequence = 1

[[committee]]
name = "SENIOR CITIZENS"
type = "primary"
referralCode = "I505"
dateRead = "2023-03-08"

[[committee]]
name = "SENIOR CITIZENS"
type = "principal"
referralCode = "I505"

[firstReading]
id = 12373
congress = 19
bill_no = "HB07454"
report = ""
comm_act = ""
referral = "I505"
ref_name = "SENIOR CITIZENS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-03-08"
