billNumber = "HB07236"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB07236"
lastScraped = "2025-09-21T23:55:21.444326"
title = "HB07236"
longTitle = "AN ACT PROMOTING AND REVITALIZING THE SALT INDUSTRY OF THE PHILIPPINES, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 8172, OTHERWISE KNOWN AS \"AN ACT FOR SALT IODIZATION NATIONWIDE (ASIN),\" PROVIDING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2023-02-21"
status = "Substituted by HB08278"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB07236.pdf"
fileSize = 3227461
author = "CUA, MIDY N."
coAuthors = [ "RIVERA, BONG", "MERCADO-REVILLA, LANI",]
[[authorsDetail]]
name = "CUA, MIDY N."
nameCode = "Cua"
date = "2023-02-21"
sequence = 1

[[coAuthorsDetail]]
name = "RIVERA, BONG"
nameCode = "Rivera"
date = "2023-08-02"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "MERCADO-REVILLA, LANI"
nameCode = "Mercado-Revilla"
date = "2024-11-06"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "E505"
dateRead = "2023-02-27"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 12155
congress = 19
bill_no = "HB07236"
report = ""
comm_act = ""
referral = "E505"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-02-27"
