billNumber = "HB08884"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB08884"
lastScraped = "2025-09-21T23:55:21.869743"
title = "HB08884"
longTitle = "AN ACT PROVIDING A COMPREHENSIVE BENEFITS PACKAGE TO MENTAL HEALTH CLIENTS UNDER PHILHEALTH´S NATIONAL HEALTH INSURANCE PROGRAM (NHIP) AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2023-08-14"
status = "Pending with the Committee on HEALTH since 2023-08-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB08884.pdf"
fileSize = 465177
author = "SUAN, LORDAN G."
coAuthors = [ "RIVERA, BONG", "REYES, RAY FLORENCE T.",]
[[authorsDetail]]
name = "SUAN, LORDAN G."
nameCode = "Suan"
date = "2023-08-14"
sequence = 1

[[coAuthorsDetail]]
name = "RIVERA, BONG"
nameCode = "Rivera"
date = "2023-10-02"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "REYES, RAY FLORENCE T."
nameCode = "Reyes"
date = "2023-11-21"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2023-08-16"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 13803
congress = 19
bill_no = "HB08884"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-08-16"
