billNumber = "HB09695"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB09695"
lastScraped = "2025-09-21T23:55:22.063537"
title = "HB09695"
longTitle = "AN ACT AMENDING REPUBLIC ACT NO. 9136, OTHERWISE KNOWN AS THE ELECTRIC POWER INDUSTRY REFORM ACT OF 2001"
scope = "National"
dateFiled = "2023-12-11"
status = "Substituted by HB11373"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB09695.pdf"
fileSize = 395506
author = "VILLANUEVA, EDUARDO \"BRO. EDDIE\" C."
coAuthors = [ "VILLAFUERTE, LUIS RAYMUND \"LRAY\" JR. F.",]
[[authorsDetail]]
name = "VILLANUEVA, EDUARDO \"BRO. EDDIE\" C."
nameCode = "Villanueva (E)"
date = "2023-12-11"
sequence = 1

[[coAuthorsDetail]]
name = "VILLAFUERTE, LUIS RAYMUND \"LRAY\" JR. F."
nameCode = "Villafuerte (L.R.)"
date = "2024-11-27"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "2023-12-12"

[[committee]]
name = "ENERGY"
type = "principal"
referralCode = "0510"

[firstReading]
id = 14614
congress = 19
bill_no = "HB09695"
report = ""
comm_act = ""
referral = "0510"
ref_name = "ENERGY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-12-12"
