billNumber = "HB09994"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB09994"
lastScraped = "2025-09-21T23:55:22.126998"
title = "HB09994"
longTitle = "AN ACT STRENGTHENING THE COMMISSION ON HUMAN RIGHTS (CHR) AS A NATIONAL HUMAN RIGHTS INSTITUTION (NHRI) AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2024-02-28"
status = "Substituted by HB11523"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB09994.pdf"
fileSize = 1033482
author = "ADIONG, ZIAUR-RAHMAN \"ZIA\" ALONTO"
[[authorsDetail]]
name = "ADIONG, ZIAUR-RAHMAN \"ZIA\" ALONTO"
nameCode = "Adiong"
date = "2024-02-28"
sequence = 1

[[committee]]
name = "HUMAN RIGHTS"
type = "primary"
referralCode = "E507"
dateRead = "2024-03-04"

[[committee]]
name = "HUMAN RIGHTS"
type = "principal"
referralCode = "E507"

[firstReading]
id = 14913
congress = 19
bill_no = "HB09994"
report = ""
comm_act = ""
referral = "E507"
ref_name = "HUMAN RIGHTS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2024-03-04"
