billNumber = "HB10772"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB10772"
lastScraped = "2025-09-21T23:55:22.343795"
title = "Improving The Delivery Of Socialized Housing Programs, Amending For The Purpose Sections 10, 18, And 20 Of Republic Act No. 7279, Otherwise Known As The “ Urban Development And Housing Act Of 1992 ”, As Amended By Republic Act No. 10884, Otherwise Known As The “ Balanced Housing Development Program Amendments ”"
longTitle = "AN ACT IMPROVING THE DELIVERY OF SOCIALIZED HOUSING PROGRAMS, AMENDING FOR THE PURPOSE SECTIONS 10, 18, AND 20 OF REPUBLIC ACT NO. 7279, OTHERWISE KNOWN AS THE \"URBAN DEVELOPMENT AND HOUSING ACT OF 1992\", AS AMENDED BY REPUBLIC ACT NO. 10884, OTHERWISE KNOWN AS THE \"BALANCED HOUSING DEVELOPMENT PROGRAM AMENDMENTS\""
scope = "National"
dateFiled = "2024-08-15"
status = "Approved by the House on 2024-09-10, transmitted to the Senate on 2024-09-12 and received by the Senate on 2024-09-12"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "LOYOLA, ROY M."
coAuthors = [ "DALIPE, MANUEL JOSE M.", "PRIMICIAS-AGABAS, MARLYN L.", "DIONISIO, ERNESTO JR. M.", "ROMUALDO, JURDIN JESUS M.", "VILLARICA, LINABELLE RUTH R.",]
[[authorsDetail]]
name = "LOYOLA, ROY M."
nameCode = "Loyola"
date = "2024-08-15"
sequence = 1

[[authorsDetail]]
name = "CO-PILAR, MA. VICTORIA"
nameCode = "Co-Pilar"
date = "2024-08-15"
sequence = 2

[[authorsDetail]]
name = "Benitez, Francisco \"Kiko\" B."
nameCode = "Benitez"
date = "2024-08-15"
sequence = 3

[[authorsDetail]]
name = "TANJUATCO, EMIGDIO P., III"
nameCode = "Tanjuatco"
date = "2024-08-15"
sequence = 4

[[authorsDetail]]
name = "TOLENTINO, ANIELA BIANCA D."
nameCode = "Tolentino"
date = "2024-08-15"
sequence = 5

[[authorsDetail]]
name = "REVILLA, RAMON JOLO III B."
nameCode = "Revilla (R.J.)"
date = "2024-08-15"
sequence = 6

[[authorsDetail]]
name = "ACOP, ROMEO M."
nameCode = "Acop"
date = "2024-08-15"
sequence = 7

[[authorsDetail]]
name = "MERCADO-REVILLA, LANI"
nameCode = "Mercado-Revilla"
date = "2024-08-15"
sequence = 8

[[authorsDetail]]
name = "ADVINCULA, ADRIAN JAY C."
nameCode = "Advincula"
date = "2024-08-15"
sequence = 9

[[authorsDetail]]
name = "FERRER, ANTONIO A."
nameCode = "Ferrer (A.)"
date = "2024-08-15"
sequence = 10

[[authorsDetail]]
name = "REVILLA, BRYAN B."
nameCode = "Revilla (B.)"
date = "2024-08-15"
sequence = 11

[[authorsDetail]]
name = "Olivarez, Edwin L."
nameCode = "Olivarez"
date = "2024-08-15"
sequence = 12

[[authorsDetail]]
name = "Lacson-Noel, Josephine Veronique \"Jaye\" R."
nameCode = "Lacson-Noel"
date = "2024-08-15"
sequence = 13

[[authorsDetail]]
name = "ABANTE, BIENVENIDO M., JR."
nameCode = "Abante"
date = "2024-08-15"
sequence = 14

[[authorsDetail]]
name = "Peña, Romulo \"Kid\" Jr."
nameCode = "Peña"
date = "2024-08-15"
sequence = 15

[[authorsDetail]]
name = "Villafuerte, Luis Raymund \"Lray\" Jr. F."
nameCode = "Villafuerte (L.R.)"
date = "2024-08-15"
sequence = 16

[[authorsDetail]]
name = "Go, Mark O."
nameCode = "Go (M.)"
date = "2024-08-15"
sequence = 17

[[authorsDetail]]
name = "Salceda, Joey Sarte"
nameCode = "Salceda"
date = "2024-08-15"
sequence = 18

[[authorsDetail]]
name = "Sacdalan, Joselito \"Joel\" S."
nameCode = "Sacdalan"
date = "2024-08-15"
sequence = 19

[[authorsDetail]]
name = "GUINTU, HOWARD A."
nameCode = "Guintu"
date = "2024-08-15"
sequence = 20

[[authorsDetail]]
name = "Bongalon, Raul Angelo \"Jil\" D."
nameCode = "Bongalon"
date = "2024-08-15"
sequence = 21

[[authorsDetail]]
name = "ORTEGA, FRANCISCO PAOLO P., V"
nameCode = "Ortega"
date = "2024-08-15"
sequence = 22

[[authorsDetail]]
name = "Magsino, Marissa \"Del Mar\" P."
nameCode = "Magsino"
date = "2024-08-15"
sequence = 23

[[authorsDetail]]
name = "Tambunting, Gus S."
nameCode = "Tambunting"
date = "2024-08-15"
sequence = 24

[[authorsDetail]]
name = "ATAYDE, JUAN CARLOS \"ARJO\" C."
nameCode = "Atayde"
date = "2024-08-15"
sequence = 25

[[authorsDetail]]
name = "RIVERA, NOEL \"BONG\" N."
nameCode = "Rivera"
date = "2024-08-15"
sequence = 26

[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez (R.)"
date = "2024-08-15"
sequence = 27

[[authorsDetail]]
name = "LUISTRO, ATTY. GERVILLE \"JINKY BITRICS\" R."
nameCode = "Luistro"
date = "2024-08-15"
sequence = 28

[[authorsDetail]]
name = "Mangaoang, Allen Jesse C."
nameCode = "Mangaoang"
date = "2024-08-15"
sequence = 29

[[authorsDetail]]
name = "AQUINO-MAGSAYSAY, MILAGROS"
nameCode = "Aquino-Magsaysay"
date = "2024-08-15"
sequence = 30

[[authorsDetail]]
name = "Cruz, Ambrosio Jr. C."
nameCode = "Cruz (A.)"
date = "2024-08-15"
sequence = 31

[[authorsDetail]]
name = "BASCUG, ALFELITO \"ALFEL\" M."
nameCode = "Bascug"
date = "2024-08-15"
sequence = 32

[[authorsDetail]]
name = "ORDANES, RODOLFO \"OMPONG\" M."
nameCode = "Ordanes"
date = "2024-08-15"
sequence = 33

[[authorsDetail]]
name = "CUA, MIDY N."
nameCode = "Cua"
date = "2024-08-15"
sequence = 34

[[authorsDetail]]
name = "Verzosa, Samuel Jr. S."
nameCode = "Verzosa"
date = "2024-08-15"
sequence = 35

[[coAuthorsDetail]]
name = "DALIPE, MANUEL JOSE M."
nameCode = "Dalipe"
date = "2024-09-04"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "PRIMICIAS-AGABAS, MARLYN L."
nameCode = "Primicias-Agabas"
date = "2024-09-04"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DIONISIO, ERNESTO JR. M."
nameCode = "Dionisio"
date = "2024-09-04"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "ROMUALDO, JURDIN JESUS M."
nameCode = "Romualdo"
date = "2024-09-09"
journalNo = "J000"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "VILLARICA, LINABELLE RUTH R."
nameCode = "Villarica"
date = "2024-09-16"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "HOUSING AND URBAN DEVELOPMENT"
type = "primary"
referralCode = "0518"
dateRead = "2024-08-20"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[motherBills]]
bill_no = "HB05754"
sequence = 1
date = "2024-08-15"
flag = "S"

[[motherBills]]
bill_no = "HB07230"
sequence = 2
date = "2024-08-15"
flag = "S"

[[substitutedBills]]
bill_no = "HB05754"
sequence = 1
date = "2024-08-15"
flag = "S"

[[substitutedBills]]
bill_no = "HB07230"
sequence = 2
date = "2024-08-15"
flag = "S"

[firstReading]
id = 15691
congress = 19
bill_no = "HB10772"
report = "01169"
comm_act = ""
referral = "0518"
ref_name = "HOUSING AND URBAN DEVELOPMENT"
sub_name = "HOUSING AND URBAN DEVELOPMENT, WAYS AND MEANS"
recomm = "Recommending its approval in substitution of House Bills Numbered 5754 and 7230"
remarks = ""
file = "CR01169.pdf"
date_read = "2024-08-20"
date_ob = "2024-08-20"
date_report = "2024-08-15"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_19/CR01169.pdf"

[secondReading]
id = 1318
congress = 19
bill_no = "HB10772"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2024-08-27"
date_approved = "2024-09-04"
recommitted_bill = ""
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
date_debate_closed = "2024-09-04"
date_amend_closed = "2024-09-04"

[thirdReading]
id = 14004
congress = 19
bill_no = "HB10772"
title_third = "AN ACT IMPROVING THE DELIVERY OF SOCIALIZED HOUSING PROGRAMS, \r\nAMENDING FOR THE PURPOSE SECTIONS 10, 18, AND 20 OF REPUBLIC \r\nACT NO. 7279, OTHERWISE KNOWN AS THE â€œURBAN DEVELOPMENT AND \r\nHOUSING ACT OF 1992â€�, AS AMENDED BY REPUBLIC ACT NO. 10884, \r\nOTHERWISE KNOWN AS THE \"BALANCED HOUSING DEVELOPMENT \r\nPROGRAM AMENDMENTS\"      "
date_dist = "2024-09-05"
date_adopt = "2024-09-10"
remarks = "      "
no_yeas = 178
no_nays = 3
no_abstent = 0
date_trans = "2024-09-12"
date_rec = "2024-09-12"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "HBT10772.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_19/HBT10772.pdf"
