billNumber = "HB11188"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB11188"
lastScraped = "2025-09-21T23:55:22.439953"
title = "HB11188"
longTitle = "AN ACT MANDATING THE USE AND FORTIFICATION OF RICE GRAINS, AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 8976, OTHERWISE KNOWN AS “AN ACT ESTABLISHING THE PHILIPPINE FOOD FORTIFICATION PROGRAM AND FOR OTHER PURPOSES,” APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES\r\n"
scope = "National"
dateFiled = "2024-12-10"
status = "Pending with the Committee on HEALTH since 2024-12-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB11188.pdf"
fileSize = 199016
author = "DY, FAUSTINO MICHAEL CARLOS III T."
coAuthors = [ "LOYOLA, ROY M.",]
[[authorsDetail]]
name = "DY, FAUSTINO MICHAEL CARLOS III T."
nameCode = "Dy (F.M.C.)"
date = "2024-12-10"
sequence = 1

[[coAuthorsDetail]]
name = "LOYOLA, ROY M."
nameCode = "Loyola"
date = "2024-12-18"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2024-12-16"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 16107
congress = 19
bill_no = "HB11188"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2024-12-16"
