billNumber = "HB11442"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB11442"
lastScraped = "2025-09-21T23:55:22.504310"
title = "Amending Section 25 (a) Of Republic Act No. 9404, Otherwise Known As The Charter Of The City Of Tabuk"
longTitle = "AN ACT AMENDING SECTION 25 (a) OF REPUBLIC ACT NO. 9404, OTHERWISE KNOWN AS THE CHARTER OF THE CITY OF TABUK \r\n\r\n"
scope = "Local"
dateFiled = "2025-02-05"
status = "Approved by the House on 2025-06-09, transmitted to the Senate on 2025-06-11 and received by the Senate on 2025-06-11"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Mangaoang, Allen Jesse C."
[[authorsDetail]]
name = "Mangaoang, Allen Jesse C."
nameCode = "Mangaoang"
date = "2025-02-05"
sequence = 1

[[authorsDetail]]
name = "Sagarbarria, Manuel T."
nameCode = "Sagarbarria"
date = "2025-02-05"
sequence = 2

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2025-06-02"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[motherBills]]
bill_no = "HB07203"
sequence = 1
date = "2025-02-05"
flag = "S"

[[substitutedBills]]
bill_no = "HB07203"
sequence = 1
date = "2025-02-05"
flag = "S"

[firstReading]
id = 16361
congress = 19
bill_no = "HB11442"
report = "01425"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "LOCAL GOVERNMENT"
recomm = "Recommending its approval in substitution of House Bill No. 7203"
remarks = ""
file = "CR01425.pdf"
date_read = "2025-06-02"
date_ob = "2025-06-02"
date_fri = "2025-06-03"
date_report = "2025-02-05"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_19/CR01425.pdf"

[secondReading]
id = 1613
congress = 19
bill_no = "HB11442"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_approved = "2025-06-03"
recommitted_bill = ""
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
date_debate_closed = "2025-06-03"
date_amend_closed = "2025-06-03"

[thirdReading]
id = 14225
congress = 19
bill_no = "HB11442"
title_third = "AN ACT AMENDING SECTION 25 (a) OF REPUBLIC ACT NO. 9404, OTHERWISE KNOWN \r\nAS THE CHARTER OF THE CITY OF TABUK    "
date_dist = "2025-06-05"
date_adopt = "2025-06-09"
remarks = "     "
no_yeas = 183
no_nays = 0
no_abstent = 3
date_trans = "2025-06-11"
date_rec = "2025-06-11"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "HBT11442.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_19/HBT11442.pdf"
