billNumber = "HB11496"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HB11496"
lastScraped = "2025-09-21T23:55:22.515064"
title = "HB11496"
longTitle = "AN ACT ESTABLISHING A CAMPUS OF THE UNIVERSITY OF SCIENCE AND TECHNOLOGY OF SOUTHERN PHILIPPINES IN BARANGAY LUMBIA, CITY OF CAGAYAN DE ORO, PROVINCE OF MISAMIS ORIENTAL, TO BE KNOWN AS THE “UNIVERSITY OF SCIENCE AND TECHNOLOGY OF SOUTHERN PHILIPPINES-LUMBIA CAMPUS”, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2025-04-07"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2025-06-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HB11496.pdf"
fileSize = 884801
author = "SUAN, LORDAN G."
[[authorsDetail]]
name = "SUAN, LORDAN G."
nameCode = "Suan"
date = "2025-04-07"
sequence = 1

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2025-06-02"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 16415
congress = 19
bill_no = "HB11496"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-06-02"
