billNumber = "HCR0006"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HCR0006"
lastScraped = "2025-09-21T23:55:22.534111"
title = "HCR0006"
longTitle = "CONCURRENT RESOLUTION ESTABLISHING THE PHILIPPINE CONGRESS-BANGSAMORO PARLIAMENT FORUM, AS PROVIDED UNDER ARTICLE VI, SECTION 3 OF REPUBLIC ACT NO. 11054, OTHERWISE KNOWN AS THE “ORGANIC LAW FOR THE BANGSAMORO\r\nAUTONOMOUS REGION IN MUSLIM MINDANAO”"
scope = "National"
dateFiled = "2022-12-06"
status = "House adopted Senate Concurrent Resolution as an amendment to House Concurrent Resolution"
statusOrder = 29.2
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Gatchalian, Rex"
[[authorsDetail]]
name = "Gatchalian, Rex"
nameCode = "Gatchalian"
date = "2022-12-06"
sequence = 1

[[authorsDetail]]
name = "ADIONG, ZIAUR-RAHMAN \"ZIA\" ALONTO"
nameCode = "Adiong"
date = "2022-12-06"
sequence = 2

[[authorsDetail]]
name = "BALINDONG, YASSER ALONTO"
nameCode = "Balindong"
date = "2022-12-06"
sequence = 3

[[authorsDetail]]
name = "Bordado, Gabriel Jr. H."
nameCode = "Bordado"
date = "2022-12-06"
sequence = 4

[[authorsDetail]]
name = "FRESNEDI, JAIME R."
nameCode = "Fresnedi"
date = "2022-12-06"
sequence = 5

[[authorsDetail]]
name = "PANALIGAN, ARNAN C."
nameCode = "Panaligan"
date = "2022-12-06"
sequence = 6

[[authorsDetail]]
name = "ADVINCULA, ADRIAN JAY C."
nameCode = "Advincula"
date = "2022-12-06"
sequence = 7

[[authorsDetail]]
name = "Zubiri, Jose Maria Jr. R."
nameCode = "Zubiri"
date = "2022-12-06"
sequence = 8

[[authorsDetail]]
name = "ROQUE, LAARNI LAVIN"
nameCode = "Roque"
date = "2022-12-06"
sequence = 9

[[authorsDetail]]
name = "DOMINGO, DANILO \"DANNY\" A."
nameCode = "Domingo"
date = "2022-12-06"
sequence = 10

[[authorsDetail]]
name = "RAMA, EDUARDO R."
nameCode = "Rama"
date = "2022-12-06"
sequence = 11

[[authorsDetail]]
name = "NISAY, JERNIE JETT V."
nameCode = "Nisay"
date = "2022-12-06"
sequence = 12

[[authorsDetail]]
name = "ASISTIO, DEAN"
nameCode = "Asistio"
date = "2022-12-06"
sequence = 13

[[authorsDetail]]
name = "CORVERA, DALE B."
nameCode = "Corvera"
date = "2022-12-06"
sequence = 14

[[authorsDetail]]
name = "Hataman, Mujiv S."
nameCode = "Hataman"
date = "2022-12-06"
sequence = 15

[[authorsDetail]]
name = "Gorriceta, Michael B."
nameCode = "Gorriceta"
date = "2022-12-06"
sequence = 16

[[authorsDetail]]
name = "FORTES, WOWO"
nameCode = "Fortes"
date = "2022-12-06"
sequence = 17

[[authorsDetail]]
name = "Bolilia, Lianda B."
nameCode = "Bolilia"
date = "2022-12-06"
sequence = 18

[[authorsDetail]]
name = "PLEYTO, SALVADOR A."
nameCode = "Pleyto"
date = "2022-12-06"
sequence = 19

[[authorsDetail]]
name = "GUINTU, HOWARD A."
nameCode = "Guintu"
date = "2022-12-06"
sequence = 20

[[authorsDetail]]
name = "Go, Mark O."
nameCode = "Go (M.)"
date = "2022-12-06"
sequence = 21

[[authorsDetail]]
name = "LEGARDA, ANTONIO B., JR"
nameCode = "Legarda"
date = "2022-12-06"
sequence = 22

[[authorsDetail]]
name = "Salo, Ron P."
nameCode = "Salo"
date = "2022-12-06"
sequence = 23

[[authorsDetail]]
name = "MASTURA, BAI DIMPLE I."
nameCode = "Mastura"
date = "2022-12-06"
sequence = 24

[[authorsDetail]]
name = "GARDIOLA, EDWIN L."
nameCode = "Gardiola"
date = "2022-12-06"
sequence = 25

[[authorsDetail]]
name = "Palma, Wilter Y."
nameCode = "Palma"
date = "2022-12-06"
sequence = 26

[[authorsDetail]]
name = "SOLON, STEVE CHIONGBIAN"
nameCode = "Solon"
date = "2022-12-06"
sequence = 27

[[authorsDetail]]
name = "GUTIERREZ, RAMON RODRIGO L."
nameCode = "Gutierrez"
date = "2022-12-06"
sequence = 28

[[authorsDetail]]
name = "CRUZ, RICARDO S., JR."
nameCode = "Cruz (R.)"
date = "2022-12-06"
sequence = 29

[[authorsDetail]]
name = "GARCIA, JOSE ARTURO S., JR."
nameCode = "Garcia (J.A.)"
date = "2022-12-06"
sequence = 30

[[authorsDetail]]
name = "Miguel, Peter B."
nameCode = "Miguel"
date = "2022-12-06"
sequence = 31

[[authorsDetail]]
name = "RODRIGUEZ, EULOGIO \"LEO\" R."
nameCode = "Rodriguez (E.)"
date = "2022-12-06"
sequence = 32

[[authorsDetail]]
name = "Peña, Romulo \"Kid\" Jr."
nameCode = "Peña"
date = "2022-12-06"
sequence = 33

[[authorsDetail]]
name = "GARCIA, DANTE S."
nameCode = "Garcia (D.)"
date = "2022-12-06"
sequence = 34

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2022-12-07"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[motherBills]]
bill_no = "HCR0003"
sequence = 1
date = "2022-12-06"
flag = "S"

[[substitutedBills]]
bill_no = "HCR0003"
sequence = 1
date = "2022-12-06"
flag = "S"

[firstReading]
id = 16488
congress = 19
bill_no = "HCR0006"
report = "00213"
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = "LOCAL GOVERNMENT"
recomm = "Recommending its approval in substitution of House Concurrent Resolution No. 3"
remarks = ""
file = "CR00213.pdf"
date_read = "2022-12-07"
date_ob = "2022-12-07"
date_report = "2022-12-06"
committee_report = "https://docs.congress.hrep.online/legisdocs/first_19/CR00213.pdf"

[secondReading]
id = 272
congress = 19
bill_no = "HCR0006"
adopted_resolution = "CR00005"
adopted_resolution_title = "CONCURRENT RESOLUTION ESTABLISHING THE PHILIPPINE CONGRESS-BANGSAMORO PARLIAMENT FORUM, AS PROVIDED UNDER ARTICLE VI, SECTION 3 OF REPUBLIC ACT NO. 11054, OTHERWISE KNOWN AS THE “ORGANIC LAW FOR THE BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "House Adopting Senate Concurrent Resolution No. 5 as an Amendment to House Concurrent Resolution No. 6 on December 13, 2022.                              \r\n                              \r\nTransmitted and received by the Senate on December 15, 2022"
recommended_reconsidered = " "
date_calendared = "2022-12-13"
date_approved = "2022-12-13"
recommitted_bill = ""
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = "CR00005"
action_on_adopted_resolution = ""
file = "HCR0006.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_19/HCR0006.pdf"

[thirdReading]
id = 13201
congress = 19
bill_no = "HCR0006"
title_third = "                 "
remarks = "Message received from Senate informing the House of Representatives that on December 12, 2022, the Senate designated Senators Loren Legarda, Joseph Victor G. Ejercito, Francis \"Tol\" N. Tolentino, Robinhood C. Padilla and Aquilino \"Koko\" Pimentel III as members of the Philippine Congress - Bangsamoro Parliament Forum pursuant to Senate Concurrent Resolution No. 5           "
no_yeas = 0
no_nays = 0
no_abstent = 0
date_adopt_amend = "2022-12-13"
amend_ind = " "
ccreqby = "S"
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
dte_copyenroll = "2023-01-25"
dte_signedenroll_sen = "2023-02-06"
file = "HCR0006.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_19/HCR0006.pdf"
