billNumber = "HR00254"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR00254"
lastScraped = "2025-09-21T23:55:22.591269"
title = "HR00254"
longTitle = "A RESOLUTION EXPRESSING PROFOUND SORROW OF THE HOUSE OF REPRESENTATIVES ON THE DEATH OF FIDEL VALDEZ RAMOS, 12TH PRESIDENT OF THE REPUBLIC\r\nOF THE PHILIPPINES AND HONORING HIS CONTRIBUTIONS TO THE COUNTRY"
scope = "National"
dateFiled = "2022-08-16"
status = "Pending with the Committee on RULES since 2022-08-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR00254.pdf"
fileSize = 2355169
author = "ARENAS, MARIA RACHEL J."
[[authorsDetail]]
name = "ARENAS, MARIA RACHEL J."
nameCode = "Arenas"
date = "2022-08-16"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2022-08-17"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 16798
congress = 19
bill_no = "HR00254"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-17"
