billNumber = "HR00111"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR00111"
lastScraped = "2025-09-21T23:55:22.564787"
title = "HR00111"
longTitle = "A RESOLUTION CONGRATULATING AND COMMENDING TRIBU LUMAD BASAKANON FOR WINNING GOLD MEDAL IN THE INTERNATIONAL CATEGORY OF THE POWERFUL DAEGU FESTIVAL"
scope = "National"
dateFiled = "2022-07-28"
status = "Substituted by HR00458"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR00111.pdf"
fileSize = 441534
author = "De Venecia, Christopher V.P."
[[authorsDetail]]
name = "De Venecia, Christopher V.P."
nameCode = "De Venecia"
date = "2022-07-28"
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2022-08-03"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 16655
congress = 19
bill_no = "HR00111"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-08-03"
