billNumber = "HR01092"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR01092"
lastScraped = "2025-09-21T23:55:22.790636"
title = "HR01092"
longTitle = "RESOLUTION DIRECTING THE APPROPRIATE HOUSE COMMITTEE, TO CONDUCT AN\r\nINQUIRY, IN AID OF LEGISLATION, INTO THE UNWARRANTED GRADUATION OF NON-POOR BENEFICIARIES OF THE PANTAWID PAMILYANG PILIPINO PROGRAM (4PS) AND URGE THE DEPARTMENT OF SOCIAL WELFARE AND DEVELOPMENT (DSWD) TO INSTITUTE A SYSTEMATIC APPEAL MECHANISM FOR BENEFICIARIES WHO WISH TO APPEAL THEIR GRADUATION FROM THE PROGRAM"
scope = "National"
dateFiled = "2023-06-20"
status = "Substituted by HR02191"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR01092.pdf"
fileSize = 378543
author = "Lee, Wilbert \"Manoy\" T."
[[authorsDetail]]
name = "Lee, Wilbert \"Manoy\" T."
nameCode = "Lee"
date = "2023-06-20"
sequence = 1

[[committee]]
name = "POVERTY ALLEVIATION"
type = "primary"
referralCode = "B502"
dateRead = "2023-07-25"

[[committee]]
name = "POVERTY ALLEVIATION"
type = "principal"
referralCode = "B502"

[firstReading]
id = 17636
congress = 19
bill_no = "HR01092"
report = ""
comm_act = ""
referral = "B502"
ref_name = "POVERTY ALLEVIATION"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2023-08-01"
date_read = "2023-07-25"
