billNumber = "HR01482"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR01482"
lastScraped = "2025-09-21T23:55:22.868575"
title = "HR01482"
longTitle = "RESOLUTION URGING THE APPROPRIATE PHILIPPINE GOVERNMENT DEPARTMENTS AND AGENCIES TO EXTEND THEIR FULL COOPERATION TO THE OFFICE OF THE PROSECUTOR OF THE INTERNATIONAL CRIMINAL COURT (ICC) WITH RESPECT TO ITS INVESTIGATION OF ANY ALLEGED CRIME WITHIN THE JURISDICTION OF THE ICC, INCLUDING BUT NOT LIMITED TO THE CRIME AGAINST HUMANITY OF MURDER, COMMITTED IN THE PHILIPPINES IN THE CONTEXT OF THE SO-CALLED 'WAR ON DRUGS' CAMPAIGN"
scope = "National"
dateFiled = "2023-11-21"
status = "Consolidated into HR01477"
statusOrder = 9.2
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR01482.pdf"
fileSize = 154745
author = "Lagman, Edcel C."
[[authorsDetail]]
name = "Lagman, Edcel C."
nameCode = "Lagman"
date = "2023-11-21"
sequence = 1

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "0520"
dateRead = "2023-11-22"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[[committee]]
name = "HUMAN RIGHTS"
type = "secondary"
referralCode = "E507"

[firstReading]
id = 18027
congress = 19
bill_no = "HR01482"
report = ""
comm_act = ""
referral = "0520"
ref_name = "JUSTICE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-11-22"
