billNumber = "HR01394"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR01394"
lastScraped = "2025-09-21T23:55:22.853424"
title = "HR01394"
longTitle = "A RESOLUTION URGING THE HOUSE OF REPRESENTATIVES, THROUGH THE APPROPRIATE COMMITTEE, TO CONDUCT AN INQUIRY IN AID OF LEGISLATION ON THE LATE PAYMENTS MADE BY THE DEPARTMENT OF HEALTH (DOH) FOR ITS FINANCIAL OBLIGATIONS TO THE GOVERNMENT AND PRIVATE HOSPITALS/FACILITIES THAT ARE UNDER THE MEDICAL ASSISTANCE TO INDIGENT PATIENTS (MAIP) PROGRAM"
scope = "National"
dateFiled = "2023-10-19"
status = "Pending with the Committee on HEALTH since 2023-11-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR01394.pdf"
fileSize = 368768
author = "Palma, Wilter Y."
[[authorsDetail]]
name = "Palma, Wilter Y."
nameCode = "Palma"
date = "2023-10-19"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2023-11-08"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 17938
congress = 19
bill_no = "HR01394"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2023-11-14"
date_read = "2023-11-08"
