billNumber = "HR01495"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR01495"
lastScraped = "2025-09-21T23:55:22.871251"
title = "HR01495"
longTitle = "A RESOLUTION EXPRESSING THE SUPPORT OF THE HOUSE OF REPRESENTATIVES OF THE PHILIPPINES FOR TAIWAN´S INCLUSION IN THE UNITED NATIONS FRAMEWORK\r\nCONVENTION ON CLIMATE CHANGE (UNFCCC) AND THE PARIS AGREEMENT AND ITS\r\nMEANINGFUL PARTICIPATION AS AN OBSERVER IN UNFCCC COP28 SCHEDULED TO\r\nTAKE PLACE FROM NOVEMBER 30 TO DECEMBER 12, 2023 IN DUBAI"
scope = "National"
dateFiled = "2023-12-04"
status = "Pending with the Committee on CLIMATE CHANGE since 2023-12-06"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR01495.pdf"
fileSize = 339529
author = "RODRIGUEZ, RUFUS B."
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez (R.)"
date = "2023-12-04"
sequence = 1

[[committee]]
name = "CLIMATE CHANGE"
type = "primary"
referralCode = "H503"
dateRead = "2023-12-06"

[[committee]]
name = "CLIMATE CHANGE"
type = "principal"
referralCode = "H503"

[firstReading]
id = 18040
congress = 19
bill_no = "HR01495"
report = ""
comm_act = ""
referral = "H503"
ref_name = "CLIMATE CHANGE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2023-12-06"
