billNumber = "HR01387"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR01387"
lastScraped = "2025-09-21T23:55:22.851446"
title = "HR01387"
longTitle = "RESOLUTION URGING THE DEPARTMENT OF INFORMATION AND COMMUNICATIONS\r\nTECHNOLOGY (DICT) TO CONDUCT A GOVERMENT-WIDE CYBERSECURITY AUDIT, IN LIGHT OF THE CONTINUOUS PROLIFERATION AND ALARMING TREND OF CYBERATTACKS AGAINST THE GOVERNMENT AND PRIVATE FIRMS IN THE COUNTRY AND DIRECTING THE APPROPRIATE HOUSE COMMITTEE, IN AID OF LEGISLATION, TO SUMMON THE DICT TO SUBMIT THE REPORT OF THIS AUDIT TO CONGRESS, WITH THE END IN VIEW OF DETERMINING THE REMEDIAL LEGISLATION NEEDED TO STRENGTHEN OUR EXISTING CYBERSECURITY POLICIES AND LAWS"
scope = "National"
dateFiled = "2023-10-16"
status = "Pending with the Committee on INFORMATION AND COMMUNICATIONS TECHNOLOGY since 2024-04-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR01387.pdf"
fileSize = 440291
author = "Lee, Wilbert \"Manoy\" T."
[[authorsDetail]]
name = "Lee, Wilbert \"Manoy\" T."
nameCode = "Lee"
date = "2023-10-16"
sequence = 1

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "primary"
referralCode = "E504"
dateRead = "2023-11-07"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[[committee]]
name = "PUBLIC INFORMATION"
type = "secondary"
referralCode = "0528"

[firstReading]
id = 17931
congress = 19
bill_no = "HR01387"
report = ""
comm_act = ""
referral = "E504"
ref_name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2024-04-30"
date_read = "2023-11-07"
