billNumber = "HR01622"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR01622"
lastScraped = "2025-09-21T23:55:22.897938"
title = "HR01622"
longTitle = "A RESOLUTION HONORING THE LIFE AND LEGACY OF MARY JANE GUCK A.K.A “JACLYN JOSE”, AND EXPRESSING THE HEARTFELT CONDOLENCES AND DEEPEST SYMPATHY OF THE HOUSE OF REPRESENATIVES TO THE BEREAVED FAMILY"
scope = "National"
dateFiled = "2024-03-05"
status = "Pending with the Committee on RULES since 2024-03-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR01622.pdf"
fileSize = 407272
author = "Robes, Florida \"Rida\" P."
[[authorsDetail]]
name = "Robes, Florida \"Rida\" P."
nameCode = "Robes"
date = "2024-03-05"
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2024-03-11"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 18167
congress = 19
bill_no = "HR01622"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2024-03-11"
