billNumber = "HR02165"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=HR02165"
lastScraped = "2025-09-21T23:55:23.000187"
title = "HR02165"
longTitle = "RESOLUTION EXPRESSING THE PROFOUND CONDOLENCES OF THE HOUSE OF REPRESENTATIVES TO THE FAMILY OF HONORABLE DEOGRACIAS VICTOR BARBERS SAVELLANO, UNDERSECRETARY OF THE DEPARTMENT OF AGRICULTURE FOR LIVESTOCK, AND FORMER REPRESENTATIVE OF THE FIRST LEGISLATIVE DISTRICT OF ILOCOS SUR DURING THE SEVENTEENTH AND EIGHTEENTH CONGRESSES"
scope = "National"
dateFiled = "2025-01-13"
status = "Adopted as Resolution No. HR00287 on 2025-01-13"
statusOrder = 15.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_19/HR02165.pdf"
fileSize = 210592
author = "ROMUALDEZ, FERDINAND MARTIN G."
coAuthors = [ "VELOSO-TUAZON, ANNA",]
[[authorsDetail]]
name = "ROMUALDEZ, FERDINAND MARTIN G."
nameCode = "Romualdez (F.M.)"
date = "2025-01-13"
sequence = 1

[[authorsDetail]]
name = "Gonzales, Aurelio \"Dong\" Jr. D."
nameCode = "Gonzales (A.)"
date = "2025-01-13"
sequence = 2

[[authorsDetail]]
name = "Dalipe, Manuel Jose \"Mannix\" M."
nameCode = "Dalipe"
date = "2025-01-13"
sequence = 3

[[coAuthorsDetail]]
name = "VELOSO-TUAZON, ANNA"
nameCode = "Veloso-Tuazon"
date = "2025-01-16"
journalNo = "J000"
sessionNo = "3RS"

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2025-01-13"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[motherBills]]
bill_no = "HR02159"
sequence = 1
flag = "C"

[[motherBills]]
bill_no = "HR02163"
sequence = 2
flag = "C"

[[consolidatedBills]]
bill_no = "HR02159"
sequence = 1
flag = "C"

[[consolidatedBills]]
bill_no = "HR02163"
sequence = 2
flag = "C"

[firstReading]
id = 18710
congress = 19
bill_no = "HR02165"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-01-13"

[secondReading]
id = 1471
congress = 19
bill_no = "HR02165"
adopted_resolution = "HR00287"
adopted_resolution_title = "RESOLUTION EXPRESSING THE PROFOUND CONDOLENCES OF THE HOUSE OF REPRESENTATIVES TO THE FAMILY OF HONORABLE DEOGRACIAS VICTOR BARBERS SAVELLANO, UNDERSECRETARY OF THE DEPARTMENT OF AGRICULTURE FOR LIVESTOCK, AND FORMER REPRESENTATIVE OF THE FIRST LEGISLATIVE DISTRICT OF ILOCOS SUR DURING THE SEVENTEENTH AND EIGHTEENTH CONGRESSES"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_approved = "2025-01-13"
recommitted_bill = ""
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
file = "HR02165.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_19/HR02165.pdf"
