billNumber = "PS00193"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=PS00193"
lastScraped = "2025-09-21T23:55:23.065229"
title = "Impact Of R A 8479 Also Known As The “ Downstream Oil Deregulation Act Of 1998”"
longTitle = "IMPACT OF RA 8479 ALSO KNOWN AS THE “DOWNSTREAM OIL DEREGULATION ACT OF 1998”"
scope = "National"
dateFiled = "2023-08-14"
status = "Pending with the Committee on ENERGY since 2023-08-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Tulfo, Erwin T."
[[authorsDetail]]
name = "Tulfo, Erwin T."
nameCode = "Tulfo (E.)"
date = "2023-08-14"
sequence = 1

[[committee]]
name = "ENERGY"
type = "primary"
referralCode = "0510"
dateRead = "2023-08-14"

[[committee]]
name = "ENERGY"
type = "principal"
referralCode = "0510"

[firstReading]
id = 19089
congress = 19
bill_no = "PS00193"
report = ""
comm_act = ""
referral = "0510"
ref_name = "ENERGY"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2023-08-23"
date_read = "2023-08-14"
