billNumber = "PS00265"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=PS00265"
lastScraped = "2025-09-21T23:55:23.076067"
title = "Philippine High-level Delegation Visit To The Uk On Creative Industries"
longTitle = "“UNITED KINGDOM MISSION VISIT ON CREATIVE INDUSTRIES”"
scope = "National"
dateFiled = "2023-12-12"
status = "Pending with the Committee on CREATIVE INDUSTRIES since 2024-01-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "De Venecia, Christopher V.P."
[[authorsDetail]]
name = "De Venecia, Christopher V.P."
nameCode = "De Venecia"
date = "2023-12-12"
sequence = 1

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "primary"
referralCode = "J505"
dateRead = "2023-12-12"

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 19161
congress = 19
bill_no = "PS00265"
report = ""
comm_act = ""
referral = "J505"
ref_name = "CREATIVE INDUSTRIES"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2024-01-30"
date_read = "2023-12-12"
