billNumber = "PS00272"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=PS00272"
lastScraped = "2025-09-21T23:55:23.077123"
title = "C O P 28 Regarding Nuclear Power"
longTitle = "COP28 OR 28TH CONFERENCE OF THE PARTIES TO THE UNITED NATIONS FRAMEWORK CONVENTION ON CLIMATE CHANGE"
scope = "National"
dateFiled = "2024-01-22"
status = "Pending with the Committee on NUCLEAR ENERGY since 2024-01-31"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "COJUANGCO, MARK O."
[[authorsDetail]]
name = "COJUANGCO, MARK O."
nameCode = "Cojuangco (M.)"
date = "2024-01-22"
sequence = 1

[[committee]]
name = "NUCLEAR ENERGY"
type = "primary"
referralCode = "K501"
dateRead = "2024-01-22"

[[committee]]
name = "NUCLEAR ENERGY"
type = "principal"
referralCode = "K501"

[firstReading]
id = 19168
congress = 19
bill_no = "PS00272"
report = ""
comm_act = ""
referral = "K501"
ref_name = "NUCLEAR ENERGY"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2024-01-31"
date_read = "2024-01-22"
