billNumber = "PS00076"
billType = "HB"
congress = 19
apiCongressId = 19
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=19&q=PS00076"
lastScraped = "2025-09-21T23:55:23.046411"
title = "Comprehensive And Responsive Civil Statistics System Or (crvs) For Children"
longTitle = "COMPREHENSIVE AND RESPONSIVE CIVIL STATISTICS SYSTEM OR (CRVS) FOR CHILDREN"
scope = "National"
dateFiled = "2022-11-21"
status = "Pending with the Committee on POPULATION AND FAMILY RELATIONS since 2022-11-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Chan, Ma. Cynthia K."
[[authorsDetail]]
name = "Chan, Ma. Cynthia K."
nameCode = "Chan"
date = "2022-11-21"
sequence = 1

[[committee]]
name = "POPULATION AND FAMILY RELATIONS"
type = "primary"
referralCode = "0512"
dateRead = "2022-11-29"

[[committee]]
name = "POPULATION AND FAMILY RELATIONS"
type = "principal"
referralCode = "0512"

[firstReading]
id = 18972
congress = 19
bill_no = "PS00076"
report = ""
comm_act = ""
referral = "0512"
ref_name = "POPULATION AND FAMILY RELATIONS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2022-11-29"
