billNumber = "SBN-02237"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-2237"
lastScraped = "2025-09-20T21:14:49.731789"
title = "CONVERSION OF SAN SIMON ROAD, DALANDANAN, IN THE CITY OF VALENZUELA, INTO A NATIONAL ROAD"
filedDate = "May 24, 2023"
author = "Marcos, Imee R."
longTitle = "AN ACT PROVIDING FOR THE CONVERSION OF SAN SIMON ROAD, DALANDANAN, IN THE CITY OF VALENZUELA, METRO MANILA INTO A NATIONAL ROAD AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Roads, Conversion",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4180638081!.pdf"
pdfFileName = "SBN-2237 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "5/24/2023"
action = "Introduced by Senator IMEE R. MARCOS;"

[[legislativeHistory]]
date = "5/29/2023"
action = "Read on First Reading and Referred to the Committee on RULES;"

[status]
status = "Pending in the Committee"
date = "5/29/2023"

[committee]
name = "Rules"
type = "primary"
