billNumber = "SBN-01633"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-1633"
lastScraped = "2025-09-20T21:12:03.906924"
title = "21ST CENTURY SCHOOL BOARDS ACT"
filedDate = "January 4, 2023"
author = "Ejercito, Joseph Victor G."
longTitle = "AN ACT STRENGTHENING THE INVOLVEMENT OF LOCAL COMMUNITIES AND LOCAL GOVERNMENT UNITS IN BASIC EDUCATION GOVERNANCE BY EMPOWERING THEM AS PARTNERS IN EDUCATING THE LEARNERS, ENGAGING THEIR PARTICIPATION IN THE DELIVERY OF BASIC SERVICES AND ASSESSMENT OF THE EFFECTIVITY AND EFFECTIVENESS THEREOF, AND INTEGRATING THEIR INTERVENTIONS TO ACHIEVE THE SHARED GOAL OF QUALITY INCLUSIVE EDUCATION, AMENDING FOR THE PURPOSE OF SECTIONS 98, 99, 100 AND 272 OF REPUBLIC ACT NO. 7160, OTHERWISE KNOWN AS THE LOCAL GOVERNMENT CODE OF 1991, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Local School Boards", "Basic Education/Basic Education Institutions", "Local Government Units (LGUS)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4027536679!.pdf"
pdfFileName = "SBN-1633 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/4/2023"
action = "Introduced by Senator JOSEPH VICTOR G. EJERCITO;"

[[legislativeHistory]]
date = "1/23/2023"
action = "Read on First Reading and Referred to the Committees on LOCAL GOVERNMENT; BASIC EDUCATION and FINANCE;"

[[legislativeHistory]]
date = "2/20/2023"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "3/7/2024"
action = "Conducted TECHNICAL WORKING GROUP;"

[status]
status = "Pending in the Committee"
date = "1/23/2023"

[committee]
name = "Local Government"
type = "primary"
