billNumber = "SBN-01793"
billType = "SBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=SBN-1793"
lastScraped = "2025-09-20T21:12:47.423912"
title = "FREE PROFESSIONAL EXAMINATION ACT OF 2023"
filedDate = "January 30, 2023"
author = "Revilla Jr., Ramon Bong"
longTitle = "AN ACT EXEMPTING QUALIFIED INDIGENT FILIPINOS FROM PAYMENT OF PROFESSIONAL EXAMINATION FEES AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Indigenous People", "Professional Licensure Examinations",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4055236961!.pdf"
pdfFileName = "SBN-1793 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/30/2023"
action = "Introduced by Senator RAMON BONG REVILLA JR.;"

[[legislativeHistory]]
date = "2/1/2023"
action = "Read on First Reading and Referred to the Committees on CIVIL SERVICE, GOVERNMENT REORGANIZATION AND PROFESSIONAL REGULATION; SOCIAL JUSTICE, WELFARE AND RURAL DEVELOPMENT and FINANCE;"

[status]
status = "Pending in the Committee"
date = "2/1/2023"

[committee]
name = "Civil Service, Government Reorganization and Professional Regulation"
type = "primary"
