billNumber = "HB00876"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB00876"
lastScraped = "2025-09-22T00:46:56.716833"
title = "HB00876"
longTitle = "AN ACT CONVERTING PARACALE HIGH SCHOOL IN THE MUNICIPALITY OF PARACALE, PROVINCE OF CAMARINES NORTE, INTO A NATIONAL HIGH SCHOOL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-08-31"
status = "Pending with the Committee on EDUCATION AND CULTURE since 1987-09-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Unico"
[[authorsDetail]]
name = "Unico"
nameCode = "Unico"
date = ""
sequence = 0

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "509"
dateRead = "1987-09-01"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 135573
congress = 8
bill_no = "HB00876"
referral = "509"
ref_name = "EDUCATION AND CULTURE"
sub_name = ""
date_read = "1987-09-01"
