billNumber = "HB00413"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB00413"
lastScraped = "2025-09-22T00:46:56.633991"
title = "HB00413"
longTitle = "AN ACT PROVIDING FOR THE AMENDMENT OF SECTION 5 OF EXECUTIVE ORDER NO. 189, SERIES OF 1987, THEREBYLIMITING TO FIFTY PERCENT THE SHARE OF THE NATIONAL GOVERNMENT FROM COLLECTIONS ACCRUING TO THE SPECIAL EDUCATION FUND"
scope = "National"
dateFiled = "1987-08-17"
status = "Pending with the Committee on WAYS AND MEANS since 1987-08-18"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Martinez"
coAuthors = [ "CAMASURA, JUANITO JR. G.", "MONFORT, NARCISO D.",]
[[authorsDetail]]
name = "Martinez"
nameCode = "Martinez"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "CAMASURA, JUANITO JR. G."
nameCode = "Camasura"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "542"
dateRead = "1987-08-18"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[firstReading]
id = 135110
congress = 8
bill_no = "HB00413"
comm_act = "CHANGE OF REFERRAL FROM THE CTTE. ON EDUCATION AND CULTURE TO THE CTTE. ON WAYS AND MEANS ON AUGUST"
referral = "542"
ref_name = "WAYS AND MEANS"
sub_name = ""
date_read = "1987-08-18"
