billNumber = "HB01875"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB01875"
lastScraped = "2025-09-22T00:46:56.890314"
title = "HB01875"
longTitle = "AN ACT CONVERTING THE PROVINCIAL ROAD FROM THE HIGHWAY BOUNDARY BETWEEN THE MUNICIPALITIES OF BARILI AND DUMANJUG (KM. #67) TO THE HIGHWAY BOUNDARY BETWEEN THE MUNICIPALITIES OF SAMBOAN AND SANTANDER(KM. #146), IN THE ISLAND PROVINCE OF CEBU INTO ANATIONAL ROAD, AND APPROPRIATING THE NECESSARY FUNUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-09-23"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-09-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Abines"
[[authorsDetail]]
name = "Abines"
nameCode = "Abines"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-09-29"

[[committee]]
name = "WELFARE OF CHILDREN"
type = "principal"
referralCode = "F501"

[firstReading]
id = 136566
congress = 8
bill_no = "HB01875"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1987-09-29"
