billNumber = "HB02846"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB02846"
lastScraped = "2025-09-22T00:46:57.066237"
title = "HB02846"
longTitle = "AN ACT INCREASING THE ANNUAL SHARE OF THE BARANGAYS IN THE BASIC PROPERTY TAX COLLECTIONS: AMENDINGFOR THE PURPOSE PRESIDENTIAL DECREE NUMBERED FOURHUNDRED SIXTY-FOUR, OTHERWISE KNOWN AS THE REAL PROPERTY TAX CODE, AS AMENDED BY PRESIDENTIAL DECREENUMBERED TWELVE HUNDRED AND THIRTY"
scope = "National"
dateFiled = "1987-10-15"
status = "Pending with the Committee on WAYS AND MEANS since 1987-10-19"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Acosta"
coAuthors = [ "ANDOLANA, GREGORIO A.", "BANDON, ALAWADIN JR. T.", "ECLEO, GLENDA B.", "MONFORT, NARCISO D.", "PUYAT-REYES, MA. CONSUELO", "SINGSON, LUIS C.",]
[[authorsDetail]]
name = "Acosta"
nameCode = "Acosta"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ANDOLANA, GREGORIO A."
nameCode = "Andolana"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BANDON, ALAWADIN JR. T."
nameCode = "Bandon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ECLEO, GLENDA B."
nameCode = "Ecleo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PUYAT-REYES, MA. CONSUELO"
nameCode = "Puyat-reyes"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SINGSON, LUIS C."
nameCode = "Singson"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "542"
dateRead = "1987-10-19"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 137535
congress = 8
bill_no = "HB02846"
referral = "542"
ref_name = "WAYS AND MEANS"
sub_name = ""
date_read = "1987-10-19"
