billNumber = "HB02352"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB02352"
lastScraped = "2025-09-22T00:46:56.972467"
title = "HB02352"
longTitle = "AN ACT TO ESTABLISH, ORGANIZE AND MAINTAIN A TREATMENT AND REHABILITATION CENTER FOR USERS AND DEPENDENTS OF PROHIBITED AND DANGEROUS DRUGS IN THE MUNICIPALITY OF LUISIANA, PROVINCE OF LAGUNA AND TO AUTHORIZE THE APPROPRIATION OF FUNDS FOR THE PURPOSE"
scope = "Local"
dateFiled = "1987-10-06"
status = "Pending with the Committee on HEALTH since 1987-10-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Palacol"
[[authorsDetail]]
name = "Palacol"
nameCode = "Palacol"
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1987-10-07"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 137041
congress = 8
bill_no = "HB02352"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1987-10-07"
