billNumber = "HB02860"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB02860"
lastScraped = "2025-09-22T00:46:57.068794"
title = "HB02860"
longTitle = "AN ACT PROVIDING FOR THE RENOVATION AND EXPANSIONOF THE PUBLIC MARKET IN THE MUNICIPALITY OF SARA,PROVINCE OF ILOILO, AND AUTHORIZING THE APPROPRIATION OF FUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-10-15"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-10-19"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Tupas"
[[authorsDetail]]
name = "Tupas"
nameCode = "Tupas"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-10-19"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 137549
congress = 8
bill_no = "HB02860"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1987-10-19"
