billNumber = "HB02823"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB02823"
lastScraped = "2025-09-22T00:46:57.061520"
title = "HB02823"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF FISHPORTIN BARANGAY OLD SAGAY, IN THE MUNICIPALITY OF SAGAY, PROVINCE OF NEGROS OCCIDENTAL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-10-15"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-10-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Puey"
[[authorsDetail]]
name = "Puey"
nameCode = "Puey"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-10-16"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 137512
congress = 8
bill_no = "HB02823"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1987-10-16"
