billNumber = "HB02818"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB02818"
lastScraped = "2025-09-22T00:46:57.060580"
title = "HB02818"
longTitle = "AN ACT UPGRADING PRESENT RETIREMENT BENEFITS PAIDTO POLICE PERSONNEL TO A LEVEL EQUAL TO THAT CURRENTLY ENJOYED BY MILITARY PERSONNEL"
scope = "National"
dateFiled = "1987-10-15"
status = "Pending with the Committee on PUBLIC INFORMATION since 1987-10-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Sison"
coAuthors = [ "VENECIA, JOSE JR. C. DE", "BENGSON, ANTONIO III E.", "ORBOS, OSCAR M.", "LAZATIN, CARMELO F.", "ESTRELLA, CONRADO III M.", "AQUINO, FLORANTE L.", "GILLEGO, BONIFACIO H.", "SINGSON, LUIS C.",]
[[authorsDetail]]
name = "Sison"
nameCode = "Sison"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "VENECIA, JOSE JR. C. DE"
nameCode = "Venecia"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BENGSON, ANTONIO III E."
nameCode = "Bengson"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ORBOS, OSCAR M."
nameCode = "Orbos"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAZATIN, CARMELO F."
nameCode = "Lazatin"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESTRELLA, CONRADO III M."
nameCode = "Estrella"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AQUINO, FLORANTE L."
nameCode = "Aquino"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GILLEGO, BONIFACIO H."
nameCode = "Gillego"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SINGSON, LUIS C."
nameCode = "Singson"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "PUBLIC INFORMATION"
type = "primary"
referralCode = "528"
dateRead = "1987-10-16"

[[committee]]
name = "GOVERNMENT REORGANIZATION"
type = "principal"
referralCode = "0516"

[firstReading]
id = 137507
congress = 8
bill_no = "HB02818"
referral = "528"
ref_name = "PUBLIC INFORMATION"
sub_name = ""
date_read = "1987-10-16"
