billNumber = "HB03170"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB03170"
lastScraped = "2025-09-22T00:46:57.117879"
title = "HB03170"
longTitle = "AN ACT PROVIDING FOR THE CONCRETING, IMPROVEMENT AND MAINTENANCE OF THE TIGAON-GOA-SAN JOSE-LAGONOYNAT IONAL ROAD IN THE PROVINCE OF CAMARINES SUR, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-10-22"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-11-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Pilapil"
[[authorsDetail]]
name = "Pilapil"
nameCode = "Pilapil"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-11-09"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 137859
congress = 8
bill_no = "HB03170"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1987-11-09"
