billNumber = "HB04909"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB04909"
lastScraped = "2025-09-22T00:46:57.413278"
title = "HB04909"
longTitle = "AN ACT PROVIDING FOR THE REPAIR AND IMPROVEMENT OF A MUNICIPAL HALL IN THE MUNICIPALITY OF BACON, PROVINCE OF SORSOGON, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-12-21"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-12-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Escudero"
[[authorsDetail]]
name = "Escudero"
nameCode = "Escudero"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-12-29"

[[committee]]
name = "JUSTICE"
type = "principal"
referralCode = "0520"

[firstReading]
id = 139592
congress = 8
bill_no = "HB04909"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1987-12-29"
