billNumber = "HB04444"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB04444"
lastScraped = "2025-09-22T00:46:57.336338"
title = "HB04444"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A DRAINAGE SYSTEM ALONG MAHARLIKA HIGHWAY TO THE SOUTHEASTOF ALLACAPAN CENTRAL SCHOOL IN THE MUNICIPALITY OF ALLACAPAN, PROVINCE OF CAGAYAN, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1987-12-09"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-12-15"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Puzon"
[[authorsDetail]]
name = "Puzon"
nameCode = "Puzon"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-12-15"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 139128
congress = 8
bill_no = "HB04444"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = "PUBLIC WORKS AND HIGHWAYS"
date_read = "1987-12-15"
