billNumber = "HB04192"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB04192"
lastScraped = "2025-09-22T00:46:57.290600"
title = "HB04192"
longTitle = "AN ACT AMENDING EXECUTIVE ORDER NO. 177, SECTIONS17 AND 19(A) THE CHILD AND YOUTH RESEARCH CENTER AS AN ATTACHED AGENCY TO THE DEPARTMENT OF EDUCATION, CULTURE AND SPORTS AND RENAMING IT TO NATIONALINSTITU TE OF CHILD-YOUTH DEVELOPMENT STUDIES (NICYDS)"
scope = "National"
dateFiled = "1987-12-02"
status = "Pending with the Committee on EDUCATION AND CULTURE since 1987-12-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Garcia"
coAuthors = [ "AQUINO, HERMINIO S.",]
[[authorsDetail]]
name = "Garcia"
nameCode = "Garcia"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "AQUINO, HERMINIO S."
nameCode = "Aquino"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "509"
dateRead = "1987-12-08"

[[committee]]
name = "ENERGY"
type = "principal"
referralCode = "0510"

[firstReading]
id = 138878
congress = 8
bill_no = "HB04192"
comm_act = "CONSOLIDAT ED WITH HB 7411"
referral = "509"
ref_name = "EDUCATION AND CULTURE"
sub_name = ""
date_read = "1987-12-08"
