billNumber = "HB04201"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB04201"
lastScraped = "2025-09-22T00:46:57.292267"
title = "HB04201"
longTitle = "AN ACT PROVIDING FOR THE INCLUSION AS MEMBERS OF THE BOARD OF TRUSTEES THE PROVINCIAL ELECTED REPRESENTATIVES IN THE CONGRESS AND ALL THE INCUMBENT MAYORS IN THE PROVINCE, AMENDING FOR THE PURPOSE FIRST PARAGRAPH OF SECTION SIX OF BATAS PAMBANSA BILANG TATLONG DAAN PITUMPU'T PITO, OTHERWISE KNOWN AS AN \"ACT CONVERTING THE MARINDUQUE SCHOOL OF ARTSAND TRADE INTO MARINDUQUE INSTITUTE OF SCIENCE AND TECHNOLOGY,\" BROADENING FOR THE PURPOSE ITS CURRICULAR PROGRAMS IN SCIENCE AND TECHNOLOGY"
scope = "Local"
dateFiled = "1987-12-02"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1987-12-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Reyes"
[[authorsDetail]]
name = "Reyes"
nameCode = "Reyes"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1987-12-08"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 138887
congress = 8
bill_no = "HB04201"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1987-12-08"
