billNumber = "HB05751"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB05751"
lastScraped = "2025-09-22T00:46:57.556989"
title = "HB05751"
longTitle = "AN ACT TO FURTHER AMEND ACT NO. 3815, AS AMENDED BY P.D. 1232 IN ORDER TO INCREASE THE PENALTY FOR OFFENSES COMMITTED AGAINST ANY TRAVELER IS IN THE IMMEDIATE VICINITY OF AN INTERNATIONAL PORT FACILITY (WHETHER SUCH FACILITY BE SEAPORT OF AN AIRPORT), IMMEDIATELY AFTER ARRIVAL OR IMMEDIATELY PRIOR TO DEPARTURE, OR IF THE OFFENSE IS COMMITTED WHILESUCH TRAVELER IS ON HIS WAY TO OR FROM AN INTERNATIONAL PORT FACILITY"
scope = "National"
dateFiled = "1988-02-24"
status = "Pending with the Committee on REVISION OF LAWS since 1988-03-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Santos"
coAuthors = [ "MONFORT, NARCISO D.",]
[[authorsDetail]]
name = "Santos"
nameCode = "Santos"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "531"
dateRead = "1988-03-01"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 140432
congress = 8
bill_no = "HB05751"
referral = "531"
ref_name = "REVISION OF LAWS"
sub_name = ""
date_read = "1988-03-01"
