billNumber = "HB05271"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB05271"
lastScraped = "2025-09-22T00:46:57.478204"
title = "HB05271"
longTitle = "AN ACT GRANTING MONTHLY COMPENSATION TO BARANGAY OFFICIALS AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1988-02-04"
status = "Pending with the Committee on LOCAL GOVERNMENT since 1988-02-08"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Yap"
coAuthors = [ "YAP, RENATO A.", "ROA, BENEDICTA B.", "MAR, RAUL V. DEL", "ALMARIO, THELMA Z.", "LABARIA, VIOLETA T.", "MONFORT, NARCISO D.", "PAYUMO, FELICITO C.", "ESTRELLA, ERNESTO T.", "BERNARDEZ, RUDOLFO A.", "CLAVER, WILLIAM F.", "MASKARINO, CORNELIO P.", "SATOR, BALTAZAR A.", "UNICO, RENATO M.",]
[[authorsDetail]]
name = "Yap"
nameCode = "Yap"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "YAP, RENATO A."
nameCode = "Yap"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROA, BENEDICTA B."
nameCode = "Roa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAR, RAUL V. DEL"
nameCode = "Mar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALMARIO, THELMA Z."
nameCode = "Almario"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LABARIA, VIOLETA T."
nameCode = "Labaria"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PAYUMO, FELICITO C."
nameCode = "Payumo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESTRELLA, ERNESTO T."
nameCode = "Estrella"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BERNARDEZ, RUDOLFO A."
nameCode = "Bernardez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CLAVER, WILLIAM F."
nameCode = "Claver"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MASKARINO, CORNELIO P."
nameCode = "Maskarino"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SATOR, BALTAZAR A."
nameCode = "Sator"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "UNICO, RENATO M."
nameCode = "Unico"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "522"
dateRead = "1988-02-08"

[[committee]]
name = "PUBLIC INFORMATION"
type = "principal"
referralCode = "0528"

[firstReading]
id = 139954
congress = 8
bill_no = "HB05271"
referral = "522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
date_read = "1988-02-08"
