billNumber = "HB05181"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB05181"
lastScraped = "2025-09-22T00:46:57.457701"
title = "HB05181"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A RURAL HEALTH CENTER IN BARANGAY PAWA, MUNICIPALITY OF CUYO, PROVINCE OF PALAWAN, TO BE KNOWN AS THE PAWA RURAL HEALTH CENTER, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-01-28"
status = "Pending with the Committee on HEALTH since 1988-02-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ponce De Leon"
coAuthors = [ "ROA, BENEDICTA B.", "MITRA, RAMON JR. V.",]
[[authorsDetail]]
name = "Ponce De Leon"
nameCode = "Ponce De Leon"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ROA, BENEDICTA B."
nameCode = "Roa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MITRA, RAMON JR. V."
nameCode = "Mitra"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1988-02-04"

[[committee]]
name = "ECONOMIC AFFAIRS"
type = "principal"
referralCode = "0536"

[firstReading]
id = 139864
congress = 8
bill_no = "HB05181"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1988-02-04"
