billNumber = "HB05331"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB05331"
lastScraped = "2025-09-22T00:46:57.487509"
title = "HB05331"
longTitle = "AN ACT ESTABLISHING A FIFTEEN-BED CAPACITY EMERGENCY HOSPITAL IN THE MUNICIPALITY OF PLARIDEL, PROVINCE OF BULACAN, TO BE KNOWN AS THE PLARIDEL EMERGENCY HOSPITAL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-02-08"
status = "Pending with the Committee on HEALTH since 1988-02-10"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Rivera"
[[authorsDetail]]
name = "Rivera"
nameCode = "Rivera"
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1988-02-10"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[firstReading]
id = 140014
congress = 8
bill_no = "HB05331"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1988-02-10"
