billNumber = "HB06353"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB06353"
lastScraped = "2025-09-22T00:46:57.738410"
title = "HB06353"
longTitle = "AN ACT REQUIRING THE GOVERNMENT TELECOMMUNICATI ONS OFFICE AND PRIVATE TELECOMMUNICATI ONS FIRMS TO OFFER PUBLIC INTEREST TELEGRAM SERVICE"
scope = "National"
dateFiled = "1988-03-11"
status = "Pending with the Committee on TRANSPORTATION AND COMMUNICATION since 1988-03-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lagman, Edcel C."
coAuthors = [ "BANDON, ALAWADIN JR. T.", "LABARIA, VIOLETA T.", "DRAGON, RENATO P.", "COSETENG, ANNA DOMINIQUE M. L.",]
[[authorsDetail]]
name = "Lagman, Edcel C."
nameCode = "Lagman"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "BANDON, ALAWADIN JR. T."
nameCode = "Bandon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LABARIA, VIOLETA T."
nameCode = "Labaria"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "COSETENG, ANNA DOMINIQUE M. L."
nameCode = "Coseteng"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "TRANSPORTATION AND COMMUNICATION"
type = "primary"
referralCode = "540"
dateRead = "1988-03-16"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 141034
congress = 8
bill_no = "HB06353"
referral = "540"
ref_name = "TRANSPORTATION AND COMMUNICATION"
sub_name = ""
date_read = "1988-03-16"
