billNumber = "HB06495"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB06495"
lastScraped = "2025-09-22T00:46:57.762559"
title = "HB06495"
longTitle = "AN ACT INCREASING THE PENALTY FOR ILLEGAL RECRUITMENT AMENDING FOR THE PURPOSE ARTICLE THIRTY-NINE OF PRESIDENTIAL DECREE NUMBERED FOUR HUNDRED AND FORTY TWO, OTHERWISE KNOWN AS THE LABOR CODE OF THEPHILIPPINES, AS AMENDED"
scope = "National"
dateFiled = "1988-03-15"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 1988-03-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Singson"
coAuthors = [ "SINGSON, ERIC D.", "ESTRELLA, ERNESTO T.",]
[[authorsDetail]]
name = "Singson"
nameCode = "Singson"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "SINGSON, ERIC D."
nameCode = "Singson"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESTRELLA, ERNESTO T."
nameCode = "Estrella"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "521"
dateRead = "1988-03-17"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 141176
congress = 8
bill_no = "HB06495"
referral = "521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
date_read = "1988-03-17"
