billNumber = "HB07127"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB07127"
lastScraped = "2025-09-22T00:46:57.859951"
title = "HB07127"
longTitle = "AN ACT ESTABLISHING AN ICE PLANT AND COLD STORAGEIN BARANGAY CALUMPANG, MUNICIPALITY OF BALUD, PROVINCE OF MASBATE, AND APPROPRIATING FUNDS THEREFORAND FOR OTHER PURPOSESAN ACT ESTABLISHING AN ICE PLANT AND COLD STORAGEIN BARANGAY CALUMPANG, MUNICIPALITY OF BALUD, PROVINCE OF MASBATE, AND APPROPRIATING FUNDS THEREFORAND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "1988-03-23"
status = "Pending with the Committee on AGRICULTURE AND FOODS since 1988-03-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bakunawa"
[[authorsDetail]]
name = "Bakunawa"
nameCode = "Bakunawa"
date = ""
sequence = 0

[[committee]]
name = "AGRICULTURE AND FOODS"
type = "primary"
referralCode = "503"
dateRead = "1988-03-25"

[[committee]]
name = "CIVIL SERVICE AND PROFESSIONAL REGULATION"
type = "principal"
referralCode = "0506"

[firstReading]
id = 141808
congress = 8
bill_no = "HB07127"
referral = "503"
ref_name = "AGRICULTURE AND FOODS"
sub_name = ""
date_read = "1988-03-25"
