billNumber = "HB08442"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB08442"
lastScraped = "2025-09-22T00:46:58.095590"
title = "HB08442"
longTitle = "AN ACT APPROPRIATING THE SUM OF ONE MILLION THREEHUNDRED FIFTY THOUSAND PESOS (P1,350,000.00) FOR THE CONSTRUCTION OF AN ALL-WEATHER FARM-TO-MARKET ROAD CONNECTING BARANGAY SAN JOSE, BARANGAY MAMUNTAY AND BARANGAY PINAGWARISAN, ALL IN THE MUNICIPALITY OF BANSUD, PROVINCE OF CAMARINES NORTE"
scope = "Local"
dateFiled = "1988-04-28"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-05-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Unico"
[[authorsDetail]]
name = "Unico"
nameCode = "Unico"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-05-03"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 143120
congress = 8
bill_no = "HB08442"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-05-03"
