billNumber = "HB08142"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB08142"
lastScraped = "2025-09-22T00:46:58.022609"
title = "HB08142"
longTitle = "AN ACT CONVERTING THE BAGUMBAYAN-KULA MAN-LEBAK PROVINCIAL ROAD OF THE PROVINCE OF SULTAN KUDARAT, INTO A NATIONAL ROAD"
scope = "Local"
dateFiled = "1988-04-25"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-04-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Valdez"
[[authorsDetail]]
name = "Valdez"
nameCode = "Valdez"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-04-28"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 142820
congress = 8
bill_no = "HB08142"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-04-28"
