billNumber = "HB08335"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB08335"
lastScraped = "2025-09-22T00:46:58.077773"
title = "HB08335"
longTitle = "AN ACT ESTABLISHING A RATTAN AND BAMBOO SEEDLING FARM IN THE MUNICIPALITY OF BANAYBANAY, PROVINCE OF DAVAO ORIENTAL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-04-27"
status = "Pending with the Committee on AGRICULTURE AND FOODS since 1988-05-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Almario"
[[authorsDetail]]
name = "Almario"
nameCode = "Almario"
date = ""
sequence = 0

[[committee]]
name = "AGRICULTURE AND FOODS"
type = "primary"
referralCode = "503"
dateRead = "1988-05-02"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 143013
congress = 8
bill_no = "HB08335"
referral = "503"
ref_name = "AGRICULTURE AND FOODS"
sub_name = ""
date_read = "1988-05-02"
