billNumber = "HB08731"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB08731"
lastScraped = "2025-09-22T00:46:58.141155"
title = "HB08731"
longTitle = "AN ACT CONVERTING THE TIAGAN-MATIBUEY BARANGAY HIGH SCHOOL IN THE MUNICIPALITY OF SAN EMILIO, PROVINCE OF ILOCOS SUR, INTO A NATIONAL HIGH SCHOOL TO BE KNOWN AS THE TIAGAN-MATIBUEY NATIONAL HIGH SCHOOL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-05-04"
status = "Pending with the Committee on EDUCATION AND CULTURE since 1988-05-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Singson"
coAuthors = [ "SINGSON, LUIS C.",]
[[authorsDetail]]
name = "Singson"
nameCode = "Singson"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "SINGSON, LUIS C."
nameCode = "Singson"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "509"
dateRead = "1988-05-09"

[[committee]]
name = "ECOLOGY"
type = "principal"
referralCode = "A501"

[firstReading]
id = 143408
congress = 8
bill_no = "HB08731"
referral = "509"
ref_name = "EDUCATION AND CULTURE"
sub_name = ""
date_read = "1988-05-09"
