billNumber = "HB09229"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB09229"
lastScraped = "2025-09-22T00:46:58.221420"
title = "HB09229"
longTitle = "AN ACT CREATING A SPECIAL HEALTH CARE FUND AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1988-05-10"
status = "Pending with the Committee on HEALTH since 1988-05-16"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Monfort"
coAuthors = [ "LABARIA, VIOLETA T.", "ALMARIO, THELMA Z.",]
[[authorsDetail]]
name = "Monfort"
nameCode = "Monfort"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LABARIA, VIOLETA T."
nameCode = "Labaria"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALMARIO, THELMA Z."
nameCode = "Almario"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1988-05-16"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 143904
congress = 8
bill_no = "HB09229"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1988-05-16"
