billNumber = "HB11524"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB11524"
lastScraped = "2025-09-22T00:46:58.589861"
title = "HB11524"
longTitle = "AN ACT TO FURTHER EXTEND PROTECTION TO LABOR, STRENGTHEN THE CONSTITUTIONAL RIGHTS OF WORKERS TO SELF-ORGANIZATI ON AND FREE COLLECTIVE BARGAINING, AND PROMOTE INDUSTRIAL PEACE, AMENDING FOR THE PURPOSE CERTAIN PROVISIONS OF PD 442, OTHERWISE KNOWNAS THE LABOR CODE OF THE PHILIPPINES, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1988-05-30"
status = "REPUBLIC ACT (RA06715) enacted on 1989-03-02"
statusOrder = 33.0
urgent = true
adminBill = true
pdfUrl = ""
fileSize = 0
coAuthors = [ "CHIPECO, JOAQUIN JR. M.",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "CHIPECO, JOAQUIN JR. M."
nameCode = "Chipeco"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "532"
dateRead = "1988-05-30"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 146193
congress = 8
bill_no = "HB11524"
report = "00187"
referral = "532"
ref_name = "RULES"
sub_name = "LABOR AND EMPLOYMENT"
recomm = "APPROVAL"
date_read = "1988-05-30"
date_ob = "1988-05-30"
date_cal = "1988-05-30"
date_unass = "1988-05-30"
date_report = "1988-05-30"

[secondReading]
id = 20749
congress = 8
bill_no = "HB11524"
date_approved = "1988-10-05"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 524
congress = 8
bill_no = "HB11524"
date_dist = "1988-10-17"
date_adopt = "1988-10-21"
no_yeas = 131
no_nays = 0
no_abstent = 0
date_trans = "1988-10-24"
date_rqcc = "1988-11-28"
date_agrcc = "1989-01-12"
ccreqby = "H"
act_pres = "A"
dte_hsagcc = "1989-01-19"
dte_snagcc = "1989-01-23"
dte_transp = "1989-02-08"
dte_actedp = "1989-03-02"
