billNumber = "HB11145"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB11145"
lastScraped = "2025-09-22T00:46:58.528200"
title = "HB11145"
longTitle = "AN ACT ESTABLISHING A PUBLIC INFORMATION CENTER IN MALASSA, BONGAO, TAWI-TAWI, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-05-26"
status = "Pending with the Committee on PUBLIC ORDER AND SECURITY since 1988-05-31"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bandon"
[[authorsDetail]]
name = "Bandon"
nameCode = "Bandon"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC ORDER AND SECURITY"
type = "primary"
referralCode = "529"
dateRead = "1988-05-31"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 145814
congress = 8
bill_no = "HB11145"
referral = "529"
ref_name = "PUBLIC ORDER AND SECURITY"
sub_name = ""
date_read = "1988-05-31"
