billNumber = "HB12837"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB12837"
lastScraped = "2025-09-22T00:46:58.853493"
title = "HB12837"
longTitle = "AN ACT ESTABLISHING A BARANGAY HEALTH CENTER IN BARANGAY LAHUG IN CEBU CITY, TO BE KNOWN AS THE LAHUG HEALTH CENTER, AND APPROPRIATING FUNDS THEREFORAN ACT ESTABLISHING A BARANGAY HEALTH CENTER IN BARANGAY LAHUG IN CEBU CITY, TO BE KNOWN AS THE LAHUG HEALTH CENTER, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-06-06"
status = "Pending with the Committee on HEALTH since 1988-06-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Mar"
[[authorsDetail]]
name = "Mar"
nameCode = "Mar"
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1988-06-09"

[firstReading]
id = 147505
congress = 8
bill_no = "HB12837"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1988-06-09"
