billNumber = "HB14603"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB14603"
lastScraped = "2025-09-22T00:46:59.139348"
title = "HB14603"
longTitle = "1988 NA BATAS PARA SA KAGAMITANG PANG-GAWAING-BA YAN O PUBLIC WORKS EQUIPMENT ACT OF 19881988 NA BATAS PARA SA KAGAMITANG PANG-GAWAING-BA YAN O PUBLIC WORKS EQUIPMENT ACT OF 19881988 NA BATAS PARA SA KAGAMITANG PANG-GAWAING-BA YAN O PUBLIC WORKS EQUIPMENT ACT OF 19881988 NA BATAS PARA SA KAGAMITANG PANG-GAWAING-BA YAN O PUBLIC WORKS EQUIPMENT ACT OF 1988"
scope = "National"
dateFiled = "1988-07-22"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-07-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Joson"
coAuthors = [ "DANS, ALVIN G.", "WEBB, FREDDIE N.",]
[[authorsDetail]]
name = "Joson"
nameCode = "Joson"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DANS, ALVIN G."
nameCode = "Dans"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "WEBB, FREDDIE N."
nameCode = "Webb"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-07-28"

[firstReading]
id = 149267
congress = 8
bill_no = "HB14603"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-07-28"
