billNumber = "HB14727"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB14727"
lastScraped = "2025-09-22T00:46:59.157901"
title = "HB14727"
longTitle = "AN ACT CONVERTING THE LUMBOG-BIU-OS ROAD IN THE MUNICIPALITY OF VINCENZO SAGUN, PROVINCE OF ZAMBOANGA DEL SUR, INTO A NATIONAL ROAD TO BE KNOWN AS THE LUMBOG-BIU-OS NATIONAL ROAD AND APPROPRIATING FUNDS THEREFORAN ACT CONVERTING THE LUMBOG-BIU-OS ROAD IN THE MUNICIPALITY OF VINCENZO SAGUN, PROVINCE OF ZAMBOANGA DEL SUR, INTO A NATIONAL ROAD TO BE KNOWN AS THE LUMBOG-BIU-OS NATIONAL ROAD AND APPROPRIATING FUNDS THEREFORAN ACT CONVERTING THE LUMBOG-BIU-OS ROAD IN THE MUNICIPALITY OF VINCENZO SAGUN, PROVINCE OF ZAMBOANGA DEL SUR, INTO A NATIONAL ROAD TO BE KNOWN AS THE LUMBOG-BIU-OS NATIONAL ROAD AND APPROPRIATING FUNDS THEREFORAN ACT CONVERTING THE LUMBOG-BIU-OS ROAD IN THE MUNICIPALITY OF VINCENZO SAGUN, PROVINCE OF ZAMBOANGA DEL SUR, INTOA NATIONAL ROAD TO BE KNOWN AS THE LUMBOG-BIU-OS NATIONAL ROAD AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1988-07-26"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-08-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Cerilles"
[[authorsDetail]]
name = "Cerilles"
nameCode = "Cerilles"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-08-01"

[firstReading]
id = 149390
congress = 8
bill_no = "HB14727"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-08-01"
