billNumber = "HB15922"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB15922"
lastScraped = "2025-09-22T00:46:59.339878"
title = "HB15922"
longTitle = "AN ACT APPROPRIATING THE SUM OF FIVE HUNDRED THOUSAND PESOS (P500,000.00) FOR THE REPAIR AND IMPROVEMENT OF THE DRAINAGE SYSTEM OF 1ST STREET, FROM RODRIGUEZ AVENUE TO EXEQUIEL STREET, BARANGAY STO. NINO, MUNICIPALITY OF MARIKINA, METRO MANILA"
scope = "Local"
dateFiled = "1988-08-15"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-08-18"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Angeles"
[[authorsDetail]]
name = "Angeles"
nameCode = "Angeles"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-08-18"

[firstReading]
id = 150572
congress = 8
bill_no = "HB15922"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-08-18"
