billNumber = "HB16443"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB16443"
lastScraped = "2025-09-22T00:46:59.419734"
title = "HB16443"
longTitle = "AN ACT ESTABLISHING A MINI-SPORTS CENTER IN BARANGAY TOLOGAN, MUNICIPALITY OF HAGONOY, PROVINCE OF DAVAO DEL SUR"
scope = "Local"
dateFiled = "1988-08-23"
status = "Pending with the Committee on YOUTH AND SPORTS DEVELOPMENT since 1988-08-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Camasura"
[[authorsDetail]]
name = "Camasura"
nameCode = "Camasura"
date = ""
sequence = 0

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "primary"
referralCode = "543"
dateRead = "1988-08-29"

[firstReading]
id = 151089
congress = 8
bill_no = "HB16443"
referral = "543"
ref_name = "YOUTH AND SPORTS DEVELOPMENT"
sub_name = ""
date_read = "1988-08-29"
