billNumber = "HB19514"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB19514"
lastScraped = "2025-09-22T00:46:59.902095"
title = "HB19514"
longTitle = "AN ACT ABOLISHING SMALL BARANGAYSAN ACT ABOLISHING SMALL BARANGAYS"
scope = "National"
dateFiled = "1988-10-17"
status = "Pending with the Committee on LOCAL GOVERNMENT since 1988-10-20"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Montejo"
coAuthors = [ "ADASA, ARTEMIO JR. A.",]
[[authorsDetail]]
name = "Montejo"
nameCode = "Montejo"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ADASA, ARTEMIO JR. A."
nameCode = "Adasa"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "522"
dateRead = "1988-10-20"

[firstReading]
id = 154144
congress = 8
bill_no = "HB19514"
referral = "522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
date_read = "1988-10-20"
