billNumber = "HB19831"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB19831"
lastScraped = "2025-09-22T00:46:59.951126"
title = "HB19831"
longTitle = "AN ACT GRANTING TO TARLAC ENTERPRISES, INC., A FRANCHISE TO CONSTRUCT, MAINTAIN AND OPERATE AN ELECTRIC LIGHT, HEAT AND POWER SYSTEM IN THE MUNICIPALITY OF TARLAC, PROVINCE OF TARLAC FOR A PERIOD OF TWENTY-FIVE YEARS, AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "1988-10-28"
status = "REPUBLIC ACT RA07606 (Lapsed into law on 1992-06-04)"
statusOrder = 32.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Tinga"
coAuthors = [ "YAP, JOSE V.", "CORPORATIONS AND FRANCHISES", "BACALTOS, ANTONIO T.", "BAGATSING, RAMON  JR. S.", "BENGSON, ANTONIO III E.", "CABOCHAN, JOSE L.", "CAMASURA, JUANITO JR. G.", "CHIPECO, JOAQUIN JR. M.", "DIMAPORO, ABDULLAH D.", "DOMINGO, SIMPLICIO JR. B.", "DRAGON, RENATO P.", "ENVERGA, WILFRIDO L.", "ESCUDERO, SALVADOR III H.", "ESPINOSA, MOISES R.", "LAGMAN, EDCEL C.", "LAZATIN, CARMELO F.", "TAGARAO, MARIO L.", "TUPAS, NIEL D.", "YAP, RENATO A.", "YULO, MARIANO M.", "ZARRAGA, ISIDRO C.",]
[[authorsDetail]]
name = "Tinga"
nameCode = "Tinga"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "YAP, JOSE V."
nameCode = "Yap"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CORPORATIONS AND FRANCHISES"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BACALTOS, ANTONIO T."
nameCode = "Bacaltos"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BAGATSING, RAMON  JR. S."
nameCode = "Bagatsing"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BENGSON, ANTONIO III E."
nameCode = "Bengson"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CABOCHAN, JOSE L."
nameCode = "Cabochan"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CAMASURA, JUANITO JR. G."
nameCode = "Camasura"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CHIPECO, JOAQUIN JR. M."
nameCode = "Chipeco"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DIMAPORO, ABDULLAH D."
nameCode = "Dimaporo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DOMINGO, SIMPLICIO JR. B."
nameCode = "Domingo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ENVERGA, WILFRIDO L."
nameCode = "Enverga"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESCUDERO, SALVADOR III H."
nameCode = "Escudero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESPINOSA, MOISES R."
nameCode = "Espinosa"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAGMAN, EDCEL C."
nameCode = "Lagman"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LAZATIN, CARMELO F."
nameCode = "Lazatin"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAGARAO, MARIO L."
nameCode = "Tagarao"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TUPAS, NIEL D."
nameCode = "Tupas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "YAP, RENATO A."
nameCode = "Yap"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "YULO, MARIANO M."
nameCode = "Yulo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ZARRAGA, ISIDRO C."
nameCode = "Zarraga"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "532"
dateRead = "1989-04-18"

[firstReading]
id = 154460
congress = 8
bill_no = "HB19831"
report = "00390"
referral = "532"
ref_name = "RULES"
sub_name = "CORPORATIONS AND FRANCHISES"
recomm = "APPROVAL IN SUBSTITUTI ON OF HB05177"
date_read = "1989-04-18"
date_ob = "1989-04-18"
date_cal = "1989-04-18"
date_unass = "1989-04-18"
date_report = "1988-10-28"

[secondReading]
id = 20905
congress = 8
bill_no = "HB19831"
date_calendared = "1989-04-18"
date_approved = "1989-04-21"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 675
congress = 8
bill_no = "HB19831"
date_dist = "1989-04-27"
date_adopt = "1989-05-18"
no_yeas = 142
no_nays = 0
no_abstent = 0
date_trans = "1989-05-19"
date_rec = "1989-05-24"
date_agram = "1992-02-04"
amend_ind = "Y"
act_pres = "L"
dte_transp = "1992-03-26"
dte_actedp = "1992-06-04"
