billNumber = "HB20634"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB20634"
lastScraped = "2025-09-22T00:47:00.067911"
title = "HB20634"
longTitle = "AN ACT PROVIDING FOR THE CEMENTING OF THE TALUDTUD BARANGAY ROAD IN BARANGAY TALUDTUD, MUNICIPALITYOF BALAYAN, PROVINCE OF BATANGAS"
scope = "Local"
dateFiled = "1988-11-23"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-11-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Apacible"
[[authorsDetail]]
name = "Apacible"
nameCode = "Apacible"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-11-28"

[firstReading]
id = 155260
congress = 8
bill_no = "HB20634"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-11-28"
