billNumber = "HB20480"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB20480"
lastScraped = "2025-09-22T00:47:00.045025"
title = "HB20480"
longTitle = "AN ACT PROVIDING FOR THE REHABILITATION OF THE CALINGLEBENG-BA BADAC ROAD IN THE MUNICIPALITY OF KABAYAN, PROVINCE OF BENGUET, AND APPROPRIATING FUNDSTHEREFOR"
scope = "Local"
dateFiled = "1988-11-21"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1988-11-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Dangwa"
[[authorsDetail]]
name = "Dangwa"
nameCode = "Dangwa"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1988-11-24"

[firstReading]
id = 155107
congress = 8
bill_no = "HB20480"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1988-11-24"
