billNumber = "HB21668"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB21668"
lastScraped = "2025-09-22T00:47:00.253611"
title = "HB21668"
longTitle = "AN ACT DECLARING THE PARCEL OF LAND WITH LOT NO. 1882-TS-220 KNOWN AS THE NURSERY SITE SITUATED AT BARANGAY POBLACION, MUNICIPALITY OF KIDAPAWAN, PROVINCE OF COTABATO, AS A HOUSING SITE, TO BE ALIENATED AND AWARDED TO ITS PRESENT AND ACTUAL OCCUPANTS"
scope = "Local"
dateFiled = "1989-01-10"
status = "Pending with the Committee on HOUSING since 1989-01-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Andolana"
coAuthors = [ "WEBB, FREDDIE N.",]
[[authorsDetail]]
name = "Andolana"
nameCode = "Andolana"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "WEBB, FREDDIE N."
nameCode = "Webb"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "HOUSING"
type = "primary"
referralCode = "518"
dateRead = "1989-01-17"

[firstReading]
id = 156287
congress = 8
bill_no = "HB21668"
referral = "518"
ref_name = "HOUSING"
sub_name = ""
date_read = "1989-01-17"
