billNumber = "HB24388"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB24388"
lastScraped = "2025-09-22T00:47:00.677245"
title = "HB24388"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF THE BARANGAY HALL OF BARANGAY CASILE IN THE MUNICIPALITY OF BINAN, PROVINCE OF LAGUNA, AND APPROPRIATING FUND THEREFOR"
scope = "Local"
dateFiled = "1989-05-12"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1989-05-17"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Joaquin"
coAuthors = [ "DRAGON, RENATO P.",]
[[authorsDetail]]
name = "Joaquin"
nameCode = "Joaquin"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1989-05-17"

[firstReading]
id = 158949
congress = 8
bill_no = "HB24388"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1989-05-17"
