billNumber = "HB24664"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB24664"
lastScraped = "2025-09-22T00:47:00.719583"
title = "HB24664"
longTitle = "AN ACT REORGANIZING THE NATIONAL STUD FARM, DEFINING ITS POWERS AND FUNCTIONS, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1989-05-29"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES since 1989-05-31"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bagatsing"
coAuthors = [ "BAGATSING, AMADO S.", "GUZMAN, NICANOR JR. G. DE", "COJUANGCO, JOSE  JR. S.", "ZARRAGA, ISIDRO C.",]
[[authorsDetail]]
name = "Bagatsing"
nameCode = "Bagatsing"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "BAGATSING, AMADO S."
nameCode = "Bagatsing"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GUZMAN, NICANOR JR. G. DE"
nameCode = "Guzman"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "COJUANGCO, JOSE  JR. S."
nameCode = "Cojuangco"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ZARRAGA, ISIDRO C."
nameCode = "Zarraga"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES"
type = "primary"
referralCode = "515"
dateRead = "1989-05-31"

[firstReading]
id = 159214
congress = 8
bill_no = "HB24664"
referral = "515"
ref_name = "GOVERNMENT ENTERPRISES"
sub_name = ""
date_read = "1989-05-31"
