billNumber = "HB24401"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB24401"
lastScraped = "2025-09-22T00:47:00.678970"
title = "HB24401"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A PRIMARY SCHOOLBUILDING FOR THE CHAPIDES PRIMARY SCHOOL IN BARANGAY GUSARAN, MUNICIPALITY OF KABAYAN, PROVINCE OF BENGUET, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1989-05-15"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1989-05-18"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Dangwa"
[[authorsDetail]]
name = "Dangwa"
nameCode = "Dangwa"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1989-05-18"

[firstReading]
id = 158962
congress = 8
bill_no = "HB24401"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1989-05-18"
