billNumber = "HB25927"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB25927"
lastScraped = "2025-09-22T00:47:00.939345"
title = "HB25927"
longTitle = "AN ACT PROVIDING FOR THE ASPHALTING OF THE BARANGAY ROAD IN BARANGAY IBA, MUNICIPALITY OF TAAL, PROVINCE OF BATANGAS, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1989-08-17"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1989-08-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Apacible"
[[authorsDetail]]
name = "Apacible"
nameCode = "Apacible"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1989-08-28"

[firstReading]
id = 160444
congress = 8
bill_no = "HB25927"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1989-08-28"
