billNumber = "HB25144"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB25144"
lastScraped = "2025-09-22T00:47:00.792604"
title = "HB25144"
longTitle = "AN ACT ESTABLISHING AN AGRICULTURAL HIGH SCHOOL IN THE DISTRICT OF MARILAG, CITY OF DAVAO TO BE KNOWN AS MARILAG HIGH SCHOOL OF AGRICULTURE, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1989-06-15"
status = "REPUBLIC ACT (RA07019) enacted on 1991-05-20"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
coAuthors = [ "APPROPRIATIONS",]
[[authorsDetail]]
name = ""
nameCode = ""
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "APPROPRIATIONS"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "532"
dateRead = "1989-08-07"

[firstReading]
id = 159685
congress = 8
bill_no = "HB25144"
report = "00697"
referral = "532"
ref_name = "RULES"
sub_name = "EDUCATION AND CULTURE"
recomm = "APPROVAL IN SUBSTITUTI ON OF HB00465"
date_read = "1989-08-07"
date_ob = "1990-08-07"
date_cal = "1990-08-07"
date_unass = "1990-08-07"
date_report = "1989-06-15"

[secondReading]
id = 21081
congress = 8
bill_no = "HB25144"
date_approved = "1989-09-29"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 839
congress = 8
bill_no = "HB25144"
date_dist = "1989-10-10"
date_adopt = "1989-11-23"
no_yeas = 140
no_nays = 0
no_abstent = 0
date_trans = "1989-11-24"
date_rec = "1989-12-11"
amend_ind = "N"
act_pres = "A"
dte_transp = "1991-04-18"
dte_actedp = "1991-05-20"
