billNumber = "HB25113"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB25113"
lastScraped = "2025-09-22T00:47:00.787791"
title = "HB25113"
longTitle = "AN ACT AMENDING REPUBLIC ACT 6425 (THE DANGEROUS DRUGS OF 1972), AS AMENDED"
scope = "National"
dateFiled = "1989-06-09"
status = "Pending with the Committee on REVISION OF LAWS since 1989-07-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Escudero"
coAuthors = [ "PLAZA, CHARITO B.", "PEDRO, HILARIO III L. DE", "PONCE DE LEON, DAVID A.",]
[[authorsDetail]]
name = "Escudero"
nameCode = "Escudero"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PLAZA, CHARITO B."
nameCode = "Plaza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PEDRO, HILARIO III L. DE"
nameCode = "Pedro"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PONCE DE LEON, DAVID A."
nameCode = "Ponce De Leon"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "REVISION OF LAWS"
type = "primary"
referralCode = "531"
dateRead = "1989-07-25"

[firstReading]
id = 159654
congress = 8
bill_no = "HB25113"
referral = "531"
ref_name = "REVISION OF LAWS"
sub_name = ""
date_read = "1989-07-25"
