billNumber = "HB26918"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB26918"
lastScraped = "2025-09-22T00:47:01.091426"
title = "HB26918"
longTitle = "AN ACT TO CREATE AND ESTABLISH A NATIONAL HIGH SCHOOL IN BARANGAY POBLACION, MUNICIPALITY OF ASTURIAS, PROVINCE OF CEBU, TO BE KNOWN AS THE ASTURIAS NATIONAL HIGH SCHOOL AND TO APPROPRIATE FUNDS THEREFOR"
scope = "Local"
dateFiled = "1989-10-04"
status = "Pending with the Committee on EDUCATION AND CULTURE since 1989-10-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Garcia"
[[authorsDetail]]
name = "Garcia"
nameCode = "Garcia"
date = ""
sequence = 0

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "509"
dateRead = "1989-10-09"

[firstReading]
id = 161422
congress = 8
bill_no = "HB26918"
referral = "509"
ref_name = "EDUCATION AND CULTURE"
sub_name = ""
date_read = "1989-10-09"
