billNumber = "HB27871"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB27871"
lastScraped = "2025-09-22T00:47:01.257974"
title = "HB27871"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A WAITING SHED WITH A TOILET IN BARANGAY ONDOL MUNICIPALITY OF LOBOC PROVINCE OF BOHOL AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1989-12-19"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1989-12-22"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Zarraga"
[[authorsDetail]]
name = "Zarraga"
nameCode = "Zarraga"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1989-12-22"

[firstReading]
id = 162354
congress = 8
bill_no = "HB27871"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1989-12-22"
