billNumber = "HB27608"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB27608"
lastScraped = "2025-09-22T00:47:01.196500"
title = "HB27608"
longTitle = "AN ACT ESTABLISHING A BARANGAY INFORMATION CENTERIN BARANGAY AGUINALDO, MUNICIPALITY OF ARTECHE, PROVINCE OF EASTERN SAMAR"
scope = "Local"
dateFiled = "1989-11-29"
status = "Pending with the Committee on PUBLIC INFORMATION since 1989-12-06"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramirez"
[[authorsDetail]]
name = "Ramirez"
nameCode = "Ramirez"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC INFORMATION"
type = "primary"
referralCode = "528"
dateRead = "1989-12-06"

[firstReading]
id = 162105
congress = 8
bill_no = "HB27608"
referral = "528"
ref_name = "PUBLIC INFORMATION"
sub_name = ""
date_read = "1989-12-06"
