billNumber = "HB29679"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB29679"
lastScraped = "2025-09-22T00:47:01.525312"
title = "HB29679"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF A FISH PORT IN BARANGAY ONDOL, MUNICIPALITY OF INABANGA, PROVINCE OF BOHOL, AND APPROPRIATING FUNDS THEREFORAND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "1990-03-13"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1990-03-19"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Tirol"
[[authorsDetail]]
name = "Tirol"
nameCode = "Tirol"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1990-03-19"

[firstReading]
id = 164151
congress = 8
bill_no = "HB29679"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1990-03-19"
