billNumber = "HB31599"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB31599"
lastScraped = "2025-09-22T00:47:01.845147"
title = "HB31599"
longTitle = "AN ACT ESTABLISHING A 5-BED CAPACITY MEDICAL INFORMARY IN THE MUNICIPALITY OF STA. ELENA, PROVINCE OF CAMARINES NORTE, TO BE KNOWN AS STA. ELENA MEDICAL INFORMARY AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1990-07-31"
status = "REPUBLIC ACT (RA07450) enacted on 1992-04-27"
statusOrder = 33.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Unico"
[[authorsDetail]]
name = "Unico"
nameCode = "Unico"
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1990-08-06"

[firstReading]
id = 166063
congress = 8
bill_no = "HB31599"
report = "01488"
referral = "517"
ref_name = "HEALTH"
sub_name = "HEALTH"
recomm = "Approval with amendments"
date_read = "1990-08-06"
date_ob = "1991-06-03"
date_cal = "1991-06-03"
date_unass = "1991-06-03"
date_report = "1991-05-23"

[secondReading]
id = 21311
congress = 8
bill_no = "HB31599"
date_approved = "1991-08-15"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 1057
congress = 8
bill_no = "HB31599"
date_dist = "1991-08-22"
date_adopt = "1991-09-04"
no_yeas = 140
no_nays = 0
no_abstent = 0
date_trans = "1991-09-05"
amend_ind = "N"
act_pres = "A"
dte_actedp = "1992-04-27"
