billNumber = "HB31226"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB31226"
lastScraped = "2025-09-22T00:47:01.787989"
title = "HB31226"
longTitle = "AN ACT PROVIDING FOR AN INCREASE IN THE TIME ALLOTMENT FOR SCIENCE AND TECHNOLOGY SUBJECTS IN THE ELEMENTARY AND SECONDARY CURRICULUM AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "1990-06-07"
status = "Pending with the Committee on EDUCATION AND CULTURE since 1990-07-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramirez"
coAuthors = [ "WEBB, FREDDIE N.",]
[[authorsDetail]]
name = "Ramirez"
nameCode = "Ramirez"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "WEBB, FREDDIE N."
nameCode = "Webb"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "EDUCATION AND CULTURE"
type = "primary"
referralCode = "509"
dateRead = "1990-07-24"

[firstReading]
id = 165692
congress = 8
bill_no = "HB31226"
referral = "509"
ref_name = "EDUCATION AND CULTURE"
sub_name = ""
date_read = "1990-07-24"
