billNumber = "HB31631"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB31631"
lastScraped = "2025-09-22T00:47:01.850185"
title = "HB31631"
longTitle = "AN ACT PROVIDING FOR THE ACQUISITION AND DEVELOPMENT OF HOUSING FOR THE POOR FISHERMEN OF MALALAG, DAVAO DEL SUR, AND THE APPROPRIATION OF FUNDS THEREFOR"
scope = "Local"
dateFiled = "1990-08-01"
status = "Pending with the Committee on HOUSING since 1990-08-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bautista"
[[authorsDetail]]
name = "Bautista"
nameCode = "Bautista"
date = ""
sequence = 0

[[committee]]
name = "HOUSING"
type = "primary"
referralCode = "518"
dateRead = "1990-08-07"

[firstReading]
id = 166095
congress = 8
bill_no = "HB31631"
referral = "518"
ref_name = "HOUSING"
sub_name = ""
date_read = "1990-08-07"
