billNumber = "HB32600"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB32600"
lastScraped = "2025-09-22T00:47:02.004169"
title = "HB32600"
longTitle = "AN ACT TO ESTABLISH A COCONUT BY-PRODUCT PROCESSING CENTER IN BARANGAY DAMPIGAN, MUNICIPALITY OF DOLORES, PROVINCE OF EASTERN SAMAR, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1990-10-16"
status = "Pending with the Committee on AGRICULTURE AND FOODS since 1990-10-22"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramirez"
[[authorsDetail]]
name = "Ramirez"
nameCode = "Ramirez"
date = ""
sequence = 0

[[committee]]
name = "AGRICULTURE AND FOODS"
type = "primary"
referralCode = "503"
dateRead = "1990-10-22"

[firstReading]
id = 167064
congress = 8
bill_no = "HB32600"
referral = "503"
ref_name = "AGRICULTURE AND FOODS"
sub_name = ""
date_read = "1990-10-22"
