billNumber = "HB32980"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB32980"
lastScraped = "2025-09-22T00:47:02.072200"
title = "HB32980"
longTitle = "AN ACT CREATING THE MUNICIPALITY OF MASAGUISI IN THE PROVINCE OF ORIENTAL MINDORO"
scope = "Local"
dateFiled = "1990-11-27"
status = "Pending with the Committee on LOCAL GOVERNMENT since 1990-12-03"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Punzalan"
[[authorsDetail]]
name = "Punzalan"
nameCode = "Punzalan"
date = ""
sequence = 0

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "522"
dateRead = "1990-12-03"

[firstReading]
id = 167444
congress = 8
bill_no = "HB32980"
referral = "522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
date_read = "1990-12-03"
