billNumber = "HB32643"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB32643"
lastScraped = "2025-09-22T00:47:02.011103"
title = "HB32643"
longTitle = "AN ACT PROVIDING FOR THE IMPROVEMENT OF BARANGAY ROAD AT BARANGAY MAYBOCOG, MUNICIPALITY OF MAYDOLONG, PROVINCE OF EASTERN SAMAR, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1990-10-22"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 1990-10-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramirez"
[[authorsDetail]]
name = "Ramirez"
nameCode = "Ramirez"
date = ""
sequence = 0

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "530"
dateRead = "1990-10-25"

[firstReading]
id = 167107
congress = 8
bill_no = "HB32643"
referral = "530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
date_read = "1990-10-25"
