billNumber = "HB32900"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB32900"
lastScraped = "2025-09-22T00:47:02.056305"
title = "HB32900"
longTitle = "AN ACT PROVIDING FOR LOCAL HOUSING AUTONOMY THROUGH THE ESTABLISHMENT OF LOCAL HOUSING AUTHORITIES THROUGHOUT THE COUNTRY, DEFINING THEIR FUNCTIONS, AND APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1990-11-20"
status = "Pending with the Committee on HOUSING since 1990-11-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Nograles"
coAuthors = [ "RAMIREZ, JOSE T.", "DRAGON, RENATO P.", "MAR, RAUL V. DEL",]
[[authorsDetail]]
name = "Nograles"
nameCode = "Nograles"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "RAMIREZ, JOSE T."
nameCode = "Ramirez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAR, RAUL V. DEL"
nameCode = "Mar"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "HOUSING"
type = "primary"
referralCode = "518"
dateRead = "1990-11-26"

[firstReading]
id = 167364
congress = 8
bill_no = "HB32900"
referral = "518"
ref_name = "HOUSING"
sub_name = ""
date_read = "1990-11-26"
