billNumber = "HB33202"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB33202"
lastScraped = "2025-09-22T00:47:02.106765"
title = "HB33202"
longTitle = "AN ACT PROVIDING FOR THE CONSTRUCTION OF PUBLIC RESTROOMS ALONG NATIONAL HIGHWAYS, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1990-12-14"
status = "Approved by the House on 1991-03-21, transmitted to on 1991-03-22 and received by the Senate on 1991"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Escudero"
coAuthors = [ "PLAZA, CHARITO B.",]
[[authorsDetail]]
name = "Escudero"
nameCode = "Escudero"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PLAZA, CHARITO B."
nameCode = "Plaza"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "532"
dateRead = "1991-01-22"

[firstReading]
id = 167666
congress = 8
bill_no = "HB33202"
report = "01234"
referral = "532"
ref_name = "RULES"
sub_name = "PUBLIC WORKS AND HIGHWAYS"
recomm = "Approval in substituti on of HB 25783"
date_read = "1991-01-22"
date_ob = "1991-01-22"
date_cal = "1991-01-22"
date_unass = "1991-01-22"
date_report = "1990-12-14"

[secondReading]
id = 21372
congress = 8
bill_no = "HB33202"
date_calendared = "1991-02-14"
date_approved = "1991-02-20"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 1104
congress = 8
bill_no = "HB33202"
date_dist = "1991-02-28"
date_adopt = "1991-03-21"
no_yeas = 126
no_nays = 0
no_abstent = 0
date_trans = "1991-03-22"
date_rec = "1991-04-08"
