billNumber = "HB33863"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB33863"
lastScraped = "2025-09-22T00:47:02.215004"
title = "HB33863"
longTitle = "AN ACT PROHIBITING THE APPOINTMENT OF LEADERS OF CITIZENS ARMS DURING ELECTIONS TO GOVERNMENT POSITIONS WITHIN TWO YEARS IMMEDIATELY AFTER THE ELECTION FOR WHICH THEY WERE DEPUTIZED BY THE COMMISSION ON ELECTIONS"
scope = "National"
dateFiled = "1991-03-15"
status = "Pending with the Committee on SUFFRAGE AND ELECTORAL REFORMS since 1991-03-21"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Webb"
coAuthors = [ "LOPEZ, AL IGNATIUS G.",]
[[authorsDetail]]
name = "Webb"
nameCode = "Webb"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LOPEZ, AL IGNATIUS G."
nameCode = "Lopez"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "primary"
referralCode = "537"
dateRead = "1991-03-21"

[firstReading]
id = 168327
congress = 8
bill_no = "HB33863"
referral = "537"
ref_name = "SUFFRAGE AND ELECTORAL REFORMS"
sub_name = ""
date_read = "1991-03-21"
