billNumber = "HB33414"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB33414"
lastScraped = "2025-09-22T00:47:02.143070"
title = "HB33414"
longTitle = "AN ACT CREATING THE MUNICIPALITY OF SAN RAMON IN THE PROVINCE OF MASBATE"
scope = "Local"
dateFiled = "1991-01-30"
status = "Approved by the House on 1991-10-17, transmitted to on 1991-10-18 and received by the Senate on 1991"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Espinosa"
coAuthors = [ "MARTINEZ, CELESTINO JR. E.", "ANDAYA, ROLANDO R.", "LOCAL GOVERNMENT",]
[[authorsDetail]]
name = "Espinosa"
nameCode = "Espinosa"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "MARTINEZ, CELESTINO JR. E."
nameCode = "Martinez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANDAYA, ROLANDO R."
nameCode = "Andaya"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LOCAL GOVERNMENT"
nameCode = ""
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "532"
dateRead = "1991-05-22"

[firstReading]
id = 167878
congress = 8
bill_no = "HB33414"
report = "01298"
referral = "532"
ref_name = "RULES"
sub_name = "LOCAL GOVERNMENT"
recomm = "Approval in substituti on of HB 985"
date_read = "1991-05-22"
date_ob = "1991-05-22"
date_cal = "1991-05-22"
date_unass = "1991-05-22"
date_report = "1991-01-30"

[secondReading]
id = 21388
congress = 8
bill_no = "HB33414"
date_approved = "1991-06-06"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"

[thirdReading]
id = 1119
congress = 8
bill_no = "HB33414"
date_dist = "1991-09-03"
date_adopt = "1991-10-17"
no_yeas = 133
no_nays = 0
no_abstent = 0
date_trans = "1991-10-18"
date_rec = "1991-12-06"
