billNumber = "HB34021"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB34021"
lastScraped = "2025-09-22T00:47:02.242684"
title = "HB34021"
longTitle = "AN ACT ESTABLISHING A FRUIT TREE SEEDLING NURSERY AT BARANGAY UMABAY INTERIOR IN THE MUNICIPALITY OF MOBO, PROVINCE OF MASBATE, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1991-04-24"
status = "Pending with the Committee on AGRICULTURE AND FOODS since 1991-04-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bakunawa"
[[authorsDetail]]
name = "Bakunawa"
nameCode = "Bakunawa"
date = ""
sequence = 0

[[committee]]
name = "AGRICULTURE AND FOODS"
type = "primary"
referralCode = "503"
dateRead = "1991-04-30"

[firstReading]
id = 168483
congress = 8
bill_no = "HB34021"
referral = "503"
ref_name = "AGRICULTURE AND FOODS"
sub_name = ""
date_read = "1991-04-30"
