billNumber = "HB34026"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB34026"
lastScraped = "2025-09-22T00:47:02.243509"
title = "HB34026"
longTitle = "AN ACT ESTABLISHING A BARANGAY HERBAL CENTER IN BARANGAY MABUHAY, MUNICIPALITY OF CAN-AVID, PROVINCE OF EASTERN SAMAR, AND PROVIDING FUNDS THEREFOR"
scope = "Local"
dateFiled = "1991-04-24"
status = "Pending with the Committee on HEALTH since 1991-04-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ramirez"
[[authorsDetail]]
name = "Ramirez"
nameCode = "Ramirez"
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1991-04-30"

[firstReading]
id = 168488
congress = 8
bill_no = "HB34026"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1991-04-30"
