billNumber = "HB35357"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB35357"
lastScraped = "2025-09-22T00:47:02.503580"
title = "HB35357"
longTitle = "AN ACT REVISING THE RGULATIONS FOR THE PRACTICE, LICENSING AND REGISTRATION PF ELECTRICAL ENGINEERS AND ELECTRICIANS, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. ONE HUNDRED AND EIGHTY-FOUR, OTHERWISE KNOWN AS THE \"ELECTRICAL ENGINEERING LAW\""
scope = "National"
dateFiled = "1992-01-22"
status = "Business for the day on 1992-01-30"
statusOrder = 10.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Joaquin"
coAuthors = [ "PALACOL, MAGDALENO M.", "CHIPECO, JOAQUIN JR. M.", "AQUINO, FLORANTE L.", "ESTRELLA, CONRADO III M.",]
[[authorsDetail]]
name = "Joaquin"
nameCode = "Joaquin"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PALACOL, MAGDALENO M."
nameCode = "Palacol"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CHIPECO, JOAQUIN JR. M."
nameCode = "Chipeco"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AQUINO, FLORANTE L."
nameCode = "Aquino"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESTRELLA, CONRADO III M."
nameCode = "Estrella"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "532"
dateRead = "1992-01-27"

[firstReading]
id = 169802
congress = 8
bill_no = "HB35357"
report = "01744"
referral = "532"
ref_name = "RULES"
sub_name = "CIVIL SERVICE"
recomm = "Approval in substituti on of House Bill No. 5507"
date_read = "1992-01-27"
date_ob = "1992-01-27"
date_cal = "1992-01-27"
date_unass = "1992-01-27"
date_report = "1992-01-22"

[secondReading]
id = 21571
congress = 8
bill_no = "HB35357"
date_calendared = "1992-01-30"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = "N"
