billNumber = "HB35303"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HB35303"
lastScraped = "2025-09-22T00:47:02.493978"
title = "HB35303"
longTitle = "AN ACT PROVIDING THAT ANY LAND ACQUIRED UNDER THE FREE PATENT OR HOMESTEAD PROVISIONS, WHEN PROPERLY CONVEYED, SHALL BE SUBJECT TO REPURCHASE WITHIN THREE (3) YEARS FROM THE DATE OF THE CONVEYANCE, AMENDING FOR THE PURPOSE THE PUBLIC LAND ACT"
scope = "National"
dateFiled = "1991-12-18"
status = "Pending with the Committee on NATURAL RESOURCES since 1991-12-19"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Monfort"
[[authorsDetail]]
name = "Monfort"
nameCode = "Monfort"
date = ""
sequence = 0

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "526"
dateRead = "1991-12-19"

[firstReading]
id = 169748
congress = 8
bill_no = "HB35303"
referral = "526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
date_read = "1991-12-19"
