billNumber = "HR00884"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR00884"
lastScraped = "2025-09-22T00:47:02.698621"
title = "HR00884"
longTitle = "RESOLUTION DIRECTING THE HOUSE COMMITTEE ON LABORAND EMPLOYMENT TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, INTO THE REPORTED BANNING OF FILIPINO CONTRACT WORKERS IN THE KINGDOM OF SAUDI ARABIA AND TO PROPOSE MEASURES THEREFOR"
scope = "National"
dateFiled = "1988-08-24"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 1988-08-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Isidro"
[[authorsDetail]]
name = "Isidro"
nameCode = "Isidro"
date = ""
sequence = 0

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "521"
dateRead = "1988-08-30"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 170764
congress = 8
bill_no = "HR00884"
referral = "521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
date_read = "1988-08-30"
