billNumber = "HR00292"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR00292"
lastScraped = "2025-09-22T00:47:02.583381"
title = "HR00292"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON PUBLIC ORDER AND SECURITY TO CONDUCT AN INQUIRY IN AID OF LEGISLATION, INTO THE PROLIFERATION AND CONTINUOUS USE AND MANUFACTURE OF FIRECRACKERS AND PYROTECHNICSWAR E DURING CHRISTMAS, NEW YEAR, TOWN FIESTAS, AND MAJOR EVENTS, AND PROPOSE REMEDIAL MEASURES OR REGULATION THERETO FOR STRICT ENFORCEMENT"
scope = "National"
dateFiled = "1987-09-09"
status = "Pending with the Committee on PUBLIC INFORMATION since 1989-09-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Adasa"
coAuthors = [ "TUPAS, NIEL D.",]
[[authorsDetail]]
name = "Adasa"
nameCode = "Adasa"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "TUPAS, NIEL D."
nameCode = "Tupas"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "PUBLIC INFORMATION"
type = "primary"
referralCode = "528"
dateRead = "1989-09-14"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 170192
congress = 8
bill_no = "HR00292"
referral = "528"
ref_name = "PUBLIC INFORMATION"
sub_name = ""
date_read = "1989-09-14"
