billNumber = "HR00591"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR00591"
lastScraped = "2025-09-22T00:47:02.641956"
title = "HR00591"
longTitle = "RESOLUTION REQUESTING THE PRESIDENT OF THE REPUBLIC OF THE PHILIPPINES, HER EXCELLENCY CORAZON C. AQUINO, THRU THE SECRETARY, DEPARTMENT OF BUDGET AND MANAGEMENT TO RELEASE THE AMOUNT OF ONE HUNDRED TWENTY MILLION NINE HUNDRED EIGHTY-NINE THOUSAND EIGHT HUNDRED SIXTY-FIVE PESOS AND 58/100 (P 120,989,865.58) REPRESENTING THE FUND REQUIREMENTS FOR THE MONTH OF DECEMBER 1987, AND THE AVAILABILITY OFTHE ADDITIONAL AMOUNT OF P1,153,620,485. 00 TO SUPPORT THE ADDITIONAL PENSION REQUIREMENT FOR CY 1988 IMPLEMENTING THE PENSION ADJUSTMENT OF AFP RETIREES PURSUANT TO PRESIDENTIAL DECREE NO.1638 AND REPUBLIC ACT NO. 6638"
scope = "National"
dateFiled = "1988-02-24"
status = "Pending with the Committee on APPROPRIATIONS since 1988-03-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Unico"
coAuthors = [ "PAYUMO, FELICITO C.", "MONFORT, NARCISO D.", "GARCIA, SIMEON JR. E.", "ROA, BENEDICTA B.",]
[[authorsDetail]]
name = "Unico"
nameCode = "Unico"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "PAYUMO, FELICITO C."
nameCode = "Payumo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GARCIA, SIMEON JR. E."
nameCode = "Garcia"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROA, BENEDICTA B."
nameCode = "Roa"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "APPROPRIATIONS"
type = "primary"
referralCode = "504"
dateRead = "1988-03-01"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 170477
congress = 8
bill_no = "HR00591"
referral = "504"
ref_name = "APPROPRIATIONS"
sub_name = ""
date_read = "1988-03-01"
