billNumber = "HR00335"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR00335"
lastScraped = "2025-09-22T00:47:02.591889"
title = "HR00335"
longTitle = "RESOLUTION DIRECTING THE COMMITTEE ON CRIME, FRAUD, AND CORRUPTION TO INVESTIGATE IMMEDIATELY THE QUESTIONABLE CIRCUMSTANCES BEHIND THE ASUMPTION BY THE GOVERNMENT OF THE $150 MILLION LOAN OF THE PRIVATE DEVELOPMENT CORPORATIONS OF THE PHILIPPINES (PDCP), AS WELL AS THE HIGHLY IRREGULAR DISCHARGINGOF THE GUARANTEE OBLIGATION OF THE SAME OF FAR EAST BANK AND TRUST CO."
scope = "National"
dateFiled = "1987-09-18"
status = "Pending with the Committee on  since 1987-09-23"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Dragon"
coAuthors = [ "ANIAG, FRANCISCO JR. B.", "BANDON, ALAWADIN JR. T.", "BORJA-AGANA, VENICE",]
[[authorsDetail]]
name = "Dragon"
nameCode = "Dragon"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "ANIAG, FRANCISCO JR. B."
nameCode = "Aniag"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BANDON, ALAWADIN JR. T."
nameCode = "Bandon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BORJA-AGANA, VENICE"
nameCode = "Borja-agana"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 170233
congress = 8
bill_no = "HR00335"
comm_act = "REFERRED TO THE SPECIAL CTTE. ON CRIME, FRAUD & CORRUPTION"
referral = ""
ref_name = ""
sub_name = ""
date_read = "1987-09-23"
