billNumber = "HR00723"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR00723"
lastScraped = "2025-09-22T00:47:02.667087"
title = "HR00723"
longTitle = "RESOLUTION REQUESTING THE DEPARTMENT OF AGRARIAN REFORM TO PROVIDE THE CONGRESS WITH THE LIST OF THE NAMES OF LAND OWNERS AND THE AREA OF THEIR LAND HOLDINGS, INCLUDING THE STATUS AND PRODUCTION CAPACITY OF THE LANDS SUBJECT TO DISTRIBUTION, IN ACCORDANCE WITH THE AGRARIAN REFORM PROGRAM OF THE GOVERNMENT"
scope = "National"
dateFiled = "1988-05-25"
status = "Pending with the Committee on AGRARIAN REFORM since 1988-05-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bakunawa"
[[authorsDetail]]
name = "Bakunawa"
nameCode = "Bakunawa"
date = ""
sequence = 0

[[committee]]
name = "AGRARIAN REFORM"
type = "primary"
referralCode = "502"
dateRead = "1988-05-30"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 170605
congress = 8
bill_no = "HR00723"
referral = "502"
ref_name = "AGRARIAN REFORM"
sub_name = ""
date_read = "1988-05-30"
