billNumber = "HR00196"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR00196"
lastScraped = "2025-09-22T00:47:02.563742"
title = "HR00196"
longTitle = "RESOLUTION TO DETERMINE MEASURES IN AID OF LEGISLATION TO ASSIST SMALL FILIPINO BUSINESSES AND INDUSTRIES THROUGH THE PROPER IMPLEMENTATION OF THE FLAG LAW"
scope = "National"
dateFiled = "1987-08-21"
status = "Pending with the Committee on TRADE AND INDUSTRY since 1987-08-26"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bagatsing"
coAuthors = [ "LAGMAN, EDCEL C.", "ROMERO, MIGUEL L.", "PILAPIL, EDUARDO P.", "ANDOLANA, GREGORIO A.",]
[[authorsDetail]]
name = "Bagatsing"
nameCode = "Bagatsing"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "LAGMAN, EDCEL C."
nameCode = "Lagman"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMERO, MIGUEL L."
nameCode = "Romero"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PILAPIL, EDUARDO P."
nameCode = "Pilapil"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ANDOLANA, GREGORIO A."
nameCode = "Andolana"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "539"
dateRead = "1987-08-26"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 170098
congress = 8
bill_no = "HR00196"
referral = "539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
date_read = "1987-08-26"
