billNumber = "HR01648"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR01648"
lastScraped = "2025-09-22T00:47:02.862221"
title = "HR01648"
longTitle = "RESOLUTION REQUESTING THE DEPARTMENT OF HEALTH, THROUGH ITS REGIONAL OFFICE IN REGION V, TO CONDUCT REGULAR QUARTERLY MEDICAL AND DENTAL SERVICES AMONG THE STRATEGIC BARANGAYS IN THE SECOND DISTRICT OF MASBATE, IN LINE WITH THE GOVERNMENT'S HEALTH CARE PROGRAM"
scope = "Local"
dateFiled = "1990-02-05"
status = "Pending with the Committee on HEALTH since 1990-02-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bakunawa"
[[authorsDetail]]
name = "Bakunawa"
nameCode = "Bakunawa"
date = ""
sequence = 0

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "517"
dateRead = "1990-02-05"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[firstReading]
id = 171493
congress = 8
bill_no = "HR01648"
referral = "517"
ref_name = "HEALTH"
sub_name = ""
date_read = "1990-02-05"
