billNumber = "HR01713"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR01713"
lastScraped = "2025-09-22T00:47:02.871275"
title = "HR01713"
longTitle = "RESOLUTION URGING THE LOCAL GOVERNMENT UNITS TO EXPROPRIATE PRIVATE LANDS FOR THE PURPOSE OF ESTABLISHING MORE SCHOOLS"
scope = "National"
dateFiled = "1990-03-29"
status = "Pending with the Committee on LOCAL GOVERNMENT since 1990-03-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Cabochan"
[[authorsDetail]]
name = "Cabochan"
nameCode = "Cabochan"
date = ""
sequence = 0

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "522"
dateRead = "1990-03-29"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 171555
congress = 8
bill_no = "HR01713"
referral = "522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
date_read = "1990-03-29"
