billNumber = "HR01736"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR01736"
lastScraped = "2025-09-22T00:47:02.874681"
title = "HR01736"
longTitle = "RESOLUTION URGING ALL LOCAL GOVERNMENT UNITS TO IMPLEMENT THE SPIRIT OF THE NEW COOPERATIVE CODE BY ALLOWING THE PRIVATE SECTOR, REGISTERED AS MARKET COOPERATIVES, TO OPERATE, MANAGE AND ADMINISTER PUBLIC MARKETS LOCATED IN THEIR RESPECTIVE AREAS"
scope = "National"
dateFiled = "1990-05-08"
status = "Pending with the Committee on LOCAL GOVERNMENT since 1990-05-14"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bagatsing"
coAuthors = [ "MATHAY, ISMAEL JR. A.",]
[[authorsDetail]]
name = "Bagatsing"
nameCode = "Bagatsing"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "MATHAY, ISMAEL JR. A."
nameCode = "Mathay"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "522"
dateRead = "1990-05-14"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 171575
congress = 8
bill_no = "HR01736"
referral = "522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
date_read = "1990-05-14"
