billNumber = "HR01164"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR01164"
lastScraped = "2025-09-22T00:47:02.763056"
title = "HR01164"
longTitle = "RESOLUTION URGING THE DEPARTMENT OF TRADE AND INDUSTRY, THE DEPARTMENT OF FINANCE, THE CENTRAL BANKOF THE PHILIPPINES AND THE NATIONAL ECONOMIC AND DEVELOPMENT AUTHORITY TO DEFER THE IMPLEMENTATION OF THE IMPORT LIBERALIZATION PROGRAM UNTIL SUCH A TIME THAT A COMPREHENSIVE STUDY OF THE EFFECTS OF THE PROGRAM HAS BEEN UNDERTAKEN AND THAT INDICATIONS WILL SHOW THAT THE PROGRAM SHALL BE ADVANTAGEOUS TO THE NATIONAL ECONOMY AND SHALL PROMOTE THE NATIONAL INTEREST"
scope = "National"
dateFiled = "1989-02-16"
status = "Pending with the Committee on TRADE AND INDUSTRY since 1989-02-22"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Bagatsing"
coAuthors = [ "MONFORT, NARCISO D.",]
[[authorsDetail]]
name = "Bagatsing"
nameCode = "Bagatsing"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "MONFORT, NARCISO D."
nameCode = "Monfort"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "TRADE AND INDUSTRY"
type = "primary"
referralCode = "539"
dateRead = "1989-02-22"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 171038
congress = 8
bill_no = "HR01164"
referral = "539"
ref_name = "TRADE AND INDUSTRY"
sub_name = ""
date_read = "1989-02-22"
