billNumber = "HR02003"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR02003"
lastScraped = "2025-09-22T00:47:02.924186"
title = "HR02003"
longTitle = "RESOLUTION DIRECTING THE HOUSE COMMITTEE ON BANKS TO REQUEST THE DEVELOPMENT BANK OF THE PHILIPPINES TO SET ASIDE P10 MILLION OF ITS FUNDS FOR RESEARCH FOR THE FIRST DISTRICT OF SURIGAO DEL SUR TO HELP THE PROVINCE DEVELOP MORE LIVELIHOOD AND MINERALPROJECTS"
scope = "Local"
dateFiled = "1990-10-30"
status = "Pending with the Committee on BANKS AND CURRENCIES since 1990-11-07"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Ty"
[[authorsDetail]]
name = "Ty"
nameCode = "Ty"
date = ""
sequence = 0

[[committee]]
name = "BANKS AND CURRENCIES"
type = "primary"
referralCode = "505"
dateRead = "1990-11-07"

[[committee]]
name = "YOUTH AND SPORTS DEVELOPMENT"
type = "principal"
referralCode = "0543"

[firstReading]
id = 171839
congress = 8
bill_no = "HR02003"
referral = "505"
ref_name = "BANKS AND CURRENCIES"
sub_name = ""
date_read = "1990-11-07"
