billNumber = "HR02059"
billType = "HB"
congress = 8
apiCongressId = 8
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=8&q=HR02059"
lastScraped = "2025-09-22T00:47:02.933663"
title = "HR02059"
longTitle = "RESOLUTION DIRECTING THE APPROPRIATE COMMITTEE OF THE HOUSE OF REPRESENTATIVES TO CONDUCT, IN AID OF LEGISLATION, AN IMMEDIATE PUBLIC INVESTIGATION OF ALL THE COMPROMISE AGREEMENTS, DEALS, TRANSACTIONS, SETTLEMENTS AND SIMILAR ACTIVITIES ENTERED INTO, NEGOTIATED, PURSUED AND IMPLEMENTED AND/OR CURRENTLY OR PROSPECTIVELY BEING ENTERED INTO, NEGOTIATED, OR INTENDED TO BE PURSUED AND IMPLEMENTED BY THE PRESIDENTIAL COMMISSION ON GOOD GOVERNMENT IN RELATION TO PERSONS, AGENCIES OR SUCH OTHER ENTITIES WHOSE ASSETS, CHATTELS, PROPERTIES AND OTHER SIMILAR INTERESTS HAVE BEEN SUBJECT TO SEQUESTRATION ON SUSPICION THAT THEY CONSTITUTE ILL-GOTTEN WEALTH AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "1990-11-29"
status = "Pending with the Committee on JUSTICE since 1990-12-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Albano"
coAuthors = [ "WEBB, FREDDIE N.", "DRAGON, RENATO P.", "MAR, RAUL V. DEL",]
[[authorsDetail]]
name = "Albano"
nameCode = "Albano"
date = ""
sequence = 0

[[coAuthorsDetail]]
name = "WEBB, FREDDIE N."
nameCode = "Webb"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DRAGON, RENATO P."
nameCode = "Dragon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MAR, RAUL V. DEL"
nameCode = "Mar"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "JUSTICE"
type = "primary"
referralCode = "520"
dateRead = "1990-12-05"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 171895
congress = 8
bill_no = "HR02059"
referral = "520"
ref_name = "JUSTICE"
sub_name = ""
date_read = "1990-12-05"
