billNumber = "HBN-09710"
billType = "HBN"
congress = 19
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=19&q=HBN-9710"
lastScraped = "2025-09-20T21:22:19.560031"
title = "SWARA SUG MEDIA CORPORATION"
longTitle = "AN ACT REVOKING THE LEGISLATIVE FRANCHISE GRANTED TO SWARA SUG MEDIA CORPORATION, OPERATING UNDER THE BUSINESS NAME SONSHINE MEDIA NETWORK INTERNATIONAL, REPEALING FOR THE PURPOSE REPUBLIC ACT NO- 11422, ENTITLED “AN ACT RENEWING FOR ANOTHER TWENTY-FIVE (25) YEARS THE FRANCHISE GRANTED TO SWARA SUG MEDIA CORPORATION UNDER REPUBLIC ACT NO. 8122, ENTITLED 'AN ACT GRANTING THE SWARA SUG MEDIA CORPORATION OF THE PHILIPPINES A FRANCHISE TO CONSTRUCT, INSTALL, OPERATE AND MAINTAIN FOR COMMERCIAL PURPOSES RADIO AND TELEVISION BROADCASTING STATIONS IN THE PHILIPPINES AND FOR OTHER PURPOSES'"
scope = "Local"
subject = [ "Franchise Sales", "Franchise Business",]
pdfUrl = "https://web.senate.gov.ph/lisdata/4385839849!.pdf"
pdfFileName = "HBN-9710 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "3/21/2024"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "5/6/2024"
action = "Read on First Reading and Referred to the Committee on PUBLIC SERVICES;"

[status]
status = "Pending in the Committee"
date = "5/6/2024"

[committee]
name = "Public Services"
type = "primary"
