billNumber = "SBN-01951"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-1951"
lastScraped = "2025-09-20T23:30:30.604144"
title = "INCOME AND REVENUE (PROVINCIAL GOVERNORS, CITY AND MUNICIPAL MAYORS AND PUNONG BARANGAY)"
filedDate = "December 10, 2007"
author = "Villar, Manny"
longTitle = "AN ACT REQUIRING PROVINCIAL GOVERNORS, CITY AND MUNICIPAL MAYORS AND PUNONG BARANGAY TO POST AND PUBLISH WITHIN THE TERRITORIAL JURISDICTION OF THEIR LOCAL GOVERNMENT UNITS A SUMMARY OF ALL INCOME AND REVENUE FROM BOTH PUBLIC AND PRIVATE SOURCES AS WELL AS A LISTING OF ALL DISBURSEMENTS, EXPENDITURES AND UTILIZATION OF FUNDS AND FOR OTHER PURPOSES"
scope = "National"
pdfUrl = "https://web.senate.gov.ph/lisdata/65695816!.pdf"
pdfFileName = "SBN-1951 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "12/10/2007"
action = "Introduced by Senator MANNY VILLAR;"

[[legislativeHistory]]
date = "12/11/2007"
action = "Read on First Reading and Referred to the Committee on LOCAL GOVERNMENT;"

[status]
status = "Pending in the Committee"
date = "12/11/2007"

[committee]
name = "Local Government"
type = "primary"
