billNumber = "SBN-00917"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-917"
lastScraped = "2025-09-20T23:19:01.338967"
title = "STUDENT EMPLOYMENT PROGRAM EXPANDED COVERAGE"
filedDate = "July 3, 2007"
author = "Angara, Edgardo J."
longTitle = "AN ACT EXPANDING AND STRENGTHENING THE COVERAGE OF R. A. NO. 7323, OTHERWISE KNOWN AS THE SPECIAL PROGRAM FOR EMPLOYMENT OF STUDENTS"
scope = "National"
subject = [ "R.A.No. 7323, Amendments", "Student Employment Program Expanded Coverage",]
pdfUrl = "https://web.senate.gov.ph/lisdata/51764543!.pdf"
pdfFileName = "SBN-917 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/3/2007"
action = "Introduced by Senator EDGARDO J. ANGARA;"

[[legislativeHistory]]
date = "9/4/2007"
action = "Read on First Reading and Referred to the Committee on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT;"

[[legislativeHistory]]
date = "2/27/2008"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[[legislativeHistory]]
date = "3/10/2008"
action = "Returned and submitted jointly by the Committee(s) on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT and FINANCE per Committee Report No. 41, recommending that it be substituted by SBN-2116;"

[[legislativeHistory]]
date = "3/11/2008"
action = "Committee Report calendared for Ordinary Business;"

[[legislativeHistory]]
date = "3/11/2008"
action = "SUBSTITUTED BY SBN-2116 WHICH BECAME R.A.NO. 9547."

[status]
status = "Consolidated/Substituted in the Committee Report"
date = "3/11/2008"

[committee]
name = "Labor, Employment and Human Resources Development"
type = "primary"
