billNumber = "SBN-02016"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-2016"
lastScraped = "2025-09-20T23:31:13.400121"
title = "VISIT PHILIPPINES ACT OF 2008"
filedDate = "January 29, 2008"
author = "Defensor Santiago, Miriam"
longTitle = "AN ACT TO ESTABLISH AN INTERGOVERNMENTAL TASK FORCE FOR INTERNATIONAL VISITOR ASSISTANCE TO MAKE PHILIPPINES THE PREMIERE TRAVEL AND TOURISM DESTINATION IN THE WORLD"
scope = "National"
pdfUrl = "https://web.senate.gov.ph/lisdata/67365969!.pdf"
pdfFileName = "SBN-2016 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/29/2008"
action = "Introduced by Senator MIRIAM DEFENSOR SANTIAGO;"

[[legislativeHistory]]
date = "1/30/2008"
action = "Read on First Reading and Referred to the Committee(s) on TOURISM and FINANCE;"

[status]
status = "Pending in the Committee"
date = "1/30/2008"

[committee]
name = "Tourism"
type = "primary"
