billNumber = "SBN-02408"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-2408"
lastScraped = "2025-09-20T23:36:16.307055"
title = "EDUCATORS IN BASIC EDUCATION COMPENSATION ACT"
filedDate = "June 11, 2008"
author = "Angara, Edgardo J., Pangilinan, Francis N., Trillanes IV, Antonio \"Sonny\" F., Zubiri, Juan Miguel F., Legarda, Loren B., Revilla Jr., Ramon A., Defensor Santiago, Miriam, Cayetano, Alan Peter \"Companero\" S."
longTitle = "AN ACT PROVIDING FOR ADDITIONAL SUPPORT AND COMPENSATION FOR EDUCATORS IN BASIC EDUCATION"
scope = "National"
subject = [ "Basic Education Program",]
pdfUrl = "https://web.senate.gov.ph/lisdata/76766911!.pdf"
pdfFileName = "SBN-2408 (CR-77)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/11/2008"
action = "Prepared and submitted jointly by the Committee(s) on EDUCATION, ARTS AND CULTURE, CIVIL SERVICE AND GOVERNMENT REORGANIZATION and FINANCE with Senator(s) EDGARDO J. ANGARA, FRANCIS N. PANGILINAN, ANTONIO 'SONNY' F. TRILLANES IV, JUAN MIGUEL F. ZUBIRI, LOREN B. LEGARDA, RAMON A. REVILLA JR., MIRIAM DEFENSOR SANTIAGO and ALAN PETER 'COMPANERO' S. CAYETANO as author(s) per Committee Report No. 77, recommending its approval in substitution of SBNos. 69, 137, 756, 1544, 1611, 1955 and 2300;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Sponsors: Senator(s) ALAN PETER 'COMPANERO' S. CAYETANO, EDGARDO J. ANGARA, FRANCIS N. PANGILINAN, JUAN MIGUEL F. ZUBIRI and LOREN B. LEGARDA;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Committee Report Calendared for Ordinary Business;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Transferred from Ordinary Business to Special Order;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Sponsorship speech of Senator ALAN PETER 'COMPANERO' S. CAYETANO;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Interpellation of Senator AQUILINO Q. PIMENTEL JR.;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Remarks of Senator(s) LOREN B. LEGARDA and FRANCIS 'CHIZ' G. ESCUDERO;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Period of interpellation closed;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Upon their requests, Senators MANNY VILLAR, MIGUEL ZUBIRI and Companera PIA S. CAYETANO were made cosponsors of the bill;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Period of amendment closed;"

[[legislativeHistory]]
date = "6/11/2008"
action = "Approved on Second Reading without Amendment;"

[[legislativeHistory]]
date = "7/16/2008"
action = "Printed copies were distributed to the Senators;"

[[legislativeHistory]]
date = "7/29/2008"
action = "Approved on Third Reading;"

[[legislativeHistory]]
date = "7/29/2008"
action = "In favor: (22) Senators Angara, Aquino, Arroyo, Biazon, Alan Peter Cayetano, Pia Cayetano, Miriam Defensor Santiago, Jinggoy Ejercito Estrada, Enrile, Escudero, Gordon, Honasan, Lacson, Lapid, Legarda, M.A, Madrigal, Pangilinan, Pimentel, Jr., Revilla, Jr., Roxas, Villar, and Zubiri; Against: N o n e; Abstention: N o n e;"

[[legislativeHistory]]
date = "7/31/2008"
action = "Sent to the House of Representatives requesting for concurrence;"

[status]
status = "Pending in the House of Representatives"
date = "7/31/2008"

[committee]
name = "Education, Arts and Culture"
type = "primary"
