billNumber = "SBN-00563"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-563"
lastScraped = "2025-09-20T23:14:29.960617"
title = "IMMEDIATE RELEASE OF RETIREMENT PAY OF EMPLOYEES"
filedDate = "July 2, 2007"
author = "Ejercito-Estrada, Jinggoy P."
longTitle = "AN ACT AMENDING ARTICLE 287 OF PRESIDENTIAL DECREE NO. 442, AS AMENDED, OTHERWISE KNOWN AS THE LABOR CODE OF THE PHILIPPINES, BY REQUIRING EMPLOYERS TO RELEASE THE RETIREMENT PAY OF EMPLOYEES WITHIN FIFTEEN DAYS FROM SUBMISSION OF COMPLETE DOCUMENTARY REQUIREMENTS"
scope = "National"
subject = [ "Retirement Benefits Payment (Immediate Release)", "Labor Code (Article 287, Pd 442)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/47744105!.pdf"
pdfFileName = "SBN-563 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/2/2007"
action = "Introduced by Senator JINGGOY P. EJERCITO-ESTRADA;"

[[legislativeHistory]]
date = "8/22/2007"
action = "Read on First Reading and Referred to the Committee on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT;"

[status]
status = "Pending in the Committee"
date = "8/22/2007"

[committee]
name = "Labor, Employment and Human Resources Development"
type = "primary"
