billNumber = "SBN-02701"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-2701"
lastScraped = "2025-09-20T23:39:53.404140"
title = "CRIMINAL NEGLIGENCE"
filedDate = "November 10, 2008"
author = "Escudero, Francis \"Chiz\" G."
longTitle = "AN ACT INCREASING THE PENALTY FOR CRIMINAL NEGLIGENCE COMMITTED BY COMMON CARRIERS, FURTHER AMENDING ARTICLE 365 OF ACT NO. 3815, AS AMENDED, OR THE REVISED PENAL CODE"
scope = "National"
subject = [ "Revised Penal Code (RA 3815; Amendments)", "Road Tragedies/Vehicular Accidents",]
pdfUrl = "https://web.senate.gov.ph/lisdata/91628300!.pdf"
pdfFileName = "SBN-2701 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "11/10/2008"
action = "Introduced by Senator FRANCIS 'CHIZ' G. ESCUDERO;"

[[legislativeHistory]]
date = "11/12/2008"
action = "Read on First Reading and Referred to the Committee(s) on JUSTICE AND HUMAN RIGHTS and PUBLIC SERVICES;"

[status]
status = "Pending in the Committee"
date = "11/12/2008"

[committee]
name = "Justice and Human Rights"
type = "primary"
