billNumber = "SBN-03185"
billType = "SBN"
congress = 14
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=14&q=SBN-3185"
lastScraped = "2025-09-20T23:45:24.143825"
title = "MEAT INSPECTION LAW"
filedDate = "April 27, 2009"
author = "Trillanes IV, Antonio \"Sonny\" F."
longTitle = "AN ACT AMENDING REPUBLIC ACT NO. 9296 OTHERWISE KNOWN AS THE MEAT INSPECTION LAW, INCREASING THE PENALTIES FOR VIOLATIONS THEREOF, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Meat Products",]
pdfUrl = "https://web.senate.gov.ph/lisdata/108899660!.pdf"
pdfFileName = "SBN-3185, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "4/27/2009"
action = "Introduced by Senator ANTONIO 'SONNY' F. TRILLANES IV;"

[[legislativeHistory]]
date = "4/28/2009"
action = "Read on First Reading and Referred to the Committee on AGRICULTURE AND FOOD;"

[status]
status = "Pending in the Committee"
date = "4/28/2009"

[committee]
name = "Agriculture and Food"
type = "primary"
