billNumber = "HBN-06057"
billType = "HBN"
congress = 16
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=16&q=HBN-6057"
lastScraped = "2025-09-20T23:54:37.056265"
title = "LAND TRANSPORTATION OFFICE (LTO), MUNICIPALITY OF MEDELLIN, PROVINCE OF CEBU"
longTitle = "AN ACT CONVERTING THE LAND TRANSPORTATION OFFICE - MEDELLIN EXTENSION OFFICE IN THE MUNICIPALITY OF MEDELLIN, PROVINCE OF CEBU INTO A REGULAR DISTRICT OFFICE AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Land Transportation Office (LTO)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2222918944!.pdf"
pdfFileName = "HBN-6057 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "9/9/2015"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "9/15/2015"
action = "Read on First Reading and Referred to the Committee(s) on PUBLIC SERVICES; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "9/15/2015"

[committee]
name = "Public Services"
type = "primary"
