billNumber = "HBN-05102"
billType = "HBN"
congress = 16
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=16&q=HBN-5102"
lastScraped = "2025-09-20T23:52:43.129846"
title = "NORTH COTABATO THIRD DISTRICT ENGINEERING OFFICE"
longTitle = "AN ACT ESTABLISHING THE THIRD DISTRICT ENGINEERING OFFICE IN THE MUNICIPALITY OF MATALAM, PROVINCE OF NORTH COTABATO AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Engineering District Office",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2019617306!.pdf"
pdfFileName = "HBN-5102 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "12/3/2014"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "12/9/2014"
action = "Read on First Reading and Referred to the Committee(s) on PUBLIC WORKS; and FINANCE;"

[[legislativeHistory]]
date = "2/3/2016"
action = "Returned and submitted jointly by the Committee(s) on PUBLIC WORKS and FINANCE per Committee Report No. 483, recommending its approval without amendment;"

[[legislativeHistory]]
date = "5/30/2016"
action = "Motion of the Majority Leader, Senator Alan Peter Compañero S. Cayetano, that the matters appearing in the Reference of Business for todays session be deemed read and transmitted to the Archives;"

[[legislativeHistory]]
date = "5/30/2016"
action = "COMMITTEE REPORT SENT TO THE ARCHIVES."

[status]
status = "Committee Report Sent to the Archives"
date = "5/30/2016"

[committee]
name = "Public Works"
type = "primary"
