billNumber = "HBN-06932"
billType = "HBN"
congress = 17
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=17&q=HBN-6932"
lastScraped = "2025-09-20T23:43:37.452005"
title = "SOUTHERN LEYTE TOURISM ZONE"
longTitle = "AN ACT DECLARING THE PROVINCE OF SOUTHERN LEYTE A TOURISM ZONE AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Tourism Zone",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2719723413!.pdf"
pdfFileName = "HBN-6932 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/24/2018"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "1/29/2018"
action = "Read on First Reading and Referred to the Committee(s) on TOURISM; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "1/29/2018"

[committee]
name = "Tourism"
type = "primary"
