billNumber = "HBN-10561"
billType = "HBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=HBN-10561"
lastScraped = "2025-09-20T21:22:31.550787"
title = "ENTERPRISE-BASED EDUCATION AND TRAINING (EBET) PROGRAM ACT"
longTitle = "AN ACT ESTABLISHING AN ENTERPRISE-BASED EDUCATION AND TRAINING PROGRAM AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
subject = [ "Enterprise-Based Education and Training (EBET) Program",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3699533344!.pdf"
pdfFileName = "HBN-10561 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/24/2022"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "1/26/2022"
action = "Read on First Reading and Referred to the Committees on HIGHER, TECHNICAL AND VOCATIONAL EDUCATION; WAYS AND MEANS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "1/26/2022"

[committee]
name = "Higher, Technical and Vocational Education"
type = "primary"
