billNumber = "HBN-09837"
billType = "HBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=HBN-9837"
lastScraped = "2025-09-20T21:21:25.467522"
title = "BISLIG CITY MEDICAL CENTER (BISLIG, SURIGAO DEL SUR)"
longTitle = "AN ACT CONVERTING THE BISLIG DISTRICT HOSPITAL IN THE CITY OF BISLIG, PROVINCE OF SURIGAO DEL SUR, INTO A MEDICAL CENTER TO BE KNOWN AS THE BISLIG CITY MEDICAL CENTER, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
subject = [ "Hospitals, Conversion",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3606932530!.pdf"
pdfFileName = "HBN-9837 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/26/2021"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "9/1/2021"
action = "Read on First Reading and Referred to the Committees on HEALTH AND DEMOGRAPHY and FINANCE;"

[[legislativeHistory]]
date = "3/22/2022"
action = "Conducted JOINT COMMITTEE MEETINGS/HEARINGS;"

[status]
status = "Pending in the Committee"
date = "9/1/2021"

[committee]
name = "Health and Demography"
type = "primary"
