billNumber = "SBN-00567"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-567"
lastScraped = "2025-09-20T23:15:08.647917"
title = "TEACHING OF HUMAN RIGHTS"
filedDate = "July 7, 2010"
author = "Ejercito-Estrada, Jinggoy P."
longTitle = "AN ACT REQUIRING THE TEACHING OF HUMAN RIGHTS AS MANDATORY IN ALL PUBLIC AND PRIVATE SCHOOLS"
scope = "National"
subject = [ "Human Rights",]
pdfUrl = "https://web.senate.gov.ph/lisdata/79516831!.pdf"
pdfFileName = "SBN-567, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/7/2010"
action = "Introduced by Senator JINGGOY P. EJERCITO-ESTRADA;"

[[legislativeHistory]]
date = "8/9/2010"
action = "Read on First Reading and Referred to the Committee(s) on EDUCATION, ARTS AND CULTURE and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/9/2010"

[committee]
name = "Education, Arts and Culture"
type = "primary"
