billNumber = "SBN-02398"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-2398"
lastScraped = "2025-09-20T23:33:23.000075"
title = "SANGLEY POINT CONVERSION ACT"
filedDate = "August 12, 2010"
author = "Revilla Jr., Ramon A."
longTitle = "AN ACT DIRECTING THE CONVERSION OF SANGLEY POINT IN CAVITE CITY INTO AN INTERNATIONAL LOGISTICS HUB"
scope = "National"
subject = [ "Sangley Point",]
pdfUrl = "https://web.senate.gov.ph/lisdata/99878567!.pdf"
pdfFileName = "SBN-2398 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/12/2010"
action = "Introduced by Senator RAMON A. REVILLA JR.;"

[[legislativeHistory]]
date = "9/21/2010"
action = "Read on First Reading and Referred to the Committee(s) on ECONOMIC AFFAIRS; LOCAL GOVERNMENT; WAYS AND MEANS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "9/21/2010"

[committee]
name = "Economic Affairs"
type = "primary"
