billNumber = "SBN-00758"
billType = "SBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=SBN-758"
lastScraped = "2025-09-20T23:17:41.833613"
title = "TAX REFORM ACT (SEC. 181, R.A. NO. 8424)"
filedDate = "July 7, 2010"
author = "Ejercito-Estrada, Jinggoy P., Escudero, Francis \"Chiz\" G."
longTitle = "AN ACT EXEMPTING MONEY TRANSFERS TO THE PHILIPPINES OF OVERSEAS FOREIGN WORKERS FROM THE IMPOSITION OF DOCUMENTARY STAMP TAX, AMENDING FOR THE PURPOSE SECTION 181 OF REPUBLIC ACT NO. 8424, OTHERWISE KNOWN AS THE ‘TAX REFORM ACT OF 1997,’ AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Overseas Filipino Workers (OFW)", "Documentary Stamp Tax", "Tax Reform Act",]
pdfUrl = "https://web.senate.gov.ph/lisdata/81176589!.pdf"
pdfFileName = "SBN-758 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/7/2010"
action = "Introduced by Senator JINGGOY P. EJERCITO-ESTRADA;"

[[legislativeHistory]]
date = "8/11/2010"
action = "Read on First Reading and Referred to the Committee on WAYS AND MEANS;"

[[legislativeHistory]]
date = "2/9/2011"
action = "Senator FRANCIS 'CHIZ' G. ESCUDERO was made as coauthor;"

[status]
status = "Pending in the Committee"
date = "8/11/2010"

[committee]
name = "Ways and Means"
type = "primary"
