billNumber = "SBN-01862"
billType = "SBN"
congress = 17
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=17&q=SBN-1862"
lastScraped = "2025-09-20T23:33:28.480539"
title = "EXPANDED SEAT BELTS USE ACT OF 2018"
filedDate = "July 4, 2018"
author = "De Lima, Leila M."
longTitle = "AN ACT AMENDING SECTION 5 AND SECTION 12 OF REPUBLIC ACT NO. 8750, OTHERWISE KNOWN AS SEAT BELTS USE ACT OF 1999"
scope = "National"
subject = [ "Seatbelts",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2809424397!.pdf"
pdfFileName = "SBN-1862 as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/4/2018"
action = "Introduced by Senator LEILA M. DE LIMA;"

[[legislativeHistory]]
date = "7/25/2018"
action = "Read on First Reading and Referred to the Committee on PUBLIC SERVICES;"

[status]
status = "Pending in the Committee"
date = "7/25/2018"

[committee]
name = "Public Services"
type = "primary"
