billNumber = "SBN-00141"
billType = "SBN"
congress = 17
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=17&q=SBN-141"
lastScraped = "2025-09-20T23:10:42.443550"
title = "INTEGRATED URBAN AGRICULTURE ACT OF 2016"
filedDate = "June 30, 2016"
author = "Villar, Cynthia A."
longTitle = "AN ACT MANDATING THE DEPARTMENT OF AGRICULTURE TO PROMOTE URBAN AGRICULTURAL DEVELOPMENT IN THE COUNTRY'S METROPOLITAN AREAS, TO ADDRESS FOOD SECURITY, AND PROVIDING FUNDS THEREFOR"
scope = "National"
subject = [ "Department of Agriculture", "Food Security", "Tax Credit", "Agricultural Development",]
pdfUrl = "https://web.senate.gov.ph/lisdata/2356120178!.pdf"
pdfFileName = "SBN-141 as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "6/30/2016"
action = "Introduced by Senator CYNTHIA A. VILLAR;"

[[legislativeHistory]]
date = "8/1/2016"
action = "Read on First Reading and Referred to the Committee(s) on AGRICULTURE AND FOOD; WAYS AND MEANS; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/1/2016"

[committee]
name = "Agriculture and Food"
type = "primary"
