billNumber = "HB00464"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB00464"
lastScraped = "2025-09-21T23:39:48.389627"
title = "HB00464"
longTitle = "AN ACT INSTITUTIONALIZING THE PHILIPPINE BLOOD CENTER AND REGIONAL BLOOD CENTERS AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2025-06-30"
status = "Pending with the Committee on HEALTH since 2025-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB00464.pdf"
fileSize = 147031
author = "REMULLA, CRISPIN DIEGO D."
coAuthors = [ "VILLARICA, LINABELLE RUTH R.", "RIVERA, NOEL \"Bong\" N.",]
[[authorsDetail]]
name = "REMULLA, CRISPIN DIEGO D."
nameCode = "Remulla"
date = "2025-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "VILLARICA, LINABELLE RUTH R."
nameCode = "Villarica"
date = "2025-08-27"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "RIVERA, NOEL \"Bong\" N."
nameCode = "Rivera"
date = "2025-08-27"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2025-07-29"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 465
congress = 103
bill_no = "HB00464"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-29"
