billNumber = "HB00422"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB00422"
lastScraped = "2025-09-21T23:39:48.380572"
title = "HB00422"
longTitle = "AN ACT CREATING THE SUSTAINABLE BICOL RIVER DEVELOPMENT AUTHORITY, PRESCRIBING ITS POWERS, FUNCTIONS AND DUTIES, PROVIDING FUNDS THEREFOR, AND FOR OTHER PURPOSES"
scope = "Local"
dateFiled = "2025-06-30"
status = "Pending with the Committee on GOVERNMENT ENTERPRISES AND PRIVATIZATION since 2025-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB00422.pdf"
fileSize = 8258989
author = "VILLAFUERTE, MIGUEL LUIS R."
[[authorsDetail]]
name = "VILLAFUERTE, MIGUEL LUIS R."
nameCode = "Villafuerte (M. L. R.)"
date = "2025-06-30"
sequence = 1

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2025-07-29"

[[committee]]
name = "ECOLOGY"
type = "principal"
referralCode = "A501"

[firstReading]
id = 423
congress = 103
bill_no = "HB00422"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-29"
