billNumber = "HB00495"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB00495"
lastScraped = "2025-09-21T23:39:48.396723"
title = "HB00495"
longTitle = "AN ACT ESTABLISHING A TECHNICAL EDUCATION AND SKILLS DEVELOPMENT AUTHORITY (TESDA) TRAINING AND ASSESSMENT CENTER IN LUPI, SAN FERNANDO, PROVINCE OF CAMARINES SUR, TO BE KNOWN AS THE LUPI, SAN FERNANDO TESDA TRAINING AND ASSESSMENT CENTER, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2025-06-30"
status = "Pending with the Committee on HIGHER AND TECHNICAL EDUCATION since 2025-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB00495.pdf"
fileSize = 184105
author = "HORIBATA, TSUYOSHI ANTHONY \"HORI\" G."
coAuthors = [ "VILLAFUERTE, MIGUEL LUIS R.",]
[[authorsDetail]]
name = "HORIBATA, TSUYOSHI ANTHONY \"HORI\" G."
nameCode = "Horibata"
date = "2025-06-30"
sequence = 1

[[coAuthorsDetail]]
name = "VILLAFUERTE, MIGUEL LUIS R."
nameCode = "Villafuerte (M. L. R.)"
date = "2025-07-30"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "primary"
referralCode = "C502"
dateRead = "2025-07-29"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 496
congress = 103
bill_no = "HB00495"
report = ""
comm_act = ""
referral = "C502"
ref_name = "HIGHER AND TECHNICAL EDUCATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-29"
