billNumber = "HB00180"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB00180"
lastScraped = "2025-09-21T23:39:48.331400"
title = "HB00180"
longTitle = "AN ACT ESTABLISHING A WHARF IN THE MUNICIPALITY OF IPIL, PROVINCE OF ZAMBOANGA SIBUGAY TO SERVE AS A GATEWAY TO BULUAN ISLAND FOR ECONOMIC AND TOURISM DEVELOPMENT, APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2025-06-30"
status = "Pending with the Committee on TRANSPORTATION since 2025-08-27"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB00180.pdf"
fileSize = 88083
author = "HOFER-HASIM, MARLESA \"DOC MARLY\""
[[authorsDetail]]
name = "HOFER-HASIM, MARLESA \"DOC MARLY\""
nameCode = "Hofer-Hasim"
date = "2025-06-30"
sequence = 1

[[committee]]
name = "TRANSPORTATION"
type = "primary"
referralCode = "E509"
dateRead = "2025-07-29"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 181
congress = 103
bill_no = "HB00180"
report = ""
comm_act = ""
referral = "E509"
ref_name = "TRANSPORTATION"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2025-08-27"
date_read = "2025-07-29"
