billNumber = "HB01066"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB01066"
lastScraped = "2025-09-21T23:39:48.510652"
title = "HB01066"
longTitle = "AN ACT INCREASING THE BED CAPACITY OF THE SOUTHERN PHILIPPINES MEDICAL CENTER, IN THE CITY OF DAVAO, PROVINCE OF DAVAO DEL SUR, FROM ONE THOUSAND FIVE HUNDRED (1,500) TO TWO THOUSAND (2,000) BEDS, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2025-07-02"
status = "Pending with the Committee on HEALTH since 2025-07-29"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB01066.pdf"
fileSize = 779151
author = "UNGAB, ISIDRO T."
[[authorsDetail]]
name = "UNGAB, ISIDRO T."
nameCode = "Ungab"
date = "2025-07-02"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2025-07-29"

[[committee]]
name = "NATURAL RESOURCES"
type = "principal"
referralCode = "0526"

[firstReading]
id = 1067
congress = 103
bill_no = "HB01066"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-29"
