billNumber = "HB01384"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB01384"
lastScraped = "2025-09-21T23:39:48.570853"
title = "HB01384"
longTitle = "AN ACT ESTABLISHING THE UPLAND SUSTAINABLE AGRI-FORESTRY DEVELOPMENT (USAD) PROGRAM IN UPLAND AGRICULTURAL LANDS AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2025-07-07"
status = "Pending with the Committee on AGRICULTURE AND FOOD since 2025-07-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB01384.pdf"
fileSize = 562388
author = "PLAZA, EDDIEBONG G."
coAuthors = [ "CARI, CARL NICOLAS C.",]
[[authorsDetail]]
name = "PLAZA, EDDIEBONG G."
nameCode = "Plaza"
date = "2025-07-07"
sequence = 1

[[authorsDetail]]
name = "BASCUG, ALFELITO \"ALFEL\" M."
nameCode = "Bacsug"
date = "2025-07-07"
sequence = 2

[[coAuthorsDetail]]
name = "CARI, CARL NICOLAS C."
nameCode = "Cari"
date = "2025-08-18"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "primary"
referralCode = "E505"
dateRead = "2025-07-30"

[[committee]]
name = "TOURISM"
type = "principal"
referralCode = "0538"

[firstReading]
id = 1385
congress = 103
bill_no = "HB01384"
report = ""
comm_act = ""
referral = "E505"
ref_name = "AGRICULTURE AND FOOD"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-30"
