billNumber = "HB02825"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB02825"
lastScraped = "2025-09-21T23:39:48.848248"
title = "HB02825"
longTitle = "AN ACT PROMOTING MENSTRUAL HEALTH AND HYGIENE BY PROVIDING FREE MENSTRUAL PRODUCTS TO INDIGENT WOMEN AND TO GIRLS ENROLLED IN PUBLIC SCHOOLS NATIONWIDE AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2025-07-31"
status = "Pending with the Committee on HEALTH since 2025-08-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB02825.pdf"
fileSize = 151187
author = "MONTES, IRIS MARIE DEMESA"
coAuthors = [ "YATCO, FLORABEL C.", "TAN, KEITH MICAH \"Atty. Mike\" D.L.",]
[[authorsDetail]]
name = "MONTES, IRIS MARIE DEMESA"
nameCode = "Montes"
date = "2025-07-31"
sequence = 1

[[coAuthorsDetail]]
name = "YATCO, FLORABEL C."
nameCode = "Yatco"
date = "2025-08-11"
journalNo = "J000"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "TAN, KEITH MICAH \"Atty. Mike\" D.L."
nameCode = "Tan (K. M. D.L.)"
date = "2025-08-13"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2025-08-05"

[[committee]]
name = "MICRO, SMALL AND MEDIUM ENTERPRISE DEVELOPMENT"
type = "principal"
referralCode = "E510"

[firstReading]
id = 2826
congress = 103
bill_no = "HB02825"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-08-05"
