billNumber = "HB02843"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB02843"
lastScraped = "2025-09-21T23:39:48.851399"
title = "HB02843"
longTitle = "AN ACT CONVERTING THE AGUSAN DEL NORTE PROVINCIAL HOSPITAL IN BUTUAN CITY, PROVINCE OF AGUSAN DEL NORTE INTO A LEVEL III TEACHING AND TRAINING HOSPITAL TO BE KNOWN AS THE AGUSAN DEL NORTE GENERAL HOSPITAL AND TRAINING CENTER AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2025-07-31"
status = "Pending with the Committee on HEALTH since 2025-08-05"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB02843.pdf"
fileSize = 801238
author = "CORVERA, DALE B."
[[authorsDetail]]
name = "CORVERA, DALE B."
nameCode = "Corvera"
date = "2025-07-31"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2025-08-05"

[[committee]]
name = "FOREIGN AFFAIRS"
type = "principal"
referralCode = "0513"

[firstReading]
id = 2844
congress = 103
bill_no = "HB02843"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-08-05"
