billNumber = "HB02397"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB02397"
lastScraped = "2025-09-21T23:39:48.773757"
title = "HB02397"
longTitle = "AN ACT CREATING A TRIPARTITE COUNCIL TO ADDRESS UNEMPLOYMENT, UNDEREMPLOYMENT, AND THE JOB-SKILLS MISMATCH PROBLEM IN THE COUNTRY, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2025-07-28"
status = "Pending with the Committee on LABOR AND EMPLOYMENT since 2025-08-04"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB02397.pdf"
fileSize = 363536
author = "VILLAFUERTE, MIGUEL LUIS R."
[[authorsDetail]]
name = "VILLAFUERTE, MIGUEL LUIS R."
nameCode = "Villafuerte (M. L. R.)"
date = "2025-07-28"
sequence = 1

[[authorsDetail]]
name = "VILLAFUERTE, VINCENZO RENATO LUIGI R."
nameCode = "Villafuerte (V. R. L. R.)"
date = "2025-07-28"
sequence = 2

[[authorsDetail]]
name = "HORIBATA, TSUYOSHI ANTHONY \"HORI\" G."
nameCode = "Horibata"
date = "2025-07-28"
sequence = 3

[[authorsDetail]]
name = "RIDON, TERRY L."
nameCode = "Ridon"
date = "2025-07-28"
sequence = 4

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "primary"
referralCode = "0521"
dateRead = "2025-08-04"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 2398
congress = 103
bill_no = "HB02397"
report = ""
comm_act = ""
referral = "0521"
ref_name = "LABOR AND EMPLOYMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-08-04"
