billNumber = "HB02724"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB02724"
lastScraped = "2025-09-21T23:39:48.830424"
title = "HB02724"
longTitle = "AN ACT EXTENDING FOR A PERIOD OF TWENTY-FIVE (25) YEARS THE TERM OF THE FRANCHISE GRANTED TO ISABELA ELECTRIC COOPERATIVE II, INC. TO CONSTRUCT, OPERATE, AND MAINTAIN DISTRIBUTION SYSTEMS FOR THE CONVEYANCE OF ELECTRIC POWER IN THE CITY OF ILAGAN AND MUNICIPALITIES OF AURORA, BURGOS, CABAGAN, DELFIN ALBANO, GAMU, MALLIG, QUEZON, QUIRINO, ROXAS, SAN MANUEL, SAN MARIANO, SAN PABLO, STA. MARIA, STO. TOMAS, TUMAUINI, BENITO SOLIVEN, NAGUILIAN, PALANAN, AND MACONACON OF THE PROVINCE OF ISABELA"
scope = "Local"
dateFiled = "2025-07-30"
status = "Pending with the Committee on LEGISLATIVE FRANCHISES since 2025-08-04"
statusOrder = 4.0
urgent = false
adminBill = false
author = "ALBANO, ANTONIO \"TONYPET\" T."
[[authorsDetail]]
name = "ALBANO, ANTONIO \"TONYPET\" T."
nameCode = "Albano"
date = "2025-07-30"
sequence = 1

[[authorsDetail]]
name = "GO, ED CHRISTOPHER S."
nameCode = "Go"
date = "2025-07-30"
sequence = 2

[[authorsDetail]]
name = "DY, FAUSTINO MICHAEL CARLOS III T."
nameCode = "Dy (F.M.C.)"
date = "2025-07-30"
sequence = 3

[[authorsDetail]]
name = "TY, ALLAN U."
nameCode = "Ty"
date = "2025-07-30"
sequence = 4

[[committee]]
name = "LEGISLATIVE FRANCHISES"
type = "primary"
referralCode = "0508"
dateRead = "2025-08-04"

[[committee]]
name = "SCIENCE AND TECHNOLOGY"
type = "principal"
referralCode = "0534"

[firstReading]
id = 2725
congress = 103
bill_no = "HB02724"
report = ""
comm_act = ""
referral = "0508"
ref_name = "LEGISLATIVE FRANCHISES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-08-04"
