billNumber = "HB02081"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB02081"
lastScraped = "2025-09-21T23:39:48.716697"
title = "HB02081"
longTitle = "AN ACT PROVIDING FOR THE ESTABLISHMENT AND MAINTENANCE OF A PUBLIC VETERINARY CLINIC IN EVERY CITY AND MUNICIPALITY, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2025-07-17"
status = "Pending with the Committee on HEALTH since 2025-07-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB02081.pdf"
fileSize = 493479
author = "PLEYTO, SALVADOR A."
[[authorsDetail]]
name = "PLEYTO, SALVADOR A."
nameCode = "Pleyto"
date = "2025-07-17"
sequence = 1

[[committee]]
name = "HEALTH"
type = "primary"
referralCode = "0517"
dateRead = "2025-07-30"

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "principal"
referralCode = "C501"

[firstReading]
id = 2082
congress = 103
bill_no = "HB02081"
report = ""
comm_act = ""
referral = "0517"
ref_name = "HEALTH"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-30"
