billNumber = "HB02088"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB02088"
lastScraped = "2025-09-21T23:39:48.717995"
title = "HB02088"
longTitle = "AN ACT DECLARING THE MALASI TREE PARK AND WILDLIFE SANCTUARY LOCATED IN BARANGAY SAN ANTONIO, MUNICIPALITY OF CABAGAN, PROVINCE OF ISABELA, AN ECOTOURISM ZONE"
scope = "Local"
dateFiled = "2025-07-17"
status = "Pending with the Committee on TOURISM since 2025-07-30"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB02088.pdf"
fileSize = 397531
author = "ALBANO, ANTONIO \"TONYPET\" T."
[[authorsDetail]]
name = "ALBANO, ANTONIO \"TONYPET\" T."
nameCode = "Albano"
date = "2025-07-17"
sequence = 1

[[committee]]
name = "TOURISM"
type = "primary"
referralCode = "0538"
dateRead = "2025-07-30"

[[committee]]
name = "LOCAL GOVERNMENT"
type = "principal"
referralCode = "0522"

[firstReading]
id = 2089
congress = 103
bill_no = "HB02088"
report = ""
comm_act = ""
referral = "0538"
ref_name = "TOURISM"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-07-30"
