billNumber = "HB03149"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HB03149"
lastScraped = "2025-09-21T23:39:48.903585"
title = "HB03149"
longTitle = "AN ACT PROVIDING FOR ALTERNATIVE MODES OF VOTING FOR PERSONS IN VULNERABLE SITUATIONS TO EXERCISE THEIR RIGHT OF SUFFRAGE, AMENDING FOR THE PURPOSE R.A. NO. 10366, OTHERWISE KNOWN AS AN ACT AUTHORIZING THE COMELEC TO ESTABLISH PRECINCTS ASSIGNED TO ACCESSIBLE POLLING PLACES EXCLUSIVELY FOR PERSONS WITH DISABILITIES AND SENIOR CITIZENS, AND APPROPRIATING FUNDS THEREFOR"
scope = "National"
dateFiled = "2025-08-05"
status = "Pending with the Committee on SUFFRAGE AND ELECTORAL REFORMS since 2025-08-11"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HB03149.pdf"
fileSize = 420828
author = "VILLARICA, LINABELLE RUTH R."
[[authorsDetail]]
name = "VILLARICA, LINABELLE RUTH R."
nameCode = "Villarica"
date = "2025-08-05"
sequence = 1

[[committee]]
name = "SUFFRAGE AND ELECTORAL REFORMS"
type = "primary"
referralCode = "0537"
dateRead = "2025-08-11"

[[committee]]
name = "TRADE AND INDUSTRY"
type = "principal"
referralCode = "0539"

[firstReading]
id = 3150
congress = 103
bill_no = "HB03149"
report = ""
comm_act = ""
referral = "0537"
ref_name = "SUFFRAGE AND ELECTORAL REFORMS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-08-11"
