billNumber = "HR00192"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=HR00192"
lastScraped = "2025-09-21T23:39:49.227739"
title = "HR00192"
longTitle = "RESOLUTION URGING THE EXECUTIVE DEPARTMENT, THROUGH THE DEPARTMENT OF FOREIGN AFFAIRS (DFA), TO INTRODUCE A RESOLUTION BEFORE THE UNITED NATIONS GENERAL ASSEMBLY (UNGA) CALLING ON THE PEOPLE'S REPUBLIC OF CHINA (PRC) TO RESPECT THE 2016 ARBITRAL RULING AND TO CEASE ITS REPEATED HOSTILE AND AGGRESSIVE ACTS AGAINST THE PHILIPPINES IN THE WEST PHILIPPINE SEA"
dateFiled = "2025-08-27"
status = "Pending with the Committee on WEST PHILIPPINE SEA since 2025-09-01"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_20/HR00192.pdf"
fileSize = 185952
author = "DE LIMA, LEILA M."
coAuthors = [ "HERNANDEZ, CHARISSE ANNE C.",]
[[authorsDetail]]
name = "DE LIMA, LEILA M."
nameCode = "De Lima"
date = "2025-08-27"
sequence = 1

[[authorsDetail]]
name = "AMANTE, LORETO S."
nameCode = "Amante"
date = "2025-08-27"
sequence = 2

[[authorsDetail]]
name = "AMATONG, ADRIAN MICHAEL A."
nameCode = "Amatong"
date = "2025-08-27"
sequence = 3

[[authorsDetail]]
name = "BAG-AO, KAKA J."
nameCode = "Bag-ao"
date = "2025-08-27"
sequence = 4

[[authorsDetail]]
name = "CENDAÑA, PERCIVAL \"PERCI\""
nameCode = "Cendaña"
date = "2025-08-27"
sequence = 5

[[authorsDetail]]
name = "DIOKNO, JOSE MANUEL TADEO \"CHEL\" I."
nameCode = "Diokno"
date = "2025-08-27"
sequence = 6

[[authorsDetail]]
name = "ERICE, EDGAR R."
nameCode = "Erice"
date = "2025-08-27"
sequence = 7

[[authorsDetail]]
name = "FRESNEDI, JAIME R."
nameCode = "Fresnedi"
date = "2025-08-27"
sequence = 8

[[authorsDetail]]
name = "ISMULA, DADAH KIRAM"
nameCode = "Ismula"
date = "2025-08-27"
sequence = 9

[[authorsDetail]]
name = "LAGMAN, CIELO KRISEL"
nameCode = "Lagman"
date = "2025-08-27"
sequence = 10

[[authorsDetail]]
name = "LUISTRO, ATTY. GERVILLE \"JINKY BITRICS\" R."
nameCode = "Luistro"
date = "2025-08-27"
sequence = 11

[[authorsDetail]]
name = "MANIQUIZ, DORIS E."
nameCode = "Maniquiz"
date = "2025-08-27"
sequence = 12

[[authorsDetail]]
name = "ODUCADO, NATHANIEL M."
nameCode = "Oducado"
date = "2025-08-27"
sequence = 13

[[authorsDetail]]
name = "ORETA, ANTOLIN A. III"
nameCode = "Oreta (A. A.)"
date = "2025-08-27"
sequence = 14

[[authorsDetail]]
name = "ROMAN, ANTONINO B., III"
nameCode = "Roman"
date = "2025-08-27"
sequence = 15

[[authorsDetail]]
name = "UMALI, ALFONSO V., JR."
nameCode = "Umali"
date = "2025-08-27"
sequence = 16

[[authorsDetail]]
name = "VELOSO-TUAZON, ANNA VICTORIA"
nameCode = "Veloso-Tuazon"
date = "2025-08-27"
sequence = 17

[[coAuthorsDetail]]
name = "HERNANDEZ, CHARISSE ANNE C."
nameCode = "Hernandez (C. A.)"
date = "2025-09-16"
journalNo = "J000"
sessionNo = "1RS"

[[committee]]
name = "WEST PHILIPPINE SEA"
type = "primary"
referralCode = "I503"
dateRead = "2025-09-01"

[[committee]]
name = "HEALTH"
type = "principal"
referralCode = "0517"

[firstReading]
id = 4748
congress = 103
bill_no = "HR00192"
report = ""
comm_act = ""
referral = "I503"
ref_name = "WEST PHILIPPINE SEA"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2025-09-01"
