billNumber = "PS00043"
billType = "HB"
congress = 20
apiCongressId = 103
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=103&q=PS00043"
lastScraped = "2025-09-21T23:39:49.249105"
title = "PS00043"
longTitle = "“PALAWAN IS NOT A DROP ZONE: STANDING FOR NATIONAL DIGNITY”"
dateFiled = "2025-08-18"
status = "Pending with the Committee on WEST PHILIPPINE SEA since 2025-08-27"
statusOrder = 4.0
urgent = false
adminBill = false
author = "ACOSTA, GIL \"KABARANGAYJR\""
[[authorsDetail]]
name = "ACOSTA, GIL \"KABARANGAYJR\""
nameCode = "Acosta"
date = "2025-08-18"
sequence = 1

[[committee]]
name = "WEST PHILIPPINE SEA"
type = "primary"
referralCode = "I503"
dateRead = "2025-08-18"

[[committee]]
name = "WAYS AND MEANS"
type = "principal"
referralCode = "0542"

[firstReading]
id = 4878
congress = 103
bill_no = "PS00043"
report = ""
comm_act = ""
referral = "I503"
ref_name = "WEST PHILIPPINE SEA"
sub_name = ""
recomm = ""
remarks = ""
date_pend = "2025-08-27"
date_read = "2025-08-18"
