billNumber = "SBN-00808"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-808"
lastScraped = "2025-09-20T21:07:37.550796"
title = "ENHANCING ADMINISTRATIVE FEASIBILITY AND EQUITABILITY OF THE TAX SYSTEM"
filedDate = "July 29, 2019"
author = "Marcos, Imee R."
longTitle = "AN ACT ENHANCING ADMINISTRATIVE FEASIBILITY AND EQUITABILITY OF THE TAX SYSTEM AND RATIONALIZING THE IMPOSITION OF THE VALUE-ADDED TAX TO ADDRESS INTERGENERATIONAL POVERTY, AMENDING FOR THE PURPOSE VARIOUS SECTIONS OF THE NATIONAL INTERNAL REVENUE CODE, AS AMENDED, AND FOR OTHER PURPOSES"
scope = "National"
subject = [ "Taxes (Value-Added Tax / Vat)", "National Internal Revenue Code (NIRC)",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3118128081!.pdf"
pdfFileName = "SBN-808 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/29/2019"
action = "Introduced by Senator IMEE R. MARCOS;"

[[legislativeHistory]]
date = "8/14/2019"
action = "Read on First Reading and Referred to the Committee on WAYS AND MEANS;"

[status]
status = "Pending in the Committee"
date = "8/14/2019"

[committee]
name = "Ways and Means"
type = "primary"
