billNumber = "SBN-02479"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-2479"
lastScraped = "2025-09-20T21:16:11.537232"
title = "RESULTS-BASED NATIONAL EVALUATION POLICY (RBNEP) ACT"
filedDate = "January 24, 2022"
author = "Hontiveros, Risa, Marcos, Imee R., Angara, Sonny, Revilla Jr., Ramon Bong"
longTitle = "AN ACT INSTITUTIONALIZING A RESULTS-BASED NATIONAL EVALUATION POLICY"
scope = "National"
subject = [ "Results-Based National Evaluation Policy",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3707333453!.pdf"
pdfFileName = "SBN-2479 (Per Ctte. Rpt. No. 444)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/24/2022"
action = "Prepared and submitted jointly by the Committees on ECONOMIC AFFAIRS and FINANCE with Senators RISA HONTIVEROS, IMEE R. MARCOS, SONNY ANGARA and RAMON BONG REVILLA JR. as authors per Committee Report No. 444, recommending its approval in substitution of SBNos. 788 and 1885;"

[[legislativeHistory]]
date = "1/25/2022"
action = "Committee Report Calendared for Ordinary Business;"

[[legislativeHistory]]
date = "1/25/2022"
action = "Sponsor: Senator IMEE R. MARCOS;"

[status]
status = "Pending Second Reading, Ordinary Business"
date = "1/25/2022"

[committee]
name = "Economic Affairs"
type = "primary"
