billNumber = "SBN-00687"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-687"
lastScraped = "2025-09-20T21:07:04.488333"
title = "MINDANAO RAILWAYS CORPORATION"
filedDate = "July 22, 2019"
author = "Pimentel, Aquilino \"Koko\" III"
longTitle = "AN ACT CREATING THE MINDANAO RAILWAYS CORPORATION PRESCRIBING ITS POWERS, FUNCTIONS, AND DUTIES, AND PROVIDING NECESSARY FUNDS FOR ITS OPERATION"
scope = "National"
subject = [ "Mindanao Railways Corporation",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3106227961!.pdf"
pdfFileName = "SBN-687 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "7/22/2019"
action = "Introduced by Senator AQUILINO 'KOKO' III PIMENTEL;"

[[legislativeHistory]]
date = "8/13/2019"
action = "Read on First Reading and Referred to the Committee(s) on GOVERNMENT CORPORATIONS AND PUBLIC ENTERPRISES; PUBLIC SERVICES; WAYS AND MEANS; and FINANCE;"

[status]
status = "Pending in the Committee"
date = "8/13/2019"

[committee]
name = "Government Corporations and Public Enterprises"
type = "primary"
