billNumber = "SBN-01536"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-1536"
lastScraped = "2025-09-20T21:11:25.487609"
title = "AMENDING SECTION 2 OF ACT NO. 3326 (TO ESTABLISH PERIODS OF PRESCRIPTION FOR VIOLATIONS)"
filedDate = "May 19, 2020"
author = "De Lima, Leila M."
longTitle = "AN ACT AMENDING SECTION 2 OF ACT NO. 3326, OTHERWISE KNOWN AS ‘AN ACT TO ESTABLISH PERIODS OF PRESCRIPTION FOR VIOLATIONS PENALIZED BY SPECIAL ACTS AND MUNICIPAL ORDINANCES AND TO PROVIDE WHEN PRESCRIPTION SHALL BEGIN TO RUN"
scope = "National"
subject = [ "Periods of Prescription",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3278229645!.pdf"
pdfFileName = "SBN-1536 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "5/19/2020"
action = "Introduced by Senator LEILA M. DE LIMA;"

[[legislativeHistory]]
date = "5/26/2020"
action = "Read on First Reading and Referred to the Committee on JUSTICE AND HUMAN RIGHTS;"

[status]
status = "Pending in the Committee"
date = "5/26/2020"

[committee]
name = "Justice and Human Rights"
type = "primary"
