billNumber = "SBN-01804"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-1804"
lastScraped = "2025-09-20T21:12:47.025778"
title = "PHILIPPINE BUILDING ACT OF 2020"
filedDate = "September 1, 2020"
author = "Revilla Jr., Ramon Bong"
longTitle = "AN ACT ESTABLISHING THE PHILIPPINE BUILDING ACT OF 2020, THEREBY REPEALING PRESIDENTIAL DECREE NO. 1096"
scope = "National"
subject = [ "Building Code of the Philippines (R.A.No. 6541)", "Buildings/Structures",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3343830248!.pdf"
pdfFileName = "SBN-1804 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "9/1/2020"
action = "Introduced by Senator RAMON BONG REVILLA JR.;"

[[legislativeHistory]]
date = "9/2/2020"
action = "Read on First Reading and Referred to the Committee(s) on PUBLIC WORKS and FINANCE;"

[status]
status = "Pending in the Committee"
date = "9/2/2020"

[committee]
name = "Public Works"
type = "primary"
