billNumber = "SBN-00970"
billType = "SBN"
congress = 18
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=18&q=SBN-970"
lastScraped = "2025-09-20T21:08:30.466359"
title = "INCREASING HAZARD PAY TO CIVILIAN DOCTORS AND NURSES OF THE AFPMMC"
filedDate = "August 27, 2019"
author = "Pacquiao, Emmanuel \"Manny\" D."
longTitle = "AN ACT INCREASING THE HAZARD PAY OF ALL PERSONNEL OF THE ARMED FORCES OF THE PHILIPPINES AND PROVIDING HAZARD PAY TO ALL CIVILIAN DOCTORS AND NURSES UNDER THE AFPMMC ASSIGNED IN CONFLICT AREAS PROVIDING FUNDS THEREFOR"
scope = "National"
subject = [ "Armed Forces of the Philippines Memorial Medical Center (AFPmmc)", "Hazard Pay", "Doctors/Physicians/Dentists", "Nurses/Nursing",]
pdfUrl = "https://web.senate.gov.ph/lisdata/3136928263!.pdf"
pdfFileName = "SBN-970, as Filed"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "8/27/2019"
action = "Introduced by Senator EMMANUEL 'MANNY' D. PACQUIAO;"

[[legislativeHistory]]
date = "8/28/2019"
action = "Read on First Reading and Referred to the Committee(s) on NATIONAL DEFENSE AND SECURITY and FINANCE;"

[[legislativeHistory]]
date = "9/3/2019"
action = "(Pursuant to Adopted Resolution No. 9: Merging of the Committee on National Defense and Security; and the Committee on Peace, Unification and Reconciliation, SBN-970 shall now be referred to the Committee on NATIONAL DEFENSE AND SECURITY, PEACE, UNIFICATION AND RECONCILIATION)"

[status]
status = "Pending in the Committee"
date = "8/28/2019"

[committee]
name = "National Defense and Security, Peace, Unification and Reconciliation"
type = "primary"
