billNumber = "HB00666"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB00666"
lastScraped = "2025-09-21T23:56:40.678920"
title = "HB00666"
longTitle = "AN ACT ADOPTING A RETAIL PRICE MAINTENANCE AND UNIFORM DISCOUNTING SCHEME IN BOOK TRADE TO ENSURE AFFORDABLE, ACCESSIBLE AND QUALITY-LADEN TEXTBOOKS AND OTHER RELATED EDUCATIONAL MATERIALS FOR PRIVATE AND PUBLIC SCHOOLS"
scope = "National"
dateFiled = "2010-07-01"
status = "Scheduled for first meeting/hearing on 2011-11-22"
statusOrder = 4.11
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB00666.pdf"
fileSize = 575832
author = "Ejercito, Joseph Victor G."
[[authorsDetail]]
name = "Ejercito, Joseph Victor G."
nameCode = "Ejercito"
date = ""
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2010-07-27"

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "principal"
referralCode = "0515"

[firstReading]
id = 56138
congress = 15
bill_no = "HB00666"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-07-27"
