billNumber = "HB01087"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB01087"
lastScraped = "2025-09-21T23:56:40.751663"
title = "HB01087"
longTitle = "AN ACT RECLASSIFYING A CERTAIN PORTION OF THE DEVELOPED TIMBERLAND IN BARANGAY PUYAT, MUNICIPALITY OF CARMEN, PROVINCE OF SURIGAO DEL SUR INTO ALIENABLE AND DISPOSABLE LAND"
scope = "Local"
dateFiled = "2010-07-08"
status = "Pending with the Committee on NATURAL RESOURCES since 2010-08-02"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Pichay, Philip A."
[[authorsDetail]]
name = "Pichay, Philip A."
nameCode = "Pichay"
date = ""
sequence = 1

[[committee]]
name = "NATURAL RESOURCES"
type = "primary"
referralCode = "0526"
dateRead = "2010-08-02"

[[committee]]
name = "LABOR AND EMPLOYMENT"
type = "principal"
referralCode = "0521"

[firstReading]
id = 56559
congress = 15
bill_no = "HB01087"
report = ""
comm_act = ""
referral = "0526"
ref_name = "NATURAL RESOURCES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-08-02"
