billNumber = "HB01875"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB01875"
lastScraped = "2025-09-21T23:56:40.900291"
title = "HB01875"
longTitle = "AN ACT SEPARATING THE TOMINJAO NATIONAL HIGH SCHOOL IN THE MUNICIPALITY OF DAANBANTAYAN, PROVINCE OF CEBU FROM THE CALAPE NATIONAL HIGH SCHOOL, MUNICIPALITY OF DAANBANTAYAN, PROVINCE OF CEBU, CONVERTING IT INTO AN INDEPENDENT NATIONAL HIGH SCHOOL, AND APPROPRIATING FUNDS THEREFOR"
scope = "Local"
dateFiled = "2010-07-28"
status = "Approved by the Committee on 2011-02-01"
statusOrder = 4.33
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Salimbangon, Benhur L."
[[authorsDetail]]
name = "Salimbangon, Benhur L."
nameCode = "Salimbangon"
date = ""
sequence = 1

[[committee]]
name = "BASIC EDUCATION AND CULTURE"
type = "primary"
referralCode = "C501"
dateRead = "2010-08-04"

[[committee]]
name = "WELFARE OF CHILDREN"
type = "principal"
referralCode = "F501"

[firstReading]
id = 57347
congress = 15
bill_no = "HB01875"
report = ""
comm_act = ""
referral = "C501"
ref_name = "BASIC EDUCATION AND CULTURE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-08-04"
