billNumber = "HB01399"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB01399"
lastScraped = "2025-09-21T23:56:40.820799"
title = "HB01399"
longTitle = "AN ACT PROVIDING FOR OMNIBUS AMENDMENTS TO REPUBLIC ACT NO. 8291, OTHERWISE KNOWN AS \\\"THE GOVERNMENT SERVICE INSURANCE ACT OF 1997\\\""
scope = "National"
dateFiled = "2010-07-15"
status = "Substituted by HB06904"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB01399.pdf"
fileSize = 627266
author = "RODRIGUEZ, RUFUS B."
coAuthors = [ "SYJUCO, AUGUSTO, JR. LIMCACO", "RODRIGUEZ, MAXIMO JR. B.",]
[[authorsDetail]]
name = "RODRIGUEZ, RUFUS B."
nameCode = "Rodriguez (R.)"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "SYJUCO, AUGUSTO, JR. LIMCACO"
nameCode = "Syjuco"
date = ""
journalNo = "J025"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "RODRIGUEZ, MAXIMO JR. B."
nameCode = "Rodriguez (M.)"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
type = "primary"
referralCode = "0515"
dateRead = "2010-08-02"

[[committee]]
name = "INFORMATION AND COMMUNICATIONS TECHNOLOGY"
type = "principal"
referralCode = "E504"

[firstReading]
id = 56871
congress = 15
bill_no = "HB01399"
report = ""
comm_act = ""
referral = "0515"
ref_name = "GOVERNMENT ENTERPRISES AND PRIVATIZATION"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-08-02"
