billNumber = "HB03303"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB03303"
lastScraped = "2025-09-21T23:56:41.149923"
title = "HB03303"
longTitle = "AN ACT DECLARING THE BALETE PASS IN STA. FE, NUEVA VIZCAYA AS A NATIONAL SHRINE TO BE KNOWN AS BALETE PASS NATIONAL SHRINE"
scope = "Local"
dateFiled = "2010-09-22"
status = "Substituted by HB05054"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Padilla, Carlos M."
coAuthors = [ "GO, ANA CRISTINA SIQUIAN", "AGGABAO, GIORGIDI BUZA", "ALBANO, RODOLFO JR. BAGUNU", "DY, NAPOLEON SANCHEZ", "BONOAN-DAVID, MA. THERESA BRONDIAL",]
[[authorsDetail]]
name = "Padilla, Carlos M."
nameCode = "Padilla"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "GO, ANA CRISTINA SIQUIAN"
nameCode = "Go (A.C.)"
date = ""
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "AGGABAO, GIORGIDI BUZA"
nameCode = "Aggabao"
date = ""
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "ALBANO, RODOLFO JR. BAGUNU"
nameCode = "Albano"
date = ""
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "DY, NAPOLEON SANCHEZ"
nameCode = "Dy"
date = ""
journalNo = "J027"
sessionNo = "1RS"

[[coAuthorsDetail]]
name = "BONOAN-DAVID, MA. THERESA BRONDIAL"
nameCode = "Bonoan-David"
date = ""
journalNo = "J037"
sessionNo = "1RS"

[[committee]]
name = "VETERANS AFFAIRS AND WELFARE"
type = "primary"
referralCode = "A506"
dateRead = "2010-09-27"

[[committee]]
name = "CLIMATE CHANGE"
type = "principal"
referralCode = "H503"

[firstReading]
id = 58775
congress = 15
bill_no = "HB03303"
report = ""
comm_act = ""
referral = "A506"
ref_name = "VETERANS AFFAIRS AND WELFARE"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-09-27"
