billNumber = "HB03210"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB03210"
lastScraped = "2025-09-21T23:56:41.133112"
title = "HB03210"
longTitle = "AN ACT REQUIRING ALL GOVERNMENT AGENCIES, INSTRUMENTALITIES, LOCAL GOVERNMENT UNITS, AND GOVERNMENT OWNED AND/OR CONTROLLED CORPORATIONS (GOCCs) AND ALL PRIVATE ESTABLISHMENTS TO USE SECURITY WATER-MARKED PAPER IN ALL RECEIPTS AND INVOICES, PERMITS, LICENSES, CLEARANCES, OFFICIAL PAPERS OR DOCUMENTS"
scope = "National"
dateFiled = "2010-09-16"
status = "Substituted by HB04224"
statusOrder = 9.1
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB03210.pdf"
fileSize = 557566
author = "Velarde, Mariano Michael Jr. M."
coAuthors = [ "TIENG, WILLIAM IRWIN C.",]
[[authorsDetail]]
name = "Velarde, Mariano Michael Jr. M."
nameCode = "Velarde"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "TIENG, WILLIAM IRWIN C."
nameCode = "Tieng"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "WAYS AND MEANS"
type = "primary"
referralCode = "0542"
dateRead = "2010-09-21"

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "principal"
referralCode = "0530"

[firstReading]
id = 58682
congress = 15
bill_no = "HB03210"
report = ""
comm_act = ""
referral = "0542"
ref_name = "WAYS AND MEANS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-09-21"
