billNumber = "HB03382"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB03382"
lastScraped = "2025-09-21T23:56:41.163852"
title = "HB03382"
longTitle = "AN ACT TO ESTABLISH FINANCIAL MANAGEMENT REFORMS FOR GOVERNMENT RESEARCH AND DEVELOPMENT OPERATIONS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2010-09-28"
status = "Referred to Stakeholders on 2012-08-23"
statusOrder = 4.01
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB03382.pdf"
fileSize = 703762
author = "Palmones, Angelo B."
coAuthors = [ "VILLAFUERTE, LUIS ROBREDO",]
[[authorsDetail]]
name = "Palmones, Angelo B."
nameCode = "Palmones"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "VILLAFUERTE, LUIS ROBREDO"
nameCode = "Villafuerte"
date = ""
journalNo = "J009"
sessionNo = "3RS"

[[committee]]
name = "SCIENCE AND TECHNOLOGY"
type = "primary"
referralCode = "0534"
dateRead = "2010-10-04"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 58854
congress = 15
bill_no = "HB03382"
report = ""
comm_act = ""
referral = "0534"
ref_name = "SCIENCE AND TECHNOLOGY"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2010-10-04"
