billNumber = "HB04699"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB04699"
lastScraped = "2025-09-21T23:56:41.428529"
title = "HB04699"
longTitle = "AN ACT PROVIDING FOR THE SECURITY OF TENURE OF FARMERS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2011-05-19"
status = "Pending with the Committee on AGRARIAN REFORM since 2011-05-25"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB04699.pdf"
fileSize = 637799
author = "Mariano, Rafael V."
coAuthors = [ "ILAGAN, LUZVIMINDA C.", "CASIÑO, TEODORO A.", "COLMENARES, NERI", "DE JESUS, EMERENCIANA", "TINIO, DANTE ANTONIO LUANSING",]
[[authorsDetail]]
name = "Mariano, Rafael V."
nameCode = "Mariano"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "ILAGAN, LUZVIMINDA C."
nameCode = "Ilagan"
date = ""
journalNo = "J003"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "CASIÑO, TEODORO A."
nameCode = "Casiño"
date = ""
journalNo = "J008"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "COLMENARES, NERI"
nameCode = "Colmenares"
date = ""
journalNo = "J008"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "DE JESUS, EMERENCIANA"
nameCode = "De Jesus"
date = ""
journalNo = "J008"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "TINIO, DANTE ANTONIO LUANSING"
nameCode = "Tinio"
date = ""
journalNo = "J008"
sessionNo = "2RS"

[[committee]]
name = "AGRARIAN REFORM"
type = "primary"
referralCode = "0502"
dateRead = "2011-05-25"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[firstReading]
id = 60171
congress = 15
bill_no = "HB04699"
report = ""
comm_act = ""
referral = "0502"
ref_name = "AGRARIAN REFORM"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2011-05-25"
