billNumber = "HB05927"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB05927"
lastScraped = "2025-09-21T23:56:41.661624"
title = "Strengthening Further The Workers' Right To Self-organization, Amending For The Purpose Articles 234-a, 235, 236, And 237, And Repealing Articles 234 (c) And 270 Of Presidential Decree No. 442"
longTitle = "AN ACT STRENGTHENING FURTHER THE WORKERS' RIGHT TO SELF-ORGANIZATION, AMENDING FOR THE PURPOSE ARTICLES 234-A, 235, 236 AND 237, AND REPEALING ARTICLES 234 (C) AND 270 OF PRESIDENTIAL DECREE NO. 442, AS AMENDED, OTHERWISE KNOWN AS THE LABOR CODE OF THE PHILIPPINES"
scope = "National"
dateFiled = "2012-02-27"
status = "Approved by the House on 2012-11-19, transmitted to on 2012-11-22 and received by the Senate on 2012-11-22"
statusOrder = 21.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB05927.pdf"
fileSize = 601890
author = "Belmonte, Feliciano Jr. R."
coAuthors = [ "VILLAROSA, MA. AMELITA CALIMBAS", "GONZALES, NEPTALI II MEDINA", "HERRERA-DY, BERNADETTE RAMIREZ", "ONG, EMIL LAO", "COSALAN, RONALD MORALES", "UMALI, REYNALDO VILLAR", "DE JESUS, EMERENCIANA", "ROMAN, HERMINIA BATISTA", "PICHAY, PHILIP ARREZA", "EJERCITO, JOSEPH VICTOR GOMEZ", "KHO, DAVID L.", "BELLO, WALDEN", "AGLIPAY, EMMELINE Y.", "OBILLO, REENA CONCEPCION G.", "GARIN, SHARON S.", "EVARDONE, BEN PAGARAN", "PALMONES, ANGELO B.", "BRAVO, NARCISO JR. RECIO", "MATUGAS, FRANCISCO TINIO", "CRUZ-GONZALES, CINCHONA", "FORTUNO, SALVIO BALERA", "VILLAR, MARK AGUILAR", "MARIANO, RAFAEL V.",]
[[authorsDetail]]
name = "Belmonte, Feliciano Jr. R."
nameCode = "Belmonte (F.)"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "VILLAROSA, MA. AMELITA CALIMBAS"
nameCode = "Calimbas-Villarosa"
date = ""
journalNo = "J045"
sessionNo = "2RS"

[[coAuthorsDetail]]
name = "GONZALES, NEPTALI II MEDINA"
nameCode = "Gonzales (N.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "HERRERA-DY, BERNADETTE RAMIREZ"
nameCode = "Herrera-Dy"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ONG, EMIL LAO"
nameCode = "Ong"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "COSALAN, RONALD MORALES"
nameCode = "Cosalan"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "UMALI, REYNALDO VILLAR"
nameCode = "Umali (R.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DE JESUS, EMERENCIANA"
nameCode = "De Jesus"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ROMAN, HERMINIA BATISTA"
nameCode = "Roman"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PICHAY, PHILIP ARREZA"
nameCode = "Pichay"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "EJERCITO, JOSEPH VICTOR GOMEZ"
nameCode = "Ejercito"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "KHO, DAVID L."
nameCode = "Kho (D.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BELLO, WALDEN"
nameCode = "Bello"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AGLIPAY, EMMELINE Y."
nameCode = "Aglipay"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "OBILLO, REENA CONCEPCION G."
nameCode = "Obillo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GARIN, SHARON S."
nameCode = "Garin (S.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "EVARDONE, BEN PAGARAN"
nameCode = "Evardone"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "PALMONES, ANGELO B."
nameCode = "Palmones"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BRAVO, NARCISO JR. RECIO"
nameCode = "Bravo"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MATUGAS, FRANCISCO TINIO"
nameCode = "Matugas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CRUZ-GONZALES, CINCHONA"
nameCode = "Cruz-Gonzales"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "FORTUNO, SALVIO BALERA"
nameCode = "Fortuno"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "VILLAR, MARK AGUILAR"
nameCode = "Villar"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MARIANO, RAFAEL V."
nameCode = "Mariano"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2012-02-28"

[[committee]]
name = "AGRICULTURE AND FOOD"
type = "principal"
referralCode = "E505"

[[motherBills]]
bill_no = "HB04552"
sequence = 1
flag = "S"

[[substitutedBills]]
bill_no = "HB04552"
sequence = 1
flag = "S"

[firstReading]
id = 61399
congress = 15
bill_no = "HB05927"
report = "01905"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "LABOR AND EMPLOYMENT"
recomm = "approval"
remarks = ""
date_read = "2012-02-28"
date_ob = "2012-02-28"
date_report = "2012-02-27"

[secondReading]
id = 8149
congress = 15
bill_no = "HB05927"
adopted_resolution = ""
adopted_resolution_title = ""
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "Adopted the Explanatory Note as the sponsorship remarks."
recommended_reconsidered = " "
date_calendared = "2012-03-07"
date_approved = "2012-10-17"
adopted_resolution_with_amendment = " "
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""

[thirdReading]
id = 9479
congress = 15
bill_no = "HB05927"
date_dist = "2012-11-05"
date_adopt = "2012-11-19"
remarks = "     "
no_yeas = 204
no_nays = 0
no_abstent = 0
date_trans = "2012-11-22"
date_rec = "2012-11-22"
amend_ind = " "
ccreqby = " "
for_enroll = " "
act_pres = " "
cc_yeas = 0
cc_nays = 0
cc_absten = 0
file = "hbt5927.pdf"
third_reading_copy = "https://docs.congress.hrep.online/legisdocs/third_15/hbt5927.pdf"
