billNumber = "HB06480"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB06480"
lastScraped = "2025-09-21T23:56:41.773933"
title = "HB06480"
longTitle = "AN ACT ADOPTING THE INTEGRATED RIVER BASIN MANAGEMENT APPROACH AS A COMPREHENSIVE FRAMEWORK IN DEVELOPING AND MANAGING THE COUNTRY'S RIVER BASIN SYSTEMS AND FOR OTHER PURPOSES"
scope = "National"
dateFiled = "2012-08-16"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2012-08-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB06480.pdf"
fileSize = 1676478
author = "Villarica, Linabelle Ruth R."
[[authorsDetail]]
name = "Villarica, Linabelle Ruth R."
nameCode = "Villarica"
date = ""
sequence = 1

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2012-08-28"

[[committee]]
name = "CREATIVE INDUSTRIES"
type = "principal"
referralCode = "J505"

[firstReading]
id = 61952
congress = 15
bill_no = "HB06480"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2012-08-28"
