billNumber = "HB06834"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HB06834"
lastScraped = "2025-09-21T23:56:41.866014"
title = "HB06834"
longTitle = "AN ACT MANDATING THE CREATION OF A COMMITTEE ON ENVIRONMENTAL PROTECTION IN EACH LOCAL GOVERNMENT LEGISLATIVE COUNCIL"
scope = "National"
dateFiled = "2013-01-22"
status = "Pending with the Committee on LOCAL GOVERNMENT since 2013-01-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = "https://docs.congress.hrep.online/legisdocs/basic_15/HB06834.pdf"
fileSize = 195579
author = "Bonoan-David, Ma. Theresa B."
[[authorsDetail]]
name = "Bonoan-David, Ma. Theresa B."
nameCode = "Bonoan-David"
date = ""
sequence = 1

[[committee]]
name = "LOCAL GOVERNMENT"
type = "primary"
referralCode = "0522"
dateRead = "2013-01-28"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 62306
congress = 15
bill_no = "HB06834"
report = ""
comm_act = ""
referral = "0522"
ref_name = "LOCAL GOVERNMENT"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2013-01-28"
