billNumber = "HJR0015"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HJR0015"
lastScraped = "2025-09-21T23:56:41.898708"
title = "HJR0015"
longTitle = "A RESOLUTION URGING THE DEPARTMENT OF PUBLIC WORKS AND HIGHWAYS, DEPARTMENT OF TRANSPORTATION AND COMMUNICATIONS AND NATIONAL ECONOMIC DEVELOPMENT AUTHORITY TO PRIORITIZE THE CONDUCT OF A FULL BLOWN FEASIBILITY STUDY ON THE \\\"ONE VISAYAS FRIENDSHIP BRIDGE PROJECT\\\""
scope = "National"
dateFiled = "2011-02-21"
status = "Pending with the Committee on PUBLIC WORKS AND HIGHWAYS since 2011-02-28"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Mercado, Roger G."
coAuthors = [ "MIRAFLORES, FLORENCIO TUMBOCON", "DEL ROSARIO, ANTONIO RAFAEL GARCIA", "CASTRO, JANE TAN", "NAVA, JOAQUIN CARLOS RAHMAN ARAÑO", "DEFENSOR, ARTHUR JR. RIVERA", "BIRON, FERJENEL G.", "TREÑAS, JERRY PEREZ", "MARAÑON, ALFREDO III DALISAY", "BENITEZ, ALFREDO ABELARDO BANTUG", "ARROYO, IGNACIO JR. TUASON", "ALVAREZ, MERCEDES KHO", "RELAMPAGOS, RENE LOPEZ", "AUMENTADO, ERICO BOYLES", "YAP, ARTHUR CUA", "GULLAS, EDUARDO RIVERA", "GARCIA, PABLO PARAS", "GARCIA, PABLO JOHN FIEL", "SALIMBANGON, BENHUR LAGO", "DURANO, RAMON VI HOTCHKISS", "QUISUMBING, GABRIEL L. ROMUALDEZ", "OSMEÑA, TOMAS DE LA RAMA", "LIMKAICHONG, JOCELYN SY", "ARNAIZ, GEORGE PLANTO", "ESPINA, ROGELIO JIMENEZ", "EVARDONE, BEN PAGARAN", "APOSTOL, SERGIO A. FIGUEROA", "GOMEZ, LUCY TORRES", "CARI, JOSE CARLOS LORETO", "DAZA, RAUL AGUILA", "ONG, EMIL LAO", "SARMIENTO, MEL SENEN SEVILLA", "TAN, MILAGROSA TEE",]
[[authorsDetail]]
name = "Mercado, Roger G."
nameCode = "Mercado (R.)"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "MIRAFLORES, FLORENCIO TUMBOCON"
nameCode = "Miraflores"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEL ROSARIO, ANTONIO RAFAEL GARCIA"
nameCode = "Del Rosario (A.G.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CASTRO, JANE TAN"
nameCode = "Castro"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "NAVA, JOAQUIN CARLOS RAHMAN ARAÑO"
nameCode = "Nava"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DEFENSOR, ARTHUR JR. RIVERA"
nameCode = "Defensor"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BIRON, FERJENEL G."
nameCode = "Biron"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TREÑAS, JERRY PEREZ"
nameCode = "Treñas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "MARAÑON, ALFREDO III DALISAY"
nameCode = "Marañon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "BENITEZ, ALFREDO ABELARDO BANTUG"
nameCode = "Benitez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ARROYO, IGNACIO JR. TUASON"
nameCode = "Arroyo (I.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ALVAREZ, MERCEDES KHO"
nameCode = "Alvarez (M.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "RELAMPAGOS, RENE LOPEZ"
nameCode = "Relampagos"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "AUMENTADO, ERICO BOYLES"
nameCode = "Aumentado"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "YAP, ARTHUR CUA"
nameCode = "Yap (A.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GULLAS, EDUARDO RIVERA"
nameCode = "Gullas"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GARCIA, PABLO PARAS"
nameCode = "Garcia (P.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GARCIA, PABLO JOHN FIEL"
nameCode = "Garcia (P.J.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SALIMBANGON, BENHUR LAGO"
nameCode = "Salimbangon"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DURANO, RAMON VI HOTCHKISS"
nameCode = "Durano"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "QUISUMBING, GABRIEL L. ROMUALDEZ"
nameCode = "Quisumbing"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "OSMEÑA, TOMAS DE LA RAMA"
nameCode = "Osmeña"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "LIMKAICHONG, JOCELYN SY"
nameCode = "Limkaichong"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ARNAIZ, GEORGE PLANTO"
nameCode = "Arnaiz"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ESPINA, ROGELIO JIMENEZ"
nameCode = "Espina"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "EVARDONE, BEN PAGARAN"
nameCode = "Evardone"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "APOSTOL, SERGIO A. FIGUEROA"
nameCode = "Apostol"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "GOMEZ, LUCY TORRES"
nameCode = "Gomez"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "CARI, JOSE CARLOS LORETO"
nameCode = "Cari"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "DAZA, RAUL AGUILA"
nameCode = "Daza"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "ONG, EMIL LAO"
nameCode = "Ong"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "SARMIENTO, MEL SENEN SEVILLA"
nameCode = "Sarmiento (M.)"
date = ""
journalNo = ""
sessionNo = ""

[[coAuthorsDetail]]
name = "TAN, MILAGROSA TEE"
nameCode = "Tan"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "PUBLIC WORKS AND HIGHWAYS"
type = "primary"
referralCode = "0530"
dateRead = "2011-02-28"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[firstReading]
id = 62445
congress = 15
bill_no = "HJR0015"
report = ""
comm_act = ""
referral = "0530"
ref_name = "PUBLIC WORKS AND HIGHWAYS"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2011-02-28"
