billNumber = "HR01203"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HR01203"
lastScraped = "2025-09-21T23:56:42.240355"
title = "HR01203"
longTitle = "RESOLUTION COMMENDING AND CONGRATULATING HON. EMMANUEL DAPIDRAN PACQUIAO FOR HIS REMARKABLE VICTORY OVER 'SUGAR' SHANE MOSLEY OF THE UNITED STATES OF AMERICA, ON THEIR BOXING MATCH HELD ON MAY 7, 2011 AT LAS VEGAS, USA, THEREBY RETAINING HIS WBO WELTERWEIGHT TITLE"
scope = "National"
dateFiled = "2011-05-09"
status = "Pending with the Committee on RULES since 2011-05-09"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Lopez, Carol Jayne B."
[[authorsDetail]]
name = "Lopez, Carol Jayne B."
nameCode = "Lopez (C.J.)"
date = ""
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2011-05-09"

[[committee]]
name = "TRANSPORTATION"
type = "principal"
referralCode = "E509"

[firstReading]
id = 63673
congress = 15
bill_no = "HR01203"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2011-05-09"
