billNumber = "HR01314"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HR01314"
lastScraped = "2025-09-21T23:56:42.264580"
title = "HR01314"
longTitle = "A RESOLUTION DIRECTING THE COMMITTEE ON HEALTH TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION ON THE REPORTS THAT 15 MILLION HOUSEHOLDS NATIONWIDE HAVE NO ACCESS TO POTABLE WATER"
scope = "National"
dateFiled = "2011-05-25"
status = "Adopted Resolution (Pending with the committee on PUBLIC WORKS AND HIGHWAYS since 2011-08-15)"
statusOrder = 5.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "RODRIGUEZ, MAXIMO B., JR."
coAuthors = [ "RODRIGUEZ, RUFUS BAUTISTA",]
[[authorsDetail]]
name = "RODRIGUEZ, MAXIMO B., JR."
nameCode = "Rodriguez (M.)"
date = ""
sequence = 1

[[coAuthorsDetail]]
name = "RODRIGUEZ, RUFUS BAUTISTA"
nameCode = "Rodriguez (R.)"
date = ""
journalNo = ""
sessionNo = ""

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2011-05-31"

[[committee]]
name = "HIGHER AND TECHNICAL EDUCATION"
type = "principal"
referralCode = "C502"

[firstReading]
id = 63784
congress = 15
bill_no = "HR01314"
report = "01295"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Adoption with amendments."
remarks = ""
date_read = "2011-05-31"
date_ob = "2011-08-15"
date_report = "2011-08-15"

[secondReading]
id = 7483
congress = 15
bill_no = "HR01314"
adopted_resolution = ""
adopted_resolution_title = "RESOLUTION DIRECTING THE COMMITTEE ON PUBLIC WORKS AND HIGHWAYS TO CONDUCT AN INQUIRY, IN AID OF LEGISLATION, ON THE REPORTS THAT 15 MILLION HOUSEHOLDS NATIONWIDE HAVE NO ACCESS TO POTABLE WATER"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = "Referred to the Ctte. on Public Works and Highways."
recommended_reconsidered = " "
date_calendared = "2011-08-15"
date_approved = "2011-08-15"
adopted_resolution_with_amendment = "Y"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
date_refferral = "2011-08-15"
action_on_adopted_resolution = ""
