billNumber = "HR01051"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HR01051"
lastScraped = "2025-09-21T23:56:42.154103"
title = "HR01051"
longTitle = "RESOLUTION COMMENDING THE THREE FILIPINO-AMERICAN PRODUCERS OF THE BEST SHORT FILM \\\"GOD OF LOVE\\\" IN THE 83RD ANNUAL ACADEMY AWARDS"
scope = "National"
dateFiled = "2011-03-07"
status = "Adopted as Resolution No. HR00113 on 2011-05-25"
statusOrder = 15.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Haresco, Teodorico Jr. T."
[[authorsDetail]]
name = "Haresco, Teodorico Jr. T."
nameCode = "Haresco"
date = ""
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2011-03-14"

[[committee]]
name = "RULES"
type = "principal"
referralCode = "0532"

[[motherBills]]
bill_no = "HR01056"
sequence = 1
flag = "C"

[[consolidatedBills]]
bill_no = "HR01056"
sequence = 1
flag = "C"

[firstReading]
id = 63521
congress = 15
bill_no = "HR01051"
report = "01020"
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = "RULES"
recomm = "Adoption without amendments in consolidation with House Resolution No. 1056."
remarks = ""
date_read = "2011-03-14"
date_ob = "2011-05-25"
date_report = "2011-05-25"

[secondReading]
id = 7121
congress = 15
bill_no = "HR01051"
adopted_resolution = "HR00113"
adopted_resolution_title = "RESOLUTION COMMENDING THE THREE FILIPINO-AMERICAN PRODUCERS OF THE BEST SHORT FILM \"GOD OF LOVE\" IN THE 83RD ANNUAL ACADEMY AWARDS"
reasons = ""
comm_report_no = ""
comm_report_action = ""
remarks = ""
recommended_reconsidered = " "
date_calendared = "2011-05-25"
date_approved = "2011-05-25"
adopted_resolution_with_amendment = "N"
concurred_by_the_senate_with_amend = " "
concurrent_resolution_no = ""
action_on_adopted_resolution = ""
file = "HR01051.pdf"
adopted_resolution_file = "https://docs.congress.hrep.online/legisdocs/second_15/HR01051.pdf"
