billNumber = "HR02527"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=HR02527"
lastScraped = "2025-09-21T23:56:42.541077"
title = "HR02527"
longTitle = "A RESOLUTION COMMENDING MS. CANDICE ADEA FOR WINNING FIRST PRIZE IN THE PRESTIGIOUS 2012 HELSINKI INTERNATIONAL BALLET COMPETITION"
scope = "National"
dateFiled = "2012-07-03"
status = "Pending with the Committee on RULES since 2012-07-24"
statusOrder = 4.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Angara, Juan Edgardo M."
[[authorsDetail]]
name = "Angara, Juan Edgardo M."
nameCode = "Angara"
date = ""
sequence = 1

[[committee]]
name = "RULES"
type = "primary"
referralCode = "0532"
dateRead = "2012-07-24"

[firstReading]
id = 64996
congress = 15
bill_no = "HR02527"
report = ""
comm_act = ""
referral = "0532"
ref_name = "RULES"
sub_name = ""
recomm = ""
remarks = ""
date_read = "2012-07-24"
