billNumber = "PS00530"
billType = "HB"
congress = 15
apiCongressId = 15
url = "https://www.congress.gov.ph/legisdocs/?v=billsresults&congress=15&q=PS00530"
lastScraped = "2025-09-21T23:56:42.740929"
title = "Dual Citizenship Of Those Seeking Public Office"
longTitle = ""
scope = "National"
dateFiled = "2013-02-04"
status = "Pending First Reading (Filed last 2013-02-04)"
statusOrder = 1.0
urgent = false
adminBill = false
pdfUrl = ""
fileSize = 0
author = "Velasco, Lord Allan Jay Q."
[[authorsDetail]]
name = "Velasco, Lord Allan Jay Q."
nameCode = "Velasco"
date = ""
sequence = 1

