billNumber = "HBN-04195"
billType = "HBN"
congress = 15
url = "https://web.senate.gov.ph/lis/bill_res.aspx?congress=15&q=HBN-4195"
lastScraped = "2025-09-20T23:50:51.894938"
title = "RETIREMENT AGE FOR UNDERGROUND MINE WORKERS"
longTitle = "AN ACT EXTENDING THE COVERAGE OF THE REDUCED RETIREMENT AGE FOR UNDERGROUND MINE WORKERS TO INCLUDE MILL PLANT WORKERS AND SUPPORT SERVICES PERSONNEL SUCH AS MECHANICAL, ELECTRICAL AND TAILINGS POND PERSONNEL, AMENDING FURTHER ARTICLE 287 OF PRESIDENTIAL DECREE NO. 442, OTHERWISE KNOWN AS THE LABOR CODE OF THE PHILIPPINES, AS AMENDED"
scope = "National"
subject = [ "Labor Code of the Philippines (P.D.No. 442; Amendments)", "Retirement Age",]
pdfUrl = "https://web.senate.gov.ph/lisdata/1271710743!.pdf"
pdfFileName = "HBN-4195 (as filed)"
[[legislativeHistory]]
date = ""
action = "Entitled:"

[[legislativeHistory]]
date = "1/26/2012"
action = "Sent to the Senate requesting for concurrence;"

[[legislativeHistory]]
date = "1/31/2012"
action = "Read on First Reading and Referred to the Committee on LABOR, EMPLOYMENT AND HUMAN RESOURCES DEVELOPMENT;"

[status]
status = "Pending in the Committee"
date = "1/31/2012"

[committee]
name = "Labor, Employment and Human Resources Development"
type = "primary"
