id = 416
authorId = "C033"
fullName = "Cojuangco, Carlos O."
lastName = "COJUANGCO"
firstName = "CARLOS"
middleName = "OPPEN"
suffix = ""
nickName = "Charlie"
email = ""
website = ""
room = ""
local = ""
directLine = ""
chiefOfStaff = ""
partyAffiliation = ""
partyAffiliationDesc = ""
current = false
lastScraped = "2025-09-23T02:52:22.773291"
[[principalAuthoredBills]]
congress = 11
count = 37
[[principalAuthoredBills.bills]]
billNo = "HB00114"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00487"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00666"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00667"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00684"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00685"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00941"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01085"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01805"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01806"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01807"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01808"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01809"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01810"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01972"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02051"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02052"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02053"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02054"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02055"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02056"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02116"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03115"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB04787"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB05429"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB07213"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB07214"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB07215"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB08239"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB08809"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB08810"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB09152"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB10651"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB12880"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00131"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00406"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00457"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = ""
sequenceNo = 0


[[principalAuthoredBills]]
congress = 12
count = 22
[[principalAuthoredBills.bills]]
billNo = "HB00813"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00814"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00815"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00816"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00817"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB00818"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01023"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01024"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01025"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01026"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01027"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01028"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01029"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01030"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01031"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01032"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01033"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01034"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB01035"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02986"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00803"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR01171"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 0


[[principalAuthoredBills]]
congress = 13
count = 5
[[principalAuthoredBills.bills]]
billNo = "HB03784"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03785"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03786"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03787"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04324"
date = ""
name = "COJUANGCO, CARLOS O."
nameCode = "Cojuangco"
sequenceNo = 1


[[principalAuthoredBills]]
congress = 17
count = 50
[[principalAuthoredBills.bills]]
billNo = "HB00001"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 6

[[principalAuthoredBills.bills]]
billNo = "HB00003"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB00004"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB00005"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB00006"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB00008"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB00009"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB00010"
date = "2016-06-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB02331"
date = "2016-08-02"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02332"
date = "2016-08-02"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02333"
date = "2016-08-02"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02334"
date = "2016-08-02"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03384"
date = "2016-08-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 26

[[principalAuthoredBills.bills]]
billNo = "HB03408"
date = "2016-08-31"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 15

[[principalAuthoredBills.bills]]
billNo = "HB03504"
date = "2016-09-06"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 28

[[principalAuthoredBills.bills]]
billNo = "HB04727"
date = "2017-01-11"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 9

[[principalAuthoredBills.bills]]
billNo = "HB05670"
date = "2017-05-18"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 80

[[principalAuthoredBills.bills]]
billNo = "HB05777"
date = "2017-05-29"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 32

[[principalAuthoredBills.bills]]
billNo = "HB06060"
date = "2017-07-26"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB06157"
date = "2017-08-09"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB06215"
date = "2017-08-16"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 16

[[principalAuthoredBills.bills]]
billNo = "HB06425"
date = "2017-09-19"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 7

[[principalAuthoredBills.bills]]
billNo = "HB06517"
date = "2017-10-02"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 16

[[principalAuthoredBills.bills]]
billNo = "HB06574"
date = "2017-10-10"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB06893"
date = "2017-12-13"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 4

[[principalAuthoredBills.bills]]
billNo = "HB07184"
date = "2018-02-14"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB07233"
date = "2018-02-22"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 52

[[principalAuthoredBills.bills]]
billNo = "HB07513"
date = "2018-04-17"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB07652"
date = "2018-05-09"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 22

[[principalAuthoredBills.bills]]
billNo = "HB07878"
date = "2018-06-21"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 7

[[principalAuthoredBills.bills]]
billNo = "HB08165"
date = "2018-08-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 101

[[principalAuthoredBills.bills]]
billNo = "HB08169"
date = "2018-09-03"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 22

[[principalAuthoredBills.bills]]
billNo = "HB08636"
date = "2018-11-21"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 86

[[principalAuthoredBills.bills]]
billNo = "HB08702"
date = "2018-12-03"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB08844"
date = "2019-01-17"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 13

[[principalAuthoredBills.bills]]
billNo = "HB08883"
date = "2019-01-28"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 102

[[principalAuthoredBills.bills]]
billNo = "HB08908"
date = "2019-01-29"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 14

[[principalAuthoredBills.bills]]
billNo = "HB08912"
date = "2019-01-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 42

[[principalAuthoredBills.bills]]
billNo = "HB08981"
date = "2019-01-31"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 23

[[principalAuthoredBills.bills]]
billNo = "HB09103"
date = "2019-02-08"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 21

[[principalAuthoredBills.bills]]
billNo = "HB09121"
date = "2019-02-12"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 18

[[principalAuthoredBills.bills]]
billNo = "HB09146"
date = "2019-02-18"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 21

[[principalAuthoredBills.bills]]
billNo = "HB09155"
date = "2019-03-05"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 56

[[principalAuthoredBills.bills]]
billNo = "HB09156"
date = "2019-03-05"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 81

[[principalAuthoredBills.bills]]
billNo = "HR00635"
date = "2016-12-14"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 17

[[principalAuthoredBills.bills]]
billNo = "HR01049"
date = "2017-05-31"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 10

[[principalAuthoredBills.bills]]
billNo = "HR01053"
date = "2017-05-31"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 23

[[principalAuthoredBills.bills]]
billNo = "HR01718"
date = "2018-02-21"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02001"
date = "2018-07-11"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HR02367"
date = "2018-12-12"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 15


[[principalAuthoredBills]]
congress = 18
count = 17
[[principalAuthoredBills.bills]]
billNo = "HB00618"
date = "2019-07-01"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB04228"
date = "2019-08-28"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 7

[[principalAuthoredBills.bills]]
billNo = "HB06313"
date = "2020-02-18"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06476"
date = "2020-03-04"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06501"
date = "2020-03-05"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 6

[[principalAuthoredBills.bills]]
billNo = "HB06815"
date = "2020-05-26"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 62

[[principalAuthoredBills.bills]]
billNo = "HB06878"
date = "2020-05-31"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 14

[[principalAuthoredBills.bills]]
billNo = "HB06895"
date = "2020-06-01"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 15

[[principalAuthoredBills.bills]]
billNo = "HB07685"
date = "2020-09-17"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB07727"
date = "2020-09-22"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 9

[[principalAuthoredBills.bills]]
billNo = "HB07829"
date = "2020-10-05"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB09560"
date = "2021-06-01"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 91

[[principalAuthoredBills.bills]]
billNo = "HB09575"
date = "2021-06-02"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 26

[[principalAuthoredBills.bills]]
billNo = "HB10107"
date = "2021-08-30"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB10153"
date = "2021-09-07"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 7

[[principalAuthoredBills.bills]]
billNo = "HR00534"
date = "2019-11-18"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01441"
date = "2020-12-21"
name = "COJUANGCO, CHARLIE"
nameCode = "Cojuangco"
sequenceNo = 7


