id = 493
authorId = "D034"
fullName = "Gatchalian, Sherwin T."
lastName = "Gatchalian"
firstName = "Sherwin"
middleName = "Ting"
suffix = ""
nickName = ""
email = ""
website = ""
room = ""
local = ""
directLine = ""
chiefOfStaff = ""
partyAffiliation = ""
partyAffiliationDesc = ""
current = false
lastScraped = "2025-09-23T02:52:23.141447"
[[principalAuthoredBills]]
congress = 12
count = 19
[[principalAuthoredBills.bills]]
billNo = "HB02158"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02159"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02516"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02517"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB02832"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03000"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03318"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03375"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03376"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03979"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB03980"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB04067"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HB04242"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00032"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00077"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00078"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00176"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00189"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0

[[principalAuthoredBills.bills]]
billNo = "HR00232"
date = ""
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian"
sequenceNo = 0


[[principalAuthoredBills]]
congress = 16
count = 85
[[principalAuthoredBills.bills]]
billNo = "HB02053"
date = "2013-07-30"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02338"
date = "2013-08-07"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02624"
date = "2013-08-28"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02625"
date = "2013-08-28"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03428"
date = "2013-11-25"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03434"
date = "2013-11-26"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03680"
date = "2014-01-15"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03681"
date = "2014-01-15"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03838"
date = "2014-02-05"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03855"
date = "2014-02-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03927"
date = "2014-02-17"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04284"
date = "2014-04-03"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04359"
date = "2014-05-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04360"
date = "2014-05-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04361"
date = "2014-05-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04433"
date = "2014-05-15"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04434"
date = "2014-05-15"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04661"
date = "2014-06-17"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04662"
date = "2014-06-17"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04714"
date = "2014-07-08"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04740"
date = "2014-07-15"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04759"
date = "2014-07-24"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04785"
date = "2014-08-04"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04801"
date = "2014-08-05"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04946"
date = "2014-09-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04947"
date = "2014-09-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04948"
date = "2014-09-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04990"
date = "2014-09-10"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05008"
date = "2014-09-16"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05072"
date = "2014-09-29"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05097"
date = "2014-10-14"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05098"
date = "2014-10-14"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05099"
date = "2014-10-14"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05206"
date = "2014-11-18"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 2

[[principalAuthoredBills.bills]]
billNo = "HB05231"
date = "2014-11-26"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 7

[[principalAuthoredBills.bills]]
billNo = "HB05242"
date = "2014-12-03"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05243"
date = "2014-12-03"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05244"
date = "2014-12-03"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05245"
date = "2014-12-03"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05348"
date = "2015-01-21"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05378"
date = "2015-01-29"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05404"
date = "2015-02-04"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05674"
date = "2015-04-16"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05709"
date = "2015-05-05"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05715"
date = "2015-05-05"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05731"
date = "2015-05-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05732"
date = "2015-05-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05760"
date = "2015-05-13"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05867"
date = "2015-06-09"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05892"
date = "2015-06-23"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05896"
date = "2015-06-23"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05905"
date = "2015-07-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05974"
date = "2015-07-30"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05975"
date = "2015-07-30"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05976"
date = "2015-07-30"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06160"
date = "2015-09-21"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06181"
date = "2015-09-29"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06252"
date = "2015-11-04"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06268"
date = "2015-11-09"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 47

[[principalAuthoredBills.bills]]
billNo = "HB06434"
date = "2016-02-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06435"
date = "2016-02-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00542"
date = "2013-11-25"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00543"
date = "2013-11-25"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00727"
date = "2014-01-29"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00885"
date = "2014-02-25"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00909"
date = "2014-03-04"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01013"
date = "2014-04-07"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01336"
date = "2014-08-04"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01341"
date = "2014-08-05"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01425"
date = "2014-08-28"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01444"
date = "2014-09-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01474"
date = "2014-09-09"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01507"
date = "2014-09-16"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01754"
date = "2014-12-10"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01762"
date = "2014-12-11"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01791"
date = "2015-01-06"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02059"
date = "2015-05-05"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02098"
date = "2015-05-18"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02178"
date = "2015-06-16"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02399"
date = "2015-09-21"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02419"
date = "2015-09-28"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02467"
date = "2015-10-27"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02576"
date = "2015-12-16"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02653"
date = "2016-02-02"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "PS00211"
date = "2014-06-09"
name = "GATCHALIAN, SHERWIN T."
nameCode = "Gatchalian (S.)"
sequenceNo = 1


[[principalAuthoredBills]]
congress = 19
count = 1
[[principalAuthoredBills.bills]]
billNo = "SB01604"
date = ""
name = "GATCHALIAN, WIN"
nameCode = "Gatchalian"
sequenceNo = 1


