id = 620
authorId = "F043"
fullName = "Tupas, Niel Jr. C."
lastName = "TUPAS"
firstName = "NIEL JR."
middleName = "CAUSING"
suffix = "JR."
nickName = "Junjun"
email = ""
website = ""
room = ""
local = ""
directLine = ""
chiefOfStaff = ""
partyAffiliation = ""
partyAffiliationDesc = ""
current = false
lastScraped = "2025-09-23T02:52:23.940160"
[[principalAuthoredBills]]
congress = 14
count = 35
[[principalAuthoredBills.bills]]
billNo = "HB02486"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02487"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02586"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03460"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03630"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03631"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03632"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03633"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03634"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03635"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03636"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03694"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03695"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03710"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03753"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04060"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04061"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04637"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04638"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04640"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04641"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04642"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04643"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04673"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04719"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04902"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04957"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05977"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06447"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00796"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00927"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01229"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01484"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01568"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "PS00020"
date = ""
name = "TUPAS, NIEL JR. C."
nameCode = "Tupas"
sequenceNo = 1


[[principalAuthoredBills]]
congress = 15
count = 29
[[principalAuthoredBills.bills]]
billNo = "HB00177"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB00178"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB00179"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB01174"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB01175"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB01176"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB01177"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB01178"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02416"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03489"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03691"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03916"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03941"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03942"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04453"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04474"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04909"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06570"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00313"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01089"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01459"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01519"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01553"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01623"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01718"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01759"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02198"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02722"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "RPT0004"
date = ""
name = "TUPAS, NIEL JR. CAUSING"
nameCode = "Tupas"
sequenceNo = 1


[[principalAuthoredBills]]
congress = 16
count = 27
[[principalAuthoredBills.bills]]
billNo = "HB00980"
date = "2013-07-02"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB00981"
date = "2013-07-02"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB00982"
date = "2013-07-02"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB00983"
date = "2013-07-02"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB01093"
date = "2013-07-04"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02032"
date = "2013-07-30"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB02300"
date = "2013-08-06"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB03224"
date = "2013-10-22"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04090"
date = "2014-03-06"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04108"
date = "2014-03-10"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04428"
date = "2014-05-15"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04537"
date = "2014-05-29"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04653"
date = "2014-06-16"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04738"
date = "2014-07-14"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05283"
date = "2014-12-11"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HB05286"
date = "2014-12-11"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 13

[[principalAuthoredBills.bills]]
billNo = "HB05581"
date = "2015-03-16"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB05940"
date = "2015-07-22"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06068"
date = "2015-08-27"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06180"
date = "2015-09-29"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB06381"
date = "2016-01-12"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00115"
date = "2013-07-25"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00234"
date = "2013-08-28"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR00265"
date = "2013-09-04"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR01543"
date = "2014-10-02"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02394"
date = "2015-09-17"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HR02485"
date = "2015-11-03"
name = "TUPAS, NEIL JR C."
nameCode = "Tupas"
sequenceNo = 1


