id = 57
authorId = "J018"
fullName = "CALIXTO, ANTONINO G."
lastName = "Calixto"
firstName = "Antonino"
middleName = ""
suffix = ""
nickName = "HON. ANTONINO  G. CALIXTO"
email = ""
website = ""
room = "RVM-103"
local = "7096"
directLine = "8952-4146"
chiefOfStaff = ""
partyAffiliation = ""
partyAffiliationDesc = ""
current = true
lastScraped = "2025-09-23T02:52:22.680102"
memberType = 70
district = 28
[[memberships]]
congress = 103
congressDesc = "20th Congress"
type = 70
typeDesc = "District Representative"
district = 28
partyListId = 0
partyListName = ""

[[memberships]]
congress = 19
congressDesc = "19th Congress"
type = 70
typeDesc = "District Representative"
district = 28
partyListId = 0
partyListName = ""

[[committees]]
code = "0504"
name = "APPROPRIATIONS"
title = "Vice Chairperson"

[[committees]]
code = "0514"
name = "GAMES AND AMUSEMENTS"
title = "Member for the Majority"

[[committees]]
code = "E502"
name = "METRO MANILA DEVELOPMENT"
title = "Vice Chairperson"

[[committees]]
code = "0526"
name = "NATURAL RESOURCES"
title = "Member for the Majority"

[[committees]]
code = "0539"
name = "TRADE AND INDUSTRY"
title = "Member for the Majority"

[[principalAuthoredBills]]
congress = 18
count = 26
[[principalAuthoredBills.bills]]
billNo = "HB00059"
date = "2019-07-01"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 28

[[principalAuthoredBills.bills]]
billNo = "HB02116"
date = "2019-07-15"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04395"
date = "2019-09-04"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04396"
date = "2019-09-04"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB04933"
date = "2019-09-30"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 64

[[principalAuthoredBills.bills]]
billNo = "HB05989"
date = "2020-01-22"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 168

[[principalAuthoredBills.bills]]
billNo = "HB07725"
date = "2020-09-21"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 68

[[principalAuthoredBills.bills]]
billNo = "HB07805"
date = "2020-10-01"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 35

[[principalAuthoredBills.bills]]
billNo = "HB07808"
date = "2020-10-01"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 41

[[principalAuthoredBills.bills]]
billNo = "HB07829"
date = "2020-10-05"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 165

[[principalAuthoredBills.bills]]
billNo = "HB08698"
date = "2021-02-15"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 41

[[principalAuthoredBills.bills]]
billNo = "HB09350"
date = "2021-05-17"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 54

[[principalAuthoredBills.bills]]
billNo = "HB09487"
date = "2021-05-26"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 17

[[principalAuthoredBills.bills]]
billNo = "HB09948"
date = "2021-08-09"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 54

[[principalAuthoredBills.bills]]
billNo = "HB10108"
date = "2021-08-30"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 50

[[principalAuthoredBills.bills]]
billNo = "HB10109"
date = "2021-08-30"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 51

[[principalAuthoredBills.bills]]
billNo = "HB10215"
date = "2021-09-14"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 51

[[principalAuthoredBills.bills]]
billNo = "HB10233"
date = "2021-09-16"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 51

[[principalAuthoredBills.bills]]
billNo = "HB10243"
date = "2021-09-19"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 51

[[principalAuthoredBills.bills]]
billNo = "HB10244"
date = "2021-09-19"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 50

[[principalAuthoredBills.bills]]
billNo = "HB10255"
date = "2021-09-20"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 51

[[principalAuthoredBills.bills]]
billNo = "HB10582"
date = "2021-12-09"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 21

[[principalAuthoredBills.bills]]
billNo = "HB10699"
date = "2022-01-25"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 29

[[principalAuthoredBills.bills]]
billNo = "HR00328"
date = "2019-09-12"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 47

[[principalAuthoredBills.bills]]
billNo = "HR00764"
date = "2020-03-04"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 5

[[principalAuthoredBills.bills]]
billNo = "HR02488"
date = "2022-02-03"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 8


[[principalAuthoredBills]]
congress = 19
count = 11
[[principalAuthoredBills.bills]]
billNo = "HB07600"
date = "2023-03-14"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 13

[[principalAuthoredBills.bills]]
billNo = "HB07939"
date = "2023-05-05"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 252

[[principalAuthoredBills.bills]]
billNo = "HB08001"
date = "2023-05-09"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 61

[[principalAuthoredBills.bills]]
billNo = "HB08456"
date = "2023-05-30"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 235

[[principalAuthoredBills.bills]]
billNo = "HB08965"
date = "2023-08-23"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB10729"
date = "2024-08-07"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 1

[[principalAuthoredBills.bills]]
billNo = "HB11038"
date = "2024-11-06"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 9

[[principalAuthoredBills.bills]]
billNo = "HB11189"
date = "2024-12-10"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 7

[[principalAuthoredBills.bills]]
billNo = "HB11287"
date = "2025-01-15"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 36

[[principalAuthoredBills.bills]]
billNo = "HB11402"
date = "2025-02-04"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 22

[[principalAuthoredBills.bills]]
billNo = "HR01562"
date = "2024-01-31"
name = "CALIXTO, ANTONINO"
nameCode = "Calixto"
sequenceNo = 71


[photo]
url = "https://docs.congress.hrep.online/members/20th/J018_20250721105348_.jpg"
size = 114395
type = "image/jpeg"
